import { readFileSync } from "node:fs";
import type { MdacOption } from "./official-options";

type MdacOptionKind = "city" | "state" | "accommodation" | "country";

type MdacZhTranslationCache = {
  city?: Record<string, string>;
};

function loadTranslationCache(): MdacZhTranslationCache {
  try {
    return JSON.parse(readFileSync(new URL("./option-translations.zh.json", import.meta.url), "utf8")) as MdacZhTranslationCache;
  } catch {
    return {};
  }
}

const TRANSLATION_CACHE = loadTranslationCache();

const CITY_VALUE_ZH_OVERRIDES: Record<string, string> = {
  // MDAC has a few official city options whose English values differ but whose
  // machine translations collapse into the same Chinese label. Keep ambiguous
  // or non-localized official placeholders in English so users can distinguish
  // the exact official option that will be submitted.
  "0514": "LINGGI",
  "0522": "林茂",
  "0700": "P PINANG",
  "0707": "牛汝莪",
  "0715": "PULAU PINANG",
  "0722": "日落洞",
  "0849": "和丰",
  "0865": "SG SIPUT (U)",
  "1305": "柏卡奴",
  "1332": "PEKENU",
};

const STATE_ZH_OVERRIDES: Record<string, string> = {
  JOHOR: "柔佛",
  KEDAH: "吉打",
  KELANTAN: "吉兰丹",
  MELAKA: "马六甲",
  "N SEMBILAN": "森美兰",
  "NEGERI SEMBILAN": "森美兰",
  PAHANG: "彭亨",
  "P PINANG": "槟城",
  "PULAU PINANG": "槟城",
  PERAK: "霹雳",
  PERLIS: "玻璃市",
  SELANGOR: "雪兰莪",
  TERENGGANU: "登嘉楼",
  SABAH: "沙巴",
  SARAWAK: "砂拉越",
  "W.PERSEKUTUAN": "吉隆坡联邦直辖区",
  "WP KUALA LUMPUR": "吉隆坡联邦直辖区",
  "W.P LABUAN": "纳闽联邦直辖区",
  "WP LABUAN": "纳闽联邦直辖区",
  PUTRAJAYA: "布城联邦直辖区",
  "WP PUTRAJAYA": "布城联邦直辖区",
};

const CITY_ZH_OVERRIDES: Record<string, string> = {
  JOHOR: "柔佛",
  KEDAH: "吉打",
  KELANTAN: "吉兰丹",
  MELAKA: "马六甲",
  "N SEMBILAN": "森美兰",
  PAHANG: "彭亨",
  "P PINANG": "槟城",
  PERAK: "霹雳",
  PERLIS: "玻璃市",
  SELANGOR: "雪兰莪",
  TERENGGANU: "登嘉楼",
  SABAH: "沙巴",
  SARAWAK: "砂拉越",
  "W.PERSEKUTUAN": "吉隆坡联邦直辖区",
  "W.P LABUAN": "纳闽联邦直辖区",
  PUTRAJAYA: "布城",
  "JOHOR BAHRU": "新山",
  "KUALA LUMPUR": "吉隆坡",
  "KOTA KINABALU": "哥打京那巴鲁",
  KUCHING: "古晋",
  IPOH: "怡保",
  "ALOR SETAR": "亚罗士打",
  "KOTA BHARU": "哥打巴鲁",
  "KUALA TERENGGANU": "瓜拉登嘉楼",
  "PULAU PINANG": "槟城",
  GEORGETOWN: "乔治市",
  MELAKA: "马六甲",
  SEREMBAN: "芙蓉",
  KUANTAN: "关丹",
  SHAH_ALAM: "莎阿南",
  "SHAH ALAM": "莎阿南",
  PETALING_JAYA: "八打灵再也",
  "PETALING JAYA": "八打灵再也",
  KLANG: "巴生",
  SUBANG_JAYA: "梳邦再也",
  "SUBANG JAYA": "梳邦再也",
  PUTRAJAYA: "布城",
  LABUAN: "纳闽",
  MIRI: "美里",
  SIBU: "诗巫",
  BINTULU: "民都鲁",
  SANDAKAN: "山打根",
  TAWAU: "斗湖",
  LAHAD_DATU: "拿笃",
  "LAHAD DATU": "拿笃",
  LANGKAWI: "兰卡威",
  "BATU PAHAT": "峇株巴辖",
  "ASAHAN, JOHOR": "柔佛亚沙汉",
  "AYER BALOI": "亚逸峇鲁",
  "AYER HITAM": "亚依淡",
  BAKRI: "峇吉里",
  "BATU ANAM": "峇都安南",
  BEKOK: "彼咯",
  BENUT: "文律",
  "BUKIT GAMBIR": "武吉甘蜜",
  "BUKIT PASIR": "武吉巴西",
  CHAAH: "遮阿",
  ENDAU: "丰盛港恩岛",
  "GELANG PATAH": "振林山",
  GEMAS: "金马士",
  GERSEK: "格昔",
  "G. TAIB ANDAK": "甘榜泰益安达",
  JEMENTAH: "利民达",
  KAHANG: "加亨",
  "KG KNGAN T DR": "甘榜肯雅甘东",
  "KOTA TINGGI": "哥打丁宜",
  KUKUP: "龟咯",
  MUAR: "麻坡",
  KLUANG: "居銮",
  LABIS: "拉美士",
  "LAYANG-LAYANG": "拉央拉央",
  MASAI: "马赛",
  SEGAMAT: "昔加末",
  KULAI: "古来",
  MERSING: "丰盛港",
  PAGOH: "巴莪",
  PALOH: "巴罗",
  PANCHOR: "班卒",
  "PARIT JAWA": "巴力爪哇",
  "PARIT RAJA": "巴力拉惹",
  "PARIT SULONG": "巴力士隆",
  "PASIR GUDANG": "巴西古当",
  "PEKAN NANAS": "北干那那",
  PENGERANG: "边佳兰",
  PONTIAN: "笨珍",
  RENGIT: "龙引",
  SKUDAI: "士姑来",
  SEMERAH: "士美拉",
  SENAI: "士乃",
  SENGGARANG: "新加兰",
  "SIMPANG RENGGAM": "新邦令金",
  "SUNGAI MATI": "双溪马地",
  TANGKAK: "东甲",
  "ULU TIRAM": "乌鲁地南",
  "YONG PENG": "永平",
  SAGIL: "砂益",
  "BUKIT KEPONG": "武吉甲洞",
  LENGA: "岭嘉",
  "SUNGAI BALANG": "双溪峇浪",
  "GEMAS BARU": "新金马士",
  RENGGAM: "令金",
  "BANDAR PENAWAR": "本那哇镇",
  LEDANG: "礼让",
  "ISKANDAR PUTERI": "依斯干达公主城",
  "KULAI JAYA": "古来再也",
  "KANGKAR PULAI": "江加蒲莱",
  BALING: "华玲",
  "BANDAR BAHARU": "万拉峇鲁",
  BEDONG: "峇东",
  GURUN: "莪仑",
  JITRA: "日得拉",
  KARANGAN: "加冷岸",
  "KEPALA BATAS": "甲抛峇底",
  KODIANG: "哥打央",
  "KOTA KUALA MUDA": "瓜拉姆达城",
  "KUALA KEDAH": "瓜拉吉打",
  "KUALA KETIL": "瓜拉吉底",
  "KUALA NERANG": "瓜拉尼浪",
  KULIM: "居林",
  KUPANG: "古邦",
  LANGGAR: "冷甲",
  LUNAS: "鲁乃",
  MERBOK: "默博",
  "PADANG SERAI": "巴东色海",
  PENDANG: "笨筒",
  "POKOK SENA": "波各先那",
  SERDANG: "沙登",
  SIK: "锡",
  "SUNGAI PETANI": "双溪大年",
  YAN: "铅",
  CHANGLOON: "樟仑",
  SINTOK: "新笃",
  "SG. BAKAP": "双溪峇甲",
  "BUKIT KAYU HITAM": "黑木山",
  "SIMPANG EMPAT": "四湾岛",
  "KOTA SARANG SEMUT": "哥打沙浪瑟姆",
  JENIANG: "仁岭",
  "AYER LANAS": "亚逸拉那",
  BACHOK: "万捷",
  "CHERANG RUKU": "遮浪鲁古",
  DABONG: "达蓬",
  "GUA MUSANG": "话望生",
  JELI: "日里",
  "K DESA PAHLAWAN": "甘榜德沙巴拉万",
  KETEREH: "格底里",
  "KUALA KRAI": "瓜拉吉赖",
  MACHANG: "马樟",
  MELOR: "美罗",
  "PASIR MAS": "巴西马",
  "PASIR PUTEH": "巴西富地",
  "PULAI CHONDONG": "普莱宗东",
  "RANTAU PANJANG": "兰斗班让",
  "TANAH MERAH": "丹那美拉",
  TEMANGAN: "德曼岸",
  TUMPAT: "道北",
  "WAKAF BHARU": "华卡峇鲁",
  SELISING: "士里星",
  "KUALA BALAH": "瓜拉峇拉",
  "ALOR GAJAH": "亚罗牙也",
  "BATANG MELAKA": "峇登马六甲",
  BEMBAN: "万里望",
  "DURIAN TUNGGAL": "榴梿洞葛",
  JASIN: "野新",
  "K/SUNGAI BARU": "瓜拉双溪峇鲁",
  "LUBOK CHINA": "鲁博中国",
  "MASJID TANAH": "马日丹那",
  MERLIMAU: "万里茂",
  "SUNGAI RAMBAI": "双溪南眉",
  "SUNGAI UDANG": "双溪乌当",
  TAMPIN: "淡边",
  "TANJONG KELING": "丹绒吉宁",
  SELANDAR: "士兰道",
  "BUKIT KATIL": "武吉卡迪",
  "AYER KEROH": "爱极乐",
  "BATU BERENDAM": "峇都伯伦丹",
  BAHAU: "马口",
  "BATU KIKIR": "峇都基基",
  "DURIAN TIPUS": "榴梿知布",
  GEMENCHEH: "金马士新村",
  JOHOL: "柔河",
  KOTA: "哥打",
  "KUALA KLAWANG": "瓜拉格拉旺",
  "KUALA PILAH": "瓜拉庇劳",
  LABU: "拉务",
  LENGGENG: "冷宜",
  LINGGI: "林茂",
  MANTIN: "文丁",
  NILAI: "汝来",
  "PASIR PANJANG": "巴西班让",
  PEDAS: "不叻士",
  "PORT DICKSON": "波德申",
  REMBAU: "林茂",
  ROMPIN: "云冰",
  SELIAU: "士了",
  "SRI MENANTI": "斯里 Menanti",
  "SI RUSA": "芦骨直落",
  SILIAU: "士留",
  "SIMPANG PERTANG": "新邦柏当",
  "SUNGAI GADUT": "双溪加都",
  "TANJUNG IPOH": "丹绒怡保",
  TITI: "知知港",
  "BUKIT PELANDOK": "武吉不兰律",
  CHUAH: "朱湖",
  LUKUT: "芦骨",
  "TELUK KEMANG": "直落甘望",
  "PENG.KEMPAS": "甘榜甘巴斯",
  JELEBU: "日叻务",
  "BANDAR SERI JEMPOL": "斯里仁保镇",
  JUASSEH: "瓜拉庇劳爪西",
  "B BARU JEMPOL": "仁保新镇",
  "BANDAR ENSTEK": "恩斯德镇",
  "PUSAT BANDAR PALONG": "巴隆市中心",
  "BANDAR JENGKA": "而连突珍卡镇",
  BENTA: "文达",
  BENTONG: "文冬",
  BESERAH: "勿舍拉",
  "BUKIT FRASER": "福隆港",
  CHENOR: "遮诺",
  DONG: "冬",
  GAMBANG: "甘孟",
  GENTING: "云顶",
  JERANTUT: "而连突",
  KARAK: "加叻",
  KEMAYAN: "金马扬",
  "KUALA LIPIS": "瓜拉立卑",
  "KUALA ROMPIN": "瓜拉云冰",
  LANCHANG: "冷昌",
  "LURAH BILUT": "美律谷",
  MARAN: "马兰",
  MENGKARAK: "明加叻",
  MENTAKAB: "文德甲",
  "MUADZAM SHAH": "姆阿占沙",
  "PADANG TENGKU": "巴当东姑",
  PEKAN: "北根",
  RAUB: "劳勿",
  RINGLET: "冷力",
  "SUNGAI LEMBING": "双溪林明",
  "SUNGAI RUAN": "双溪阮",
  "TANAH RATA": "丹那拉打",
  TEMERLOH: "淡马鲁",
  TRIANG: "直凉",
  "BDR TUN RAZAK": "敦拉萨镇",
  "C HIGHLANDS": "金马仑高原",
  "BANDAR BERA": "百乐镇",
  SEGA: "昔加",
  BRINCHANG: "碧兰璋",
  "AYER ITAM": "亚依淡",
  "BALIK PULAU": "浮罗山背",
  "BATU FERRINGHI": "峇都丁宜",
  "BAYAN LEPAS": "峇六拜",
  "BUKIT MERTAJAM": "大山脚",
  BUTTERWORTH: "北海",
  GELUGOR: "日落洞",
  "NIBONG TEBAL": "高渊",
  PENAGA: "本那牙",
  "PENANG HILL": "升旗山",
  PERAI: "北赖",
  "PERMATANG PAUH": "峇东埔",
  "SIMPANG AMPAT": "新邦安拔",
  "SUNGAI JAWI": "双溪爪夷",
  "TANJONG BUNGAH": "丹绒武雅",
  "TASEK GELUGOR": "打昔牛汝莪",
  "USM P/PINANG": "槟城理科大学",
  "SUNGAI BAKAP": "双溪峇甲",
  JELUTONG: "日落洞",
  MINDEN: "敏登",
  "TANJONG TOKONG": "丹绒道光",
  "BAYAN BARU": "峇央峇鲁",
  "AYER TAWAR": "爱大华",
  "BAGAN DATOH": "峇眼拿督",
  "BAGAN SERAI": "峇眼色海",
  "BATU GAJAH": "华都牙也",
  "BATU KURAU": "峇都古楼",
  BERUAS: "木威",
  BIDOR: "美罗",
  BOTA: "波打",
  "CHKT KERUING": "章卡遮鲁因",
  CHEMOR: "珠宝",
  CHENDERIANG: "积莪营",
  "CHENDERONG BALAI": "正隆峇莱",
  ENGGOR: "安宜",
  GERIK: "宜力",
  GOPENG: "务边",
  "HUTAN MELINTANG": "半港",
  "KLIAN INTAN": "克连因丹",
  KAMPAR: "金宝",
  "KAMPONG GAJAH": "甘榜牙也",
  "KG KEPAYANG": "甘榜甲巴央",
  KAMUNTING: "甘文丁",
  "KUALA KANGSAR": "江沙",
  "KUALA SEPETANG": "十八丁",
  LAHAT: "拿乞",
  LANGKAP: "冷甲",
  LENGGONG: "玲珑",
  LUMUT: "红土坎",
  "MALIM NAWAR": "万里望",
  "MAMBANG DIAWAN": "万邦刁湾",
  MANONG: "万浓",
  MATANG: "马登",
  MENGLEMBU: "孟加兰",
  "PADANG RENGAS": "巴东令牙",
  PANGKOR: "邦咯",
  "PANTAI REMIS": "班台",
  PARIT: "巴力",
  "PARIT BUNTAR": "巴里文打",
  "PENGKALAN HULU": "高乌",
  PUSING: "布先",
  SAUK: "绍嘉",
  SELAMA: "司南马",
  SELEKOH: "实兆远附近士力古",
  SEMANGGOL: "士曼谷",
  SIMPANG: "新邦",
  SITIAWAN: "实兆远",
  "SLIM RIVER": "仕林河",
  "SUNGAI SIPUT": "和丰",
  "SUNGAI SUMUN": "双溪苏木",
  SUNGKAI: "宋溪",
  TAIPING: "太平",
  "TANJUNG MALIM": "丹绒马林",
  "TG.PIANDANG": "丹绒比安当",
  "TG.RAMBUTAN": "丹绒红毛丹",
  "TANJONG TUALANG": "丹绒端朗",
  TAPAH: "打巴",
  "TAPAH ROAD": "打巴路",
  "TELUK INTAN": "安顺",
  TEMOH: "地摩",
  TRONG: "直弄",
  TERONOH: "端洛",
  "ULU KINTA": "乌鲁近打",
  "ULU BERNAM": "乌鲁安南",
  "SG SIPUT (U)": "和丰",
  "BEHRANG STESEN": "美冷车站",
  TROLAK: "仕林河卓腊",
  "KUALA DIPANG": "瓜拉地棚",
  "KUALA KURAU": "瓜拉古楼",
  "SERI MANJUNG": "斯里曼绒",
  CHIKUS: "积古斯",
  ARAU: "亚娄",
  "KAKI BUKIT": "加基武吉",
  KANGAR: "加央",
  "KUALA PERLIS": "瓜拉玻璃市",
  "PADANG BESAR": "巴东勿刹",
  AMPANG: "安邦",
  BANTING: "万津",
  "BTG.BERJUNTAI": "万挠柏占泰",
  "BATANG KALI": "峇冬加里",
  "BATU 9 CHERAS": "蕉赖九哩",
  "BATU ARANG": "煤炭山",
  "BATU CAVES": "黑风洞",
  BERANANG: "武来岸",
  "BUKIT ROTAN": "武吉罗丹",
  DENGKIL: "龙溪",
  "HULU LANGAT": "乌鲁冷岳",
  JENJAROM: "仁嘉隆",
  JERAM: "而榄",
  KAJANG: "加影",
  KAPAR: "加埔",
  KERLING: "吉粦",
  "K. KUBU BHARU": "新古毛",
  "KUALA SELANGOR": "瓜拉雪兰莪",
  "PELABUHAN KLANG": "巴生港",
  PUCHONG: "蒲种",
  "PULAU CAREY": "凯里岛",
  "PULAU KETAM": "吉胆岛",
  "PULAU INDAH": "英达岛",
  RASA: "叻思",
  RAWANG: "万挠",
  "SABAK BERNAM": "沙白安南",
  SEKINCAN: "适耕庄",
  SEMENYIH: "士毛月",
  SEPANG: "雪邦",
  SERENDAH: "双文丹",
  "SERI KEMBANGAN": "史里肯邦安",
  "SG AYER TAWAR": "双溪亚逸达华",
  "SUNGAI BESAR": "大港",
  "SUNGAI BULOH": "双溪毛糯",
  "SUNGAI PELEK": "双溪比力",
  "TANJONG KARANG": "丹绒加弄",
  "TANJONG SEPAT": "丹绒士拔",
  "TELOK P. GARANG": "直落邦里玛加朗",
  "UKM BANGI": "国大万宜",
  "UPM SERDANG": "博特拉大学沙登",
  "HULU BERNAM": "乌鲁安南",
  "BDR. BARU BANGI": "万宜新镇",
  "PUTRAJAYA(1.2.2001)": "布城",
  CYBERJAYA: "赛城",
  SELAYANG: "士拉央",
  "BANDAR BARU SUNGAI BULOH": "双溪毛糯新镇",
  "ULU YAM BARU": "乌鲁音峇鲁",
  GOMBAK: "鹅唛",
  "TASIK PUTERI": "太子湖",
  CHERAS: "蕉赖",
  "BANDAR PUNCAK ALAM": "本查阿南镇",
  AJIL: "阿吉尔",
  BESUT: "勿述",
  "BUKIT BESI": "武吉勿西",
  DUNGUN: "龙运",
  JERTIH: "日底",
  "BDR PERMAISURI": "柏迈苏里镇",
  KEMAMAN: "甘马挽",
  KEMASEK: "格马昔",
  KIJAL: "基惹",
  "KUALA BERANG": "瓜拉勿浪",
  "KUALA BESUT": "瓜拉勿述",
  MARANG: "马江",
  PAKA: "北加",
  KERTEH: "吉利地",
  "MUKTAFI BILLAH SHAH": "穆克达菲比拉沙",
  "KAMPONG RAJA": "甘榜拉惹",
  CUKAI: "朱盖",
  "KUALA NERUS": "瓜拉尼鲁斯",
  "BANDAR KETENGAH JAYA": "格登雅也镇",
  BEAUFORT: "保佛",
  BELURAN: "比鲁兰",
  BONGAWAN: "孟加湾",
  INANAM: "下南南",
  KENINGAU: "根地咬",
  "KOTA BELUD": "哥打毛律",
  "KOTA MARUDU": "哥打马鲁都",
  "KUALA PENYU": "瓜拉班尤",
  KUDAT: "古达",
  KUNAK: "古纳",
  LAMAG: "拉玛",
  LIKAS: "里卡士",
  MEMBAKUT: "民巴吉",
  MENUMBUK: "孟奴卜",
  NABAWAN: "纳巴湾",
  PAPAR: "吧巴",
  PENAMPANG: "兵南邦",
  RANAU: "兰瑙",
  SEMPORNA: "仙本那",
  SIPITANG: "实必丹",
  TAMBUNAN: "担布南",
  TAMPARULI: "担波罗里",
  "TANJUNG ARU": "丹绒亚路",
  TENOM: "丹南",
  TUARAN: "斗亚兰",
  "K. KINABATANGAN": "京那巴当岸",
  PUTATAN: "必打丹",
  TELUPID: "特鲁必",
  ASAJAYA: "阿沙再也",
  BALINGIAN: "峇林宜安",
  BARAM: "巴南",
  BAU: "石隆门",
  BEKENU: "柏卡奴",
  BELAGA: "巫拉甲",
  BELAWAI: "勿拉威",
  BETONG: "木中",
  BINTANGOR: "民丹莪",
  DALAT: "达叻",
  DARO: "达佬",
  DEBAK: "德巴",
  ENGKILILI: "英吉利里",
  JULAU: "如楼",
  KABONG: "加邦",
  KANOWIT: "加拿逸",
  KAPIT: "加帛",
  "KOTA SAMARAHAN": "哥打三马拉汉",
  LAWAS: "老越",
  LIMBANG: "林梦",
  LINGGA: "林加",
  "LONG LAMA": "弄拉玛",
  "LUBOK ANTU": "鲁勃安都",
  LUNDU: "伦乐",
  MATU: "玛都",
  MUKAH: "木胶",
  "NANGA MEDAMIT": "南嘉美达密",
  NIAH: "尼亚",
  PEKENU: "柏卡奴",
  PUSA: "布沙",
  ROBAN: "罗班",
  SARATOK: "实拉卓",
  SARIKEI: "泗里街",
  SEBAUH: "实包勿",
  SEBUYAU: "实文然",
  SERIAN: "西连",
  SIMUNJAN: "成邦江",
  SONG: "桑",
  SPAOH: "实巴荷",
  "SRI AMAN": "诗里阿曼",
  SUNDAR: "双达",
  TATAU: "达岛",
  TEBAKANG: "打巴江",
  SIBU: "诗巫",
  TEBEDU: "打必禄",
  PAKAN: "巴干",
  SIBUTI: "西布地",
  OYA: "乌也",
  "LAPANGAN TERBANG KOTA KINABALU": "哥打京那巴鲁机场",
  MARUDI: "马鲁帝",
  SIBURAN: "西布兰",
};

function normalizeKey(value: string): string {
  return value.trim().replace(/\s+/g, " ").toUpperCase();
}

function cleanZh(value: string): string {
  return value
    .trim()
    .replace(/\s+/g, "")
    .replace(/，/g, " / ")
    .replace(/^马来西亚/, "")
    .replace(/邮政编码/g, "")
    .replace(/区$/g, "");
}

function mdacOptionLabelZh(kind: MdacOptionKind, option: MdacOption): string {
  if (kind === "state") {
    return STATE_ZH_OVERRIDES[normalizeKey(option.official_label ?? option.label_en)] ?? option.label_zh;
  }
  if (kind === "city") {
    const valueOverride = CITY_VALUE_ZH_OVERRIDES[option.value];
    if (valueOverride) return valueOverride;
    const cached = TRANSLATION_CACHE.city?.[option.value];
    const override = CITY_ZH_OVERRIDES[normalizeKey(option.label_en)];
    const zh = override ?? (cached ? cleanZh(cached) : null);
    return zh || option.label_zh;
  }
  return option.label_zh;
}

export function localizeMdacOptions(kind: MdacOptionKind, options: MdacOption[]): MdacOption[] {
  return options.map((option) => ({
    ...option,
    label_zh: mdacOptionLabelZh(kind, option),
  }));
}

export function localizeMdacCityOptionsByState(optionsByState: Record<string, MdacOption[]>): Record<string, MdacOption[]> {
  return Object.fromEntries(
    Object.entries(optionsByState).map(([state, options]) => [state, localizeMdacOptions("city", options)]),
  );
}
