import { toBilingualSeedRow, type BilingualSeedField } from "../bilingual-seed-row";

export const JP_VISIT_JAPAN_WEB_VISA_TYPE = "JP_VISIT_JAPAN_WEB";

export type JpVjwFieldDef = BilingualSeedField;

type JpVjwOption = {
  value: string;
  text: string;
  label_zh: string;
  label_en: string;
  official_label: string;
};

const rules = (labelZh: string, extra: Record<string, unknown> = {}) => ({
  label_zh: labelZh,
  official: true,
  ...extra,
});

const option = (value: string, labelZh: string, labelEn = value): JpVjwOption => ({
  value,
  text: labelEn,
  label_zh: labelZh,
  label_en: labelEn,
  official_label: labelEn,
});

const YES_NO = [option("yes", "是", "Yes"), option("no", "否", "No")];
const SEX_OPTIONS = [
  option("Male", "男", "Male"),
  option("Female", "女", "Female"),
  option("Other", "其他", "Other"),
];
const PASSPORT_TYPE_OPTIONS = [option("Ordinary passport", "普通护照")];
const NATIONALITY_OPTIONS = [option("China", "中国")];
const PURPOSE_OPTIONS = [option("Tourism", "旅游", "Tourism")];
const showIf = (expression: string) => ({ showIf: expression });

export const JP_VISIT_JAPAN_WEB_FORM_FIELDS: JpVjwFieldDef[] = [
  {
    field_name: "passport_type",
    label: "Passport Type",
    field_type: "select",
    required: true,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 1,
    options: PASSPORT_TYPE_OPTIONS,
    validation_rules: rules("护照类型", {
      first_phase_value: "Ordinary passport",
      allowed_values: ["Ordinary passport"],
    }),
  },
  {
    field_name: "surname",
    label: "Surname (as shown in passport)",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 2,
    validation_rules: rules("姓（按护照）", { maxLength: 80, passport_source: true }),
  },
  {
    field_name: "given_names",
    label: "Given Names (as shown in passport)",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 3,
    validation_rules: rules("名（按护照）", { maxLength: 100, passport_source: true }),
  },
  {
    field_name: "full_name",
    label: "Full Name (derived from surname and given names)",
    field_type: "computed",
    required: false,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 13,
    conditional_logic: showIf("false"),
    validation_rules: rules("全名（由姓和名组合）", {
      runner_canonical_key: "full_name",
      derived_from: ["surname", "given_names"],
      no_user_input: true,
      passport_source: true,
    }),
  },
  {
    field_name: "date_of_birth",
    label: "Date of Birth",
    field_type: "date",
    required: true,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 4,
    validation_rules: rules("出生日期", { format: "YYYY-MM-DD", passport_source: true }),
  },
  {
    field_name: "nationality",
    label: "Nationality",
    field_type: "select",
    required: true,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 5,
    options: NATIONALITY_OPTIONS,
    validation_rules: rules("国籍", { first_phase_value: "China", passport_source: true }),
  },
  {
    field_name: "sex",
    label: "Sex",
    field_type: "select",
    required: true,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 6,
    options: SEX_OPTIONS,
    validation_rules: rules("性别", { passport_source: true }),
  },
  {
    field_name: "passport_number",
    label: "Passport Number",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 7,
    validation_rules: rules("护照号码", { maxLength: 32, passport_source: true }),
  },
  {
    field_name: "passport_expiry_date",
    label: "Passport Expiry Date",
    field_type: "date",
    required: true,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 8,
    validation_rules: rules("护照有效期至", { format: "YYYY-MM-DD", passport_source: true }),
  },
  {
    field_name: "passport_issuing_country",
    label: "Passport Issuing Country",
    field_type: "select",
    required: true,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 9,
    options: NATIONALITY_OPTIONS,
    validation_rules: rules("护照签发国家", { first_phase_value: "China", passport_source: true }),
  },
  {
    field_name: "email_address",
    label: "Email Address",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 10,
    validation_rules: rules("电子邮箱地址", {
      pattern: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
      runner_policy: "use_managed_alias_for_official_account_and_forward_updates_with_consent",
    }),
  },
  {
    field_name: "phone_number",
    label: "Telephone Number",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 11,
    validation_rules: rules("联系电话", { maxLength: 32 }),
  },
  {
    field_name: "residence_country",
    label: "Country/Region of Residence",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 12,
    validation_rules: rules("居住国家 / 地区", { maxLength: 80 }),
  },
  {
    field_name: "arrival_date",
    label: "Date of Arrival in Japan",
    field_type: "date",
    required: true,
    step_number: 2,
    step_name: "Arrival and Stay",
    display_order: 1,
    validation_rules: rules("抵达日本日期", { format: "YYYY-MM-DD", timezone: "Asia/Tokyo" }),
  },
  {
    field_name: "arrival_airport",
    label: "Intended Port of Entry",
    field_type: "select",
    required: true,
    step_number: 2,
    step_name: "Arrival and Stay",
    display_order: 2,
    validation_rules: rules("计划入境机场 / 港口", {
      dynamic_option_source: "visit_japan_web_official_airports_and_ports",
      option_identity: "official_value",
      runtime_code_resolution: "required_before_live_submit",
    }),
  },
  {
    field_name: "flight_number",
    label: "Flight Number",
    field_type: "text",
    required: true,
    step_number: 2,
    step_name: "Arrival and Stay",
    display_order: 3,
    validation_rules: rules("抵达航班号", { maxLength: 32 }),
  },
  {
    field_name: "last_embarkation_country",
    label: "Country/Region of Last Embarkation",
    field_type: "text",
    required: true,
    step_number: 2,
    step_name: "Arrival and Stay",
    display_order: 4,
    validation_rules: rules("最后出发国家 / 地区", { maxLength: 80, runner_canonical_key: "last_embarkation_country" }),
  },
  {
    field_name: "departure_city_or_port",
    label: "City/Port of Embarkation",
    field_type: "text",
    required: true,
    step_number: 2,
    step_name: "Arrival and Stay",
    display_order: 5,
    validation_rules: rules("出发城市 / 港口", { maxLength: 120 }),
  },
  {
    field_name: "purpose_of_visit",
    label: "Purpose of Visit",
    field_type: "select",
    required: true,
    step_number: 2,
    step_name: "Arrival and Stay",
    display_order: 6,
    options: PURPOSE_OPTIONS,
    validation_rules: rules("访问目的", { first_phase_value: "Tourism" }),
  },
  {
    field_name: "planned_stay_days",
    label: "Planned Length of Stay (days)",
    field_type: "number",
    required: true,
    step_number: 2,
    step_name: "Arrival and Stay",
    display_order: 7,
    validation_rules: rules("计划停留天数", { integer: true, min: 1, max: 90 }),
  },
  {
    field_name: "accommodation_name",
    label: "Hotel or Accommodation Name",
    field_type: "text",
    required: true,
    step_number: 2,
    step_name: "Arrival and Stay",
    display_order: 8,
    validation_rules: rules("酒店或住宿名称", { maxLength: 200 }),
  },
  {
    field_name: "accommodation_address",
    label: "Address in Japan",
    field_type: "textarea",
    required: true,
    step_number: 2,
    step_name: "Arrival and Stay",
    display_order: 9,
    validation_rules: rules("日本住宿地址", { maxLength: 500 }),
  },
  {
    field_name: "accommodation_postal_code",
    label: "Postal Code in Japan",
    field_type: "text",
    required: true,
    step_number: 2,
    step_name: "Arrival and Stay",
    display_order: 10,
    validation_rules: rules("日本邮政编码", { pattern: "^[0-9]{3}-?[0-9]{4}$" }),
  },
  {
    field_name: "accommodation_phone",
    label: "Accommodation Telephone Number",
    field_type: "text",
    required: true,
    step_number: 2,
    step_name: "Arrival and Stay",
    display_order: 11,
    validation_rules: rules("住宿联系电话", { maxLength: 32 }),
  },
  {
    field_name: "has_been_deported",
    label: "Have you ever been deported from Japan, departed under a departure order, or been denied entry to Japan?",
    field_type: "radio",
    required: true,
    step_number: 3,
    step_name: "Immigration Declaration",
    display_order: 1,
    options: YES_NO,
    validation_rules: rules("您是否曾被日本强制遣返、根据出国命令离境或被日本拒绝入境？", {
      immigration_question: true,
      official_source_url: "https://www.moj.go.jp/isa/content/930002134.pdf",
    }),
  },
  {
    field_name: "has_criminal_record",
    label: "Have you ever been found guilty in a criminal case in Japan or in another country?",
    field_type: "radio",
    required: true,
    step_number: 3,
    step_name: "Immigration Declaration",
    display_order: 2,
    options: YES_NO,
    validation_rules: rules("您是否曾在日本或其他国家的刑事案件中被判有罪？", {
      immigration_question: true,
      official_source_url: "https://www.moj.go.jp/isa/content/930002134.pdf",
    }),
  },
  {
    field_name: "has_controlled_substances_or_weapons",
    label: "Do you presently have narcotics, marijuana, opium, stimulants or other controlled substances, firearms, crossbows, swords, explosives or similar items in your possession?",
    field_type: "radio",
    required: true,
    step_number: 3,
    step_name: "Immigration Declaration",
    display_order: 3,
    options: YES_NO,
    validation_rules: rules("您目前是否持有麻醉品、大麻、鸦片、兴奋剂等管制药物，或枪支、弩、刀剑、爆炸物等类似物品？", {
      immigration_question: true,
      official_source_url: "https://www.moj.go.jp/isa/content/930002134.pdf",
      legacy_aliases: ["has_drug_or_trafficking_history"],
    }),
  },
  {
    field_name: "has_prohibited_or_restricted_goods",
    label: "Are you carrying prohibited or restricted goods?",
    field_type: "radio",
    required: true,
    step_number: 4,
    step_name: "Customs Declaration",
    display_order: 1,
    options: YES_NO,
    validation_rules: rules("是否携带禁止或限制进口的物品？", { customs_question: true }),
  },
  {
    field_name: "has_dutiable_goods",
    label: "Are you carrying goods exceeding the duty-free allowance?",
    field_type: "radio",
    required: true,
    step_number: 4,
    step_name: "Customs Declaration",
    display_order: 2,
    options: YES_NO,
    validation_rules: rules("是否携带超过免税额度的物品？", { customs_question: true }),
  },
  {
    field_name: "has_commercial_goods",
    label: "Are you carrying commercial goods or samples?",
    field_type: "radio",
    required: true,
    step_number: 4,
    step_name: "Customs Declaration",
    display_order: 3,
    options: YES_NO,
    validation_rules: rules("是否携带商业货物或样品？", { customs_question: true }),
  },
  {
    field_name: "has_goods_for_other_person",
    label: "Are you carrying goods entrusted to you by another person?",
    field_type: "radio",
    required: true,
    step_number: 4,
    step_name: "Customs Declaration",
    display_order: 4,
    options: YES_NO,
    validation_rules: rules("是否携带他人委托您携带的物品？", { customs_question: true }),
  },
  {
    field_name: "has_unaccompanied_baggage",
    label: "Are you carrying unaccompanied baggage?",
    field_type: "radio",
    required: true,
    step_number: 4,
    step_name: "Customs Declaration",
    display_order: 5,
    options: YES_NO,
    validation_rules: rules("是否有托运以外的非随身行李？", { customs_question: true }),
  },
  {
    field_name: "has_cash_or_valuables_over_threshold",
    label: "Are you carrying cash or other means of payment above the declaration threshold?",
    field_type: "radio",
    required: true,
    step_number: 4,
    step_name: "Customs Declaration",
    display_order: 6,
    options: YES_NO,
    validation_rules: rules("是否携带超过申报门槛的现金或支付工具？", {
      customs_question: true,
      threshold_must_be_confirmed_from_current_japan_customs_guidance: true,
    }),
  },
  {
    field_name: "customs_declaration",
    label: "Customs Declaration (derived from the individual customs answers)",
    field_type: "computed",
    required: false,
    step_number: 4,
    step_name: "Customs Declaration",
    display_order: 7,
    conditional_logic: showIf("false"),
    validation_rules: rules("海关申报（由各项海关答案汇总）", {
      runner_canonical_key: "customs_declaration",
      derived_from: [
        "has_prohibited_or_restricted_goods",
        "has_dutiable_goods",
        "has_commercial_goods",
        "has_goods_for_other_person",
        "has_unaccompanied_baggage",
        "has_cash_or_valuables_over_threshold",
      ],
      aggregation: "yes_if_any_customs_answer_is_yes_else_no",
      no_user_input: true,
      do_not_ask_as_single_customs_question: true,
    }),
  },
  {
    field_name: "customs_declaration_confirmed",
    label: "I confirm that my customs declaration is complete and truthful.",
    field_type: "checkbox",
    required: true,
    step_number: 4,
    step_name: "Customs Declaration",
    display_order: 8,
    validation_rules: rules("我确认海关申报完整且真实", {
      final_review: true,
      boolean_contract: "must_be_true",
      official_value: "true",
    }),
  },
  {
    field_name: "immigration_declaration",
    label: "I confirm that my immigration information is complete and truthful.",
    field_type: "checkbox",
    required: true,
    step_number: 3,
    step_name: "Final Review and Authorization",
    display_order: 1,
    validation_rules: rules("我确认入境信息完整且真实", {
      final_review: true,
      runner_canonical_key: "immigration_declaration",
      boolean_contract: "must_be_true",
      official_value: "true",
    }),
  },
  {
    field_name: "final_declaration",
    label: "Final Declaration (derived from the immigration and customs confirmations)",
    field_type: "computed",
    required: false,
    step_number: 4,
    step_name: "Customs Declaration",
    display_order: 9,
    conditional_logic: showIf("false"),
    validation_rules: rules("最终申报（由入境和海关确认汇总）", {
      runner_canonical_key: "final_declaration",
      derived_from: ["immigration_declaration", "customs_declaration_confirmed"],
      no_user_input: true,
      aggregation: "yes_only_when_all_confirmations_are_true",
    }),
  },
];

export const JP_VISIT_JAPAN_WEB_OFFICIAL_FIELD_NAMES =
  JP_VISIT_JAPAN_WEB_FORM_FIELDS.map((field) => field.field_name);

export function bilingualJpVjwRows() {
  return JP_VISIT_JAPAN_WEB_FORM_FIELDS.map((field) =>
    toBilingualSeedRow(JP_VISIT_JAPAN_WEB_VISA_TYPE, field),
  );
}
