import { toBilingualSeedRow, type BilingualSeedField } from "../bilingual-seed-row";
import {
  JP_VJW_AIRLINE_OPTIONS,
  JP_VJW_CITIES_BY_PREFECTURE,
  JP_VJW_EMBARKATION_POINT_OPTIONS,
  JP_VJW_NATIONALITY_OPTIONS,
  JP_VJW_OFFICIAL_MASTER_SOURCE,
  JP_VJW_PREFECTURE_OPTIONS,
} from "./official-master";

export const JP_VISIT_JAPAN_WEB_VISA_TYPE = "JP_VISIT_JAPAN_WEB";

export type JpVjwFieldDef = BilingualSeedField;

type JpVjwOption = {
  value: string;
  text: string;
  label_zh: string;
  label_en: string;
  official_label: string;
};

const rules = (labelZh: string, extra: Record<string, unknown> = {}) => ({
  label_zh: labelZh,
  official: true,
  ...extra,
});

const option = (value: string, labelZh: string, labelEn = value): JpVjwOption => ({
  value,
  text: labelEn,
  label_zh: labelZh,
  label_en: labelEn,
  official_label: labelEn,
});

const YES_NO = [option("yes", "是", "Yes"), option("no", "否", "No")];
const PURPOSE_OPTIONS = [option("0", "旅游", "Tourism")];
const OCCUPATION_OPTIONS = [
  option("0100", "公司职员", "Company employee"),
  option("0200", "公司总经理、公司董事", "Company president or executive"),
  option("0300", "公务员", "Public servant"),
  option("0400", "团体职员", "Association staff member"),
  option("0500", "个体经营（自雇）", "Self-owned business"),
  option("0600", "医生", "Medical doctor"),
  option("0700", "教师", "Teacher"),
  option("0800", "学生", "Student"),
  option("0900", "无业", "Unemployed"),
  option("0990", "其他", "Other"),
];
const showIf = (expression: string) => ({ showIf: expression });

const hiddenCompatibilityRules = (labelZh: string, replacedBy?: string) => rules(labelZh, {
  no_user_input: true,
  legacy_compatibility_only: true,
  official_control: null,
  ...(replacedBy ? { replaced_by: replacedBy } : {}),
});

export const JP_VISIT_JAPAN_WEB_FORM_FIELDS: JpVjwFieldDef[] = [
  {
    field_name: "passport_type",
    label: "Passport Type",
    field_type: "computed",
    required: false,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 1,
    conditional_logic: showIf("false"),
    validation_rules: hiddenCompatibilityRules("护照类型"),
  },
  {
    field_name: "surname",
    label: "Surname (as shown in passport)",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 2,
    validation_rules: rules("姓（按护照）", { maxLength: 39, passport_source: true, official_control_type: "text" }),
  },
  {
    field_name: "given_names",
    label: "Given Names (as shown in passport)",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 3,
    validation_rules: rules("名（按护照）", { maxLength: 39, passport_source: true, official_control_type: "text" }),
  },
  {
    field_name: "full_name",
    label: "Full Name (derived from surname and given names)",
    field_type: "computed",
    required: false,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 13,
    conditional_logic: showIf("false"),
    validation_rules: rules("全名（由姓和名组合）", {
      runner_canonical_key: "full_name",
      derived_from: ["surname", "given_names"],
      no_user_input: true,
      passport_source: true,
    }),
  },
  {
    field_name: "date_of_birth",
    label: "Date of Birth",
    field_type: "date",
    required: true,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 4,
    validation_rules: rules("出生日期", { format: "YYYY-MM-DD", passport_source: true }),
  },
  {
    field_name: "nationality",
    label: "Nationality",
    field_type: "select",
    required: true,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 5,
    options: JP_VJW_NATIONALITY_OPTIONS,
    validation_rules: rules("国籍", {
      first_phase_value: "CHN",
      passport_source: true,
      official_control_type: "select",
      option_identity: "ICAO nationality code",
    }),
  },
  {
    field_name: "sex",
    label: "Sex",
    field_type: "computed",
    required: false,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 6,
    conditional_logic: showIf("false"),
    validation_rules: hiddenCompatibilityRules("性别"),
  },
  {
    field_name: "passport_number",
    label: "Passport Number",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 7,
    validation_rules: rules("护照号码", { maxLength: 32, passport_source: true }),
  },
  {
    field_name: "passport_expiry_date",
    label: "Passport Expiry Date",
    field_type: "date",
    required: true,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 8,
    validation_rules: rules("护照有效期至", { format: "YYYY-MM-DD", passport_source: true }),
  },
  {
    field_name: "passport_issuing_country",
    label: "Passport Issuing Country",
    field_type: "computed",
    required: false,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 9,
    conditional_logic: showIf("false"),
    validation_rules: hiddenCompatibilityRules("护照签发国家"),
  },
  {
    field_name: "email_address",
    label: "Email Address",
    field_type: "computed",
    required: false,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 10,
    conditional_logic: showIf("false"),
    validation_rules: hiddenCompatibilityRules("电子邮箱地址", "application-scoped managed alias"),
  },
  {
    field_name: "phone_number",
    label: "Telephone Number",
    field_type: "computed",
    required: false,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 11,
    conditional_logic: showIf("false"),
    validation_rules: hiddenCompatibilityRules("联系电话", "accommodation_phone"),
  },
  {
    field_name: "residence_country",
    label: "Country/Region of Residence",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 12,
    validation_rules: rules("居住国家 / 地区", { maxLength: 80, official_control_type: "text" }),
  },
  {
    field_name: "occupation",
    label: "Occupation",
    field_type: "select",
    required: true,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 13,
    options: OCCUPATION_OPTIONS,
    validation_rules: rules("职业", {
      official_control: "occupation",
      official_control_type: "select",
      official_options_snapshot: "Visit Japan Web main.1dcb51ecdb7a1ed7.js occupationMaster",
      option_identity: "official_code",
      helper_zh: "请按实际情况选择当前职业；退休人员或列表未涵盖的职业请选择“其他”。",
    }),
  },
  {
    field_name: "residence_city",
    label: "City of Residence",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: "Traveller and Passport",
    display_order: 14,
    validation_rules: rules("现居住城市", {
      maxLength: 120,
      official_control: "cityName",
      official_control_type: "text",
      helper_zh: "请填写您目前实际居住的城市，不是本次航班的出发机场。",
    }),
  },
  {
    field_name: "arrival_date",
    label: "Date of Arrival in Japan",
    field_type: "date",
    required: true,
    step_number: 2,
    step_name: "Arrival and Stay",
    display_order: 1,
    validation_rules: rules("抵达日本日期", {
      format: "YYYY-MM-DD",
      timezone: "Asia/Tokyo",
      official_control_type: "date",
    }),
  },
  {
    field_name: "arrival_airport",
    label: "Intended Arrival Airport in Japan",
    field_type: "computed",
    required: false,
    step_number: 2,
    step_name: "Arrival and Stay",
    display_order: 2,
    conditional_logic: showIf("false"),
    validation_rules: hiddenCompatibilityRules("计划入境机场", "arrival_airline + flight_number"),
  },
  {
    field_name: "arrival_airline",
    label: "Arrival Airline",
    field_type: "select",
    required: true,
    step_number: 2,
    step_name: "Arrival and Stay",
    display_order: 3,
    options: JP_VJW_AIRLINE_OPTIONS,
    validation_rules: rules("抵达航空公司", {
      official_control: "airlineCompany",
      official_control_type: "select",
      official_options_source: JP_VJW_OFFICIAL_MASTER_SOURCE.sourceUrl,
      official_options_schema_version: JP_VJW_OFFICIAL_MASTER_SOURCE.schemaVersion,
      official_options_sha256: JP_VJW_OFFICIAL_MASTER_SOURCE.sha256,
      option_identity: "IATA two-character code",
      helper_zh: "请选择承运航空公司；列表值与当前 Visit Japan Web 官网下拉选项一致。",
    }),
  },
  {
    field_name: "flight_number",
    label: "Flight Number",
    field_type: "text",
    required: true,
    step_number: 2,
    step_name: "Arrival and Stay",
    display_order: 4,
    validation_rules: rules("抵达航班号（仅填写数字部分）", {
      maxLength: 8,
      pattern: "^[0-9]{1,8}$",
      official_control: "flightNumber",
      helper_zh: "航空公司已在上一项单独选择，此处只填写航班号中的数字，例如 NH900 填写 900。",
    }),
  },
  {
    field_name: "last_embarkation_country",
    label: "Country/Region of Last Embarkation",
    field_type: "computed",
    required: false,
    step_number: 2,
    step_name: "Arrival and Stay",
    display_order: 5,
    conditional_logic: showIf("false"),
    validation_rules: hiddenCompatibilityRules("最后出发国家 / 地区", "departure_city_or_port"),
  },
  {
    field_name: "departure_city_or_port",
    label: "City/Port of Embarkation",
    field_type: "text",
    required: true,
    step_number: 2,
    step_name: "Arrival and Stay",
    display_order: 6,
    options: JP_VJW_EMBARKATION_POINT_OPTIONS,
    validation_rules: rules("出发城市 / 港口", {
      maxLength: 120,
      official_control: "departurePoint",
      official_control_type: "text_autocomplete_with_free_entry",
      suggestions_source: JP_VJW_OFFICIAL_MASTER_SOURCE.sourceUrl,
      suggestions_schema_version: JP_VJW_OFFICIAL_MASTER_SOURCE.schemaVersion,
      option_identity: "official English place name",
      allow_custom_value: true,
      helper_zh: "请输入并从官网同源建议中选择出发城市或港口；官网允许列表外地点时也可直接填写英文。",
    }),
  },
  {
    field_name: "purpose_of_visit",
    label: "Purpose of Visit",
    field_type: "select",
    required: true,
    step_number: 2,
    step_name: "Arrival and Stay",
    display_order: 7,
    options: PURPOSE_OPTIONS,
    validation_rules: rules("访问目的", {
      first_phase_value: "0",
      official_control_type: "select",
      option_identity: "official purpose code",
    }),
  },
  {
    field_name: "planned_stay_days",
    label: "Planned Length of Stay (days)",
    field_type: "number",
    required: true,
    step_number: 2,
    step_name: "Arrival and Stay",
    display_order: 8,
    validation_rules: rules("计划停留天数", { integer: true, min: 1, max: 90 }),
  },
  {
    field_name: "accommodation_postal_code",
    label: "Postal Code in Japan",
    field_type: "text",
    required: false,
    step_number: 2,
    step_name: "Arrival and Stay",
    display_order: 9,
    validation_rules: rules("日本邮政编码", {
      pattern: "^[0-9]{3}-?[0-9]{4}$",
      official_control: "postalCode",
      official_control_type: "text",
      helper_zh: "如填写，请输入 7 位日本邮政编码；VIZA 会在官网核对并尝试自动填写都道府县和城市。",
    }),
  },
  {
    field_name: "accommodation_prefecture",
    label: "Prefecture of Accommodation in Japan",
    field_type: "select",
    required: true,
    step_number: 2,
    step_name: "Arrival and Stay",
    display_order: 10,
    options: JP_VJW_PREFECTURE_OPTIONS,
    validation_rules: rules("日本住宿所在都道府县", {
      official_control: "prefecture",
      official_control_type: "select",
      official_options_source: JP_VJW_OFFICIAL_MASTER_SOURCE.sourceUrl,
      official_options_schema_version: JP_VJW_OFFICIAL_MASTER_SOURCE.schemaVersion,
      option_identity: "official prefecture code",
      helper_zh: "请选择住宿地址所在都道府县；选项与当前 Visit Japan Web 官网一致。",
    }),
  },
  {
    field_name: "accommodation_city",
    label: "City/Ward/Town of Accommodation in Japan",
    field_type: "select",
    required: true,
    step_number: 2,
    step_name: "Arrival and Stay",
    display_order: 11,
    validation_rules: rules("日本住宿所在市区町村", {
      official_control: "city",
      official_control_type: "select",
      dependent_on: "accommodation_prefecture",
      dependent_options: JP_VJW_CITIES_BY_PREFECTURE,
      official_options_source: JP_VJW_OFFICIAL_MASTER_SOURCE.sourceUrl,
      official_options_schema_version: JP_VJW_OFFICIAL_MASTER_SOURCE.schemaVersion,
      option_identity: "official English city/ward/town name",
      helper_zh: "请先选择都道府县，再从当前 Visit Japan Web 官网同源列表中选择市区町村。",
    }),
  },
  {
    field_name: "accommodation_address",
    label: "Address in Japan",
    field_type: "text",
    required: true,
    step_number: 2,
    step_name: "Arrival and Stay",
    display_order: 12,
    validation_rules: rules("日本住宿町名、丁目和门牌号（英文）", {
      maxLength: 45,
      official_control: "address",
      official_control_type: "text",
      helper_zh: "这里只填写町名、丁目和门牌号；都道府县与市区町村请填写在上方对应项目。",
    }),
  },
  {
    field_name: "accommodation_name",
    label: "Hotel or Accommodation Name",
    field_type: "text",
    required: true,
    step_number: 2,
    step_name: "Arrival and Stay",
    display_order: 13,
    validation_rules: rules("酒店或住宿名称（英文）", {
      maxLength: 100,
      official_control: "placeOfStay",
    }),
  },
  {
    field_name: "accommodation_phone",
    label: "Accommodation Telephone Number",
    field_type: "text",
    required: true,
    step_number: 2,
    step_name: "Arrival and Stay",
    display_order: 14,
    validation_rules: rules("日本境内可联系的住宿电话", {
      pattern: "^[0-9]{10,15}$",
      minLength: 10,
      maxLength: 15,
      official_control: "telephoneNumberInJapan",
      helper_zh: "只填写 10 至 15 位数字，不含加号、空格或连字符。",
      specific_error_zh: "住宿电话必须为 10 至 15 位数字。",
    }),
  },
  {
    field_name: "has_been_deported",
    label: "Have you ever been deported from Japan, departed under a departure order, or been denied entry to Japan?",
    field_type: "radio",
    required: true,
    step_number: 3,
    step_name: "Immigration Declaration",
    display_order: 1,
    options: YES_NO,
    validation_rules: rules("您是否曾被日本强制遣返、根据出国命令离境或被日本拒绝入境？", {
      immigration_question: true,
      official_source_url: "https://www.moj.go.jp/isa/content/930002134.pdf",
    }),
  },
  {
    field_name: "has_criminal_record",
    label: "Have you ever been found guilty in a criminal case in Japan or in another country?",
    field_type: "radio",
    required: true,
    step_number: 3,
    step_name: "Immigration Declaration",
    display_order: 2,
    options: YES_NO,
    validation_rules: rules("您是否曾在日本或其他国家的刑事案件中被判有罪？", {
      immigration_question: true,
      official_source_url: "https://www.moj.go.jp/isa/content/930002134.pdf",
    }),
  },
  {
    field_name: "has_controlled_substances_or_weapons",
    label: "Do you presently have narcotics, marijuana, opium, stimulants or other controlled substances, firearms, crossbows, swords, explosives or similar items in your possession?",
    field_type: "radio",
    required: true,
    step_number: 3,
    step_name: "Immigration Declaration",
    display_order: 3,
    options: YES_NO,
    validation_rules: rules("您目前是否持有麻醉品、大麻、鸦片、兴奋剂等管制药物，或枪支、弩、刀剑、爆炸物等类似物品？", {
      immigration_question: true,
      official_source_url: "https://www.moj.go.jp/isa/content/930002134.pdf",
      legacy_aliases: ["has_drug_or_trafficking_history"],
    }),
  },
  {
    field_name: "has_prohibited_or_restricted_goods",
    label: "Legacy combined prohibited/restricted-goods answer",
    field_type: "computed",
    required: false,
    step_number: 4,
    step_name: "Customs Declaration",
    display_order: 1,
    conditional_logic: showIf("false"),
    validation_rules: rules("旧版禁止或限制进口物品合并答案", {
      legacy_only: true,
      no_user_input: true,
      replaced_by: ["has_prohibited_goods", "has_restricted_goods"],
    }),
  },
  {
    field_name: "has_prohibited_goods",
    label: "Are you carrying prohibited articles into Japan?",
    field_type: "radio",
    required: true,
    step_number: 4,
    step_name: "Customs Declaration",
    display_order: 2,
    options: YES_NO,
    validation_rules: rules("您是否携带日本禁止入境的物品？", {
      customs_question: true,
      official_control: "question01",
      helper_zh: "包括毒品、枪支、爆炸物、假币等日本海关禁止进口的物品。",
    }),
  },
  {
    field_name: "has_restricted_goods",
    label: "Are you carrying restricted articles into Japan?",
    field_type: "radio",
    required: true,
    step_number: 4,
    step_name: "Customs Declaration",
    display_order: 3,
    options: YES_NO,
    validation_rules: rules("您是否携带需要许可、检疫或申报的限制入境物品？", {
      customs_question: true,
      official_control: "question02",
      helper_zh: "包括肉类、蔬果、动植物、药品等可能需要检疫、许可或额外申报的物品。",
    }),
  },
  {
    field_name: "has_gold_or_gold_products",
    label: "Are you carrying gold bullion or gold products?",
    field_type: "radio",
    required: true,
    step_number: 4,
    step_name: "Customs Declaration",
    display_order: 4,
    options: YES_NO,
    validation_rules: rules("您是否携带黄金（金条、金块）或黄金制品？", {
      customs_question: true,
      official_control: "question03",
    }),
  },
  {
    field_name: "has_dutiable_goods",
    label: "Are you carrying goods exceeding the duty-free allowance?",
    field_type: "radio",
    required: true,
    step_number: 4,
    step_name: "Customs Declaration",
    display_order: 5,
    options: YES_NO,
    validation_rules: rules("是否携带超过免税额度的物品？", { customs_question: true }),
  },
  {
    field_name: "has_commercial_goods",
    label: "Are you carrying commercial goods or samples?",
    field_type: "radio",
    required: true,
    step_number: 4,
    step_name: "Customs Declaration",
    display_order: 6,
    options: YES_NO,
    validation_rules: rules("是否携带商业货物或样品？", { customs_question: true }),
  },
  {
    field_name: "has_goods_for_other_person",
    label: "Are you carrying goods entrusted to you by another person?",
    field_type: "radio",
    required: true,
    step_number: 4,
    step_name: "Customs Declaration",
    display_order: 7,
    options: YES_NO,
    validation_rules: rules("是否携带他人委托您携带的物品？", { customs_question: true }),
  },
  {
    field_name: "has_unaccompanied_baggage",
    label: "Are you carrying unaccompanied baggage?",
    field_type: "radio",
    required: true,
    step_number: 4,
    step_name: "Customs Declaration",
    display_order: 8,
    options: YES_NO,
    validation_rules: rules("是否有托运以外的非随身行李？", { customs_question: true }),
  },
  {
    field_name: "has_cash_or_valuables_over_threshold",
    label: "Are you carrying cash or other means of payment above the declaration threshold?",
    field_type: "radio",
    required: true,
    step_number: 4,
    step_name: "Customs Declaration",
    display_order: 9,
    options: YES_NO,
    validation_rules: rules("是否携带超过申报门槛的现金或支付工具？", {
      customs_question: true,
      threshold_must_be_confirmed_from_current_japan_customs_guidance: true,
    }),
  },
  {
    field_name: "customs_declaration",
    label: "Customs Declaration (derived from the individual customs answers)",
    field_type: "computed",
    required: false,
    step_number: 4,
    step_name: "Customs Declaration",
    display_order: 10,
    conditional_logic: showIf("false"),
    validation_rules: rules("海关申报（由各项海关答案汇总）", {
      runner_canonical_key: "customs_declaration",
      derived_from: [
        "has_prohibited_goods",
        "has_restricted_goods",
        "has_gold_or_gold_products",
        "has_dutiable_goods",
        "has_commercial_goods",
        "has_goods_for_other_person",
        "has_unaccompanied_baggage",
        "has_cash_or_valuables_over_threshold",
      ],
      aggregation: "yes_if_any_customs_answer_is_yes_else_no",
      no_user_input: true,
      do_not_ask_as_single_customs_question: true,
    }),
  },
  {
    field_name: "customs_declaration_confirmed",
    label: "The above entry is true and correct.",
    field_type: "checkbox",
    required: true,
    step_number: 4,
    step_name: "Customs Declaration",
    display_order: 11,
    validation_rules: rules("我确认上述填写内容真实且正确", {
      final_review: true,
      boolean_contract: "must_be_true",
      official_value: "true",
      official_control: "confirmChk",
      official_control_type: "checkbox",
      helper_priority: "critical",
      helper_zh: "此为 Visit Japan Web 入境审查与海关申报合并流程的最终确认。请在核对旅客、行程、住宿、入境审查及海关答案后勾选；VIZA 将按这些已确认信息提交官网并生成二维码。",
    }),
  },
  {
    field_name: "immigration_declaration",
    label: "I have reviewed the immigration declaration answers above and confirm that they are complete and truthful.",
    field_type: "computed",
    required: false,
    step_number: 3,
    step_name: "Immigration Declaration",
    display_order: 4,
    conditional_logic: showIf("false"),
    validation_rules: rules("旧版入境申报确认", {
      runner_canonical_key: "immigration_declaration",
      no_user_input: true,
      legacy_compatibility_only: true,
      replaced_by: "customs_declaration_confirmed",
    }),
  },
  {
    field_name: "final_declaration",
    label: "Final Declaration (derived from the official final confirmation)",
    field_type: "computed",
    required: false,
    step_number: 4,
    step_name: "Customs Declaration",
    display_order: 12,
    conditional_logic: showIf("false"),
    validation_rules: rules("最终申报（由官网最终确认生成）", {
      runner_canonical_key: "final_declaration",
      derived_from: ["customs_declaration_confirmed"],
      no_user_input: true,
      aggregation: "yes_only_when_official_confirmation_is_true",
    }),
  },
];

export const JP_VISIT_JAPAN_WEB_OFFICIAL_FIELD_NAMES =
  JP_VISIT_JAPAN_WEB_FORM_FIELDS.map((field) => field.field_name);

export function bilingualJpVjwRows() {
  return JP_VISIT_JAPAN_WEB_FORM_FIELDS.map((field) =>
    toBilingualSeedRow(JP_VISIT_JAPAN_WEB_VISA_TYPE, field),
  );
}
