/**
 * Seed script: visa_form_fields for DS-160 (US nonimmigrant visa)
 * Parses LARK_EXTRACTED.md + DATA_SCHEMA.md to build structured field definitions.
 * Run: npm run seed:ds160-form-fields
 */

import * as dotenv from "dotenv";
import * as path from "path";
import { fileURLToPath } from "url";
import { createClient } from "@supabase/supabase-js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.join(__dirname, "../.env") });

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;
if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY");
  process.exit(1);
}
const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

// ─── DS-160 Field Definitions ───────────────────────────────────────────────
// Derived from LARK_EXTRACTED.md (19 sections) + DATA_SCHEMA.md
// step_number maps to DS-160 logical sections (1–11 + security)

interface FieldDef {
  field_name: string;
  label: string;
  field_type: string;
  required: boolean;
  step_number: number;
  step_name: string;
  display_order: number;
  placeholder?: string;
  validation_rules?: Record<string, unknown>;
  options?: Array<{ value: string; text: string }>;
  conditional_logic?: Record<string, unknown>;
}

const FIELDS: FieldDef[] = [
  // ─── STEP 1: Personal Information I ───────────────────────────────────────
  {
    field_name: "surname",
    label: "Surname (as in passport)",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: "Personal Information",
    display_order: 1,
    placeholder: "e.g. SMITH",
    validation_rules: { maxLength: 33, uppercase: true, message: "Enter as it appears on your passport" },
  },
  {
    field_name: "given_names",
    label: "Given Names (as in passport)",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: "Personal Information",
    display_order: 2,
    placeholder: "e.g. JOHN MICHAEL",
    validation_rules: { maxLength: 33, message: "Enter all given names as in passport" },
  },
  {
    field_name: "full_name_native_alphabet",
    label: "Full Name in Native Alphabet",
    field_type: "text",
    required: false,
    step_number: 1,
    step_name: "Personal Information",
    display_order: 3,
    placeholder: "If applicable",
    conditional_logic: { showIf: "non_roman_script_nationality" },
  },
  {
    field_name: "telecode",
    label: "Telecode (4-digit non-Roman script code)",
    field_type: "text",
    required: false,
    step_number: 1,
    step_name: "Personal Information",
    display_order: 4,
    placeholder: "4-digit code",
    validation_rules: { pattern: "^[0-9]{4}$", message: "Must be a 4-digit numeric code" },
    conditional_logic: { showIf: "full_name_native_alphabet !== null" },
  },
  {
    field_name: "other_names_used",
    label: "Have you used any other names?",
    field_type: "radio",
    required: true,
    step_number: 1,
    step_name: "Personal Information",
    display_order: 5,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "other_name_surname",
    label: "Other Name — Surname",
    field_type: "text",
    required: false,
    step_number: 1,
    step_name: "Personal Information",
    display_order: 6,
    conditional_logic: { showIf: "other_names_used === yes" },
  },
  {
    field_name: "other_name_given_names",
    label: "Other Name — Given Names",
    field_type: "text",
    required: false,
    step_number: 1,
    step_name: "Personal Information",
    display_order: 7,
    conditional_logic: { showIf: "other_names_used === yes" },
  },
  {
    field_name: "other_name_type",
    label: "Other Name — Type",
    field_type: "select",
    required: false,
    step_number: 1,
    step_name: "Personal Information",
    display_order: 8,
    options: [
      { value: "maiden", text: "Maiden Name" },
      { value: "alias", text: "Alias" },
      { value: "professional", text: "Professional Name" },
      { value: "religious", text: "Religious Name" },
      { value: "other", text: "Other" },
    ],
    conditional_logic: { showIf: "other_names_used === yes" },
  },
  {
    field_name: "sex",
    label: "Sex",
    field_type: "radio",
    required: true,
    step_number: 1,
    step_name: "Personal Information",
    display_order: 9,
    options: [{ value: "male", text: "Male" }, { value: "female", text: "Female" }],
  },
  {
    field_name: "marital_status",
    label: "Marital Status",
    field_type: "select",
    required: true,
    step_number: 1,
    step_name: "Personal Information",
    display_order: 10,
    options: [
      { value: "single", text: "Single" },
      { value: "married", text: "Married" },
      { value: "widowed", text: "Widowed" },
      { value: "divorced", text: "Divorced" },
      { value: "separated", text: "Separated" },
      { value: "other", text: "Other" },
    ],
  },
  {
    field_name: "date_of_birth",
    label: "Date of Birth",
    field_type: "date",
    required: true,
    step_number: 1,
    step_name: "Personal Information",
    display_order: 11,
    placeholder: "DD/MM/YYYY",
    validation_rules: { format: "DD-MMM-YYYY", message: "Must match passport" },
  },
  {
    field_name: "city_of_birth",
    label: "City of Birth",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: "Personal Information",
    display_order: 12,
    placeholder: "e.g. Singapore",
  },
  {
    field_name: "state_of_birth",
    label: "State/Province of Birth",
    field_type: "text",
    required: false,
    step_number: 1,
    step_name: "Personal Information",
    display_order: 13,
    placeholder: "If applicable",
  },
  {
    field_name: "country_of_birth",
    label: "Country/Region of Birth",
    field_type: "select",
    required: true,
    step_number: 1,
    step_name: "Personal Information",
    display_order: 14,
    options: [{ value: "SG", text: "SINGAPORE" }, { value: "CN", text: "CHINA" }, { value: "IN", text: "INDIA" }], // abbreviated; full list in app
    validation_rules: { source: "ISO3166-1", message: "Select country from list" },
  },
  // ─── STEP 2: Personal Information II (Nationality, IDs) ────────────────────
  {
    field_name: "nationality_country",
    label: "Country/Region of Origin (Nationality)",
    field_type: "select",
    required: true,
    step_number: 2,
    step_name: "Personal Information II",
    display_order: 1,
    validation_rules: { source: "ISO3166-1" },
  },
  {
    field_name: "other_nationality",
    label: "Hold/held another nationality?",
    field_type: "radio",
    required: true,
    step_number: 2,
    step_name: "Personal Information II",
    display_order: 2,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
    validation_rules: { message: "Include all nationalities ever held, including relinquished ones" },
  },
  {
    field_name: "other_nationality_country",
    label: "Other Country/Region of Nationality",
    field_type: "select",
    required: false,
    step_number: 2,
    step_name: "Personal Information II",
    display_order: 3,
    conditional_logic: { showIf: "other_nationality === yes" },
  },
  {
    field_name: "other_nationality_has_passport",
    label: "Do you hold a passport for that other nationality?",
    field_type: "radio",
    required: false,
    step_number: 2,
    step_name: "Personal Information II",
    display_order: 4,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
    conditional_logic: { showIf: "other_nationality === yes" },
  },
  {
    field_name: "permanent_resident_other_country",
    label: "Permanent resident of another country/region?",
    field_type: "radio",
    required: true,
    step_number: 2,
    step_name: "Personal Information II",
    display_order: 5,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
    validation_rules: { message: "Permanent resident = legally granted unlimited right to live/work" },
  },
  {
    field_name: "other_permanent_resident_country",
    label: "Other Permanent Resident Country/Region",
    field_type: "select",
    required: false,
    step_number: 2,
    step_name: "Personal Information II",
    display_order: 6,
    conditional_logic: { showIf: "permanent_resident_other_country === yes" },
  },
  {
    field_name: "national_id_number",
    label: "National Identification Number",
    field_type: "text",
    required: false,
    step_number: 2,
    step_name: "Personal Information II",
    display_order: 7,
    placeholder: "Home country national ID",
    options: [{ value: "does_not_apply", text: "Does Not Apply" }],
  },
  {
    field_name: "us_social_security_number",
    label: "U.S. Social Security Number",
    field_type: "text",
    required: false,
    step_number: 2,
    step_name: "Personal Information II",
    display_order: 8,
    placeholder: "XXX-XX-XXXX",
    validation_rules: { pattern: "^[0-9]{3}-[0-9]{2}-[0-9]{4}$" },
    options: [{ value: "does_not_apply", text: "Does Not Apply" }],
  },
  {
    field_name: "us_taxpayer_id",
    label: "U.S. Taxpayer ID Number",
    field_type: "text",
    required: false,
    step_number: 2,
    step_name: "Personal Information II",
    display_order: 9,
    options: [{ value: "does_not_apply", text: "Does Not Apply" }],
  },
  // ─── STEP 3: Travel Information ────────────────────────────────────────────
  {
    field_name: "purpose_of_trip",
    label: "Purpose of Trip to the U.S.",
    field_type: "select",
    required: true,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 1,
    options: [
      { value: "tourism", text: "Tourism/Pleasure" },
      { value: "business", text: "Business/Conference" },
      { value: "medical", text: "Medical Treatment" },
      { value: "transit", text: "Transit" },
      { value: "student", text: "Student (F/M)" },
      { value: "exchange_visitor", text: "Exchange Visitor (J)" },
      { value: "work", text: "Temporary Employment" },
      { value: "other", text: "Other" },
    ],
  },
  {
    field_name: "has_specific_plans",
    label: "Have you made specific travel plans?",
    field_type: "radio",
    required: true,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 2,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "intended_arrival_date",
    label: "Intended Date of Arrival in U.S.",
    field_type: "date",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 3,
    placeholder: "DD/MM/YYYY",
    conditional_logic: { showIf: "has_specific_plans === yes" },
  },
  {
    field_name: "intended_length_of_stay",
    label: "Intended Length of Stay",
    field_type: "text",
    required: true,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 4,
    placeholder: "e.g. 2 weeks, 6 months",
  },
  {
    field_name: "us_address_street",
    label: "U.S. Address — Street (where you will stay)",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 5,
    conditional_logic: { showIf: "has_specific_plans === yes" },
  },
  {
    field_name: "us_address_city",
    label: "U.S. Address — City",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 6,
    conditional_logic: { showIf: "has_specific_plans === yes" },
  },
  {
    field_name: "us_address_state",
    label: "U.S. Address — State",
    field_type: "select",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 7,
    conditional_logic: { showIf: "has_specific_plans === yes" },
    options: [
      { value: "AL", text: "Alabama" }, { value: "AK", text: "Alaska" }, { value: "AZ", text: "Arizona" },
      { value: "CA", text: "California" }, { value: "CO", text: "Colorado" }, { value: "CT", text: "Connecticut" },
      { value: "FL", text: "Florida" }, { value: "GA", text: "Georgia" }, { value: "HI", text: "Hawaii" },
      { value: "IL", text: "Illinois" }, { value: "MA", text: "Massachusetts" }, { value: "MD", text: "Maryland" },
      { value: "MI", text: "Michigan" }, { value: "MN", text: "Minnesota" }, { value: "MO", text: "Missouri" },
      { value: "NJ", text: "New Jersey" }, { value: "NY", text: "New York" }, { value: "NC", text: "North Carolina" },
      { value: "OH", text: "Ohio" }, { value: "PA", text: "Pennsylvania" }, { value: "TX", text: "Texas" },
      { value: "VA", text: "Virginia" }, { value: "WA", text: "Washington" }, { value: "WI", text: "Wisconsin" },
      { value: "DC", text: "District of Columbia" }, { value: "other", text: "Other" },
    ],
  },
  {
    field_name: "us_address_zip",
    label: "U.S. Address — ZIP Code",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 8,
    validation_rules: { pattern: "^[0-9]{5}(-[0-9]{4})?$" },
    conditional_logic: { showIf: "has_specific_plans === yes" },
  },
  {
    field_name: "trip_payer_type",
    label: "Who is paying for your trip?",
    field_type: "select",
    required: true,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 9,
    options: [
      { value: "self", text: "Self" },
      { value: "other_person", text: "Other Person" },
      { value: "organization", text: "Company/Organization" },
    ],
  },
  {
    field_name: "payer_name",
    label: "Payer — Name",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 10,
    conditional_logic: { showIf: "trip_payer_type !== self" },
  },
  {
    field_name: "payer_relationship",
    label: "Payer — Relationship to Applicant",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 11,
    conditional_logic: { showIf: "trip_payer_type === other_person" },
  },
  {
    field_name: "payer_phone",
    label: "Payer — Phone",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 12,
    conditional_logic: { showIf: "trip_payer_type !== self" },
  },
  {
    field_name: "payer_email",
    label: "Payer — Email",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 13,
    conditional_logic: { showIf: "trip_payer_type !== self" },
  },
  // ─── STEP 4: Travel Companions ──────────────────────────────────────────────
  {
    field_name: "has_companions",
    label: "Are you traveling with companions?",
    field_type: "radio",
    required: true,
    step_number: 4,
    step_name: "Travel Companions",
    display_order: 1,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "companion_group_travel",
    label: "Traveling as part of a group/organization?",
    field_type: "radio",
    required: false,
    step_number: 4,
    step_name: "Travel Companions",
    display_order: 2,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
    conditional_logic: { showIf: "has_companions === yes" },
  },
  {
    field_name: "companion_group_name",
    label: "Group/Organization Name",
    field_type: "text",
    required: false,
    step_number: 4,
    step_name: "Travel Companions",
    display_order: 3,
    conditional_logic: { showIf: "companion_group_travel === yes" },
  },
  {
    field_name: "companion_surname",
    label: "Companion — Surname",
    field_type: "text",
    required: false,
    step_number: 4,
    step_name: "Travel Companions",
    display_order: 4,
    conditional_logic: { showIf: "has_companions === yes && companion_group_travel === no" },
  },
  {
    field_name: "companion_given_names",
    label: "Companion — Given Names",
    field_type: "text",
    required: false,
    step_number: 4,
    step_name: "Travel Companions",
    display_order: 5,
    conditional_logic: { showIf: "has_companions === yes && companion_group_travel === no" },
  },
  {
    field_name: "companion_relationship",
    label: "Companion — Relationship",
    field_type: "text",
    required: false,
    step_number: 4,
    step_name: "Travel Companions",
    display_order: 6,
    conditional_logic: { showIf: "has_companions === yes && companion_group_travel === no" },
  },
  // ─── STEP 5: Previous U.S. Travel ──────────────────────────────────────────
  {
    field_name: "has_been_in_us",
    label: "Have you ever been in the U.S.?",
    field_type: "radio",
    required: true,
    step_number: 5,
    step_name: "Previous US Travel",
    display_order: 1,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "previous_visit_date_arrived",
    label: "Previous Visit — Date Arrived",
    field_type: "date",
    required: false,
    step_number: 5,
    step_name: "Previous US Travel",
    display_order: 2,
    conditional_logic: { showIf: "has_been_in_us === yes" },
  },
  {
    field_name: "previous_visit_length_of_stay",
    label: "Previous Visit — Length of Stay",
    field_type: "text",
    required: false,
    step_number: 5,
    step_name: "Previous US Travel",
    display_order: 3,
    conditional_logic: { showIf: "has_been_in_us === yes" },
  },
  {
    field_name: "previous_visit_immigration_status",
    label: "Previous Visit — Immigration Status",
    field_type: "text",
    required: false,
    step_number: 5,
    step_name: "Previous US Travel",
    display_order: 4,
    conditional_logic: { showIf: "has_been_in_us === yes" },
  },
  {
    field_name: "has_previous_us_visa",
    label: "Have you previously held a U.S. visa?",
    field_type: "radio",
    required: true,
    step_number: 5,
    step_name: "Previous US Travel",
    display_order: 5,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "previous_visa_date_issued",
    label: "Previous Visa — Date Issued",
    field_type: "date",
    required: false,
    step_number: 5,
    step_name: "Previous US Travel",
    display_order: 6,
    conditional_logic: { showIf: "has_previous_us_visa === yes" },
  },
  {
    field_name: "previous_visa_number",
    label: "Previous Visa — Visa Number",
    field_type: "text",
    required: false,
    step_number: 5,
    step_name: "Previous US Travel",
    display_order: 7,
    conditional_logic: { showIf: "has_previous_us_visa === yes" },
  },
  {
    field_name: "previous_visa_same_type",
    label: "Same type as current application?",
    field_type: "radio",
    required: false,
    step_number: 5,
    step_name: "Previous US Travel",
    display_order: 8,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
    conditional_logic: { showIf: "has_previous_us_visa === yes" },
  },
  {
    field_name: "previous_visa_same_country",
    label: "Applied in same country as current?",
    field_type: "radio",
    required: false,
    step_number: 5,
    step_name: "Previous US Travel",
    display_order: 9,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
    conditional_logic: { showIf: "has_previous_us_visa === yes" },
  },
  {
    field_name: "previous_visa_lost_stolen",
    label: "Was previous visa ever lost or stolen?",
    field_type: "radio",
    required: false,
    step_number: 5,
    step_name: "Previous US Travel",
    display_order: 10,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
    conditional_logic: { showIf: "has_previous_us_visa === yes" },
  },
  {
    field_name: "has_been_refused",
    label: "Has your U.S. visa ever been refused or revoked?",
    field_type: "radio",
    required: true,
    step_number: 5,
    step_name: "Previous US Travel",
    display_order: 11,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "refusal_details",
    label: "Refusal/Revocation — Details",
    field_type: "textarea",
    required: false,
    step_number: 5,
    step_name: "Previous US Travel",
    display_order: 12,
    conditional_logic: { showIf: "has_been_refused === yes" },
  },
  {
    field_name: "immigrant_petition_filed",
    label: "Has anyone ever filed an immigrant petition on your behalf?",
    field_type: "radio",
    required: true,
    step_number: 5,
    step_name: "Previous US Travel",
    display_order: 13,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  // ─── STEP 6: Address & Phone ────────────────────────────────────────────────
  {
    field_name: "home_address_line1",
    label: "Home Address — Street Address Line 1",
    field_type: "text",
    required: true,
    step_number: 6,
    step_name: "Address and Phone Information",
    display_order: 1,
  },
  {
    field_name: "home_address_line2",
    label: "Home Address — Street Address Line 2",
    field_type: "text",
    required: false,
    step_number: 6,
    step_name: "Address and Phone Information",
    display_order: 2,
  },
  {
    field_name: "home_address_city",
    label: "Home Address — City",
    field_type: "text",
    required: true,
    step_number: 6,
    step_name: "Address and Phone Information",
    display_order: 3,
  },
  {
    field_name: "home_address_state_province",
    label: "Home Address — State/Province",
    field_type: "text",
    required: false,
    step_number: 6,
    step_name: "Address and Phone Information",
    display_order: 4,
  },
  {
    field_name: "home_address_postal_code",
    label: "Home Address — Postal Code",
    field_type: "text",
    required: false,
    step_number: 6,
    step_name: "Address and Phone Information",
    display_order: 5,
  },
  {
    field_name: "home_address_country",
    label: "Home Address — Country/Region",
    field_type: "select",
    required: true,
    step_number: 6,
    step_name: "Address and Phone Information",
    display_order: 6,
  },
  {
    field_name: "mailing_same_as_home",
    label: "Is mailing address same as home?",
    field_type: "radio",
    required: true,
    step_number: 6,
    step_name: "Address and Phone Information",
    display_order: 7,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "primary_phone",
    label: "Primary Phone Number",
    field_type: "text",
    required: true,
    step_number: 6,
    step_name: "Address and Phone Information",
    display_order: 8,
    placeholder: "+65 9xxx xxxx",
    validation_rules: { message: "Include country code" },
  },
  {
    field_name: "secondary_phone",
    label: "Secondary Phone Number",
    field_type: "text",
    required: false,
    step_number: 6,
    step_name: "Address and Phone Information",
    display_order: 9,
  },
  {
    field_name: "work_phone",
    label: "Work Phone Number",
    field_type: "text",
    required: false,
    step_number: 6,
    step_name: "Address and Phone Information",
    display_order: 10,
  },
  {
    field_name: "email_address",
    label: "Email Address",
    field_type: "text",
    required: true,
    step_number: 6,
    step_name: "Address and Phone Information",
    display_order: 11,
    validation_rules: { format: "email" },
  },
  {
    field_name: "social_media_platform",
    label: "Social Media — Platform",
    field_type: "select",
    required: false,
    step_number: 6,
    step_name: "Address and Phone Information",
    display_order: 12,
    options: [
      { value: "facebook", text: "Facebook/Instagram" },
      { value: "twitter_x", text: "Twitter/X" },
      { value: "linkedin", text: "LinkedIn" },
      { value: "youtube", text: "YouTube" },
      { value: "tiktok", text: "TikTok" },
      { value: "other", text: "Other" },
    ],
    validation_rules: { message: "List all social media used in last 5 years" },
  },
  {
    field_name: "social_media_handle",
    label: "Social Media — Handle/Username",
    field_type: "text",
    required: false,
    step_number: 6,
    step_name: "Address and Phone Information",
    display_order: 13,
    conditional_logic: { showIf: "social_media_platform !== null" },
  },
  // ─── STEP 7: Passport ───────────────────────────────────────────────────────
  {
    field_name: "passport_document_type",
    label: "Passport/Travel Document Type",
    field_type: "select",
    required: true,
    step_number: 7,
    step_name: "Passport Information",
    display_order: 1,
    options: [
      { value: "regular", text: "Regular" },
      { value: "official", text: "Official" },
      { value: "diplomatic", text: "Diplomatic" },
      { value: "laissez_passer", text: "Laissez-Passer" },
      { value: "other", text: "Other" },
    ],
  },
  {
    field_name: "passport_number",
    label: "Passport/Travel Document Number",
    field_type: "text",
    required: true,
    step_number: 7,
    step_name: "Passport Information",
    display_order: 2,
    placeholder: "e.g. E1234567",
    validation_rules: { maxLength: 20, message: "Enter the number on the travel document you will use" },
  },
  {
    field_name: "passport_book_number",
    label: "Passport Book Number (if applicable)",
    field_type: "text",
    required: false,
    step_number: 7,
    step_name: "Passport Information",
    display_order: 3,
    options: [{ value: "does_not_apply", text: "Does Not Apply" }],
  },
  {
    field_name: "passport_issuing_country",
    label: "Country/Authority that Issued Passport",
    field_type: "select",
    required: true,
    step_number: 7,
    step_name: "Passport Information",
    display_order: 4,
  },
  {
    field_name: "passport_issuance_date",
    label: "Passport Issuance Date",
    field_type: "date",
    required: true,
    step_number: 7,
    step_name: "Passport Information",
    display_order: 5,
    validation_rules: { message: "Must be in the past" },
  },
  {
    field_name: "passport_expiration_date",
    label: "Passport Expiration Date",
    field_type: "date",
    required: true,
    step_number: 7,
    step_name: "Passport Information",
    display_order: 6,
    validation_rules: {
      message: "Must be valid for at least 6 months beyond intended stay",
      min_months_from_arrival: 6,
    },
    options: [{ value: "does_not_expire", text: "Does Not Expire" }],
  },
  {
    field_name: "lost_passport",
    label: "Have you ever lost a passport or had one stolen?",
    field_type: "radio",
    required: true,
    step_number: 7,
    step_name: "Passport Information",
    display_order: 7,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "lost_passport_number",
    label: "Lost/Stolen Passport — Number",
    field_type: "text",
    required: false,
    step_number: 7,
    step_name: "Passport Information",
    display_order: 8,
    conditional_logic: { showIf: "lost_passport === yes" },
  },
  {
    field_name: "lost_passport_country",
    label: "Lost/Stolen Passport — Issuing Country",
    field_type: "select",
    required: false,
    step_number: 7,
    step_name: "Passport Information",
    display_order: 9,
    conditional_logic: { showIf: "lost_passport === yes" },
  },
  // ─── STEP 8: U.S. Point of Contact ─────────────────────────────────────────
  {
    field_name: "us_contact_surname",
    label: "U.S. Contact — Surname",
    field_type: "text",
    required: true,
    step_number: 8,
    step_name: "US Point of Contact",
    display_order: 1,
    options: [{ value: "does_not_apply", text: "Does Not Apply" }],
  },
  {
    field_name: "us_contact_given_names",
    label: "U.S. Contact — Given Names",
    field_type: "text",
    required: true,
    step_number: 8,
    step_name: "US Point of Contact",
    display_order: 2,
    options: [{ value: "does_not_apply", text: "Does Not Apply" }],
  },
  {
    field_name: "us_contact_organization",
    label: "U.S. Contact — Organization (if not a person)",
    field_type: "text",
    required: false,
    step_number: 8,
    step_name: "US Point of Contact",
    display_order: 3,
  },
  {
    field_name: "us_contact_relationship",
    label: "U.S. Contact — Relationship",
    field_type: "text",
    required: true,
    step_number: 8,
    step_name: "US Point of Contact",
    display_order: 4,
    placeholder: "e.g. Friend, Employer, Hotel",
  },
  {
    field_name: "us_contact_address_street",
    label: "U.S. Contact — Street Address",
    field_type: "text",
    required: true,
    step_number: 8,
    step_name: "US Point of Contact",
    display_order: 5,
  },
  {
    field_name: "us_contact_city",
    label: "U.S. Contact — City",
    field_type: "text",
    required: true,
    step_number: 8,
    step_name: "US Point of Contact",
    display_order: 6,
  },
  {
    field_name: "us_contact_state",
    label: "U.S. Contact — State",
    field_type: "select",
    required: true,
    step_number: 8,
    step_name: "US Point of Contact",
    display_order: 7,
  },
  {
    field_name: "us_contact_zip",
    label: "U.S. Contact — ZIP Code",
    field_type: "text",
    required: true,
    step_number: 8,
    step_name: "US Point of Contact",
    display_order: 8,
    validation_rules: { pattern: "^[0-9]{5}(-[0-9]{4})?$" },
  },
  {
    field_name: "us_contact_phone",
    label: "U.S. Contact — Phone",
    field_type: "text",
    required: true,
    step_number: 8,
    step_name: "US Point of Contact",
    display_order: 9,
  },
  {
    field_name: "us_contact_email",
    label: "U.S. Contact — Email",
    field_type: "text",
    required: false,
    step_number: 8,
    step_name: "US Point of Contact",
    display_order: 10,
    validation_rules: { format: "email" },
  },
  // ─── STEP 9: Family Information ─────────────────────────────────────────────
  {
    field_name: "father_surname",
    label: "Father — Surname",
    field_type: "text",
    required: true,
    step_number: 9,
    step_name: "Family Information",
    display_order: 1,
    options: [{ value: "unknown", text: "Unknown" }],
  },
  {
    field_name: "father_given_names",
    label: "Father — Given Names",
    field_type: "text",
    required: true,
    step_number: 9,
    step_name: "Family Information",
    display_order: 2,
    options: [{ value: "unknown", text: "Unknown" }],
  },
  {
    field_name: "father_date_of_birth",
    label: "Father — Date of Birth",
    field_type: "date",
    required: true,
    step_number: 9,
    step_name: "Family Information",
    display_order: 3,
    options: [{ value: "unknown", text: "Unknown" }],
  },
  {
    field_name: "father_in_us",
    label: "Is your father in the U.S.?",
    field_type: "radio",
    required: true,
    step_number: 9,
    step_name: "Family Information",
    display_order: 4,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "father_us_status",
    label: "Father — U.S. Immigration Status",
    field_type: "text",
    required: false,
    step_number: 9,
    step_name: "Family Information",
    display_order: 5,
    conditional_logic: { showIf: "father_in_us === yes" },
  },
  {
    field_name: "mother_surname",
    label: "Mother — Surname",
    field_type: "text",
    required: true,
    step_number: 9,
    step_name: "Family Information",
    display_order: 6,
    options: [{ value: "unknown", text: "Unknown" }],
  },
  {
    field_name: "mother_given_names",
    label: "Mother — Given Names",
    field_type: "text",
    required: true,
    step_number: 9,
    step_name: "Family Information",
    display_order: 7,
    options: [{ value: "unknown", text: "Unknown" }],
  },
  {
    field_name: "mother_date_of_birth",
    label: "Mother — Date of Birth",
    field_type: "date",
    required: true,
    step_number: 9,
    step_name: "Family Information",
    display_order: 8,
    options: [{ value: "unknown", text: "Unknown" }],
  },
  {
    field_name: "mother_in_us",
    label: "Is your mother in the U.S.?",
    field_type: "radio",
    required: true,
    step_number: 9,
    step_name: "Family Information",
    display_order: 9,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "mother_us_status",
    label: "Mother — U.S. Immigration Status",
    field_type: "text",
    required: false,
    step_number: 9,
    step_name: "Family Information",
    display_order: 10,
    conditional_logic: { showIf: "mother_in_us === yes" },
  },
  {
    field_name: "spouse_surname",
    label: "Spouse — Surname",
    field_type: "text",
    required: false,
    step_number: 9,
    step_name: "Family Information",
    display_order: 11,
    conditional_logic: { showIf: "marital_status === married OR separated" },
  },
  {
    field_name: "spouse_given_names",
    label: "Spouse — Given Names",
    field_type: "text",
    required: false,
    step_number: 9,
    step_name: "Family Information",
    display_order: 12,
    conditional_logic: { showIf: "marital_status === married OR separated" },
  },
  {
    field_name: "spouse_date_of_birth",
    label: "Spouse — Date of Birth",
    field_type: "date",
    required: false,
    step_number: 9,
    step_name: "Family Information",
    display_order: 13,
    conditional_logic: { showIf: "marital_status === married OR separated" },
  },
  {
    field_name: "spouse_nationality",
    label: "Spouse — Nationality",
    field_type: "select",
    required: false,
    step_number: 9,
    step_name: "Family Information",
    display_order: 14,
    conditional_logic: { showIf: "marital_status === married OR separated" },
  },
  {
    field_name: "spouse_country_of_birth",
    label: "Spouse — Country of Birth",
    field_type: "select",
    required: false,
    step_number: 9,
    step_name: "Family Information",
    display_order: 15,
    conditional_logic: { showIf: "marital_status === married OR separated" },
  },
  {
    field_name: "has_immediate_us_relatives",
    label: "Do you have any immediate US relatives?",
    field_type: "radio",
    required: true,
    step_number: 9,
    step_name: "Family Information",
    display_order: 16,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "us_relative_relationship",
    label: "U.S. Relative — Relationship",
    field_type: "select",
    required: false,
    step_number: 9,
    step_name: "Family Information",
    display_order: 17,
    options: [
      { value: "spouse", text: "Spouse" },
      { value: "child", text: "Child" },
      { value: "sibling", text: "Sibling" },
      { value: "parent", text: "Parent" },
      { value: "fiance", text: "Fiancé/Fiancée" },
      { value: "other", text: "Other" },
    ],
    conditional_logic: { showIf: "has_immediate_us_relatives === yes" },
  },
  {
    field_name: "us_relative_status",
    label: "U.S. Relative — Immigration Status",
    field_type: "text",
    required: false,
    step_number: 9,
    step_name: "Family Information",
    display_order: 18,
    conditional_logic: { showIf: "has_immediate_us_relatives === yes" },
  },
  // ─── STEP 10: Work / Education ──────────────────────────────────────────────
  {
    field_name: "primary_occupation",
    label: "Present Occupation",
    field_type: "select",
    required: true,
    step_number: 10,
    step_name: "Work and Education",
    display_order: 1,
    options: [
      { value: "employed", text: "Employed" },
      { value: "self_employed", text: "Self Employed" },
      { value: "student", text: "Student" },
      { value: "retired", text: "Retired" },
      { value: "unemployed", text: "Unemployed" },
      { value: "homemaker", text: "Homemaker" },
      { value: "other", text: "Other" },
    ],
  },
  {
    field_name: "employer_name",
    label: "Current Employer/School Name",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work and Education",
    display_order: 2,
    options: [{ value: "does_not_apply", text: "Does Not Apply" }],
  },
  {
    field_name: "employer_address_line1",
    label: "Employer/School — Street Address",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work and Education",
    display_order: 3,
  },
  {
    field_name: "employer_city",
    label: "Employer/School — City",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work and Education",
    display_order: 4,
  },
  {
    field_name: "employer_state_province",
    label: "Employer/School — State/Province",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work and Education",
    display_order: 5,
  },
  {
    field_name: "employer_country",
    label: "Employer/School — Country",
    field_type: "select",
    required: false,
    step_number: 10,
    step_name: "Work and Education",
    display_order: 6,
  },
  {
    field_name: "employer_phone",
    label: "Employer/School — Phone",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work and Education",
    display_order: 7,
  },
  {
    field_name: "job_title",
    label: "Job Title / Course of Study",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work and Education",
    display_order: 8,
  },
  {
    field_name: "employment_start_date",
    label: "Employment/Study Start Date",
    field_type: "date",
    required: false,
    step_number: 10,
    step_name: "Work and Education",
    display_order: 9,
    validation_rules: { format: "YYYY-MM" },
  },
  {
    field_name: "monthly_salary",
    label: "Monthly Salary (in local currency)",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work and Education",
    display_order: 10,
  },
  {
    field_name: "job_duties",
    label: "Describe Duties",
    field_type: "textarea",
    required: false,
    step_number: 10,
    step_name: "Work and Education",
    display_order: 11,
  },
  {
    field_name: "has_previous_employer",
    label: "Were you previously employed?",
    field_type: "radio",
    required: true,
    step_number: 10,
    step_name: "Work and Education",
    display_order: 12,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "prev_employer_name",
    label: "Previous Employer — Name",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work and Education",
    display_order: 13,
    conditional_logic: { showIf: "has_previous_employer === yes" },
  },
  {
    field_name: "prev_employer_address",
    label: "Previous Employer — Address",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work and Education",
    display_order: 14,
    conditional_logic: { showIf: "has_previous_employer === yes" },
  },
  {
    field_name: "prev_employer_phone",
    label: "Previous Employer — Phone",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work and Education",
    display_order: 15,
    conditional_logic: { showIf: "has_previous_employer === yes" },
  },
  {
    field_name: "prev_job_title",
    label: "Previous Employer — Job Title",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work and Education",
    display_order: 16,
    conditional_logic: { showIf: "has_previous_employer === yes" },
  },
  {
    field_name: "prev_employment_dates",
    label: "Previous Employment — Start/End Dates",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work and Education",
    display_order: 17,
    conditional_logic: { showIf: "has_previous_employer === yes" },
  },
  // ─── STEP 11: Security & Background ────────────────────────────────────────
  ...([
    ["has_communicable_disease", "Do you have a communicable disease of public health significance?"],
    ["has_physical_mental_disorder", "Do you have a physical or mental disorder that poses or may pose a threat?"],
    ["is_drug_abuser", "Have you been a drug abuser or addict?"],
    ["has_arrest_conviction", "Have you ever been arrested or convicted for any offense or crime?"],
    ["has_been_detained", "Have you ever been detained, retained, or held for deportation?"],
    ["has_prostitution_involvement", "Have you sought to procure or provide prostitution services?"],
    ["has_money_laundering", "Have you engaged in money laundering?"],
    ["has_terrorist_activity", "Have you ever engaged in or do you intend to engage in terrorist activities?"],
    ["has_genocide", "Have you ordered, incited, committed, assisted, or participated in genocide?"],
    ["has_torture", "Have you ever committed, ordered, or engaged in torture?"],
    ["has_removal_order", "Are you subject to a final order of removal, exclusion, or deportation?"],
    ["has_unlawful_presence_bar", "Have you been unlawfully present, overstayed a visa, or violated your status?"],
    ["intend_polygamy", "Are you coming to the U.S. to practice polygamy?"],
    ["has_voted_in_us_election", "Have you ever voted in the U.S. in violation of a law?"],
    ["has_renounced_us_citizenship", "Have you ever renounced U.S. citizenship to avoid taxation?"],
  ] as [string, string][]).map(([fn, lbl], i) => ({
    field_name: fn,
    label: lbl,
    field_type: "radio" as const,
    required: true,
    step_number: 11,
    step_name: "Security and Background",
    display_order: i + 1,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  })),
  // Explanation fields for security yes answers
  {
    field_name: "security_explanation",
    label: "Security — Explanation (if any answer is Yes)",
    field_type: "textarea",
    required: false,
    step_number: 11,
    step_name: "Security and Background",
    display_order: 20,
    conditional_logic: { showIf: "any_security_answer === yes" },
    validation_rules: { message: "Required if any security question is answered Yes" },
  },
];

async function seed() {
  console.log(`\nSeeding DS-160 visa_form_fields (${FIELDS.length} fields)...\n`);

  const rows = FIELDS.map((f) => ({
    visa_type: "DS160",
    field_name: f.field_name,
    label: f.label,
    field_type: f.field_type,
    required: f.required,
    step_number: f.step_number,
    step_name: f.step_name,
    display_order: f.display_order,
    placeholder: f.placeholder ?? null,
    validation_rules: f.validation_rules ?? null,
    options: f.options ?? null,
    conditional_logic: f.conditional_logic ?? null,
  }));

  const BATCH = 20;
  let total = 0;
  for (let i = 0; i < rows.length; i += BATCH) {
    const batch = rows.slice(i, i + BATCH);
    const { data, error } = await supabase
      .from("visa_form_fields")
      .upsert(batch, { onConflict: "visa_type,field_name", ignoreDuplicates: false })
      .select("id");
    if (error) {
      console.error(`Batch ${Math.floor(i / BATCH) + 1} error:`, error.message);
    } else {
      total += data?.length ?? 0;
      process.stdout.write(`Batch ${Math.floor(i / BATCH) + 1}: ${data?.length ?? 0} upserted\n`);
    }
  }
  console.log(`\n✅ Done: ${total} rows seeded (${FIELDS.length} defined)`);
}

seed().catch((err) => { console.error(err); process.exit(1); });
