/**
 * Seed script: visa_form_fields for UK Standard Visitor Visa
 * Field definitions based on the official Access UK application form
 * (apply-to-visit-or-stay-in-the-uk.homeoffice.gov.uk).
 *
 * Canonical journey: Standard Visitor Visa (tourism/general visit, up to 6 months).
 * See docs/uk-visa-scope.md for scope decisions and known gaps.
 *
 * Run: npx tsx scripts/seed-uk-standard-visitor-form-fields.ts
 */

import * as dotenv from "dotenv";
import * as path from "path";
import { fileURLToPath } from "url";
import { createClient } from "@supabase/supabase-js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.join(__dirname, "../.env.local") });
dotenv.config({ path: path.join(__dirname, "../.env") });

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;
if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY");
  process.exit(1);
}
const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

// ─── UK Standard Visitor Visa Field Definitions ────────────────────────────
// Based on the Access UK online application for Standard Visitor Visa.
// Sections follow the official form order.

const VISA_TYPE = "UK_STANDARD_VISITOR";

interface FieldDef {
  field_name: string;
  label: string;
  field_type: string;
  required: boolean;
  step_number: number;
  step_name: string;
  display_order: number;
  placeholder?: string;
  validation_rules?: Record<string, unknown>;
  options?: Array<{ value: string; text: string }>;
  conditional_logic?: Record<string, unknown>;
}

const FIELDS: FieldDef[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // STEP 1: About You — Personal Details
  // ═══════════════════════════════════════════════════════════════════════════
  {
    field_name: "given_names",
    label: "Given names (as shown in your passport)",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: "About You — Personal Details",
    display_order: 1,
    placeholder: "e.g., John Michael",
    validation_rules: { maxLength: 50 },
  },
  {
    field_name: "surname",
    label: "Family name / surname (as shown in your passport)",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: "About You — Personal Details",
    display_order: 2,
    placeholder: "e.g., Smith",
    validation_rules: { maxLength: 50 },
  },
  {
    field_name: "other_names_used",
    label: "Have you been known by any other names?",
    field_type: "radio",
    required: true,
    step_number: 1,
    step_name: "About You — Personal Details",
    display_order: 3,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "other_given_names",
    label: "Other given names",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: "About You — Personal Details",
    display_order: 4,
    conditional_logic: { showIf: "other_names_used === yes" },
  },
  {
    field_name: "other_surname",
    label: "Other family names / surnames",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: "About You — Personal Details",
    display_order: 5,
    conditional_logic: { showIf: "other_names_used === yes" },
  },
  {
    field_name: "date_of_birth",
    label: "Date of birth",
    field_type: "date",
    required: true,
    step_number: 1,
    step_name: "About You — Personal Details",
    display_order: 6,
    validation_rules: { format: "DD/MM/YYYY" },
  },
  {
    field_name: "sex",
    label: "Sex",
    field_type: "select",
    required: true,
    step_number: 1,
    step_name: "About You — Personal Details",
    display_order: 7,
    options: [
      { value: "male", text: "Male" },
      { value: "female", text: "Female" },
    ],
  },
  {
    field_name: "country_of_nationality",
    label: "What is your nationality?",
    field_type: "country",
    required: true,
    step_number: 1,
    step_name: "About You — Personal Details",
    display_order: 8,
    validation_rules: { source: "ISO3166-1" },
  },
  {
    field_name: "has_other_nationalities",
    label: "Do you have any other nationalities?",
    field_type: "radio",
    required: true,
    step_number: 1,
    step_name: "About You — Personal Details",
    display_order: 9,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "other_nationality",
    label: "Other nationality",
    field_type: "country",
    required: true,
    step_number: 1,
    step_name: "About You — Personal Details",
    display_order: 10,
    conditional_logic: { showIf: "has_other_nationalities === yes" },
    validation_rules: { source: "ISO3166-1", repeatable: true, repeat_group: "other_nationalities", max_items: 5 },
  },
  {
    field_name: "country_of_birth",
    label: "Country of birth",
    field_type: "country",
    required: true,
    step_number: 1,
    step_name: "About You — Personal Details",
    display_order: 11,
    validation_rules: { source: "ISO3166-1" },
  },
  {
    field_name: "place_of_birth",
    label: "Place of birth (city or town)",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: "About You — Personal Details",
    display_order: 12,
    validation_rules: { maxLength: 60 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STEP 2: About You — Passport Details
  // ═══════════════════════════════════════════════════════════════════════════
  {
    field_name: "passport_number",
    label: "Passport number",
    field_type: "text",
    required: true,
    step_number: 2,
    step_name: "About You — Passport Details",
    display_order: 1,
    placeholder: "e.g., 123456789",
    validation_rules: { maxLength: 20 },
  },
  {
    field_name: "passport_issue_date",
    label: "Date of issue",
    field_type: "date",
    required: true,
    step_number: 2,
    step_name: "About You — Passport Details",
    display_order: 2,
    validation_rules: { format: "DD/MM/YYYY", inline_group: "passport_dates" },
  },
  {
    field_name: "passport_expiry_date",
    label: "Date of expiry",
    field_type: "date",
    required: true,
    step_number: 2,
    step_name: "About You — Passport Details",
    display_order: 3,
    validation_rules: { format: "DD/MM/YYYY", inline_group: "passport_dates" },
  },
  {
    field_name: "passport_issuing_authority",
    label: "Issuing authority",
    field_type: "text",
    required: true,
    step_number: 2,
    step_name: "About You — Passport Details",
    display_order: 4,
    placeholder: "e.g., Government of Indonesia",
    validation_rules: { maxLength: 60 },
  },
  {
    field_name: "passport_place_of_issue",
    label: "Place of issue",
    field_type: "text",
    required: true,
    step_number: 2,
    step_name: "About You — Passport Details",
    display_order: 5,
    validation_rules: { maxLength: 60 },
  },
  {
    field_name: "has_other_passports",
    label: "Do you have any other valid passports or travel documents?",
    field_type: "radio",
    required: true,
    step_number: 2,
    step_name: "About You — Passport Details",
    display_order: 6,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "other_passport_nationality",
    label: "Nationality shown on other passport",
    field_type: "country",
    required: true,
    step_number: 2,
    step_name: "About You — Passport Details",
    display_order: 7,
    conditional_logic: { showIf: "has_other_passports === yes" },
    validation_rules: { source: "ISO3166-1" },
  },
  {
    field_name: "other_passport_number",
    label: "Other passport number",
    field_type: "text",
    required: true,
    step_number: 2,
    step_name: "About You — Passport Details",
    display_order: 8,
    conditional_logic: { showIf: "has_other_passports === yes" },
    validation_rules: { maxLength: 20 },
  },
  {
    field_name: "other_passport_issue_date",
    label: "Other passport date of issue",
    field_type: "date",
    required: true,
    step_number: 2,
    step_name: "About You — Passport Details",
    display_order: 9,
    conditional_logic: { showIf: "has_other_passports === yes" },
    validation_rules: { format: "DD/MM/YYYY" },
  },
  {
    field_name: "other_passport_expiry_date",
    label: "Other passport date of expiry",
    field_type: "date",
    required: true,
    step_number: 2,
    step_name: "About You — Passport Details",
    display_order: 10,
    conditional_logic: { showIf: "has_other_passports === yes" },
    validation_rules: { format: "DD/MM/YYYY" },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STEP 3: Your Contact Details
  // ═══════════════════════════════════════════════════════════════════════════
  {
    field_name: "email_address",
    label: "Email address",
    field_type: "text",
    required: true,
    step_number: 3,
    step_name: "Your Contact Details",
    display_order: 1,
    placeholder: "e.g., name@example.com",
    validation_rules: { maxLength: 100, pattern: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$" },
  },
  {
    field_name: "phone_number",
    label: "Phone number (including country code)",
    field_type: "text",
    required: true,
    step_number: 3,
    step_name: "Your Contact Details",
    display_order: 2,
    placeholder: "e.g., +62 812 3456 7890",
    validation_rules: { maxLength: 20 },
  },
  {
    field_name: "has_alternative_phone",
    label: "Do you have an alternative phone number?",
    field_type: "radio",
    required: true,
    step_number: 3,
    step_name: "Your Contact Details",
    display_order: 3,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "alternative_phone_number",
    label: "Alternative phone number",
    field_type: "text",
    required: true,
    step_number: 3,
    step_name: "Your Contact Details",
    display_order: 4,
    conditional_logic: { showIf: "has_alternative_phone === yes" },
    validation_rules: { maxLength: 20 },
  },
  {
    field_name: "home_address_line_1",
    label: "Home address — line 1",
    field_type: "text",
    required: true,
    step_number: 3,
    step_name: "Your Contact Details",
    display_order: 5,
    validation_rules: { maxLength: 100, block_group: "home_address" },
  },
  {
    field_name: "home_address_line_2",
    label: "Home address — line 2",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Your Contact Details",
    display_order: 6,
    validation_rules: { maxLength: 100, block_group: "home_address" },
  },
  {
    field_name: "home_address_city",
    label: "Town or city",
    field_type: "text",
    required: true,
    step_number: 3,
    step_name: "Your Contact Details",
    display_order: 7,
    validation_rules: { maxLength: 60, block_group: "home_address" },
  },
  {
    field_name: "home_address_state",
    label: "County / state / province",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Your Contact Details",
    display_order: 8,
    validation_rules: { maxLength: 60, block_group: "home_address" },
  },
  {
    field_name: "home_address_postcode",
    label: "Postcode / ZIP code",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Your Contact Details",
    display_order: 9,
    validation_rules: { maxLength: 15, block_group: "home_address" },
  },
  {
    field_name: "home_address_country",
    label: "Country",
    field_type: "country",
    required: true,
    step_number: 3,
    step_name: "Your Contact Details",
    display_order: 10,
    validation_rules: { source: "ISO3166-1", block_group: "home_address" },
  },
  {
    field_name: "how_long_at_address",
    label: "How long have you lived at this address?",
    field_type: "text",
    required: true,
    step_number: 3,
    step_name: "Your Contact Details",
    display_order: 11,
    placeholder: "e.g., 3 years",
    validation_rules: { maxLength: 40 },
  },
  {
    field_name: "owns_home",
    label: "Do you own your home?",
    field_type: "radio",
    required: true,
    step_number: 3,
    step_name: "Your Contact Details",
    display_order: 12,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "correspondence_address_different",
    label: "Is your correspondence address different from your home address?",
    field_type: "radio",
    required: true,
    step_number: 3,
    step_name: "Your Contact Details",
    display_order: 13,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "correspondence_address_line_1",
    label: "Correspondence address — line 1",
    field_type: "text",
    required: true,
    step_number: 3,
    step_name: "Your Contact Details",
    display_order: 14,
    conditional_logic: { showIf: "correspondence_address_different === yes" },
    validation_rules: { maxLength: 100 },
  },
  {
    field_name: "correspondence_address_city",
    label: "Correspondence address — town or city",
    field_type: "text",
    required: true,
    step_number: 3,
    step_name: "Your Contact Details",
    display_order: 15,
    conditional_logic: { showIf: "correspondence_address_different === yes" },
    validation_rules: { maxLength: 60 },
  },
  {
    field_name: "correspondence_address_country",
    label: "Correspondence address — country",
    field_type: "country",
    required: true,
    step_number: 3,
    step_name: "Your Contact Details",
    display_order: 16,
    conditional_logic: { showIf: "correspondence_address_different === yes" },
    validation_rules: { source: "ISO3166-1" },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STEP 4: Your Family
  // ═══════════════════════════════════════════════════════════════════════════
  {
    field_name: "marital_status",
    label: "What is your current marital or civil partnership status?",
    field_type: "select",
    required: true,
    step_number: 4,
    step_name: "Your Family",
    display_order: 1,
    options: [
      { value: "single", text: "Single" },
      { value: "married", text: "Married" },
      { value: "civil_partnership", text: "In a civil partnership" },
      { value: "unmarried_partner", text: "Unmarried partner" },
      { value: "divorced", text: "Divorced" },
      { value: "widowed", text: "Widowed" },
      { value: "separated", text: "Separated" },
    ],
  },
  {
    field_name: "partner_given_names",
    label: "Partner's given names",
    field_type: "text",
    required: true,
    step_number: 4,
    step_name: "Your Family",
    display_order: 2,
    conditional_logic: { showIf: "marital_status === married || marital_status === civil_partnership || marital_status === unmarried_partner" },
    validation_rules: { maxLength: 50 },
  },
  {
    field_name: "partner_surname",
    label: "Partner's family name / surname",
    field_type: "text",
    required: true,
    step_number: 4,
    step_name: "Your Family",
    display_order: 3,
    conditional_logic: { showIf: "marital_status === married || marital_status === civil_partnership || marital_status === unmarried_partner" },
    validation_rules: { maxLength: 50 },
  },
  {
    field_name: "partner_date_of_birth",
    label: "Partner's date of birth",
    field_type: "date",
    required: true,
    step_number: 4,
    step_name: "Your Family",
    display_order: 4,
    conditional_logic: { showIf: "marital_status === married || marital_status === civil_partnership || marital_status === unmarried_partner" },
    validation_rules: { format: "DD/MM/YYYY" },
  },
  {
    field_name: "partner_nationality",
    label: "Partner's nationality",
    field_type: "country",
    required: true,
    step_number: 4,
    step_name: "Your Family",
    display_order: 5,
    conditional_logic: { showIf: "marital_status === married || marital_status === civil_partnership || marital_status === unmarried_partner" },
    validation_rules: { source: "ISO3166-1" },
  },
  {
    field_name: "partner_travelling_with_you",
    label: "Is your partner travelling to the UK with you?",
    field_type: "radio",
    required: true,
    step_number: 4,
    step_name: "Your Family",
    display_order: 6,
    conditional_logic: { showIf: "marital_status === married || marital_status === civil_partnership || marital_status === unmarried_partner" },
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "has_children",
    label: "Do you have any children under 18?",
    field_type: "radio",
    required: true,
    step_number: 4,
    step_name: "Your Family",
    display_order: 7,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "number_of_children",
    label: "How many children under 18 do you have?",
    field_type: "text",
    required: true,
    step_number: 4,
    step_name: "Your Family",
    display_order: 8,
    conditional_logic: { showIf: "has_children === yes" },
    validation_rules: { pattern: "^[0-9]{1,2}$" },
  },
  {
    field_name: "children_travelling_with_you",
    label: "Are any of your children travelling with you?",
    field_type: "radio",
    required: true,
    step_number: 4,
    step_name: "Your Family",
    display_order: 9,
    conditional_logic: { showIf: "has_children === yes" },
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "father_given_names",
    label: "Father's given names",
    field_type: "text",
    required: true,
    step_number: 4,
    step_name: "Your Family",
    display_order: 10,
    validation_rules: { maxLength: 50, block_group: "parents" },
  },
  {
    field_name: "father_surname",
    label: "Father's family name / surname",
    field_type: "text",
    required: true,
    step_number: 4,
    step_name: "Your Family",
    display_order: 11,
    validation_rules: { maxLength: 50, block_group: "parents" },
  },
  {
    field_name: "father_date_of_birth",
    label: "Father's date of birth",
    field_type: "date",
    required: true,
    step_number: 4,
    step_name: "Your Family",
    display_order: 12,
    validation_rules: { format: "DD/MM/YYYY", block_group: "parents" },
  },
  {
    field_name: "father_nationality",
    label: "Father's nationality",
    field_type: "country",
    required: true,
    step_number: 4,
    step_name: "Your Family",
    display_order: 13,
    validation_rules: { source: "ISO3166-1", block_group: "parents" },
  },
  {
    field_name: "mother_given_names",
    label: "Mother's given names",
    field_type: "text",
    required: true,
    step_number: 4,
    step_name: "Your Family",
    display_order: 14,
    validation_rules: { maxLength: 50, block_group: "parents" },
  },
  {
    field_name: "mother_surname",
    label: "Mother's family name / surname",
    field_type: "text",
    required: true,
    step_number: 4,
    step_name: "Your Family",
    display_order: 15,
    validation_rules: { maxLength: 50, block_group: "parents" },
  },
  {
    field_name: "mother_date_of_birth",
    label: "Mother's date of birth",
    field_type: "date",
    required: true,
    step_number: 4,
    step_name: "Your Family",
    display_order: 16,
    validation_rules: { format: "DD/MM/YYYY", block_group: "parents" },
  },
  {
    field_name: "mother_nationality",
    label: "Mother's nationality",
    field_type: "country",
    required: true,
    step_number: 4,
    step_name: "Your Family",
    display_order: 17,
    validation_rules: { source: "ISO3166-1", block_group: "parents" },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STEP 5: Your Accommodation in the UK
  // ═══════════════════════════════════════════════════════════════════════════
  {
    field_name: "uk_accommodation_type",
    label: "Where will you be staying in the UK?",
    field_type: "select",
    required: true,
    step_number: 5,
    step_name: "Your Accommodation in the UK",
    display_order: 1,
    options: [
      { value: "hotel", text: "Hotel or other commercial accommodation" },
      { value: "family_friends", text: "With family or friends" },
      { value: "rented", text: "Rented accommodation" },
      { value: "own_property", text: "Own property" },
      { value: "other", text: "Other" },
    ],
  },
  {
    field_name: "uk_accommodation_address_line_1",
    label: "UK accommodation address — line 1",
    field_type: "text",
    required: true,
    step_number: 5,
    step_name: "Your Accommodation in the UK",
    display_order: 2,
    validation_rules: { maxLength: 100, block_group: "uk_address" },
  },
  {
    field_name: "uk_accommodation_address_line_2",
    label: "UK accommodation address — line 2",
    field_type: "text",
    required: false,
    step_number: 5,
    step_name: "Your Accommodation in the UK",
    display_order: 3,
    validation_rules: { maxLength: 100, block_group: "uk_address" },
  },
  {
    field_name: "uk_accommodation_city",
    label: "Town or city",
    field_type: "text",
    required: true,
    step_number: 5,
    step_name: "Your Accommodation in the UK",
    display_order: 4,
    validation_rules: { maxLength: 60, block_group: "uk_address" },
  },
  {
    field_name: "uk_accommodation_postcode",
    label: "Postcode",
    field_type: "text",
    required: true,
    step_number: 5,
    step_name: "Your Accommodation in the UK",
    display_order: 5,
    placeholder: "e.g., SW1A 1AA",
    validation_rules: { maxLength: 10, block_group: "uk_address" },
  },
  {
    field_name: "uk_host_name",
    label: "Name of the person you are staying with",
    field_type: "text",
    required: true,
    step_number: 5,
    step_name: "Your Accommodation in the UK",
    display_order: 6,
    conditional_logic: { showIf: "uk_accommodation_type === family_friends" },
    validation_rules: { maxLength: 80 },
  },
  {
    field_name: "uk_host_relationship",
    label: "What is your relationship to this person?",
    field_type: "text",
    required: true,
    step_number: 5,
    step_name: "Your Accommodation in the UK",
    display_order: 7,
    conditional_logic: { showIf: "uk_accommodation_type === family_friends" },
    placeholder: "e.g., Friend, Uncle, Cousin",
    validation_rules: { maxLength: 40 },
  },
  {
    field_name: "uk_host_email",
    label: "Host's email address",
    field_type: "text",
    required: false,
    step_number: 5,
    step_name: "Your Accommodation in the UK",
    display_order: 8,
    conditional_logic: { showIf: "uk_accommodation_type === family_friends" },
    validation_rules: { maxLength: 100 },
  },
  {
    field_name: "uk_host_phone",
    label: "Host's phone number",
    field_type: "text",
    required: false,
    step_number: 5,
    step_name: "Your Accommodation in the UK",
    display_order: 9,
    conditional_logic: { showIf: "uk_accommodation_type === family_friends" },
    validation_rules: { maxLength: 20 },
  },
  {
    field_name: "uk_accommodation_other_explain",
    label: "Please describe your accommodation arrangements",
    field_type: "textarea",
    required: true,
    step_number: 5,
    step_name: "Your Accommodation in the UK",
    display_order: 10,
    conditional_logic: { showIf: "uk_accommodation_type === other" },
    validation_rules: { maxLength: 500 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STEP 6: Your Travel History
  // ═══════════════════════════════════════════════════════════════════════════
  {
    field_name: "travelled_to_uk_before",
    label: "Have you ever travelled to the UK before?",
    field_type: "radio",
    required: true,
    step_number: 6,
    step_name: "Your Travel History",
    display_order: 1,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "last_uk_visit_date",
    label: "When was your most recent visit to the UK?",
    field_type: "date",
    required: true,
    step_number: 6,
    step_name: "Your Travel History",
    display_order: 2,
    conditional_logic: { showIf: "travelled_to_uk_before === yes" },
    validation_rules: { format: "DD/MM/YYYY" },
  },
  {
    field_name: "last_uk_visit_duration",
    label: "How long did you stay?",
    field_type: "text",
    required: true,
    step_number: 6,
    step_name: "Your Travel History",
    display_order: 3,
    conditional_logic: { showIf: "travelled_to_uk_before === yes" },
    placeholder: "e.g., 2 weeks",
    validation_rules: { maxLength: 40 },
  },
  {
    field_name: "last_uk_visit_reason",
    label: "What was the reason for your visit?",
    field_type: "text",
    required: true,
    step_number: 6,
    step_name: "Your Travel History",
    display_order: 4,
    conditional_logic: { showIf: "travelled_to_uk_before === yes" },
    validation_rules: { maxLength: 100 },
  },
  {
    field_name: "uk_national_insurance_number",
    label: "Do you have a UK National Insurance number?",
    field_type: "radio",
    required: true,
    step_number: 6,
    step_name: "Your Travel History",
    display_order: 5,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "uk_national_insurance_number_value",
    label: "UK National Insurance number",
    field_type: "text",
    required: true,
    step_number: 6,
    step_name: "Your Travel History",
    display_order: 6,
    conditional_logic: { showIf: "uk_national_insurance_number === yes" },
    validation_rules: { maxLength: 13 },
  },
  {
    field_name: "visa_refused_uk",
    label: "Have you ever been refused a visa for the UK?",
    field_type: "radio",
    required: true,
    step_number: 6,
    step_name: "Your Travel History",
    display_order: 7,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "visa_refused_uk_details",
    label: "Please give details of the refusal",
    field_type: "textarea",
    required: true,
    step_number: 6,
    step_name: "Your Travel History",
    display_order: 8,
    conditional_logic: { showIf: "visa_refused_uk === yes" },
    validation_rules: { maxLength: 500 },
  },
  {
    field_name: "visa_refused_other_country",
    label: "Have you ever been refused a visa for any other country?",
    field_type: "radio",
    required: true,
    step_number: 6,
    step_name: "Your Travel History",
    display_order: 9,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "visa_refused_other_country_details",
    label: "Please give details of the refusal",
    field_type: "textarea",
    required: true,
    step_number: 6,
    step_name: "Your Travel History",
    display_order: 10,
    conditional_logic: { showIf: "visa_refused_other_country === yes" },
    validation_rules: { maxLength: 500 },
  },
  {
    field_name: "deported_removed_refused_entry",
    label: "Have you ever been deported, removed, or refused entry to any country including the UK?",
    field_type: "radio",
    required: true,
    step_number: 6,
    step_name: "Your Travel History",
    display_order: 11,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "deported_details",
    label: "Please give details",
    field_type: "textarea",
    required: true,
    step_number: 6,
    step_name: "Your Travel History",
    display_order: 12,
    conditional_logic: { showIf: "deported_removed_refused_entry === yes" },
    validation_rules: { maxLength: 500 },
  },
  {
    field_name: "countries_visited_last_10_years",
    label: "List the countries you have visited in the last 10 years",
    field_type: "textarea",
    required: true,
    step_number: 6,
    step_name: "Your Travel History",
    display_order: 13,
    placeholder: "e.g., USA (2023), Japan (2022), Australia (2021)",
    validation_rules: { maxLength: 1000 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STEP 7: Your Trip to the UK
  // ═══════════════════════════════════════════════════════════════════════════
  {
    field_name: "purpose_of_visit",
    label: "What is the main reason for your visit to the UK?",
    field_type: "select",
    required: true,
    step_number: 7,
    step_name: "Your Trip to the UK",
    display_order: 1,
    options: [
      { value: "tourism", text: "Tourism / holiday" },
      { value: "visiting_family_friends", text: "Visiting family or friends" },
      { value: "business", text: "Business" },
      { value: "short_study", text: "Short-term study (up to 6 months)" },
      { value: "medical", text: "Medical treatment" },
      { value: "transit", text: "Transit" },
      { value: "other", text: "Other" },
    ],
  },
  {
    field_name: "purpose_other_explain",
    label: "Please describe the reason for your visit",
    field_type: "textarea",
    required: true,
    step_number: 7,
    step_name: "Your Trip to the UK",
    display_order: 2,
    conditional_logic: { showIf: "purpose_of_visit === other" },
    validation_rules: { maxLength: 500 },
  },
  {
    field_name: "uk_arrival_date",
    label: "When do you plan to arrive in the UK?",
    field_type: "date",
    required: true,
    step_number: 7,
    step_name: "Your Trip to the UK",
    display_order: 3,
    validation_rules: { format: "DD/MM/YYYY", inline_group: "trip_dates" },
  },
  {
    field_name: "uk_departure_date",
    label: "When do you plan to leave the UK?",
    field_type: "date",
    required: true,
    step_number: 7,
    step_name: "Your Trip to the UK",
    display_order: 4,
    validation_rules: { format: "DD/MM/YYYY", inline_group: "trip_dates" },
  },
  {
    field_name: "visiting_family_in_uk",
    label: "Will you be visiting family while in the UK?",
    field_type: "radio",
    required: true,
    step_number: 7,
    step_name: "Your Trip to the UK",
    display_order: 5,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "uk_family_member_name",
    label: "Family member's full name",
    field_type: "text",
    required: true,
    step_number: 7,
    step_name: "Your Trip to the UK",
    display_order: 6,
    conditional_logic: { showIf: "visiting_family_in_uk === yes" },
    validation_rules: { maxLength: 80 },
  },
  {
    field_name: "uk_family_member_relationship",
    label: "What is your relationship to this person?",
    field_type: "text",
    required: true,
    step_number: 7,
    step_name: "Your Trip to the UK",
    display_order: 7,
    conditional_logic: { showIf: "visiting_family_in_uk === yes" },
    validation_rules: { maxLength: 40 },
  },
  {
    field_name: "uk_family_member_immigration_status",
    label: "What is their UK immigration status?",
    field_type: "select",
    required: true,
    step_number: 7,
    step_name: "Your Trip to the UK",
    display_order: 8,
    conditional_logic: { showIf: "visiting_family_in_uk === yes" },
    options: [
      { value: "british_citizen", text: "British citizen" },
      { value: "settled", text: "Settled (Indefinite Leave to Remain)" },
      { value: "eu_settled", text: "EU Settlement Scheme" },
      { value: "visa_holder", text: "Has a valid UK visa" },
      { value: "dont_know", text: "I don't know" },
    ],
  },
  {
    field_name: "uk_family_member_address",
    label: "Family member's UK address",
    field_type: "textarea",
    required: true,
    step_number: 7,
    step_name: "Your Trip to the UK",
    display_order: 9,
    conditional_logic: { showIf: "visiting_family_in_uk === yes" },
    validation_rules: { maxLength: 300 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STEP 8: Your Employment
  // ═══════════════════════════════════════════════════════════════════════════
  {
    field_name: "employment_status",
    label: "What is your current employment status?",
    field_type: "select",
    required: true,
    step_number: 8,
    step_name: "Your Employment",
    display_order: 1,
    options: [
      { value: "employed", text: "Employed" },
      { value: "self_employed", text: "Self-employed" },
      { value: "student", text: "Student" },
      { value: "retired", text: "Retired" },
      { value: "unemployed", text: "Unemployed" },
      { value: "homemaker", text: "Homemaker" },
      { value: "other", text: "Other" },
    ],
  },
  {
    field_name: "employer_name",
    label: "Employer's name",
    field_type: "text",
    required: true,
    step_number: 8,
    step_name: "Your Employment",
    display_order: 2,
    conditional_logic: { showIf: "employment_status === employed" },
    validation_rules: { maxLength: 80, block_group: "employer_details" },
  },
  {
    field_name: "employer_address",
    label: "Employer's address",
    field_type: "textarea",
    required: true,
    step_number: 8,
    step_name: "Your Employment",
    display_order: 3,
    conditional_logic: { showIf: "employment_status === employed" },
    validation_rules: { maxLength: 300, block_group: "employer_details" },
  },
  {
    field_name: "employer_phone",
    label: "Employer's phone number",
    field_type: "text",
    required: true,
    step_number: 8,
    step_name: "Your Employment",
    display_order: 4,
    conditional_logic: { showIf: "employment_status === employed" },
    validation_rules: { maxLength: 20, block_group: "employer_details" },
  },
  {
    field_name: "job_title",
    label: "Job title",
    field_type: "text",
    required: true,
    step_number: 8,
    step_name: "Your Employment",
    display_order: 5,
    conditional_logic: { showIf: "employment_status === employed || employment_status === self_employed" },
    validation_rules: { maxLength: 60 },
  },
  {
    field_name: "job_start_date",
    label: "When did you start this job?",
    field_type: "date",
    required: true,
    step_number: 8,
    step_name: "Your Employment",
    display_order: 6,
    conditional_logic: { showIf: "employment_status === employed || employment_status === self_employed" },
    validation_rules: { format: "DD/MM/YYYY" },
  },
  {
    field_name: "annual_income",
    label: "What is your annual income (in local currency)?",
    field_type: "text",
    required: true,
    step_number: 8,
    step_name: "Your Employment",
    display_order: 7,
    conditional_logic: { showIf: "employment_status === employed || employment_status === self_employed" },
    placeholder: "e.g., 50000000 IDR",
    validation_rules: { maxLength: 30 },
  },
  {
    field_name: "self_employed_business_name",
    label: "Business name",
    field_type: "text",
    required: true,
    step_number: 8,
    step_name: "Your Employment",
    display_order: 8,
    conditional_logic: { showIf: "employment_status === self_employed" },
    validation_rules: { maxLength: 80 },
  },
  {
    field_name: "self_employed_business_address",
    label: "Business address",
    field_type: "textarea",
    required: true,
    step_number: 8,
    step_name: "Your Employment",
    display_order: 9,
    conditional_logic: { showIf: "employment_status === self_employed" },
    validation_rules: { maxLength: 300 },
  },
  {
    field_name: "student_institution_name",
    label: "Name of school, college, or university",
    field_type: "text",
    required: true,
    step_number: 8,
    step_name: "Your Employment",
    display_order: 10,
    conditional_logic: { showIf: "employment_status === student" },
    validation_rules: { maxLength: 80 },
  },
  {
    field_name: "student_institution_address",
    label: "Institution address",
    field_type: "textarea",
    required: true,
    step_number: 8,
    step_name: "Your Employment",
    display_order: 11,
    conditional_logic: { showIf: "employment_status === student" },
    validation_rules: { maxLength: 300 },
  },
  {
    field_name: "student_course_name",
    label: "Course of study",
    field_type: "text",
    required: true,
    step_number: 8,
    step_name: "Your Employment",
    display_order: 12,
    conditional_logic: { showIf: "employment_status === student" },
    validation_rules: { maxLength: 80 },
  },
  {
    field_name: "employment_other_explain",
    label: "Please describe your situation",
    field_type: "textarea",
    required: true,
    step_number: 8,
    step_name: "Your Employment",
    display_order: 13,
    conditional_logic: { showIf: "employment_status === other" },
    validation_rules: { maxLength: 500 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STEP 9: Your Finances
  // ═══════════════════════════════════════════════════════════════════════════
  {
    field_name: "who_is_paying",
    label: "Who is paying for your visit to the UK?",
    field_type: "select",
    required: true,
    step_number: 9,
    step_name: "Your Finances",
    display_order: 1,
    options: [
      { value: "self", text: "I am paying for myself" },
      { value: "sponsor", text: "Someone else is paying for me" },
      { value: "employer", text: "My employer" },
      { value: "other", text: "Other" },
    ],
  },
  {
    field_name: "monthly_spending_money",
    label: "How much money will you have available to spend each month in the UK?",
    field_type: "text",
    required: true,
    step_number: 9,
    step_name: "Your Finances",
    display_order: 2,
    placeholder: "e.g., £2000",
    validation_rules: { maxLength: 20 },
  },
  {
    field_name: "total_cost_of_trip",
    label: "What is the total estimated cost of your trip (including flights)?",
    field_type: "text",
    required: true,
    step_number: 9,
    step_name: "Your Finances",
    display_order: 3,
    placeholder: "e.g., £3000",
    validation_rules: { maxLength: 20 },
  },
  {
    field_name: "sponsor_name",
    label: "Sponsor's full name",
    field_type: "text",
    required: true,
    step_number: 9,
    step_name: "Your Finances",
    display_order: 4,
    conditional_logic: { showIf: "who_is_paying === sponsor" },
    validation_rules: { maxLength: 80, block_group: "sponsor_details" },
  },
  {
    field_name: "sponsor_relationship",
    label: "What is your relationship to the sponsor?",
    field_type: "text",
    required: true,
    step_number: 9,
    step_name: "Your Finances",
    display_order: 5,
    conditional_logic: { showIf: "who_is_paying === sponsor" },
    validation_rules: { maxLength: 40, block_group: "sponsor_details" },
  },
  {
    field_name: "sponsor_address",
    label: "Sponsor's address",
    field_type: "textarea",
    required: true,
    step_number: 9,
    step_name: "Your Finances",
    display_order: 6,
    conditional_logic: { showIf: "who_is_paying === sponsor" },
    validation_rules: { maxLength: 300, block_group: "sponsor_details" },
  },
  {
    field_name: "sponsor_email",
    label: "Sponsor's email address",
    field_type: "text",
    required: false,
    step_number: 9,
    step_name: "Your Finances",
    display_order: 7,
    conditional_logic: { showIf: "who_is_paying === sponsor" },
    validation_rules: { maxLength: 100, block_group: "sponsor_details" },
  },
  {
    field_name: "sponsor_phone",
    label: "Sponsor's phone number",
    field_type: "text",
    required: false,
    step_number: 9,
    step_name: "Your Finances",
    display_order: 8,
    conditional_logic: { showIf: "who_is_paying === sponsor" },
    validation_rules: { maxLength: 20, block_group: "sponsor_details" },
  },
  {
    field_name: "finances_other_explain",
    label: "Please describe your financial arrangements",
    field_type: "textarea",
    required: true,
    step_number: 9,
    step_name: "Your Finances",
    display_order: 9,
    conditional_logic: { showIf: "who_is_paying === other" },
    validation_rules: { maxLength: 500 },
  },
  {
    field_name: "has_savings",
    label: "Do you have any savings?",
    field_type: "radio",
    required: true,
    step_number: 9,
    step_name: "Your Finances",
    display_order: 10,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "savings_amount",
    label: "Total savings (in local currency)",
    field_type: "text",
    required: true,
    step_number: 9,
    step_name: "Your Finances",
    display_order: 11,
    conditional_logic: { showIf: "has_savings === yes" },
    placeholder: "e.g., 100000000 IDR",
    validation_rules: { maxLength: 30 },
  },
  {
    field_name: "has_other_income",
    label: "Do you have any other income or financial support?",
    field_type: "radio",
    required: true,
    step_number: 9,
    step_name: "Your Finances",
    display_order: 12,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "other_income_details",
    label: "Please describe your other income or financial support",
    field_type: "textarea",
    required: true,
    step_number: 9,
    step_name: "Your Finances",
    display_order: 13,
    conditional_logic: { showIf: "has_other_income === yes" },
    validation_rules: { maxLength: 500 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STEP 10: Medical Treatment (conditional on purpose_of_visit)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    field_name: "medical_treatment_type",
    label: "What kind of medical treatment will you be receiving?",
    field_type: "textarea",
    required: true,
    step_number: 10,
    step_name: "Medical Treatment Details",
    display_order: 1,
    conditional_logic: { showIf: "purpose_of_visit === medical" },
    validation_rules: { maxLength: 500 },
  },
  {
    field_name: "medical_facility_name",
    label: "Name of the hospital or clinic",
    field_type: "text",
    required: true,
    step_number: 10,
    step_name: "Medical Treatment Details",
    display_order: 2,
    conditional_logic: { showIf: "purpose_of_visit === medical" },
    validation_rules: { maxLength: 80 },
  },
  {
    field_name: "medical_facility_address",
    label: "Hospital or clinic address",
    field_type: "textarea",
    required: true,
    step_number: 10,
    step_name: "Medical Treatment Details",
    display_order: 3,
    conditional_logic: { showIf: "purpose_of_visit === medical" },
    validation_rules: { maxLength: 300 },
  },
  {
    field_name: "medical_doctor_name",
    label: "Name of the doctor or consultant",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Medical Treatment Details",
    display_order: 4,
    conditional_logic: { showIf: "purpose_of_visit === medical" },
    validation_rules: { maxLength: 80 },
  },
  {
    field_name: "medical_estimated_cost",
    label: "Estimated cost of treatment",
    field_type: "text",
    required: true,
    step_number: 10,
    step_name: "Medical Treatment Details",
    display_order: 5,
    conditional_logic: { showIf: "purpose_of_visit === medical" },
    placeholder: "e.g., £10000",
    validation_rules: { maxLength: 20 },
  },
  {
    field_name: "medical_payment_arrangement",
    label: "How will you pay for your treatment?",
    field_type: "textarea",
    required: true,
    step_number: 10,
    step_name: "Medical Treatment Details",
    display_order: 6,
    conditional_logic: { showIf: "purpose_of_visit === medical" },
    validation_rules: { maxLength: 500 },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STEP 11: Additional Information & Declaration
  // ═══════════════════════════════════════════════════════════════════════════
  {
    field_name: "criminal_convictions",
    label: "Have you ever been convicted of a criminal offence in any country (including traffic offences)?",
    field_type: "radio",
    required: true,
    step_number: 11,
    step_name: "Additional Information",
    display_order: 1,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "criminal_convictions_details",
    label: "Please give details of any criminal convictions",
    field_type: "textarea",
    required: true,
    step_number: 11,
    step_name: "Additional Information",
    display_order: 2,
    conditional_logic: { showIf: "criminal_convictions === yes" },
    validation_rules: { maxLength: 1000 },
  },
  {
    field_name: "terrorism_related",
    label: "Have you ever been involved in, supported, or encouraged terrorist activities in any country?",
    field_type: "radio",
    required: true,
    step_number: 11,
    step_name: "Additional Information",
    display_order: 3,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "terrorism_details",
    label: "Please give details",
    field_type: "textarea",
    required: true,
    step_number: 11,
    step_name: "Additional Information",
    display_order: 4,
    conditional_logic: { showIf: "terrorism_related === yes" },
    validation_rules: { maxLength: 1000 },
  },
  {
    field_name: "war_crimes",
    label: "Have you ever been involved in, or suspected of involvement in, war crimes, crimes against humanity, or genocide?",
    field_type: "radio",
    required: true,
    step_number: 11,
    step_name: "Additional Information",
    display_order: 5,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "war_crimes_details",
    label: "Please give details",
    field_type: "textarea",
    required: true,
    step_number: 11,
    step_name: "Additional Information",
    display_order: 6,
    conditional_logic: { showIf: "war_crimes === yes" },
    validation_rules: { maxLength: 1000 },
  },
  {
    field_name: "organisations_concern",
    label: "Have you ever been a member of, or given support to, an organisation which has been concerned in terrorism?",
    field_type: "radio",
    required: true,
    step_number: 11,
    step_name: "Additional Information",
    display_order: 7,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "organisations_concern_details",
    label: "Please give details",
    field_type: "textarea",
    required: true,
    step_number: 11,
    step_name: "Additional Information",
    display_order: 8,
    conditional_logic: { showIf: "organisations_concern === yes" },
    validation_rules: { maxLength: 1000 },
  },
  {
    field_name: "bad_character",
    label: "Have you engaged in any other activities that might indicate you may not be considered a person of good character?",
    field_type: "radio",
    required: true,
    step_number: 11,
    step_name: "Additional Information",
    display_order: 9,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "bad_character_details",
    label: "Please give details",
    field_type: "textarea",
    required: true,
    step_number: 11,
    step_name: "Additional Information",
    display_order: 10,
    conditional_logic: { showIf: "bad_character === yes" },
    validation_rules: { maxLength: 1000 },
  },
  {
    field_name: "additional_information",
    label: "Is there anything else you would like to tell us about your application?",
    field_type: "textarea",
    required: false,
    step_number: 11,
    step_name: "Additional Information",
    display_order: 11,
    validation_rules: { maxLength: 2000 },
  },
];

// ─── Seed Runner ────────────────────────────────────────────────────────────

async function seed() {
  console.log(`Seeding ${FIELDS.length} fields for visa_type="${VISA_TYPE}"...\n`);

  // Clear existing fields for this visa type
  const { error: delError } = await supabase
    .from("visa_form_fields")
    .delete()
    .eq("visa_type", VISA_TYPE);
  if (delError) {
    console.error(`Error deleting existing ${VISA_TYPE} fields:`, delError.message);
  } else {
    console.log(`Cleared existing ${VISA_TYPE} fields`);
  }

  const rows = FIELDS.map((f) => ({
    visa_type: VISA_TYPE,
    field_name: f.field_name,
    label: f.label,
    field_type: f.field_type,
    required: f.required,
    step_number: f.step_number,
    step_name: f.step_name,
    display_order: f.display_order,
    placeholder: f.placeholder ?? null,
    validation_rules: f.validation_rules ?? null,
    options: f.options ?? null,
    conditional_logic: f.conditional_logic ?? null,
  }));

  const BATCH = 20;
  let total = 0;
  for (let i = 0; i < rows.length; i += BATCH) {
    const batch = rows.slice(i, i + BATCH);
    const { data, error } = await supabase
      .from("visa_form_fields")
      .insert(batch)
      .select("id");
    if (error) {
      console.error(`Batch ${Math.floor(i / BATCH) + 1} error:`, error.message);
    } else {
      total += data?.length ?? 0;
      process.stdout.write(`Batch ${Math.floor(i / BATCH) + 1}: ${data?.length ?? 0} inserted\n`);
    }
  }
  console.log(`\nDone: ${total} rows seeded (${FIELDS.length} defined)`);
}

seed().catch((err) => { console.error(err); process.exit(1); });
