/**
 * Seed script: visa_form_fields for DS-160 (US nonimmigrant visa)
 * Field definitions match the actual DS-160 online form exactly.
 * Run: npm run seed:ds160-form-fields
 */

import * as dotenv from "dotenv";
import * as path from "path";
import { fileURLToPath } from "url";
import { createClient } from "@supabase/supabase-js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.join(__dirname, "../.env.local") });
dotenv.config({ path: path.join(__dirname, "../.env") });

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY!;
if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY");
  process.exit(1);
}
const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

// ─── DS-160 Field Definitions ───────────────────────────────────────────────
// Matches the actual DS-160 online form exactly.
// Uses validation_rules JSON for metadata like has_does_not_apply, repeatable, etc.

interface FieldDef {
  field_name: string;
  label: string;
  field_type: string;
  required: boolean;
  step_number: number;
  step_name: string;
  display_order: number;
  placeholder?: string;
  validation_rules?: Record<string, unknown>;
  options?: Array<{ value: string; text: string }>;
  conditional_logic?: Record<string, unknown>;
}

const FIELDS: FieldDef[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // STEP 1: Personal Information 1
  // ═══════════════════════════════════════════════════════════════════════════
  {
    field_name: "surname",
    label: "Surnames",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: "Personal Information 1",
    display_order: 1,
    placeholder: "e.g., FERNANDEZ GARCIA",
    validation_rules: { maxLength: 33, uppercase: true },
  },
  {
    field_name: "given_names",
    label: "Given Names",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: "Personal Information 1",
    display_order: 2,
    placeholder: "e.g., JUAN MIGUEL",
    validation_rules: { maxLength: 33 },
  },
  {
    field_name: "full_name_native_alphabet",
    label: "Full Name in Native Alphabet",
    field_type: "text",
    required: false,
    step_number: 1,
    step_name: "Personal Information 1",
    display_order: 3,
    validation_rules: { has_does_not_apply: true, does_not_apply_label: "Does Not Apply/Technology Not Available" },
  },
  {
    field_name: "other_names_used",
    label: "Have you ever used other names (i.e., maiden, religious, professional, alias, etc.)?",
    field_type: "radio",
    required: true,
    step_number: 1,
    step_name: "Personal Information 1",
    display_order: 4,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "other_surname",
    label: "Other Surnames Used (maiden, religious, professional, aliases, etc.)",
    field_type: "text",
    required: false,
    step_number: 1,
    step_name: "Personal Information 1",
    display_order: 5,
    placeholder: "e.g., FERNANDEZ GARCIA",
    conditional_logic: { showIf: "other_names_used === yes" },
    validation_rules: { repeatable: true, repeat_group: "other_names" },
  },
  {
    field_name: "other_given_names",
    label: "Other Given Names Used",
    field_type: "text",
    required: false,
    step_number: 1,
    step_name: "Personal Information 1",
    display_order: 6,
    placeholder: "e.g., JUAN MIGUEL",
    conditional_logic: { showIf: "other_names_used === yes" },
    validation_rules: { repeatable: true, repeat_group: "other_names" },
  },
  {
    field_name: "has_telecode",
    label: "Do you have a telecode that represents your name?",
    field_type: "radio",
    required: true,
    step_number: 1,
    step_name: "Personal Information 1",
    display_order: 7,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "telecode_surname",
    label: "Telecode Surname",
    field_type: "text",
    required: false,
    step_number: 1,
    step_name: "Personal Information 1",
    display_order: 8,
    conditional_logic: { showIf: "has_telecode === yes" },
    validation_rules: { repeatable: true, repeat_group: "telecode" },
  },
  {
    field_name: "telecode_given_names",
    label: "Telecode Given Names",
    field_type: "text",
    required: false,
    step_number: 1,
    step_name: "Personal Information 1",
    display_order: 9,
    conditional_logic: { showIf: "has_telecode === yes" },
    validation_rules: { repeatable: true, repeat_group: "telecode" },
  },
  {
    field_name: "sex",
    label: "Sex",
    field_type: "radio",
    required: true,
    step_number: 1,
    step_name: "Personal Information 1",
    display_order: 10,
    options: [{ value: "male", text: "Male" }, { value: "female", text: "Female" }],
  },
  {
    field_name: "marital_status",
    label: "Marital Status",
    field_type: "select",
    required: true,
    step_number: 1,
    step_name: "Personal Information 1",
    display_order: 11,
    options: [
      { value: "married", text: "MARRIED" },
      { value: "common_law", text: "COMMON LAW MARRIAGE" },
      { value: "civil_union", text: "CIVIL UNION/DOMESTIC PARTNERSHIP" },
      { value: "single", text: "SINGLE" },
      { value: "widowed", text: "WIDOWED" },
      { value: "divorced", text: "DIVORCED" },
      { value: "legally_separated", text: "LEGALLY SEPARATED" },
      { value: "other", text: "OTHER" },
    ],
  },
  {
    field_name: "date_of_birth",
    label: "Date of Birth",
    field_type: "date",
    required: true,
    step_number: 1,
    step_name: "Personal Information 1",
    display_order: 12,
    validation_rules: { format: "DD-MMM-YYYY" },
  },
  {
    field_name: "city_of_birth",
    label: "City of Birth",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: "Personal Information 1",
    display_order: 13,
  },
  {
    field_name: "state_of_birth",
    label: "State/Province of Birth",
    field_type: "text",
    required: false,
    step_number: 1,
    step_name: "Personal Information 1",
    display_order: 14,
    validation_rules: { has_does_not_apply: true },
  },
  {
    field_name: "country_of_birth",
    label: "Country/Region of Birth",
    field_type: "select",
    required: true,
    step_number: 1,
    step_name: "Personal Information 1",
    display_order: 15,
    validation_rules: { source: "ISO3166-1" },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STEP 2: Personal Information 2 (Nationality, IDs)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    field_name: "nationality_country",
    label: "Country/Region of Origin (Nationality)",
    field_type: "select",
    required: true,
    step_number: 2,
    step_name: "Personal Information 2",
    display_order: 1,
    validation_rules: { source: "ISO3166-1" },
  },
  {
    field_name: "other_nationality",
    label: "Do you hold or have you held any nationality other than the one indicated above on nationality?",
    field_type: "radio",
    required: true,
    step_number: 2,
    step_name: "Personal Information 2",
    display_order: 2,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "other_nationality_country",
    label: "Other Country/Region of Nationality",
    field_type: "select",
    required: false,
    step_number: 2,
    step_name: "Personal Information 2",
    display_order: 3,
    conditional_logic: { showIf: "other_nationality === yes" },
    validation_rules: { source: "ISO3166-1", repeatable: true, repeat_group: "other_nationality" },
  },
  {
    field_name: "other_nationality_has_passport",
    label: "Do you hold a passport for that other nationality?",
    field_type: "radio",
    required: false,
    step_number: 2,
    step_name: "Personal Information 2",
    display_order: 4,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
    conditional_logic: { showIf: "other_nationality === yes" },
    validation_rules: { repeatable: true, repeat_group: "other_nationality" },
  },
  {
    field_name: "other_nationality_passport_number",
    label: "Passport Number",
    field_type: "text",
    required: false,
    step_number: 2,
    step_name: "Personal Information 2",
    display_order: 5,
    conditional_logic: { showIf: "other_nationality_has_passport === yes" },
    validation_rules: { repeatable: true, repeat_group: "other_nationality" },
  },
  {
    field_name: "permanent_resident_other_country",
    label: "Are you a permanent resident of a country/region other than your country/region of origin (nationality) indicated above?",
    field_type: "radio",
    required: true,
    step_number: 2,
    step_name: "Personal Information 2",
    display_order: 6,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "other_permanent_resident_country",
    label: "Other Permanent Resident Country/Region",
    field_type: "select",
    required: false,
    step_number: 2,
    step_name: "Personal Information 2",
    display_order: 7,
    conditional_logic: { showIf: "permanent_resident_other_country === yes" },
    validation_rules: { source: "ISO3166-1", repeatable: true, repeat_group: "permanent_resident" },
  },
  {
    field_name: "national_id_number",
    label: "National Identification Number",
    field_type: "text",
    required: false,
    step_number: 2,
    step_name: "Personal Information 2",
    display_order: 8,
    validation_rules: { has_does_not_apply: true },
  },
  {
    field_name: "us_social_security_number",
    label: "U.S. Social Security Number",
    field_type: "text",
    required: false,
    step_number: 2,
    step_name: "Personal Information 2",
    display_order: 9,
    validation_rules: { has_does_not_apply: true, pattern: "^[0-9]{3}-[0-9]{2}-[0-9]{4}$" },
  },
  {
    field_name: "us_taxpayer_id",
    label: "U.S. Taxpayer ID Number",
    field_type: "text",
    required: false,
    step_number: 2,
    step_name: "Personal Information 2",
    display_order: 10,
    validation_rules: { has_does_not_apply: true },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STEP 3: Travel Information
  // ═══════════════════════════════════════════════════════════════════════════
  {
    field_name: "purpose_of_trip",
    label: "Purpose of Trip to the U.S.",
    field_type: "select",
    required: true,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 1,
    validation_rules: { repeatable: true, repeat_group: "trip_purpose" },
    options: [
      { value: "A", text: "FOREIGN GOVERNMENT OFFICIAL (A)" },
      { value: "B", text: "TEMP. BUSINESS OR PLEASURE VISITOR (B)" },
      { value: "C", text: "ALIEN IN TRANSIT (C)" },
      { value: "CW/E2C", text: "CNMI WORKER OR INVESTOR (CW/E2C)" },
      { value: "D", text: "CREWMEMBER (D)" },
      { value: "E", text: "TREATY TRADER OR INVESTOR (E)" },
      { value: "F", text: "ACADEMIC OR LANGUAGE STUDENT (F)" },
      { value: "G", text: "INTERNATIONAL ORGANIZATION REP./EMP. (G)" },
      { value: "H", text: "TEMPORARY WORKER (H)" },
      { value: "I", text: "FOREIGN MEDIA REPRESENTATIVE (I)" },
      { value: "J", text: "EXCHANGE VISITOR (J)" },
      { value: "K", text: "FIANCÉ(E) OR SPOUSE OF A U.S. CITIZEN (K)" },
      { value: "L", text: "INTRACOMPANY TRANSFEREE (L)" },
      { value: "M", text: "VOCATIONAL/NONACADEMIC STUDENT (M)" },
      { value: "N", text: "OTHER (N)" },
      { value: "NATO", text: "NATO STAFF (NATO)" },
      { value: "O", text: "ALIEN WITH EXTRAORDINARY ABILITY (O)" },
      { value: "P", text: "INTERNATIONALLY RECOGNIZED ALIEN (P)" },
      { value: "Q", text: "CULTURAL EXCHANGE VISITOR (Q)" },
      { value: "R", text: "RELIGIOUS WORKER (R)" },
      { value: "S", text: "INFORMANT OR WITNESS (S)" },
      { value: "T", text: "VICTIM OF TRAFFICKING (T)" },
      { value: "TD/TN", text: "NAFTA PROFESSIONAL (TD/TN)" },
      { value: "U", text: "VICTIM OF CRIMINAL ACTIVITY (U)" },
      { value: "PARCIS", text: "PAROLE BENEFICIARY (PARCIS)" },
    ],
  },
  {
    field_name: "purpose_of_trip_specify",
    label: "Specify",
    field_type: "select",
    required: true,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 2,
    validation_rules: { repeatable: true, repeat_group: "trip_purpose" },
    options: [
      { value: "B1/B2", text: "BUSINESS OR TOURISM (TEMPORARY VISITOR) (B1/B2)" },
      { value: "B1", text: "BUSINESS (TEMPORARY VISITOR) (B1)" },
      { value: "B2", text: "TOURISM/MEDICAL TREATMENT (TEMPORARY VISITOR) (B2)" },
    ],
  },
  {
    field_name: "has_specific_plans",
    label: "Have you made specific travel plans?",
    field_type: "radio",
    required: true,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 3,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "arrival_date_day",
    label: "Date of Arrival in U.S. (Day)",
    field_type: "select",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 4,
    validation_rules: { repeatable: true, repeat_group: "specific_travel_plans", max_items: 1 },
    conditional_logic: { showIf: "has_specific_plans === yes" },
    options: [
      { value: "01", text: "01" },
      { value: "02", text: "02" },
      { value: "03", text: "03" },
      { value: "04", text: "04" },
      { value: "05", text: "05" },
      { value: "06", text: "06" },
      { value: "07", text: "07" },
      { value: "08", text: "08" },
      { value: "09", text: "09" },
      { value: "10", text: "10" },
      { value: "11", text: "11" },
      { value: "12", text: "12" },
      { value: "13", text: "13" },
      { value: "14", text: "14" },
      { value: "15", text: "15" },
      { value: "16", text: "16" },
      { value: "17", text: "17" },
      { value: "18", text: "18" },
      { value: "19", text: "19" },
      { value: "20", text: "20" },
      { value: "21", text: "21" },
      { value: "22", text: "22" },
      { value: "23", text: "23" },
      { value: "24", text: "24" },
      { value: "25", text: "25" },
      { value: "26", text: "26" },
      { value: "27", text: "27" },
      { value: "28", text: "28" },
      { value: "29", text: "29" },
      { value: "30", text: "30" },
      { value: "31", text: "31" },
    ],
  },
  {
    field_name: "arrival_date_month",
    label: "Date of Arrival in U.S. (Month)",
    field_type: "select",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 5,
    validation_rules: { repeatable: true, repeat_group: "specific_travel_plans", max_items: 1 },
    conditional_logic: { showIf: "has_specific_plans === yes" },
    options: [
      { value: "JAN", text: "JAN" },
      { value: "FEB", text: "FEB" },
      { value: "MAR", text: "MAR" },
      { value: "APR", text: "APR" },
      { value: "MAY", text: "MAY" },
      { value: "JUN", text: "JUN" },
      { value: "JUL", text: "JUL" },
      { value: "AUG", text: "AUG" },
      { value: "SEP", text: "SEP" },
      { value: "OCT", text: "OCT" },
      { value: "NOV", text: "NOV" },
      { value: "DEC", text: "DEC" },
    ],
  },
  {
    field_name: "arrival_date_year",
    label: "Date of Arrival in U.S. (Year)",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 6,
    placeholder: "YYYY",
    validation_rules: { pattern: "^[0-9]{4}$", minLength: 4, maxLength: 4, repeatable: true, repeat_group: "specific_travel_plans", max_items: 1 },
    conditional_logic: { showIf: "has_specific_plans === yes" },
  },
  {
    field_name: "arrival_flight",
    label: "Arrival Flight (if known)",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 7,
    conditional_logic: { showIf: "has_specific_plans === yes" },
    validation_rules: { repeatable: true, repeat_group: "specific_travel_plans", max_items: 1 },
  },
  {
    field_name: "arrival_city",
    label: "Arrival City",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 8,
    conditional_logic: { showIf: "has_specific_plans === yes" },
    validation_rules: { repeatable: true, repeat_group: "specific_travel_plans", max_items: 1 },
  },
  {
    field_name: "departure_date_day",
    label: "Date of Departure from U.S. (Day)",
    field_type: "select",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 9,
    validation_rules: { repeatable: true, repeat_group: "specific_travel_plans", max_items: 1 },
    conditional_logic: { showIf: "has_specific_plans === yes" },
    options: [
      { value: "01", text: "01" },
      { value: "02", text: "02" },
      { value: "03", text: "03" },
      { value: "04", text: "04" },
      { value: "05", text: "05" },
      { value: "06", text: "06" },
      { value: "07", text: "07" },
      { value: "08", text: "08" },
      { value: "09", text: "09" },
      { value: "10", text: "10" },
      { value: "11", text: "11" },
      { value: "12", text: "12" },
      { value: "13", text: "13" },
      { value: "14", text: "14" },
      { value: "15", text: "15" },
      { value: "16", text: "16" },
      { value: "17", text: "17" },
      { value: "18", text: "18" },
      { value: "19", text: "19" },
      { value: "20", text: "20" },
      { value: "21", text: "21" },
      { value: "22", text: "22" },
      { value: "23", text: "23" },
      { value: "24", text: "24" },
      { value: "25", text: "25" },
      { value: "26", text: "26" },
      { value: "27", text: "27" },
      { value: "28", text: "28" },
      { value: "29", text: "29" },
      { value: "30", text: "30" },
      { value: "31", text: "31" },
    ],
  },
  {
    field_name: "departure_date_month",
    label: "Date of Departure from U.S. (Month)",
    field_type: "select",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 10,
    validation_rules: { repeatable: true, repeat_group: "specific_travel_plans", max_items: 1 },
    conditional_logic: { showIf: "has_specific_plans === yes" },
    options: [
      { value: "JAN", text: "JAN" },
      { value: "FEB", text: "FEB" },
      { value: "MAR", text: "MAR" },
      { value: "APR", text: "APR" },
      { value: "MAY", text: "MAY" },
      { value: "JUN", text: "JUN" },
      { value: "JUL", text: "JUL" },
      { value: "AUG", text: "AUG" },
      { value: "SEP", text: "SEP" },
      { value: "OCT", text: "OCT" },
      { value: "NOV", text: "NOV" },
      { value: "DEC", text: "DEC" },
    ],
  },
  {
    field_name: "departure_date_year",
    label: "Date of Departure from U.S. (Year)",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 11,
    placeholder: "YYYY",
    validation_rules: { pattern: "^[0-9]{4}$", minLength: 4, maxLength: 4, repeatable: true, repeat_group: "specific_travel_plans", max_items: 1 },
    conditional_logic: { showIf: "has_specific_plans === yes" },
  },
  {
    field_name: "departure_flight",
    label: "Departure Flight (if known)",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 12,
    conditional_logic: { showIf: "has_specific_plans === yes" },
    validation_rules: { repeatable: true, repeat_group: "specific_travel_plans", max_items: 1 },
  },
  {
    field_name: "departure_city",
    label: "Departure City",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 13,
    conditional_logic: { showIf: "has_specific_plans === yes" },
    validation_rules: { repeatable: true, repeat_group: "specific_travel_plans", max_items: 1 },
  },
  {
    field_name: "planned_location",
    label: "Location",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 14,
    conditional_logic: { showIf: "has_specific_plans === yes" },
    validation_rules: { repeatable: true, repeat_group: "planned_locations", section_label: "Provide the locations you plan to visit in the U.S." },
  },
  // --- When no specific plans ---
  {
    field_name: "intended_arrival_date_day",
    label: "Intended Date of Arrival in U.S. (Day)",
    field_type: "select",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 15,
    conditional_logic: { showIf: "has_specific_plans === no" },
    options: [
      { value: "01", text: "01" },
      { value: "02", text: "02" },
      { value: "03", text: "03" },
      { value: "04", text: "04" },
      { value: "05", text: "05" },
      { value: "06", text: "06" },
      { value: "07", text: "07" },
      { value: "08", text: "08" },
      { value: "09", text: "09" },
      { value: "10", text: "10" },
      { value: "11", text: "11" },
      { value: "12", text: "12" },
      { value: "13", text: "13" },
      { value: "14", text: "14" },
      { value: "15", text: "15" },
      { value: "16", text: "16" },
      { value: "17", text: "17" },
      { value: "18", text: "18" },
      { value: "19", text: "19" },
      { value: "20", text: "20" },
      { value: "21", text: "21" },
      { value: "22", text: "22" },
      { value: "23", text: "23" },
      { value: "24", text: "24" },
      { value: "25", text: "25" },
      { value: "26", text: "26" },
      { value: "27", text: "27" },
      { value: "28", text: "28" },
      { value: "29", text: "29" },
      { value: "30", text: "30" },
      { value: "31", text: "31" },
    ],
  },
  {
    field_name: "intended_arrival_date_month",
    label: "Intended Date of Arrival in U.S. (Month)",
    field_type: "select",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 16,
    conditional_logic: { showIf: "has_specific_plans === no" },
    options: [
      { value: "JAN", text: "JAN" },
      { value: "FEB", text: "FEB" },
      { value: "MAR", text: "MAR" },
      { value: "APR", text: "APR" },
      { value: "MAY", text: "MAY" },
      { value: "JUN", text: "JUN" },
      { value: "JUL", text: "JUL" },
      { value: "AUG", text: "AUG" },
      { value: "SEP", text: "SEP" },
      { value: "OCT", text: "OCT" },
      { value: "NOV", text: "NOV" },
      { value: "DEC", text: "DEC" },
    ],
  },
  {
    field_name: "intended_arrival_date_year",
    label: "Intended Date of Arrival in U.S. (Year)",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 17,
    placeholder: "YYYY",
    conditional_logic: { showIf: "has_specific_plans === no" },
    validation_rules: { pattern: "^[0-9]{4}$", minLength: 4, maxLength: 4 },
  },
  {
    field_name: "intended_length_of_stay_value",
    label: "Intended Length of Stay in U.S. (Value)",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 18,
    conditional_logic: { showIf: "has_specific_plans === no" },
    validation_rules: { pattern: "^[0-9]{1,3}$" },
  },
  {
    field_name: "intended_length_of_stay_unit",
    label: "Intended Length of Stay in U.S. (Unit)",
    field_type: "select",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 19,
    conditional_logic: { showIf: "has_specific_plans === no" },
    options: [
      { value: "", text: "-SELECT ONE-" },
      { value: "YEAR(S)", text: "YEAR(S)" },
      { value: "MONTH(S)", text: "MONTH(S)" },
      { value: "WEEK(S)", text: "WEEK(S)" },
      { value: "DAY(S)", text: "DAY(S)" },
      { value: "LESS THAN 24 HOURS", text: "LESS THAN 24 HOURS" },
    ],
  },
  {
    field_name: "us_address_street1",
    label: "Street Address (Line 1)",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 20,
    conditional_logic: {
      showIf:
        "has_specific_plans === yes || intended_length_of_stay_unit === YEAR(S) || intended_length_of_stay_unit === MONTH(S) || intended_length_of_stay_unit === WEEK(S) || intended_length_of_stay_unit === DAY(S)",
    },
  },
  {
    field_name: "us_address_street2",
    label: "Street Address (Line 2)",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 21,
    validation_rules: { optional_label: true },
    conditional_logic: {
      showIf:
        "has_specific_plans === yes || intended_length_of_stay_unit === YEAR(S) || intended_length_of_stay_unit === MONTH(S) || intended_length_of_stay_unit === WEEK(S) || intended_length_of_stay_unit === DAY(S)",
    },
  },
  {
    field_name: "us_address_city",
    label: "City",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 22,
    conditional_logic: {
      showIf:
        "has_specific_plans === yes || intended_length_of_stay_unit === YEAR(S) || intended_length_of_stay_unit === MONTH(S) || intended_length_of_stay_unit === WEEK(S) || intended_length_of_stay_unit === DAY(S)",
    },
  },
  {
    field_name: "us_address_state",
    label: "State",
    field_type: "select",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 23,
    validation_rules: { source: "US_STATES" },
    conditional_logic: {
      showIf:
        "has_specific_plans === yes || intended_length_of_stay_unit === YEAR(S) || intended_length_of_stay_unit === MONTH(S) || intended_length_of_stay_unit === WEEK(S) || intended_length_of_stay_unit === DAY(S)",
    },
  },
  {
    field_name: "us_address_zip",
    label: "ZIP Code",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 24,
    validation_rules: { pattern: "^[0-9]{5}(-[0-9]{4})?$" },
    conditional_logic: {
      showIf:
        "has_specific_plans === yes || intended_length_of_stay_unit === YEAR(S) || intended_length_of_stay_unit === MONTH(S) || intended_length_of_stay_unit === WEEK(S) || intended_length_of_stay_unit === DAY(S)",
    },
  },
  // --- Person/Entity Paying ---
  {
    field_name: "trip_payer_type",
    label: "Person/Entity Paying for Your Trip",
    field_type: "select",
    required: true,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 25,
    options: [
      { value: "", text: "-SELECT ONE-" },
      { value: "self", text: "SELF" },
      { value: "other_person", text: "OTHER PERSON" },
      { value: "present_employer", text: "PRESENT EMPLOYER" },
      { value: "employer_in_us", text: "EMPLOYER IN THE U.S." },
      { value: "other_company", text: "OTHER COMPANY/ORGANIZATION" },
    ],
  },
  // --- Payer: OTHER PERSON fields ---
  {
    field_name: "payer_surname",
    label: "Surnames of Person Paying for Trip",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 26,
    placeholder: "e.g., FERNANDEZ GARCIA",
    conditional_logic: { showIf: "trip_payer_type === other_person" },
    validation_rules: { repeatable: true, repeat_group: "payer_person" },
  },
  {
    field_name: "payer_given_names",
    label: "Given Names of Person Paying for Trip",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 27,
    placeholder: "e.g., JUAN MIGUEL",
    conditional_logic: { showIf: "trip_payer_type === other_person" },
    validation_rules: { repeatable: true, repeat_group: "payer_person" },
  },
  {
    field_name: "payer_phone",
    label: "Telephone Number",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 28,
    conditional_logic: { showIf: "trip_payer_type === other_person || trip_payer_type === present_employer || trip_payer_type === employer_in_us" },
    validation_rules: { repeatable: true, repeat_group: "payer_person" },
  },
  {
    field_name: "payer_email",
    label: "Email Address",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 29,
    placeholder: "e.g., emailaddress@example.com",
    validation_rules: { format: "email", has_does_not_apply: true, repeatable: true, repeat_group: "payer_person" },
    conditional_logic: { showIf: "trip_payer_type === other_person" },
  },
  {
    field_name: "payer_relationship",
    label: "Relationship to You",
    field_type: "select",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 30,
    conditional_logic: { showIf: "trip_payer_type === other_person" },
    validation_rules: { repeatable: true, repeat_group: "payer_person" },
    options: [
      { value: "", text: "- SELECT ONE -" },
      { value: "CHILD", text: "CHILD" },
      { value: "PARENT", text: "PARENT" },
      { value: "SPOUSE", text: "SPOUSE" },
      { value: "OTHER RELATIVE", text: "OTHER RELATIVE" },
      { value: "FRIEND", text: "FRIEND" },
      { value: "OTHER", text: "OTHER" },
    ],
  },
  {
    field_name: "payer_address_same_as_home",
    label: "Is the address of the party paying for your trip the same as your Home or Mailing Address?",
    field_type: "radio",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 31,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
    conditional_logic: { showIf: "trip_payer_type === other_person" },
    validation_rules: { repeatable: true, repeat_group: "payer_person" },
  },
  {
    field_name: "payer_address_street1",
    label: "Street Address (Line 1)",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 32,
    conditional_logic: { showIf: "payer_address_same_as_home === no" },
    validation_rules: { repeatable: true, repeat_group: "payer_address" },
  },
  {
    field_name: "payer_address_street2",
    label: "Street Address (Line 2)",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 33,
    validation_rules: { optional_label: true, repeatable: true, repeat_group: "payer_address" },
    conditional_logic: { showIf: "payer_address_same_as_home === no" },
  },
  {
    field_name: "payer_address_city",
    label: "City",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 34,
    conditional_logic: { showIf: "payer_address_same_as_home === no" },
    validation_rules: { repeatable: true, repeat_group: "payer_address" },
  },
  {
    field_name: "payer_address_state",
    label: "State/Province",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 35,
    validation_rules: { has_does_not_apply: true, repeatable: true, repeat_group: "payer_address" },
    conditional_logic: { showIf: "payer_address_same_as_home === no" },
  },
  {
    field_name: "payer_address_postal",
    label: "Postal Zone/ZIP Code",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 36,
    validation_rules: { has_does_not_apply: true, repeatable: true, repeat_group: "payer_address" },
    conditional_logic: { showIf: "payer_address_same_as_home === no" },
  },
  {
    field_name: "payer_address_country",
    label: "Country/Region",
    field_type: "select",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 37,
    validation_rules: { source: "ISO3166-1", repeatable: true, repeat_group: "payer_address" },
    conditional_logic: { showIf: "payer_address_same_as_home === no" },
  },
  // --- Payer: OTHER COMPANY/ORGANIZATION fields ---
  {
    field_name: "payer_org_name",
    label: "Name of Company/Organization Paying for Trip",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 38,
    conditional_logic: { showIf: "trip_payer_type === other_company || trip_payer_type === present_employer || trip_payer_type === employer_in_us" },
    validation_rules: { repeatable: true, repeat_group: "payer_org" },
  },
  {
    field_name: "payer_org_phone",
    label: "Telephone Number",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 39,
    conditional_logic: { showIf: "trip_payer_type === other_company" },
    validation_rules: { repeatable: true, repeat_group: "payer_org" },
  },
  {
    field_name: "payer_org_relationship",
    label: "Relationship to You",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 40,
    conditional_logic: { showIf: "trip_payer_type === other_company || trip_payer_type === present_employer || trip_payer_type === employer_in_us" },
    validation_rules: { repeatable: true, repeat_group: "payer_org" },
  },
  {
    field_name: "payer_org_address_street1",
    label: "Street Address (Line 1)",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 41,
    conditional_logic: { showIf: "trip_payer_type === other_company" },
    validation_rules: { repeatable: true, repeat_group: "payer_org" },
  },
  {
    field_name: "payer_org_address_street2",
    label: "Street Address (Line 2)",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 42,
    validation_rules: { optional_label: true, repeatable: true, repeat_group: "payer_org" },
    conditional_logic: { showIf: "trip_payer_type === other_company" },
  },
  {
    field_name: "payer_org_address_city",
    label: "City",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 43,
    conditional_logic: { showIf: "trip_payer_type === other_company" },
    validation_rules: { repeatable: true, repeat_group: "payer_org" },
  },
  {
    field_name: "payer_org_address_state",
    label: "State/Province",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 44,
    validation_rules: { has_does_not_apply: true, repeatable: true, repeat_group: "payer_org" },
    conditional_logic: { showIf: "trip_payer_type === other_company" },
  },
  {
    field_name: "payer_org_address_postal",
    label: "Postal Zone/ZIP Code",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 45,
    validation_rules: { has_does_not_apply: true, repeatable: true, repeat_group: "payer_org" },
    conditional_logic: { showIf: "trip_payer_type === other_company" },
  },
  {
    field_name: "payer_org_address_country",
    label: "Country/Region",
    field_type: "select",
    required: false,
    step_number: 3,
    step_name: "Travel Information",
    display_order: 46,
    validation_rules: { source: "ISO3166-1", repeatable: true, repeat_group: "payer_org" },
    conditional_logic: { showIf: "trip_payer_type === other_company" },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STEP 4: Travel Companions
  // ═══════════════════════════════════════════════════════════════════════════
  {
    field_name: "has_companions",
    label: "Are there other persons traveling with you?",
    field_type: "radio",
    required: true,
    step_number: 4,
    step_name: "Travel Companions",
    display_order: 1,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "companion_group_travel",
    label: "Are you traveling as part of a group or organization?",
    field_type: "radio",
    required: false,
    step_number: 4,
    step_name: "Travel Companions",
    display_order: 2,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
    conditional_logic: { showIf: "has_companions === yes" },
  },
  {
    field_name: "companion_group_name",
    label: "Group Name",
    field_type: "text",
    required: false,
    step_number: 4,
    step_name: "Travel Companions",
    display_order: 3,
    conditional_logic: { showIf: "companion_group_travel === yes" },
  },
  {
    field_name: "companion_surname",
    label: "Surnames",
    field_type: "text",
    required: false,
    step_number: 4,
    step_name: "Travel Companions",
    display_order: 4,
    placeholder: "e.g., FERNANDEZ GARCIA",
    conditional_logic: { showIf: "has_companions === yes" },
    validation_rules: { repeatable: true, repeat_group: "companions" },
  },
  {
    field_name: "companion_given_names",
    label: "Given Names",
    field_type: "text",
    required: false,
    step_number: 4,
    step_name: "Travel Companions",
    display_order: 5,
    placeholder: "e.g., JUAN MIGUEL",
    conditional_logic: { showIf: "has_companions === yes" },
    validation_rules: { repeatable: true, repeat_group: "companions" },
  },
  {
    field_name: "companion_relationship",
    label: "Relationship to You",
    field_type: "select",
    required: false,
    step_number: 4,
    step_name: "Travel Companions",
    display_order: 6,
    conditional_logic: { showIf: "has_companions === yes" },
    validation_rules: { repeatable: true, repeat_group: "companions" },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STEP 5: Previous U.S. Travel
  // ═══════════════════════════════════════════════════════════════════════════
  {
    field_name: "has_been_in_us",
    label: "Have you ever been in the U.S.?",
    field_type: "radio",
    required: true,
    step_number: 5,
    step_name: "Previous U.S. Travel",
    display_order: 1,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "previous_visit_date_arrived",
    label: "Date Arrived",
    field_type: "date",
    required: false,
    step_number: 5,
    step_name: "Previous U.S. Travel",
    display_order: 2,
    validation_rules: {
      format: "DD-MMM-YYYY",
      repeatable: true,
      repeat_group: "previous_visits",
      max_items: 5,
      section_label: "Provide information on your last five U.S. visits",
    },
    conditional_logic: { showIf: "has_been_in_us === yes" },
  },
  {
    field_name: "previous_visit_length_of_stay",
    label: "Length of Stay (Value)",
    field_type: "text",
    required: false,
    step_number: 5,
    step_name: "Previous U.S. Travel",
    display_order: 3,
    conditional_logic: { showIf: "has_been_in_us === yes" },
    validation_rules: {
      pattern: "^[0-9]{1,3}$",
      repeatable: true,
      repeat_group: "previous_visits",
      max_items: 5,
    },
  },
  {
    field_name: "previous_visit_length_of_stay_unit",
    label: "Length of Stay (Unit)",
    field_type: "select",
    required: false,
    step_number: 5,
    step_name: "Previous U.S. Travel",
    display_order: 4,
    conditional_logic: { showIf: "has_been_in_us === yes" },
    validation_rules: { repeatable: true, repeat_group: "previous_visits", max_items: 5 },
    options: [
      { value: "YEAR(S)", text: "YEAR(S)" },
      { value: "MONTH(S)", text: "MONTH(S)" },
      { value: "WEEK(S)", text: "WEEK(S)" },
      { value: "DAY(S)", text: "DAY(S)" },
      { value: "LESS_THAN_24_HOURS", text: "LESS THAN 24 HOURS" },
    ],
  },
  {
    field_name: "has_us_drivers_license",
    label: "Do you or did you ever hold a U.S. Driver's License?",
    field_type: "radio",
    required: true,
    step_number: 5,
    step_name: "Previous U.S. Travel",
    display_order: 5,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
    conditional_logic: { showIf: "has_been_in_us === yes" },
  },
  {
    field_name: "us_drivers_license_number",
    label: "Driver's License Number",
    field_type: "text",
    required: false,
    step_number: 5,
    step_name: "Previous U.S. Travel",
    display_order: 6,
    conditional_logic: { showIf: "has_us_drivers_license === yes" },
    validation_rules: { repeatable: true, repeat_group: "drivers_licenses" },
  },
  {
    field_name: "us_drivers_license_state",
    label: "Driver's License State",
    field_type: "select",
    required: false,
    step_number: 5,
    step_name: "Previous U.S. Travel",
    display_order: 7,
    conditional_logic: { showIf: "has_us_drivers_license === yes" },
    validation_rules: { source: "US_STATES", repeatable: true, repeat_group: "drivers_licenses" },
  },
  {
    field_name: "has_us_visa",
    label: "Have you ever been issued a U.S. Visa?",
    field_type: "radio",
    required: true,
    step_number: 5,
    step_name: "Previous U.S. Travel",
    display_order: 8,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "last_visa_issue_day",
    label: "Date Last Visa Was Issued (Day)",
    field_type: "select",
    required: true,
    step_number: 5,
    step_name: "Previous U.S. Travel",
    display_order: 9,
    conditional_logic: { showIf: "has_us_visa === yes" },
    options: [
      { value: "01", text: "01" },
      { value: "02", text: "02" },
      { value: "03", text: "03" },
      { value: "04", text: "04" },
      { value: "05", text: "05" },
      { value: "06", text: "06" },
      { value: "07", text: "07" },
      { value: "08", text: "08" },
      { value: "09", text: "09" },
      { value: "10", text: "10" },
      { value: "11", text: "11" },
      { value: "12", text: "12" },
      { value: "13", text: "13" },
      { value: "14", text: "14" },
      { value: "15", text: "15" },
      { value: "16", text: "16" },
      { value: "17", text: "17" },
      { value: "18", text: "18" },
      { value: "19", text: "19" },
      { value: "20", text: "20" },
      { value: "21", text: "21" },
      { value: "22", text: "22" },
      { value: "23", text: "23" },
      { value: "24", text: "24" },
      { value: "25", text: "25" },
      { value: "26", text: "26" },
      { value: "27", text: "27" },
      { value: "28", text: "28" },
      { value: "29", text: "29" },
      { value: "30", text: "30" },
      { value: "31", text: "31" },
    ],
  },
  {
    field_name: "last_visa_issue_month",
    label: "Date Last Visa Was Issued (Month)",
    field_type: "select",
    required: true,
    step_number: 5,
    step_name: "Previous U.S. Travel",
    display_order: 10,
    conditional_logic: { showIf: "has_us_visa === yes" },
    options: [
      { value: "JAN", text: "JAN" },
      { value: "FEB", text: "FEB" },
      { value: "MAR", text: "MAR" },
      { value: "APR", text: "APR" },
      { value: "MAY", text: "MAY" },
      { value: "JUN", text: "JUN" },
      { value: "JUL", text: "JUL" },
      { value: "AUG", text: "AUG" },
      { value: "SEP", text: "SEP" },
      { value: "OCT", text: "OCT" },
      { value: "NOV", text: "NOV" },
      { value: "DEC", text: "DEC" },
    ],
  },
  {
    field_name: "last_visa_issue_year",
    label: "Date Last Visa Was Issued (Year)",
    field_type: "text",
    required: true,
    step_number: 5,
    step_name: "Previous U.S. Travel",
    display_order: 11,
    placeholder: "YYYY",
    conditional_logic: { showIf: "has_us_visa === yes" },
    validation_rules: { pattern: "^[0-9]{4}$", minLength: 4, maxLength: 4, format: "DD-MMM-YYYY" },
  },
  {
    field_name: "visa_number",
    label: "Visa Number",
    field_type: "text",
    required: false,
    step_number: 5,
    step_name: "Previous U.S. Travel",
    display_order: 12,
    conditional_logic: { showIf: "has_us_visa === yes" },
    validation_rules: { maxLength: 20, has_does_not_apply: true, does_not_apply_label: "Do Not Know" },
  },
  {
    field_name: "visa_number_unknown",
    label: "Do Not Know",
    field_type: "checkbox",
    required: false,
    step_number: 5,
    step_name: "Previous U.S. Travel",
    display_order: 13,
    conditional_logic: { showIf: "has_us_visa === yes" },
  },
  {
    field_name: "applying_same_visa_type",
    label: "Are you applying for the same type of visa?",
    field_type: "radio",
    required: true,
    step_number: 5,
    step_name: "Previous U.S. Travel",
    display_order: 14,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
    conditional_logic: { showIf: "has_us_visa === yes" },
  },
  {
    field_name: "applying_same_country_of_issue_and_residence",
    label: "Are you applying in the same country or location where the visa above was issued, and is this country or location your place of principal of residence?",
    field_type: "radio",
    required: true,
    step_number: 5,
    step_name: "Previous U.S. Travel",
    display_order: 15,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
    conditional_logic: { showIf: "has_us_visa === yes" },
  },
  {
    field_name: "has_been_ten_printed",
    label: "Have you been ten-printed?",
    field_type: "radio",
    required: true,
    step_number: 5,
    step_name: "Previous U.S. Travel",
    display_order: 16,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
    conditional_logic: { showIf: "has_us_visa === yes" },
  },
  {
    field_name: "visa_lost_or_stolen",
    label: "Has your U.S. Visa ever been lost or stolen?",
    field_type: "radio",
    required: true,
    step_number: 5,
    step_name: "Previous U.S. Travel",
    display_order: 17,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
    conditional_logic: { showIf: "has_us_visa === yes" },
  },
  {
    field_name: "year_visa_lost_or_stolen",
    label: "Enter year visa was lost or stolen",
    field_type: "text",
    required: true,
    step_number: 5,
    step_name: "Previous U.S. Travel",
    display_order: 18,
    placeholder: "Year",
    conditional_logic: { showIf: "visa_lost_or_stolen === yes" },
    validation_rules: { pattern: "^[0-9]{4}$", minLength: 4, maxLength: 4 },
  },
  {
    field_name: "visa_lost_or_stolen_explain",
    label: "Explain",
    field_type: "textarea",
    required: true,
    step_number: 5,
    step_name: "Previous U.S. Travel",
    display_order: 19,
    conditional_logic: { showIf: "visa_lost_or_stolen === yes" },
    validation_rules: { maxLength: 2000 },
  },
  {
    field_name: "visa_cancelled_or_revoked",
    label: "Has your U.S. Visa ever been cancelled or revoked?",
    field_type: "radio",
    required: true,
    step_number: 5,
    step_name: "Previous U.S. Travel",
    display_order: 20,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
    conditional_logic: { showIf: "has_us_visa === yes" },
  },
  {
    field_name: "visa_cancelled_or_revoked_explain",
    label: "Explain",
    field_type: "textarea",
    required: true,
    step_number: 5,
    step_name: "Previous U.S. Travel",
    display_order: 21,
    conditional_logic: { showIf: "visa_cancelled_or_revoked === yes" },
    validation_rules: { maxLength: 2000 },
  },
  {
    field_name: "has_been_refused",
    label: "Have you ever been refused a U.S. Visa, or been refused admission to the United States, or withdrawn your application for admission at the port of entry?",
    field_type: "radio",
    required: true,
    step_number: 5,
    step_name: "Previous U.S. Travel",
    display_order: 22,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "refusal_explain",
    label: "Explain",
    field_type: "textarea",
    required: false,
    step_number: 5,
    step_name: "Previous U.S. Travel",
    display_order: 23,
    conditional_logic: { showIf: "has_been_refused === yes" },
    validation_rules: { repeatable: true, repeat_group: "visa_refused" },
  },
  {
    field_name: "immigrant_petition_filed",
    label: "Has anyone ever filed an immigrant petition on your behalf with the United States Citizenship and Immigration Services?",
    field_type: "radio",
    required: true,
    step_number: 5,
    step_name: "Previous U.S. Travel",
    display_order: 24,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "immigrant_petition_explain",
    label: "Explain",
    field_type: "textarea",
    required: false,
    step_number: 5,
    step_name: "Previous U.S. Travel",
    display_order: 25,
    conditional_logic: { showIf: "immigrant_petition_filed === yes" },
    validation_rules: { repeatable: true, repeat_group: "immigrant_petition" },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STEP 6: Address and Phone / Email / Social Media
  // ═══════════════════════════════════════════════════════════════════════════
  {
    field_name: "home_address_line1",
    label: "Street Address (Line 1)",
    field_type: "text",
    required: true,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 1,
  },
  {
    field_name: "home_address_line2",
    label: "Street Address (Line 2)",
    field_type: "text",
    required: false,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 2,
    validation_rules: { optional_label: true },
  },
  {
    field_name: "home_address_city",
    label: "City",
    field_type: "text",
    required: true,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 3,
  },
  {
    field_name: "home_address_state_province",
    label: "State/Province",
    field_type: "text",
    required: false,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 4,
    validation_rules: { has_does_not_apply: true },
  },
  {
    field_name: "home_address_postal_code",
    label: "Postal Zone/ZIP Code",
    field_type: "text",
    required: false,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 5,
    validation_rules: { has_does_not_apply: true },
  },
  {
    field_name: "home_address_country",
    label: "Country/Region",
    field_type: "select",
    required: true,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 6,
    validation_rules: { source: "ISO3166-1" },
  },
  {
    field_name: "mailing_same_as_home",
    label: "Is your Mailing Address the same as your Home Address?",
    field_type: "radio",
    required: true,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 7,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "mailing_address_line1",
    label: "Mailing Street Address (Line 1)",
    field_type: "text",
    required: false,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 8,
    conditional_logic: { showIf: "mailing_same_as_home === no" },
    validation_rules: { repeatable: true, repeat_group: "mailing_address" },
  },
  {
    field_name: "mailing_address_line2",
    label: "Mailing Street Address (Line 2)",
    field_type: "text",
    required: false,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 9,
    validation_rules: { optional_label: true, repeatable: true, repeat_group: "mailing_address" },
    conditional_logic: { showIf: "mailing_same_as_home === no" },
  },
  {
    field_name: "mailing_address_city",
    label: "Mailing City",
    field_type: "text",
    required: false,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 10,
    conditional_logic: { showIf: "mailing_same_as_home === no" },
    validation_rules: { repeatable: true, repeat_group: "mailing_address" },
  },
  {
    field_name: "mailing_address_state",
    label: "Mailing State/Province",
    field_type: "text",
    required: false,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 11,
    validation_rules: { has_does_not_apply: true, repeatable: true, repeat_group: "mailing_address" },
    conditional_logic: { showIf: "mailing_same_as_home === no" },
  },
  {
    field_name: "mailing_address_postal",
    label: "Mailing Postal Zone/ZIP Code",
    field_type: "text",
    required: false,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 12,
    validation_rules: { has_does_not_apply: true, repeatable: true, repeat_group: "mailing_address" },
    conditional_logic: { showIf: "mailing_same_as_home === no" },
  },
  {
    field_name: "mailing_address_country",
    label: "Mailing Country/Region",
    field_type: "select",
    required: false,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 13,
    validation_rules: { source: "ISO3166-1", repeatable: true, repeat_group: "mailing_address" },
    conditional_logic: { showIf: "mailing_same_as_home === no" },
  },
  {
    field_name: "primary_phone",
    label: "Primary Phone Number",
    field_type: "text",
    required: true,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 14,
  },
  {
    field_name: "secondary_phone",
    label: "Secondary Phone Number",
    field_type: "text",
    required: false,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 15,
    validation_rules: { has_does_not_apply: true },
  },
  {
    field_name: "work_phone",
    label: "Work Phone Number",
    field_type: "text",
    required: false,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 16,
    validation_rules: { has_does_not_apply: true },
  },
  {
    field_name: "has_other_phones",
    label: "Have you used any other phone numbers in the last five years?",
    field_type: "radio",
    required: true,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 17,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "additional_phone",
    label: "Additional Phone Number",
    field_type: "text",
    required: false,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 18,
    conditional_logic: { showIf: "has_other_phones === yes" },
    validation_rules: { repeatable: true, repeat_group: "additional_phones" },
  },
  {
    field_name: "email_address",
    label: "Email Address",
    field_type: "text",
    required: true,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 19,
    validation_rules: { format: "email" },
  },
  {
    field_name: "has_other_emails",
    label: "Have you used any other email addresses in the last five years?",
    field_type: "radio",
    required: true,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 20,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "additional_email",
    label: "Additional Email Address",
    field_type: "text",
    required: false,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 21,
    conditional_logic: { showIf: "has_other_emails === yes" },
    validation_rules: { format: "email", repeatable: true, repeat_group: "additional_emails" },
  },
  {
    field_name: "social_media_platform",
    label: "Social Media Provider/Platform",
    field_type: "select",
    required: false,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 22,
    options: [
      { value: "ASK.FM", text: "ASK.FM" },
      { value: "DOUBAN", text: "DOUBAN" },
      { value: "FACEBOOK", text: "FACEBOOK" },
      { value: "FLICKR", text: "FLICKR" },
      { value: "GOOGLE+", text: "GOOGLE+" },
      { value: "INSTAGRAM", text: "INSTAGRAM" },
      { value: "LINKEDIN", text: "LINKEDIN" },
      { value: "MYSPACE", text: "MYSPACE" },
      { value: "PINTEREST", text: "PINTEREST" },
      { value: "QZONE (QQ)", text: "QZONE (QQ)" },
      { value: "REDDIT", text: "REDDIT" },
      { value: "SINA WEIBO", text: "SINA WEIBO" },
      { value: "TENCENT WEIBO", text: "TENCENT WEIBO" },
      { value: "TUMBLR", text: "TUMBLR" },
      { value: "TWITTER", text: "TWITTER" },
      { value: "TWOO", text: "TWOO" },
      { value: "VINE", text: "VINE" },
      { value: "VKONTAKTE (VK)", text: "VKONTAKTE (VK)" },
      { value: "YOUKU", text: "YOUKU" },
      { value: "YOUTUBE", text: "YOUTUBE" },
      { value: "NONE", text: "NONE" },
    ],
    validation_rules: { repeatable: true, repeat_group: "social_media", section_label: "Social Media" },
  },
  {
    field_name: "social_media_handle",
    label: "Social Media Identifier",
    field_type: "text",
    required: false,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 23,
    conditional_logic: { showIf: "social_media_platform !== NONE && social_media_platform !== null" },
    validation_rules: { repeatable: true, repeat_group: "social_media" },
  },
  {
    field_name: "has_other_social_media",
    label: "Do you wish to provide information about your presence on any other websites or applications you have used within the last five years to create or share content (photos, videos, status updates, etc.)?",
    field_type: "radio",
    required: false,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 24,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "other_social_media_name",
    label: "Website/Application Name",
    field_type: "text",
    required: false,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 25,
    conditional_logic: { showIf: "has_other_social_media === yes" },
    validation_rules: { repeatable: true, repeat_group: "other_social_media" },
  },
  {
    field_name: "other_social_media_identifier",
    label: "Identifier",
    field_type: "text",
    required: false,
    step_number: 6,
    step_name: "Address and Phone",
    display_order: 26,
    conditional_logic: { showIf: "has_other_social_media === yes" },
    validation_rules: { repeatable: true, repeat_group: "other_social_media" },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STEP 7: Passport Information
  // ═══════════════════════════════════════════════════════════════════════════
  {
    field_name: "passport_document_type",
    label: "Passport/Travel Document Type",
    field_type: "select",
    required: true,
    step_number: 7,
    step_name: "Passport Information",
    display_order: 1,
    options: [
      { value: "regular", text: "REGULAR" },
      { value: "official", text: "OFFICIAL" },
      { value: "diplomatic", text: "DIPLOMATIC" },
      { value: "laissez_passer", text: "LAISSEZ-PASSER" },
      { value: "other", text: "OTHER" },
    ],
  },
  {
    field_name: "passport_number",
    label: "Passport/Travel Document Number",
    field_type: "text",
    required: true,
    step_number: 7,
    step_name: "Passport Information",
    display_order: 2,
    validation_rules: { maxLength: 20 },
  },
  {
    field_name: "passport_book_number",
    label: "Passport Book Number",
    field_type: "text",
    required: false,
    step_number: 7,
    step_name: "Passport Information",
    display_order: 3,
    validation_rules: { has_does_not_apply: true },
  },
  {
    field_name: "passport_issuing_country",
    label: "Country/Authority That Issued Passport/Travel Document",
    field_type: "select",
    required: true,
    step_number: 7,
    step_name: "Passport Information",
    display_order: 4,
    validation_rules: { source: "ISO3166-1" },
  },
  {
    field_name: "passport_issuance_city",
    label: "City Where Issued",
    field_type: "text",
    required: true,
    step_number: 7,
    step_name: "Passport Information",
    display_order: 5,
  },
  {
    field_name: "passport_issuance_state",
    label: "State/Province Where Issued",
    field_type: "text",
    required: false,
    step_number: 7,
    step_name: "Passport Information",
    display_order: 6,
    validation_rules: { has_does_not_apply: true },
  },
  {
    field_name: "passport_issuance_country",
    label: "Country/Region Where Issued",
    field_type: "select",
    required: true,
    step_number: 7,
    step_name: "Passport Information",
    display_order: 7,
    validation_rules: { source: "ISO3166-1" },
  },
  {
    field_name: "passport_issuance_date",
    label: "Issuance Date",
    field_type: "date",
    required: true,
    step_number: 7,
    step_name: "Passport Information",
    display_order: 8,
    validation_rules: { format: "DD-MMM-YYYY" },
  },
  {
    field_name: "passport_expiration_date",
    label: "Expiration Date",
    field_type: "date",
    required: true,
    step_number: 7,
    step_name: "Passport Information",
    display_order: 9,
    validation_rules: { format: "DD-MMM-YYYY", has_does_not_apply: true, does_not_apply_label: "No Expiration" },
  },
  {
    field_name: "lost_passport",
    label: "Have you ever lost a passport or had one stolen?",
    field_type: "radio",
    required: true,
    step_number: 7,
    step_name: "Passport Information",
    display_order: 10,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "lost_passport_number",
    label: "Lost/Stolen Passport Number",
    field_type: "text",
    required: false,
    step_number: 7,
    step_name: "Passport Information",
    display_order: 11,
    conditional_logic: { showIf: "lost_passport === yes" },
    validation_rules: { repeatable: true, repeat_group: "lost_passport" },
  },
  {
    field_name: "lost_passport_country",
    label: "Country/Authority That Issued Passport/Travel Document",
    field_type: "select",
    required: false,
    step_number: 7,
    step_name: "Passport Information",
    display_order: 12,
    validation_rules: { source: "ISO3166-1", repeatable: true, repeat_group: "lost_passport" },
    conditional_logic: { showIf: "lost_passport === yes" },
  },
  {
    field_name: "lost_passport_explain",
    label: "Explain",
    field_type: "textarea",
    required: false,
    step_number: 7,
    step_name: "Passport Information",
    display_order: 13,
    conditional_logic: { showIf: "lost_passport === yes" },
    validation_rules: { repeatable: true, repeat_group: "lost_passport" },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STEP 8: U.S. Point of Contact
  // ═══════════════════════════════════════════════════════════════════════════
  {
    field_name: "us_contact_surname",
    label: "Surnames",
    field_type: "text",
    required: true,
    step_number: 8,
    step_name: "U.S. Contact Information",
    display_order: 1,
    placeholder: "e.g., FERNANDEZ GARCIA",
  },
  {
    field_name: "us_contact_given_names",
    label: "Given Names",
    field_type: "text",
    required: true,
    step_number: 8,
    step_name: "U.S. Contact Information",
    display_order: 2,
    placeholder: "e.g., JUAN MIGUEL",
  },
  {
    field_name: "us_contact_organization",
    label: "Organization Name",
    field_type: "text",
    required: false,
    step_number: 8,
    step_name: "U.S. Contact Information",
    display_order: 3,
  },
  {
    field_name: "us_contact_relationship",
    label: "Relationship to You",
    field_type: "select",
    required: true,
    step_number: 8,
    step_name: "U.S. Contact Information",
    display_order: 4,
  },
  {
    field_name: "us_contact_address_street1",
    label: "Street Address (Line 1)",
    field_type: "text",
    required: true,
    step_number: 8,
    step_name: "U.S. Contact Information",
    display_order: 5,
  },
  {
    field_name: "us_contact_address_street2",
    label: "Street Address (Line 2)",
    field_type: "text",
    required: false,
    step_number: 8,
    step_name: "U.S. Contact Information",
    display_order: 6,
    validation_rules: { optional_label: true },
  },
  {
    field_name: "us_contact_city",
    label: "City",
    field_type: "text",
    required: true,
    step_number: 8,
    step_name: "U.S. Contact Information",
    display_order: 7,
  },
  {
    field_name: "us_contact_state",
    label: "State",
    field_type: "select",
    required: true,
    step_number: 8,
    step_name: "U.S. Contact Information",
    display_order: 8,
    validation_rules: { source: "US_STATES" },
  },
  {
    field_name: "us_contact_zip",
    label: "ZIP Code",
    field_type: "text",
    required: true,
    step_number: 8,
    step_name: "U.S. Contact Information",
    display_order: 9,
    validation_rules: { pattern: "^[0-9]{5}(-[0-9]{4})?$" },
  },
  {
    field_name: "us_contact_phone",
    label: "Phone Number",
    field_type: "text",
    required: true,
    step_number: 8,
    step_name: "U.S. Contact Information",
    display_order: 10,
  },
  {
    field_name: "us_contact_email",
    label: "Email Address",
    field_type: "text",
    required: false,
    step_number: 8,
    step_name: "U.S. Contact Information",
    display_order: 11,
    validation_rules: { format: "email" },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STEP 9: Family Information
  // ═══════════════════════════════════════════════════════════════════════════
  {
    field_name: "father_surname",
    label: "Father's Surnames",
    field_type: "text",
    required: true,
    step_number: 9,
    step_name: "Family Information",
    display_order: 1,
    placeholder: "e.g., FERNANDEZ GARCIA",
    validation_rules: { has_does_not_apply: true, does_not_apply_label: "Do Not Know" },
  },
  {
    field_name: "father_given_names",
    label: "Father's Given Names",
    field_type: "text",
    required: true,
    step_number: 9,
    step_name: "Family Information",
    display_order: 2,
    placeholder: "e.g., JUAN MIGUEL",
    validation_rules: { has_does_not_apply: true, does_not_apply_label: "Do Not Know" },
  },
  {
    field_name: "father_date_of_birth",
    label: "Father's Date of Birth",
    field_type: "date",
    required: true,
    step_number: 9,
    step_name: "Family Information",
    display_order: 3,
    validation_rules: { format: "DD-MMM-YYYY", has_does_not_apply: true, does_not_apply_label: "Do Not Know" },
  },
  {
    field_name: "father_in_us",
    label: "Is your father in the U.S.?",
    field_type: "radio",
    required: true,
    step_number: 9,
    step_name: "Family Information",
    display_order: 4,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "father_us_status",
    label: "Father's U.S. Status",
    field_type: "select",
    required: false,
    step_number: 9,
    step_name: "Family Information",
    display_order: 5,
    conditional_logic: { showIf: "father_in_us === yes" },
    validation_rules: { repeatable: true, repeat_group: "father_us" },
  },
  {
    field_name: "mother_surname",
    label: "Mother's Surnames",
    field_type: "text",
    required: true,
    step_number: 9,
    step_name: "Family Information",
    display_order: 6,
    placeholder: "e.g., FERNANDEZ GARCIA",
    validation_rules: { has_does_not_apply: true, does_not_apply_label: "Do Not Know" },
  },
  {
    field_name: "mother_given_names",
    label: "Mother's Given Names",
    field_type: "text",
    required: true,
    step_number: 9,
    step_name: "Family Information",
    display_order: 7,
    placeholder: "e.g., JUAN MIGUEL",
    validation_rules: { has_does_not_apply: true, does_not_apply_label: "Do Not Know" },
  },
  {
    field_name: "mother_date_of_birth",
    label: "Mother's Date of Birth",
    field_type: "date",
    required: true,
    step_number: 9,
    step_name: "Family Information",
    display_order: 8,
    validation_rules: { format: "DD-MMM-YYYY", has_does_not_apply: true, does_not_apply_label: "Do Not Know" },
  },
  {
    field_name: "mother_in_us",
    label: "Is your mother in the U.S.?",
    field_type: "radio",
    required: true,
    step_number: 9,
    step_name: "Family Information",
    display_order: 9,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "mother_us_status",
    label: "Mother's U.S. Status",
    field_type: "select",
    required: false,
    step_number: 9,
    step_name: "Family Information",
    display_order: 10,
    conditional_logic: { showIf: "mother_in_us === yes" },
    validation_rules: { repeatable: true, repeat_group: "mother_us" },
  },
  {
    field_name: "spouse_surname",
    label: "Spouse's Surnames",
    field_type: "text",
    required: false,
    step_number: 9,
    step_name: "Family Information",
    display_order: 11,
    placeholder: "e.g., FERNANDEZ GARCIA",
    conditional_logic: { showIf: "marital_status === married || marital_status === legally_separated || marital_status === common_law || marital_status === civil_union" },
    validation_rules: { repeatable: true, repeat_group: "spouse" },
  },
  {
    field_name: "spouse_given_names",
    label: "Spouse's Given Names",
    field_type: "text",
    required: false,
    step_number: 9,
    step_name: "Family Information",
    display_order: 12,
    placeholder: "e.g., JUAN MIGUEL",
    conditional_logic: { showIf: "marital_status === married || marital_status === legally_separated || marital_status === common_law || marital_status === civil_union" },
    validation_rules: { repeatable: true, repeat_group: "spouse" },
  },
  {
    field_name: "spouse_date_of_birth",
    label: "Spouse's Date of Birth",
    field_type: "date",
    required: false,
    step_number: 9,
    step_name: "Family Information",
    display_order: 13,
    validation_rules: { format: "DD-MMM-YYYY", repeatable: true, repeat_group: "spouse" },
    conditional_logic: { showIf: "marital_status === married || marital_status === legally_separated || marital_status === common_law || marital_status === civil_union" },
  },
  {
    field_name: "spouse_nationality",
    label: "Spouse's Nationality",
    field_type: "select",
    required: false,
    step_number: 9,
    step_name: "Family Information",
    display_order: 14,
    validation_rules: { source: "ISO3166-1", repeatable: true, repeat_group: "spouse" },
    conditional_logic: { showIf: "marital_status === married || marital_status === legally_separated || marital_status === common_law || marital_status === civil_union" },
  },
  {
    field_name: "spouse_city_of_birth",
    label: "Spouse's City of Birth",
    field_type: "text",
    required: false,
    step_number: 9,
    step_name: "Family Information",
    display_order: 15,
    conditional_logic: { showIf: "marital_status === married || marital_status === legally_separated || marital_status === common_law || marital_status === civil_union" },
    validation_rules: { repeatable: true, repeat_group: "spouse" },
  },
  {
    field_name: "spouse_country_of_birth",
    label: "Spouse's Country/Region of Birth",
    field_type: "select",
    required: false,
    step_number: 9,
    step_name: "Family Information",
    display_order: 16,
    validation_rules: { source: "ISO3166-1", repeatable: true, repeat_group: "spouse" },
    conditional_logic: { showIf: "marital_status === married || marital_status === legally_separated || marital_status === common_law || marital_status === civil_union" },
  },
  {
    field_name: "spouse_address_type",
    label: "Spouse's Address",
    field_type: "radio",
    required: false,
    step_number: 9,
    step_name: "Family Information",
    display_order: 17,
    options: [
      { value: "same_as_home", text: "Same as Home Address" },
      { value: "different", text: "Different Address" },
    ],
    conditional_logic: { showIf: "marital_status === married || marital_status === legally_separated || marital_status === common_law || marital_status === civil_union" },
    validation_rules: { repeatable: true, repeat_group: "spouse" },
  },
  {
    field_name: "has_immediate_us_relatives",
    label: "Do you have any immediate relatives, not including parents, in the United States?",
    field_type: "radio",
    required: true,
    step_number: 9,
    step_name: "Family Information",
    display_order: 18,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "us_relative_surname",
    label: "Relative's Surnames",
    field_type: "text",
    required: false,
    step_number: 9,
    step_name: "Family Information",
    display_order: 19,
    conditional_logic: { showIf: "has_immediate_us_relatives === yes" },
    validation_rules: { repeatable: true, repeat_group: "us_relatives" },
  },
  {
    field_name: "us_relative_given_names",
    label: "Relative's Given Names",
    field_type: "text",
    required: false,
    step_number: 9,
    step_name: "Family Information",
    display_order: 20,
    conditional_logic: { showIf: "has_immediate_us_relatives === yes" },
    validation_rules: { repeatable: true, repeat_group: "us_relatives" },
  },
  {
    field_name: "us_relative_relationship",
    label: "Relationship",
    field_type: "select",
    required: false,
    step_number: 9,
    step_name: "Family Information",
    display_order: 21,
    options: [
      { value: "spouse", text: "SPOUSE" },
      { value: "child", text: "CHILD" },
      { value: "sibling", text: "SIBLING" },
    ],
    conditional_logic: { showIf: "has_immediate_us_relatives === yes" },
    validation_rules: { repeatable: true, repeat_group: "us_relatives" },
  },
  {
    field_name: "us_relative_status",
    label: "Relative's U.S. Immigration Status",
    field_type: "select",
    required: false,
    step_number: 9,
    step_name: "Family Information",
    display_order: 22,
    options: [
      { value: "citizen", text: "U.S. CITIZEN" },
      { value: "lpr", text: "U.S. LEGAL PERMANENT RESIDENT (LPR)" },
      { value: "nonimmigrant", text: "NONIMMIGRANT" },
      { value: "other", text: "OTHER" },
      { value: "unknown", text: "UNKNOWN" },
    ],
    conditional_logic: { showIf: "has_immediate_us_relatives === yes" },
    validation_rules: { repeatable: true, repeat_group: "us_relatives" },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STEP 10: Work / Education / Training
  // ═══════════════════════════════════════════════════════════════════════════
  {
    field_name: "primary_occupation",
    label: "Primary Occupation",
    field_type: "select",
    required: true,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 1,
    options: [
      { value: "agriculture", text: "AGRICULTURE" },
      { value: "artist", text: "ARTIST/PERFORMER" },
      { value: "business", text: "BUSINESS" },
      { value: "communications", text: "COMMUNICATIONS" },
      { value: "computer_science", text: "COMPUTER SCIENCE" },
      { value: "culinary", text: "CULINARY/FOOD SERVICES" },
      { value: "education", text: "EDUCATION" },
      { value: "engineering", text: "ENGINEERING" },
      { value: "government", text: "GOVERNMENT" },
      { value: "homemaker", text: "HOMEMAKER" },
      { value: "legal", text: "LEGAL" },
      { value: "medical", text: "MEDICAL/HEALTH" },
      { value: "military", text: "MILITARY" },
      { value: "natural_sciences", text: "NATURAL SCIENCES" },
      { value: "not_employed", text: "NOT EMPLOYED" },
      { value: "religious", text: "RELIGIOUS" },
      { value: "research", text: "RESEARCH" },
      { value: "retired", text: "RETIRED" },
      { value: "social_sciences", text: "SOCIAL SCIENCE" },
      { value: "student", text: "STUDENT" },
      { value: "other", text: "OTHER" },
    ],
  },
  {
    field_name: "employer_name",
    label: "Present Employer or School Name",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 2,
    validation_rules: { has_does_not_apply: true },
  },
  {
    field_name: "employer_address_line1",
    label: "Street Address (Line 1)",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 3,
  },
  {
    field_name: "employer_address_line2",
    label: "Street Address (Line 2)",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 4,
    validation_rules: { optional_label: true },
  },
  {
    field_name: "employer_city",
    label: "City",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 5,
  },
  {
    field_name: "employer_state_province",
    label: "State/Province",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 6,
    validation_rules: { has_does_not_apply: true },
  },
  {
    field_name: "employer_postal_code",
    label: "Postal Zone/ZIP Code",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 7,
    validation_rules: { has_does_not_apply: true },
  },
  {
    field_name: "employer_country",
    label: "Country/Region",
    field_type: "select",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 8,
    validation_rules: { source: "ISO3166-1" },
  },
  {
    field_name: "employer_phone",
    label: "Phone Number",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 9,
  },
  {
    field_name: "job_title",
    label: "Job Title",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 10,
    validation_rules: { has_does_not_apply: true },
  },
  {
    field_name: "employment_start_date",
    label: "Start Date",
    field_type: "date",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 11,
    validation_rules: { format: "DD-MMM-YYYY" },
  },
  {
    field_name: "monthly_salary",
    label: "Monthly Salary in Local Currency",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 12,
    validation_rules: { has_does_not_apply: true },
  },
  {
    field_name: "job_duties",
    label: "Briefly Describe Your Duties",
    field_type: "textarea",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 13,
  },
  {
    field_name: "has_previous_employer",
    label: "Were you previously employed?",
    field_type: "radio",
    required: true,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 14,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "prev_employer_name",
    label: "Employer Name",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 15,
    conditional_logic: { showIf: "has_previous_employer === yes" },
    validation_rules: { repeatable: true, repeat_group: "previous_employers" },
  },
  {
    field_name: "prev_employer_address_street1",
    label: "Street Address (Line 1)",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 16,
    conditional_logic: { showIf: "has_previous_employer === yes" },
    validation_rules: { repeatable: true, repeat_group: "previous_employers" },
  },
  {
    field_name: "prev_employer_city",
    label: "City",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 17,
    conditional_logic: { showIf: "has_previous_employer === yes" },
    validation_rules: { repeatable: true, repeat_group: "previous_employers" },
  },
  {
    field_name: "prev_employer_state",
    label: "State/Province",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 18,
    conditional_logic: { showIf: "has_previous_employer === yes" },
    validation_rules: { has_does_not_apply: true, repeatable: true, repeat_group: "previous_employers" },
  },
  {
    field_name: "prev_employer_postal",
    label: "Postal Zone/ZIP Code",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 19,
    conditional_logic: { showIf: "has_previous_employer === yes" },
    validation_rules: { has_does_not_apply: true, repeatable: true, repeat_group: "previous_employers" },
  },
  {
    field_name: "prev_employer_country",
    label: "Country/Region",
    field_type: "select",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 20,
    conditional_logic: { showIf: "has_previous_employer === yes" },
    validation_rules: { source: "ISO3166-1", repeatable: true, repeat_group: "previous_employers" },
  },
  {
    field_name: "prev_employer_phone",
    label: "Telephone Number",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 21,
    conditional_logic: { showIf: "has_previous_employer === yes" },
    validation_rules: { repeatable: true, repeat_group: "previous_employers" },
  },
  {
    field_name: "prev_job_title",
    label: "Job Title",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 22,
    conditional_logic: { showIf: "has_previous_employer === yes" },
    validation_rules: { repeatable: true, repeat_group: "previous_employers" },
  },
  {
    field_name: "prev_supervisor_surname",
    label: "Supervisor's Surnames",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 23,
    conditional_logic: { showIf: "has_previous_employer === yes" },
    validation_rules: { repeatable: true, repeat_group: "previous_employers" },
  },
  {
    field_name: "prev_supervisor_given_names",
    label: "Supervisor's Given Names",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 24,
    conditional_logic: { showIf: "has_previous_employer === yes" },
    validation_rules: { repeatable: true, repeat_group: "previous_employers" },
  },
  {
    field_name: "prev_employment_start_date",
    label: "Employment Date From",
    field_type: "date",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 25,
    conditional_logic: { showIf: "has_previous_employer === yes" },
    validation_rules: { format: "DD-MMM-YYYY", repeatable: true, repeat_group: "previous_employers" },
  },
  {
    field_name: "prev_employment_end_date",
    label: "Employment Date To",
    field_type: "date",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 26,
    conditional_logic: { showIf: "has_previous_employer === yes" },
    validation_rules: { format: "DD-MMM-YYYY", repeatable: true, repeat_group: "previous_employers" },
  },
  {
    field_name: "prev_job_duties",
    label: "Briefly Describe Your Duties",
    field_type: "textarea",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 27,
    conditional_logic: { showIf: "has_previous_employer === yes" },
    validation_rules: { repeatable: true, repeat_group: "previous_employers" },
  },
  {
    field_name: "has_attended_education",
    label: "Have you attended any educational institutions at a secondary level or above?",
    field_type: "radio",
    required: true,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 28,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  },
  {
    field_name: "education_institution_name",
    label: "Name of Institution",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 29,
    conditional_logic: { showIf: "has_attended_education === yes" },
    validation_rules: { repeatable: true, repeat_group: "education" },
  },
  {
    field_name: "education_city",
    label: "City",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 30,
    conditional_logic: { showIf: "has_attended_education === yes" },
    validation_rules: { repeatable: true, repeat_group: "education" },
  },
  {
    field_name: "education_country",
    label: "Country/Region",
    field_type: "select",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 31,
    conditional_logic: { showIf: "has_attended_education === yes" },
    validation_rules: { source: "ISO3166-1", repeatable: true, repeat_group: "education" },
  },
  {
    field_name: "education_course_of_study",
    label: "Course of Study",
    field_type: "text",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 32,
    conditional_logic: { showIf: "has_attended_education === yes" },
    validation_rules: { repeatable: true, repeat_group: "education" },
  },
  {
    field_name: "education_start_date",
    label: "Date of Attendance From",
    field_type: "date",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 33,
    conditional_logic: { showIf: "has_attended_education === yes" },
    validation_rules: { format: "DD-MMM-YYYY", repeatable: true, repeat_group: "education" },
  },
  {
    field_name: "education_end_date",
    label: "Date of Attendance To",
    field_type: "date",
    required: false,
    step_number: 10,
    step_name: "Work/Education/Training",
    display_order: 34,
    conditional_logic: { showIf: "has_attended_education === yes" },
    validation_rules: { format: "DD-MMM-YYYY", repeatable: true, repeat_group: "education" },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // STEP 11: Security and Background
  // ═══════════════════════════════════════════════════════════════════════════
  ...([
    ["has_communicable_disease", "Do you have a communicable disease of public health significance?"],
    ["has_physical_mental_disorder", "Do you have a mental or physical disorder that poses or is likely to pose a threat to the safety or welfare of yourself or others?"],
    ["is_drug_abuser", "Are you or have you ever been a drug abuser or addict?"],
    ["has_arrest_conviction", "Have you ever been arrested or convicted for any offense or crime, even though subject of a pardon, amnesty, or other similar legal action?"],
    ["has_violated_controlled_substance", "Have you ever violated, or engaged in a conspiracy to violate, any law relating to controlled substances?"],
    ["intend_espionage", "Do you intend to engage in the United States in espionage, sabotage, export control violations, or any other illegal activity?"],
    ["intend_terrorist_activity", "Do you intend to engage in the United States in terrorist activities, or have you ever engaged in terrorist activities?"],
    ["has_provided_terrorist_support", "Have you ever or do you intend to provide financial assistance or other support to terrorists or terrorist organizations?"],
    ["is_terrorist_member", "Are you a member or representative of a terrorist organization?"],
    ["has_genocide", "Have you ever ordered, incited, committed, assisted, or otherwise participated in genocide?"],
    ["has_torture", "Have you ever committed, ordered, incited, assisted, or otherwise participated in torture?"],
    ["has_extrajudicial_killings", "Have you committed, ordered, incited, assisted, or otherwise participated in extrajudicial killings, political killings, or other acts of violence?"],
    ["has_child_soldier", "Have you ever engaged in the recruitment or the use of child soldiers?"],
    ["has_religious_freedom_violation", "Have you, while serving as a government official, been responsible for or directly carried out, at any time, particularly severe violations of religious freedom?"],
    ["has_trafficking", "Have you ever been directly involved in the establishment or enforcement of population controls forcing a woman to undergo an abortion against her free choice or a man or a woman to undergo sterilization against his or her free will?"],
    ["has_transplant_trafficking", "Have you ever been involved in transplant tourism or trafficking?"],
    ["has_removal_order", "Have you ever been removed or deported from any country?"],
    ["has_custody_violation", "Have you ever sought to obtain or assist others to obtain a visa, entry into the United States, or any other United States immigration benefit by fraud or willful misrepresentation?"],
    ["has_failed_to_attend_removal", "Have you failed to attend a hearing on removability or inadmissibility within the last 5 years?"],
    ["has_unlawful_presence", "Have you ever been unlawfully present, overstayed the amount of time granted by an immigration official or violated the terms of a U.S. visa?"],
    ["has_withheld_child_custody", "Have you ever withheld custody of a U.S. citizen child outside the United States from a person granted legal custody by a U.S. court, voted in the United States in violation of any law or regulation, or renounced U.S. citizenship for the purposes of avoiding taxation?"],
  ] as [string, string][]).map(([fn, lbl], i) => ({
    field_name: fn,
    label: lbl,
    field_type: "radio" as const,
    required: true,
    step_number: 11,
    step_name: "Security and Background",
    display_order: i + 1,
    options: [{ value: "yes", text: "Yes" }, { value: "no", text: "No" }],
  })),
  {
    field_name: "security_explanation",
    label: "If you answered 'Yes' to any of the above, please explain",
    field_type: "textarea",
    required: false,
    step_number: 11,
    step_name: "Security and Background",
    display_order: 30,
    conditional_logic: { showIf: "any_security_answer === yes" },
  },
];

async function seed() {
  console.log(`\nSeeding DS-160 visa_form_fields (${FIELDS.length} fields)...\n`);

  // First, delete existing DS160 fields to avoid orphans from renamed fields
  const { error: delError } = await supabase
    .from("visa_form_fields")
    .delete()
    .eq("visa_type", "DS160");
  if (delError) {
    console.error("Error deleting existing DS160 fields:", delError.message);
  } else {
    console.log("Cleared existing DS160 fields");
  }

  const rows = FIELDS.map((f) => ({
    visa_type: "DS160",
    field_name: f.field_name,
    label: f.label,
    field_type: f.field_type,
    required: f.required,
    step_number: f.step_number,
    step_name: f.step_name,
    display_order: f.display_order,
    placeholder: f.placeholder ?? null,
    validation_rules: f.validation_rules ?? null,
    options: f.options ?? null,
    conditional_logic: f.conditional_logic ?? null,
  }));

  const BATCH = 20;
  let total = 0;
  for (let i = 0; i < rows.length; i += BATCH) {
    const batch = rows.slice(i, i + BATCH);
    const { data, error } = await supabase
      .from("visa_form_fields")
      .insert(batch)
      .select("id");
    if (error) {
      console.error(`Batch ${Math.floor(i / BATCH) + 1} error:`, error.message);
    } else {
      total += data?.length ?? 0;
      process.stdout.write(`Batch ${Math.floor(i / BATCH) + 1}: ${data?.length ?? 0} inserted\n`);
    }
  }
  console.log(`\nDone: ${total} rows seeded (${FIELDS.length} defined)`);
}

seed().catch((err) => { console.error(err); process.exit(1); });
