import {
  TDAC_ACCOMMODATION_OPTIONS,
  TDAC_AIR_TRANSPORT_OPTIONS,
  TDAC_COUNTRY_OPTIONS,
  TDAC_DISTRICT_OPTIONS_BY_PROVINCE,
  TDAC_GENDER_OPTIONS,
  TDAC_LAND_TRANSPORT_OPTIONS,
  TDAC_PROVINCE_OPTIONS,
  TDAC_PURPOSE_OPTIONS,
  TDAC_RESIDENCE_REGION_OPTIONS_BY_COUNTRY,
  TDAC_SEA_TRANSPORT_OPTIONS,
  TDAC_SUBDISTRICT_OPTIONS_BY_DISTRICT,
  TDAC_TRAVEL_MODE_OPTIONS,
  type TdacOption,
} from "./official-options";

export const TH_TDAC_VISA_TYPE = "TH_TDAC_ARRIVAL_CARD";

export interface ThTdacFieldDef {
  field_name: string;
  label: string;
  field_type: string;
  required: boolean;
  step_number: number;
  step_name: string;
  display_order: number;
  placeholder?: string;
  validation_rules?: Record<string, unknown>;
  options?: TdacOption[];
  conditional_logic?: Record<string, unknown>;
}

const rules = (labelZh: string, extra: Record<string, unknown> = {}) => ({ label_zh: labelZh, official: true, ...extra });
const showIf = (expression: string) => ({ showIf: expression });
const STEP_TRAVELLER = "旅客信息";
const STEP_TRIP = "抵达和离境信息";
const STEP_ACCOMMODATION = "住宿信息";
const STEP_HEALTH = "健康申报";
const NON_TRANSIT_ONLY = "is_transit_traveler !== yes";

const transportDependentOptions = {
  air: TDAC_AIR_TRANSPORT_OPTIONS,
  land: TDAC_LAND_TRANSPORT_OPTIONS,
  sea: TDAC_SEA_TRANSPORT_OPTIONS,
};

export const TH_TDAC_FORM_FIELDS: ThTdacFieldDef[] = [
  {
    field_name: "family_name",
    label: "Family Name",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: STEP_TRAVELLER,
    display_order: 1,
    validation_rules: rules("姓氏", { pattern: "^[A-Za-z\\s'-]+$" }),
  },
  {
    field_name: "first_name",
    label: "First Name",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: STEP_TRAVELLER,
    display_order: 2,
    validation_rules: rules("名字", { pattern: "^[A-Za-z\\s'-]+$" }),
  },
  {
    field_name: "middle_name",
    label: "Middle Name",
    field_type: "text",
    required: false,
    step_number: 1,
    step_name: STEP_TRAVELLER,
    display_order: 3,
    validation_rules: rules("中间名", { pattern: "^[A-Za-z\\s'-]*$" }),
  },
  {
    field_name: "passport_number",
    label: "Passport No.",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: STEP_TRAVELLER,
    display_order: 4,
    validation_rules: rules("护照号码", { pattern: "^[A-Za-z0-9]+$" }),
  },
  {
    field_name: "nationality",
    label: "Nationality/Citizenship",
    field_type: "select",
    required: true,
    step_number: 1,
    step_name: STEP_TRAVELLER,
    display_order: 5,
    options: TDAC_COUNTRY_OPTIONS,
    validation_rules: rules("国籍 / 公民身份"),
  },
  {
    field_name: "date_of_birth",
    label: "Date of Birth",
    field_type: "date",
    required: true,
    step_number: 1,
    step_name: STEP_TRAVELLER,
    display_order: 6,
    validation_rules: rules("出生日期", { format: "YYYY-MM-DD" }),
  },
  {
    field_name: "gender",
    label: "Gender",
    field_type: "radio",
    required: true,
    step_number: 1,
    step_name: STEP_TRAVELLER,
    display_order: 7,
    options: TDAC_GENDER_OPTIONS,
    validation_rules: rules("性别"),
  },
  {
    field_name: "occupation",
    label: "Occupation",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: STEP_TRAVELLER,
    display_order: 8,
    validation_rules: rules("职业"),
  },
  {
    field_name: "visa_number",
    label: "Visa No.",
    field_type: "text",
    required: false,
    step_number: 1,
    step_name: STEP_TRAVELLER,
    display_order: 9,
    validation_rules: rules("签证号码（如有）"),
  },
  {
    field_name: "country_territory_of_residence",
    label: "Country/Territory of Residence",
    field_type: "select",
    required: true,
    step_number: 1,
    step_name: STEP_TRAVELLER,
    display_order: 10,
    options: TDAC_COUNTRY_OPTIONS,
    validation_rules: rules("居住国家 / 地区"),
  },
  {
    field_name: "city_state_of_residence",
    label: "City/State of Residence",
    field_type: "select",
    required: true,
    step_number: 1,
    step_name: STEP_TRAVELLER,
    display_order: 11,
    validation_rules: rules("居住城市 / 州", {
      dependent_on: "country_territory_of_residence",
      dependent_options: TDAC_RESIDENCE_REGION_OPTIONS_BY_COUNTRY,
    }),
  },
  {
    field_name: "phone_country_code",
    label: "Phone Country Code",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: STEP_TRAVELLER,
    display_order: 12,
    placeholder: "86",
    validation_rules: rules("电话区号", { pattern: "^[0-9]{1,4}$" }),
  },
  {
    field_name: "phone_number",
    label: "Phone Number",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: STEP_TRAVELLER,
    display_order: 13,
    validation_rules: rules("电话号码", { pattern: "^[0-9\\s-]{5,20}$" }),
  },
  {
    field_name: "email_address",
    label: "Email Address",
    field_type: "text",
    required: true,
    step_number: 1,
    step_name: STEP_TRAVELLER,
    display_order: 14,
    validation_rules: rules("电子邮箱", { format: "email" }),
  },

  {
    field_name: "arrival_date",
    label: "Date of Arrival",
    field_type: "date",
    required: true,
    step_number: 2,
    step_name: STEP_TRIP,
    display_order: 1,
    validation_rules: rules("抵达日期", { format: "YYYY-MM-DD", not_before_today: true }),
  },
  {
    field_name: "country_boarded",
    label: "Country/Territory where you Boarded",
    field_type: "select",
    required: true,
    step_number: 2,
    step_name: STEP_TRIP,
    display_order: 2,
    options: TDAC_COUNTRY_OPTIONS,
    validation_rules: rules("出发登程国家 / 地区"),
  },
  {
    field_name: "purpose_of_travel",
    label: "Purpose of Travel",
    field_type: "select",
    required: true,
    step_number: 2,
    step_name: STEP_TRIP,
    display_order: 3,
    options: TDAC_PURPOSE_OPTIONS,
    validation_rules: rules("旅行目的"),
  },
  {
    field_name: "purpose_of_travel_other",
    label: "Purpose of Travel - Other",
    field_type: "text",
    required: true,
    step_number: 2,
    step_name: STEP_TRIP,
    display_order: 4,
    conditional_logic: showIf("purpose_of_travel === others"),
    validation_rules: rules("其他旅行目的说明"),
  },
  {
    field_name: "arrival_mode_of_travel",
    label: "Arrival Mode of Travel",
    field_type: "radio",
    required: true,
    step_number: 2,
    step_name: STEP_TRIP,
    display_order: 5,
    options: TDAC_TRAVEL_MODE_OPTIONS,
    validation_rules: rules("抵达交通方式"),
  },
  {
    field_name: "arrival_mode_of_transport",
    label: "Arrival Mode of Transport",
    field_type: "select",
    required: true,
    step_number: 2,
    step_name: STEP_TRIP,
    display_order: 6,
    validation_rules: rules("抵达交通工具类型", {
      dependent_on: "arrival_mode_of_travel",
      dependent_options: transportDependentOptions,
    }),
  },
  {
    field_name: "arrival_transport_other",
    label: "Arrival Transport - Other",
    field_type: "text",
    required: true,
    step_number: 2,
    step_name: STEP_TRIP,
    display_order: 7,
    conditional_logic: showIf("arrival_mode_of_transport === others"),
    validation_rules: rules("其他抵达交通工具说明"),
  },
  {
    field_name: "arrival_transport_number",
    label: "Flight No./Vehicle No.",
    field_type: "text",
    required: true,
    step_number: 2,
    step_name: STEP_TRIP,
    display_order: 8,
    validation_rules: rules("抵达航班号 / 车船号"),
  },
  {
    field_name: "departure_date",
    label: "Date of Departure",
    field_type: "date",
    required: true,
    step_number: 2,
    step_name: STEP_TRIP,
    display_order: 9,
    validation_rules: rules("离开日期", { format: "YYYY-MM-DD", after_or_equal_field: "arrival_date" }),
  },
  {
    field_name: "departure_mode_of_travel",
    label: "Departure Mode of Travel",
    field_type: "radio",
    required: true,
    step_number: 2,
    step_name: STEP_TRIP,
    display_order: 10,
    options: TDAC_TRAVEL_MODE_OPTIONS,
    validation_rules: rules("离境交通方式"),
  },
  {
    field_name: "departure_mode_of_transport",
    label: "Departure Mode of Transport",
    field_type: "select",
    required: true,
    step_number: 2,
    step_name: STEP_TRIP,
    display_order: 11,
    validation_rules: rules("离境交通工具类型", {
      dependent_on: "departure_mode_of_travel",
      dependent_options: transportDependentOptions,
    }),
  },
  {
    field_name: "departure_transport_other",
    label: "Departure Transport - Other",
    field_type: "text",
    required: true,
    step_number: 2,
    step_name: STEP_TRIP,
    display_order: 12,
    conditional_logic: showIf("departure_mode_of_transport === others"),
    validation_rules: rules("其他离境交通工具说明"),
  },
  {
    field_name: "departure_transport_number",
    label: "Flight No./Vehicle No.",
    field_type: "text",
    required: true,
    step_number: 2,
    step_name: STEP_TRIP,
    display_order: 13,
    validation_rules: rules("离境航班号 / 车船号"),
  },

  {
    field_name: "is_transit_traveler",
    label: "I am a transit passenger, I don't stay in Thailand.",
    field_type: "checkbox",
    required: false,
    step_number: 3,
    step_name: STEP_ACCOMMODATION,
    display_order: 1,
    validation_rules: rules("我是过境旅客，不在泰国停留", {
      auto_when_arrival_departure_same_day: true,
      locked_unless_arrival_departure_same_day: true,
    }),
  },
  {
    field_name: "accommodation_type",
    label: "Type of Accommodation in Thailand",
    field_type: "select",
    required: true,
    step_number: 3,
    step_name: STEP_ACCOMMODATION,
    display_order: 2,
    conditional_logic: showIf(NON_TRANSIT_ONLY),
    options: TDAC_ACCOMMODATION_OPTIONS,
    validation_rules: rules("在泰国住宿类型"),
  },
  {
    field_name: "accommodation_type_other",
    label: "Accommodation Type - Other",
    field_type: "text",
    required: true,
    step_number: 3,
    step_name: STEP_ACCOMMODATION,
    display_order: 3,
    conditional_logic: showIf(`${NON_TRANSIT_ONLY} && accommodation_type === others`),
    validation_rules: rules("其他住宿类型说明"),
  },
  {
    field_name: "province",
    label: "Province",
    field_type: "select",
    required: true,
    step_number: 3,
    step_name: STEP_ACCOMMODATION,
    display_order: 4,
    conditional_logic: showIf(NON_TRANSIT_ONLY),
    options: TDAC_PROVINCE_OPTIONS,
    validation_rules: rules("府 / 省"),
  },
  {
    field_name: "district",
    label: "District, Area",
    field_type: "select",
    required: false,
    step_number: 3,
    step_name: STEP_ACCOMMODATION,
    display_order: 5,
    conditional_logic: showIf(NON_TRANSIT_ONLY),
    validation_rules: rules("县 / 区", {
      dependent_on: "province",
      dependent_options: TDAC_DISTRICT_OPTIONS_BY_PROVINCE,
    }),
  },
  {
    field_name: "sub_district",
    label: "Sub-District, Sub-Area",
    field_type: "select",
    required: false,
    step_number: 3,
    step_name: STEP_ACCOMMODATION,
    display_order: 6,
    conditional_logic: showIf(NON_TRANSIT_ONLY),
    validation_rules: rules("分区 / 镇", {
      dependent_on: "district",
      dependent_options: TDAC_SUBDISTRICT_OPTIONS_BY_DISTRICT,
    }),
  },
  {
    field_name: "postcode",
    label: "Post Code",
    field_type: "text",
    required: false,
    step_number: 3,
    step_name: STEP_ACCOMMODATION,
    display_order: 7,
    conditional_logic: showIf(NON_TRANSIT_ONLY),
    validation_rules: rules("邮政编码", { pattern: "^[0-9]{5}$" }),
  },
  {
    field_name: "address_in_thailand",
    label: "Address",
    field_type: "textarea",
    required: true,
    step_number: 3,
    step_name: STEP_ACCOMMODATION,
    display_order: 8,
    conditional_logic: showIf(NON_TRANSIT_ONLY),
    validation_rules: rules("泰国地址", { maxLength: 215 }),
  },

  {
    field_name: "countries_visited_last_14_days",
    label: "Countries/Territories where you stayed within two weeks before arrival",
    field_type: "multi_select",
    required: true,
    step_number: 4,
    step_name: STEP_HEALTH,
    display_order: 1,
    options: TDAC_COUNTRY_OPTIONS,
    validation_rules: rules("抵达前两周内停留过的国家 / 地区"),
  },
];
