/**
 * Checked-in DS-160 seed contract for runtime field/gate validation.
 *
 * This file intentionally contains data only; it does not import or execute
 * the database seed script. Regenerate/review it when the seed changes.
 */

export interface Ds160FieldContract {
  page: string;
  step: number;
  type: string;
  required: boolean;
  label: string;
  showIf?: string;
  repeatGroup?: string;
  allowsDoesNotApply?: boolean;
  optional?: boolean;
}

export const DS160_FIELD_CONTRACTS: Record<string, Ds160FieldContract> = {
  "consular_post": {"page":"Personal Information 1","step":1,"type":"select","required":true,"label":"Location where you will be submitting your application"},
  "surname": {"page":"Personal Information 1","step":1,"type":"text","required":true,"label":"Surnames"},
  "given_names": {"page":"Personal Information 1","step":1,"type":"text","required":true,"label":"Given Names"},
  "full_name_native_alphabet": {"page":"Personal Information 1","step":1,"type":"text","required":false,"label":"Full Name in Native Alphabet"},
  "other_names_used": {"page":"Personal Information 1","step":1,"type":"radio","required":true,"label":"Have you ever used other names (i.e., maiden, religious, professional, alias, etc.)?"},
  "other_surname": {"page":"Personal Information 1","step":1,"type":"text","required":true,"label":"Other Surnames Used (maiden, religious, professional, aliases, etc.)","showIf":"other_names_used === yes"},
  "other_given_names": {"page":"Personal Information 1","step":1,"type":"text","required":true,"label":"Other Given Names Used","showIf":"other_names_used === yes"},
  "has_telecode": {"page":"Personal Information 1","step":1,"type":"radio","required":true,"label":"Do you have a telecode that represents your name?"},
  "telecode_surname": {"page":"Personal Information 1","step":1,"type":"text","required":true,"label":"Telecode Surname","showIf":"has_telecode === yes"},
  "telecode_given_names": {"page":"Personal Information 1","step":1,"type":"text","required":true,"label":"Telecode Given Names","showIf":"has_telecode === yes"},
  "sex": {"page":"Personal Information 1","step":1,"type":"radio","required":true,"label":"Sex"},
  "marital_status": {"page":"Personal Information 1","step":1,"type":"select","required":true,"label":"Marital Status"},
  "marital_status_other_explain": {"page":"Personal Information 1","step":1,"type":"text","required":true,"label":"Other — Please Explain","showIf":"marital_status === other"},
  "date_of_birth": {"page":"Personal Information 1","step":1,"type":"date","required":true,"label":"Date of Birth"},
  "city_of_birth": {"page":"Personal Information 1","step":1,"type":"text","required":true,"label":"City of Birth"},
  "state_of_birth": {"page":"Personal Information 1","step":1,"type":"text","required":false,"label":"State/Province of Birth"},
  "country_of_birth": {"page":"Personal Information 1","step":1,"type":"select","required":true,"label":"Country/Region of Birth"},
  "nationality_country": {"page":"Personal Information 2","step":2,"type":"select","required":true,"label":"Country/Region of Origin (Nationality)"},
  "other_nationality": {"page":"Personal Information 2","step":2,"type":"radio","required":true,"label":"Do you hold or have you held any nationality other than the one indicated above on nationality?"},
  "other_nationality_country": {"page":"Personal Information 2","step":2,"type":"select","required":true,"label":"Other Country/Region of Nationality","showIf":"other_nationality === yes","repeatGroup":"other_nationality"},
  "other_nationality_has_passport": {"page":"Personal Information 2","step":2,"type":"radio","required":false,"label":"Do you hold a passport for that other nationality?","showIf":"other_nationality === yes","repeatGroup":"other_nationality"},
  "other_nationality_passport_number": {"page":"Personal Information 2","step":2,"type":"text","required":false,"label":"Passport Number","showIf":"other_nationality_has_passport === yes","repeatGroup":"other_nationality"},
  "permanent_resident_other_country": {"page":"Personal Information 2","step":2,"type":"radio","required":true,"label":"Are you a permanent resident of a country/region other than your country/region of origin (nationality) indicated above?"},
  "other_permanent_resident_country": {"page":"Personal Information 2","step":2,"type":"select","required":true,"label":"Other Permanent Resident Country/Region","showIf":"permanent_resident_other_country === yes","repeatGroup":"permanent_resident"},
  "national_id_number": {"page":"Personal Information 2","step":2,"type":"text","required":false,"label":"National Identification Number"},
  "us_social_security_number": {"page":"Personal Information 2","step":2,"type":"text","required":true,"label":"U.S. Social Security Number","allowsDoesNotApply":true},
  "us_taxpayer_id": {"page":"Personal Information 2","step":2,"type":"text","required":false,"label":"U.S. Taxpayer ID Number"},
  "purpose_of_trip": {"page":"Travel Information","step":3,"type":"select","required":true,"label":"Purpose of Trip to the U.S.","repeatGroup":"trip_purpose"},
  "purpose_of_trip_specify": {"page":"Travel Information","step":3,"type":"select","required":true,"label":"Specify","repeatGroup":"trip_purpose"},
  "has_specific_plans": {"page":"Travel Information","step":3,"type":"radio","required":true,"label":"Have you made specific travel plans?"},
  "arrival_date": {"page":"Travel Information","step":3,"type":"date","required":false,"label":"Date of Arrival in U.S.","showIf":"has_specific_plans === yes","repeatGroup":"specific_travel_plans"},
  "arrival_flight": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"Arrival Flight (if known)","showIf":"has_specific_plans === yes","repeatGroup":"specific_travel_plans"},
  "arrival_city": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"Arrival City","showIf":"has_specific_plans === yes","repeatGroup":"specific_travel_plans"},
  "departure_date": {"page":"Travel Information","step":3,"type":"date","required":false,"label":"Date of Departure from U.S.","showIf":"has_specific_plans === yes","repeatGroup":"specific_travel_plans"},
  "departure_flight": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"Departure Flight (if known)","showIf":"has_specific_plans === yes","repeatGroup":"specific_travel_plans"},
  "departure_city": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"Departure City","showIf":"has_specific_plans === yes","repeatGroup":"specific_travel_plans"},
  "planned_location": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"Location","showIf":"has_specific_plans === yes","repeatGroup":"planned_locations"},
  "intended_arrival_date": {"page":"Travel Information","step":3,"type":"date","required":false,"label":"Intended Date of Arrival in U.S.","showIf":"has_specific_plans === no"},
  "intended_length_of_stay_value": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"Intended Length of Stay in U.S. (Value)","showIf":"has_specific_plans === no"},
  "intended_length_of_stay_unit": {"page":"Travel Information","step":3,"type":"select","required":false,"label":"Intended Length of Stay in U.S. (Unit)","showIf":"has_specific_plans === no"},
  "us_address_street1": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"Street Address (Line 1)","showIf":"has_specific_plans === yes || intended_length_of_stay_unit === YEAR(S) || intended_length_of_stay_unit === MONTH(S) || intended_length_of_stay_unit === WEEK(S) || intended_length_of_stay_unit === DAY(S)"},
  "us_address_street2": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"Street Address (Line 2)","showIf":"has_specific_plans === yes || intended_length_of_stay_unit === YEAR(S) || intended_length_of_stay_unit === MONTH(S) || intended_length_of_stay_unit === WEEK(S) || intended_length_of_stay_unit === DAY(S)"},
  "us_address_city": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"City","showIf":"has_specific_plans === yes || intended_length_of_stay_unit === YEAR(S) || intended_length_of_stay_unit === MONTH(S) || intended_length_of_stay_unit === WEEK(S) || intended_length_of_stay_unit === DAY(S)"},
  "us_address_state": {"page":"Travel Information","step":3,"type":"select","required":false,"label":"State","showIf":"has_specific_plans === yes || intended_length_of_stay_unit === YEAR(S) || intended_length_of_stay_unit === MONTH(S) || intended_length_of_stay_unit === WEEK(S) || intended_length_of_stay_unit === DAY(S)"},
  "us_address_zip": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"ZIP Code","showIf":"has_specific_plans === yes || intended_length_of_stay_unit === YEAR(S) || intended_length_of_stay_unit === MONTH(S) || intended_length_of_stay_unit === WEEK(S) || intended_length_of_stay_unit === DAY(S)"},
  "trip_payer_type": {"page":"Travel Information","step":3,"type":"select","required":true,"label":"Person/Entity Paying for Your Trip"},
  "payer_surname": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"Surnames of Person Paying for Trip","showIf":"trip_payer_type === other_person"},
  "payer_given_names": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"Given Names of Person Paying for Trip","showIf":"trip_payer_type === other_person"},
  "payer_phone": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"Telephone Number","showIf":"trip_payer_type === other_person"},
  "payer_email": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"Payer Email (if applicable)","showIf":"trip_payer_type === other_person"},
  "payer_relationship": {"page":"Travel Information","step":3,"type":"select","required":false,"label":"Relationship to You","showIf":"trip_payer_type === other_person"},
  "payer_address_same_as_home": {"page":"Travel Information","step":3,"type":"radio","required":false,"label":"Is the address of the party paying for your trip the same as your Home or Mailing Address?","showIf":"trip_payer_type === other_person"},
  "payer_address_street1": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"Street Address (Line 1)","showIf":"payer_address_same_as_home === no"},
  "payer_address_street2": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"Street Address (Line 2)","showIf":"payer_address_same_as_home === no"},
  "payer_address_city": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"City","showIf":"payer_address_same_as_home === no"},
  "payer_address_state": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"State/Province","showIf":"payer_address_same_as_home === no"},
  "payer_address_postal": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"Postal Zone/ZIP Code","showIf":"payer_address_same_as_home === no"},
  "payer_address_country": {"page":"Travel Information","step":3,"type":"select","required":false,"label":"Country/Region","showIf":"payer_address_same_as_home === no"},
  "payer_org_name": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"Name of Company/Organization Paying for Trip","showIf":"trip_payer_type === other_company"},
  "payer_org_phone": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"Telephone Number","showIf":"trip_payer_type === other_company"},
  "payer_org_relationship": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"Relationship to You","showIf":"trip_payer_type === other_company"},
  "payer_org_address_street1": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"Street Address (Line 1)","showIf":"trip_payer_type === other_company"},
  "payer_org_address_street2": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"Street Address (Line 2)","showIf":"trip_payer_type === other_company"},
  "payer_org_address_city": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"City","showIf":"trip_payer_type === other_company"},
  "payer_org_address_state": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"State/Province","showIf":"trip_payer_type === other_company"},
  "payer_org_address_postal": {"page":"Travel Information","step":3,"type":"text","required":false,"label":"Postal Zone/ZIP Code","showIf":"trip_payer_type === other_company"},
  "payer_org_address_country": {"page":"Travel Information","step":3,"type":"select","required":false,"label":"Country/Region","showIf":"trip_payer_type === other_company"},
  "has_companions": {"page":"Travel Companions","step":4,"type":"radio","required":true,"label":"Are there other persons traveling with you?"},
  "companion_group_travel": {"page":"Travel Companions","step":4,"type":"radio","required":true,"label":"Are you traveling as part of a group or organization?","showIf":"has_companions === yes"},
  "companion_group_name": {"page":"Travel Companions","step":4,"type":"text","required":true,"label":"Group Name","showIf":"companion_group_travel === yes"},
  "companion_surname": {"page":"Travel Companions","step":4,"type":"text","required":true,"label":"Surnames","showIf":"companion_group_travel === no","repeatGroup":"companions"},
  "companion_given_names": {"page":"Travel Companions","step":4,"type":"text","required":true,"label":"Given Names","showIf":"companion_group_travel === no","repeatGroup":"companions"},
  "companion_relationship": {"page":"Travel Companions","step":4,"type":"select","required":true,"label":"Relationship to You","showIf":"companion_group_travel === no","repeatGroup":"companions"},
  "has_been_in_us": {"page":"Previous U.S. Travel","step":5,"type":"radio","required":true,"label":"Have you ever been in the U.S.?"},
  "previous_visit_date_arrived": {"page":"Previous U.S. Travel","step":5,"type":"date","required":false,"label":"Date Arrived","showIf":"has_been_in_us === yes","repeatGroup":"previous_visits"},
  "previous_visit_length_of_stay": {"page":"Previous U.S. Travel","step":5,"type":"text","required":false,"label":"Length of Stay (Value)","showIf":"has_been_in_us === yes","repeatGroup":"previous_visits"},
  "previous_visit_length_of_stay_unit": {"page":"Previous U.S. Travel","step":5,"type":"select","required":false,"label":"Length of Stay (Unit)","showIf":"has_been_in_us === yes","repeatGroup":"previous_visits"},
  "has_us_drivers_license": {"page":"Previous U.S. Travel","step":5,"type":"radio","required":true,"label":"Do you or did you ever hold a U.S. Driver's License?","showIf":"has_been_in_us === yes"},
  "us_drivers_license_number": {"page":"Previous U.S. Travel","step":5,"type":"text","required":false,"label":"Driver's License Number","showIf":"has_us_drivers_license === yes","repeatGroup":"drivers_licenses"},
  "us_drivers_license_state": {"page":"Previous U.S. Travel","step":5,"type":"select","required":false,"label":"Driver's License State","showIf":"has_us_drivers_license === yes","repeatGroup":"drivers_licenses"},
  "has_us_visa": {"page":"Previous U.S. Travel","step":5,"type":"radio","required":true,"label":"Have you ever been issued a U.S. Visa?"},
  "last_visa_issue_day": {"page":"Previous U.S. Travel","step":5,"type":"select","required":true,"label":"Date Last Visa Was Issued (Day)","showIf":"has_us_visa === yes"},
  "last_visa_issue_month": {"page":"Previous U.S. Travel","step":5,"type":"select","required":true,"label":"Date Last Visa Was Issued (Month)","showIf":"has_us_visa === yes"},
  "last_visa_issue_year": {"page":"Previous U.S. Travel","step":5,"type":"text","required":true,"label":"Date Last Visa Was Issued (Year)","showIf":"has_us_visa === yes"},
  "visa_number": {"page":"Previous U.S. Travel","step":5,"type":"text","required":false,"label":"Visa Number","showIf":"has_us_visa === yes"},
  "visa_number_unknown": {"page":"Previous U.S. Travel","step":5,"type":"checkbox","required":false,"label":"Do Not Know","showIf":"has_us_visa === yes"},
  "applying_same_visa_type": {"page":"Previous U.S. Travel","step":5,"type":"radio","required":true,"label":"Are you applying for the same type of visa?","showIf":"has_us_visa === yes"},
  "applying_same_country_of_issue_and_residence": {"page":"Previous U.S. Travel","step":5,"type":"radio","required":true,"label":"Are you applying in the same country or location where the visa above was issued, and is this country or location your place of principal of residence?","showIf":"has_us_visa === yes"},
  "has_been_ten_printed": {"page":"Previous U.S. Travel","step":5,"type":"radio","required":true,"label":"Have you been ten-printed?","showIf":"has_us_visa === yes"},
  "visa_lost_or_stolen": {"page":"Previous U.S. Travel","step":5,"type":"radio","required":true,"label":"Has your U.S. Visa ever been lost or stolen?","showIf":"has_us_visa === yes"},
  "year_visa_lost_or_stolen": {"page":"Previous U.S. Travel","step":5,"type":"text","required":true,"label":"Enter year visa was lost or stolen","showIf":"visa_lost_or_stolen === yes"},
  "visa_lost_or_stolen_explain": {"page":"Previous U.S. Travel","step":5,"type":"textarea","required":true,"label":"Explain","showIf":"visa_lost_or_stolen === yes"},
  "visa_cancelled_or_revoked": {"page":"Previous U.S. Travel","step":5,"type":"radio","required":true,"label":"Has your U.S. Visa ever been cancelled or revoked?","showIf":"has_us_visa === yes"},
  "visa_cancelled_or_revoked_explain": {"page":"Previous U.S. Travel","step":5,"type":"textarea","required":true,"label":"Explain","showIf":"visa_cancelled_or_revoked === yes"},
  "has_been_refused": {"page":"Previous U.S. Travel","step":5,"type":"radio","required":true,"label":"Have you ever been refused a U.S. Visa, or been refused admission to the United States, or withdrawn your application for admission at the port of entry?"},
  "refusal_explain": {"page":"Previous U.S. Travel","step":5,"type":"textarea","required":false,"label":"Explain","showIf":"has_been_refused === yes","repeatGroup":"visa_refused"},
  "immigrant_petition_filed": {"page":"Previous U.S. Travel","step":5,"type":"radio","required":true,"label":"Has anyone ever filed an immigrant petition on your behalf with the United States Citizenship and Immigration Services?"},
  "immigrant_petition_explain": {"page":"Previous U.S. Travel","step":5,"type":"textarea","required":false,"label":"Explain","showIf":"immigrant_petition_filed === yes","repeatGroup":"immigrant_petition"},
  "home_address_line1": {"page":"Address and Phone","step":6,"type":"text","required":true,"label":"Street Address (Line 1)"},
  "home_address_line2": {"page":"Address and Phone","step":6,"type":"text","required":false,"label":"Street Address (Line 2)"},
  "home_address_city": {"page":"Address and Phone","step":6,"type":"text","required":true,"label":"City"},
  "home_address_state_province": {"page":"Address and Phone","step":6,"type":"text","required":false,"label":"State/Province"},
  "home_address_postal_code": {"page":"Address and Phone","step":6,"type":"text","required":false,"label":"Postal Zone/ZIP Code"},
  "home_address_country": {"page":"Address and Phone","step":6,"type":"select","required":true,"label":"Country/Region"},
  "mailing_same_as_home": {"page":"Address and Phone","step":6,"type":"radio","required":true,"label":"Is your Mailing Address the same as your Home Address?"},
  "mailing_address_line1": {"page":"Address and Phone","step":6,"type":"text","required":true,"label":"Mailing Street Address (Line 1)","showIf":"mailing_same_as_home === no"},
  "mailing_address_line2": {"page":"Address and Phone","step":6,"type":"text","required":false,"label":"Mailing Street Address (Line 2)","showIf":"mailing_same_as_home === no"},
  "mailing_address_city": {"page":"Address and Phone","step":6,"type":"text","required":true,"label":"Mailing City","showIf":"mailing_same_as_home === no"},
  "mailing_address_state": {"page":"Address and Phone","step":6,"type":"text","required":false,"label":"Mailing State/Province","showIf":"mailing_same_as_home === no"},
  "mailing_address_postal": {"page":"Address and Phone","step":6,"type":"text","required":false,"label":"Mailing Postal Zone/ZIP Code","showIf":"mailing_same_as_home === no"},
  "mailing_address_country": {"page":"Address and Phone","step":6,"type":"select","required":true,"label":"Mailing Country/Region","showIf":"mailing_same_as_home === no"},
  "primary_phone": {"page":"Address and Phone","step":6,"type":"text","required":true,"label":"Primary Phone Number"},
  "secondary_phone": {"page":"Address and Phone","step":6,"type":"text","required":false,"label":"Secondary Phone Number"},
  "work_phone": {"page":"Address and Phone","step":6,"type":"text","required":false,"label":"Work Phone Number"},
  "has_other_phones": {"page":"Address and Phone","step":6,"type":"radio","required":true,"label":"Have you used any other phone numbers in the last five years?"},
  "additional_phone": {"page":"Address and Phone","step":6,"type":"text","required":false,"label":"Additional Phone Number","showIf":"has_other_phones === yes","repeatGroup":"additional_phones"},
  "email_address": {"page":"Address and Phone","step":6,"type":"text","required":true,"label":"Email Address"},
  "has_other_emails": {"page":"Address and Phone","step":6,"type":"radio","required":true,"label":"Have you used any other email addresses in the last five years?"},
  "additional_email": {"page":"Address and Phone","step":6,"type":"text","required":false,"label":"Additional Email Address","showIf":"has_other_emails === yes","repeatGroup":"additional_emails"},
  "social_media_platform": {"page":"Address and Phone","step":6,"type":"select","required":false,"label":"Social Media Provider/Platform","repeatGroup":"social_media"},
  "social_media_handle": {"page":"Address and Phone","step":6,"type":"text","required":false,"label":"Social Media Identifier","showIf":"social_media_platform !== NONE && social_media_platform !== null","repeatGroup":"social_media"},
  "has_other_social_media": {"page":"Address and Phone","step":6,"type":"radio","required":false,"label":"Do you wish to provide information about your presence on any other websites or applications you have used within the last five years to create or share content (photos, videos, status updates, etc.)?"},
  "other_social_media_name": {"page":"Address and Phone","step":6,"type":"text","required":false,"label":"Website/Application Name","showIf":"has_other_social_media === yes","repeatGroup":"other_social_media"},
  "other_social_media_identifier": {"page":"Address and Phone","step":6,"type":"text","required":false,"label":"Identifier","showIf":"has_other_social_media === yes","repeatGroup":"other_social_media"},
  "passport_document_type": {"page":"Passport Information","step":7,"type":"select","required":true,"label":"Passport/Travel Document Type"},
  "passport_document_type_explain": {"page":"Passport Information","step":7,"type":"text","required":true,"label":"Please explain","showIf":"passport_document_type === other"},
  "passport_number": {"page":"Passport Information","step":7,"type":"text","required":true,"label":"Passport/Travel Document Number"},
  "passport_book_number": {"page":"Passport Information","step":7,"type":"text","required":false,"label":"Passport Book Number"},
  "passport_issuing_country": {"page":"Passport Information","step":7,"type":"select","required":true,"label":"Country/Authority That Issued Passport/Travel Document"},
  "passport_issuance_city": {"page":"Passport Information","step":7,"type":"text","required":true,"label":"City Where Issued"},
  "passport_issuance_state": {"page":"Passport Information","step":7,"type":"text","required":false,"label":"State/Province Where Issued"},
  "passport_issuance_country": {"page":"Passport Information","step":7,"type":"select","required":true,"label":"Country/Region Where Issued"},
  "passport_issuance_date": {"page":"Passport Information","step":7,"type":"date","required":true,"label":"Issuance Date"},
  "passport_expiration_date": {"page":"Passport Information","step":7,"type":"date","required":true,"label":"Expiration Date"},
  "lost_passport": {"page":"Passport Information","step":7,"type":"radio","required":true,"label":"Have you ever lost a passport or had one stolen?"},
  "lost_passport_number": {"page":"Passport Information","step":7,"type":"text","required":false,"label":"Lost/Stolen Passport Number","showIf":"lost_passport === yes","repeatGroup":"lost_passport"},
  "lost_passport_country": {"page":"Passport Information","step":7,"type":"select","required":false,"label":"Country/Authority That Issued Passport/Travel Document","showIf":"lost_passport === yes","repeatGroup":"lost_passport"},
  "lost_passport_explain": {"page":"Passport Information","step":7,"type":"textarea","required":false,"label":"Explain","showIf":"lost_passport === yes","repeatGroup":"lost_passport"},
  "father_surname": {"page":"Family Information: Relatives","step":8,"type":"text","required":true,"label":"Father's Surnames"},
  "father_given_names": {"page":"Family Information: Relatives","step":8,"type":"text","required":true,"label":"Father's Given Names"},
  "father_date_of_birth": {"page":"Family Information: Relatives","step":8,"type":"date","required":true,"label":"Father's Date of Birth","showIf":"father_surname !== DO_NOT_KNOW || father_given_names !== DO_NOT_KNOW"},
  "mother_surname": {"page":"Family Information: Relatives","step":8,"type":"text","required":true,"label":"Mother's Surnames"},
  "mother_given_names": {"page":"Family Information: Relatives","step":8,"type":"text","required":true,"label":"Mother's Given Names"},
  "mother_date_of_birth": {"page":"Family Information: Relatives","step":8,"type":"date","required":true,"label":"Mother's Date of Birth","showIf":"mother_surname !== DO_NOT_KNOW || mother_given_names !== DO_NOT_KNOW"},
  "has_immediate_us_relatives": {"page":"Family Information: Relatives","step":8,"type":"radio","required":true,"label":"Do you have any immediate relatives, not including parents, in the United States?"},
  "us_relative_surname": {"page":"Family Information: Relatives","step":8,"type":"text","required":false,"label":"Surnames","showIf":"has_immediate_us_relatives === yes","repeatGroup":"us_relatives"},
  "us_relative_given_names": {"page":"Family Information: Relatives","step":8,"type":"text","required":false,"label":"Given Names","showIf":"has_immediate_us_relatives === yes","repeatGroup":"us_relatives"},
  "us_relative_relationship": {"page":"Family Information: Relatives","step":8,"type":"select","required":false,"label":"Relationship to You","showIf":"has_immediate_us_relatives === yes","repeatGroup":"us_relatives"},
  "us_relative_status": {"page":"Family Information: Relatives","step":8,"type":"select","required":false,"label":"Relative's Status","showIf":"has_immediate_us_relatives === yes","repeatGroup":"us_relatives"},
  "has_other_us_relatives": {"page":"Family Information: Relatives","step":8,"type":"radio","required":true,"label":"Do you have any other relatives in the United States?"},
  "spouse_surname": {"page":"Family Information: Spouse","step":9,"type":"text","required":false,"label":"Spouse's Surnames","showIf":"marital_status === married || marital_status === legally_separated || marital_status === common_law || marital_status === other"},
  "spouse_given_names": {"page":"Family Information: Spouse","step":9,"type":"text","required":false,"label":"Spouse's Given Names","showIf":"marital_status === married || marital_status === legally_separated || marital_status === common_law || marital_status === other"},
  "spouse_date_of_birth": {"page":"Family Information: Spouse","step":9,"type":"date","required":false,"label":"Spouse's Date of Birth","showIf":"marital_status === married || marital_status === legally_separated || marital_status === common_law || marital_status === other"},
  "spouse_nationality": {"page":"Family Information: Spouse","step":9,"type":"select","required":false,"label":"Spouse's Country/Region of Origin (Nationality)","showIf":"marital_status === married || marital_status === legally_separated || marital_status === common_law || marital_status === other"},
  "spouse_city_of_birth": {"page":"Family Information: Spouse","step":9,"type":"text","required":false,"label":"Spouse's City of Birth","showIf":"marital_status === married || marital_status === legally_separated || marital_status === common_law || marital_status === other"},
  "spouse_country_of_birth": {"page":"Family Information: Spouse","step":9,"type":"select","required":false,"label":"Spouse's Country/Region of Birth","showIf":"marital_status === married || marital_status === legally_separated || marital_status === common_law || marital_status === other"},
  "spouse_address_type": {"page":"Family Information: Spouse","step":9,"type":"select","required":false,"label":"Spouse's Address","showIf":"marital_status === married || marital_status === legally_separated || marital_status === common_law || marital_status === other"},
  "spouse_address_street1": {"page":"Family Information: Spouse","step":9,"type":"text","required":false,"label":"Street Address (Line 1)","showIf":"spouse_address_type === other"},
  "spouse_address_street2": {"page":"Family Information: Spouse","step":9,"type":"text","required":false,"label":"Street Address (Line 2)","showIf":"spouse_address_type === other"},
  "spouse_address_city": {"page":"Family Information: Spouse","step":9,"type":"text","required":false,"label":"City","showIf":"spouse_address_type === other"},
  "spouse_address_state": {"page":"Family Information: Spouse","step":9,"type":"text","required":false,"label":"State/Province","showIf":"spouse_address_type === other"},
  "spouse_address_zip": {"page":"Family Information: Spouse","step":9,"type":"text","required":false,"label":"Postal Zone/ZIP Code","showIf":"spouse_address_type === other"},
  "spouse_address_country": {"page":"Family Information: Spouse","step":9,"type":"select","required":false,"label":"Country/Region","showIf":"spouse_address_type === other"},
  "partner_surname": {"page":"Family Information: Partner","step":10,"type":"text","required":false,"label":"Partner's Surnames","showIf":"marital_status === civil_union"},
  "partner_given_names": {"page":"Family Information: Partner","step":10,"type":"text","required":false,"label":"Partner's Given Names","showIf":"marital_status === civil_union"},
  "partner_date_of_birth": {"page":"Family Information: Partner","step":10,"type":"date","required":false,"label":"Partner's Date of Birth","showIf":"marital_status === civil_union"},
  "partner_nationality": {"page":"Family Information: Partner","step":10,"type":"select","required":false,"label":"Partner's Country/Region of Origin (Nationality)","showIf":"marital_status === civil_union"},
  "partner_city_of_birth": {"page":"Family Information: Partner","step":10,"type":"text","required":false,"label":"Partner's City of Birth","showIf":"marital_status === civil_union"},
  "partner_country_of_birth": {"page":"Family Information: Partner","step":10,"type":"select","required":false,"label":"Partner's Country/Region of Birth","showIf":"marital_status === civil_union"},
  "partner_address_type": {"page":"Family Information: Partner","step":10,"type":"select","required":false,"label":"Partner's Address","showIf":"marital_status === civil_union"},
  "partner_address_street1": {"page":"Family Information: Partner","step":10,"type":"text","required":false,"label":"Street Address (Line 1)","showIf":"partner_address_type === other"},
  "partner_address_street2": {"page":"Family Information: Partner","step":10,"type":"text","required":false,"label":"Street Address (Line 2)","showIf":"partner_address_type === other"},
  "partner_address_city": {"page":"Family Information: Partner","step":10,"type":"text","required":false,"label":"City","showIf":"partner_address_type === other"},
  "partner_address_state": {"page":"Family Information: Partner","step":10,"type":"text","required":false,"label":"State/Province","showIf":"partner_address_type === other"},
  "partner_address_zip": {"page":"Family Information: Partner","step":10,"type":"text","required":false,"label":"Postal Zone/ZIP Code","showIf":"partner_address_type === other"},
  "partner_address_country": {"page":"Family Information: Partner","step":10,"type":"select","required":false,"label":"Country/Region","showIf":"partner_address_type === other"},
  "deceased_spouse_surname": {"page":"Family Information: Deceased Spouse","step":11,"type":"text","required":false,"label":"Deceased Spouse's Surnames","showIf":"marital_status === widowed"},
  "deceased_spouse_given_names": {"page":"Family Information: Deceased Spouse","step":11,"type":"text","required":false,"label":"Deceased Spouse's Given Names","showIf":"marital_status === widowed"},
  "deceased_spouse_date_of_birth": {"page":"Family Information: Deceased Spouse","step":11,"type":"date","required":false,"label":"Deceased Spouse's Date of Birth","showIf":"marital_status === widowed"},
  "deceased_spouse_nationality": {"page":"Family Information: Deceased Spouse","step":11,"type":"select","required":false,"label":"Deceased Spouse's Country/Region of Origin (Nationality)","showIf":"marital_status === widowed"},
  "deceased_spouse_city_of_birth": {"page":"Family Information: Deceased Spouse","step":11,"type":"text","required":false,"label":"Deceased Spouse's City of Birth","showIf":"marital_status === widowed"},
  "deceased_spouse_country_of_birth": {"page":"Family Information: Deceased Spouse","step":11,"type":"select","required":false,"label":"Deceased Spouse's Country/Region of Birth","showIf":"marital_status === widowed"},
  "number_of_former_spouses": {"page":"Family Information: Former Spouse","step":12,"type":"select","required":false,"label":"Number of Former Spouses","showIf":"marital_status === divorced"},
  "former_spouse_surname": {"page":"Family Information: Former Spouse","step":12,"type":"text","required":false,"label":"Former Spouse's Surnames","showIf":"marital_status === divorced","repeatGroup":"former_spouses"},
  "former_spouse_given_names": {"page":"Family Information: Former Spouse","step":12,"type":"text","required":false,"label":"Former Spouse's Given Names","showIf":"marital_status === divorced","repeatGroup":"former_spouses"},
  "former_spouse_date_of_birth": {"page":"Family Information: Former Spouse","step":12,"type":"date","required":false,"label":"Former Spouse's Date of Birth","showIf":"marital_status === divorced","repeatGroup":"former_spouses"},
  "former_spouse_nationality": {"page":"Family Information: Former Spouse","step":12,"type":"select","required":false,"label":"Former Spouse's Country/Region of Origin (Nationality)","showIf":"marital_status === divorced","repeatGroup":"former_spouses"},
  "former_spouse_city_of_birth": {"page":"Family Information: Former Spouse","step":12,"type":"text","required":false,"label":"Former Spouse's City of Birth","showIf":"marital_status === divorced","repeatGroup":"former_spouses"},
  "former_spouse_country_of_birth": {"page":"Family Information: Former Spouse","step":12,"type":"select","required":false,"label":"Former Spouse's Country/Region of Birth","showIf":"marital_status === divorced","repeatGroup":"former_spouses"},
  "former_spouse_date_of_marriage": {"page":"Family Information: Former Spouse","step":12,"type":"date","required":false,"label":"Date of Marriage","showIf":"marital_status === divorced","repeatGroup":"former_spouses"},
  "former_spouse_date_marriage_ended": {"page":"Family Information: Former Spouse","step":12,"type":"date","required":false,"label":"Date Marriage Ended","showIf":"marital_status === divorced","repeatGroup":"former_spouses"},
  "former_spouse_how_marriage_ended": {"page":"Family Information: Former Spouse","step":12,"type":"text","required":false,"label":"How the Marriage Ended","showIf":"marital_status === divorced","repeatGroup":"former_spouses"},
  "former_spouse_country_marriage_terminated": {"page":"Family Information: Former Spouse","step":12,"type":"select","required":false,"label":"Country/Region Marriage was Terminated","showIf":"marital_status === divorced","repeatGroup":"former_spouses"},
  "us_contact_surname": {"page":"US Point of Contact","step":13,"type":"text","required":false,"label":"U.S. Contact — Surname"},
  "us_contact_given_names": {"page":"US Point of Contact","step":13,"type":"text","required":false,"label":"U.S. Contact — Given Names"},
  "us_contact_organization": {"page":"US Point of Contact","step":13,"type":"text","required":false,"label":"U.S. Contact — Organization (if not a person)"},
  "us_contact_relationship": {"page":"US Point of Contact","step":13,"type":"select","required":true,"label":"U.S. Contact — Relationship"},
  "us_contact_address_street1": {"page":"US Point of Contact","step":13,"type":"text","required":true,"label":"U.S. Contact — Street Address","showIf":"us_contact_relationship !== _empty"},
  "us_contact_address_street2": {"page":"US Point of Contact","step":13,"type":"text","required":false,"label":"Street Address (Line 2)","showIf":"us_contact_relationship !== _empty"},
  "us_contact_city": {"page":"US Point of Contact","step":13,"type":"text","required":true,"label":"U.S. Contact — City","showIf":"us_contact_relationship !== _empty"},
  "us_contact_state": {"page":"US Point of Contact","step":13,"type":"select","required":true,"label":"U.S. Contact — State","showIf":"us_contact_relationship !== _empty"},
  "us_contact_zip": {"page":"US Point of Contact","step":13,"type":"text","required":true,"label":"U.S. Contact — ZIP Code","showIf":"us_contact_relationship !== _empty"},
  "us_contact_phone": {"page":"US Point of Contact","step":13,"type":"text","required":true,"label":"U.S. Contact — Phone","showIf":"us_contact_relationship !== _empty"},
  "us_contact_email": {"page":"US Point of Contact","step":13,"type":"text","required":false,"label":"U.S. Contact — Email","showIf":"us_contact_relationship !== _empty"},
  "primary_occupation": {"page":"Work/Education/Training: Present","step":14,"type":"select","required":true,"label":"Primary Occupation"},
  "occupation_other_explain": {"page":"Work/Education/Training: Present","step":14,"type":"text","required":true,"label":"Specify Other","showIf":"primary_occupation === other"},
  "not_employed_explain": {"page":"Work/Education/Training: Present","step":14,"type":"textarea","required":true,"label":"Explain","showIf":"primary_occupation === not_employed"},
  "employer_name": {"page":"Work/Education/Training: Present","step":14,"type":"text","required":false,"label":"Present Employer or School Name","showIf":"primary_occupation !== _empty && primary_occupation !== retired && primary_occupation !== homemaker && primary_occupation !== not_employed"},
  "employer_address_line1": {"page":"Work/Education/Training: Present","step":14,"type":"text","required":false,"label":"Street Address (Line 1)","showIf":"primary_occupation !== _empty && primary_occupation !== retired && primary_occupation !== homemaker && primary_occupation !== not_employed"},
  "employer_address_line2": {"page":"Work/Education/Training: Present","step":14,"type":"text","required":false,"label":"Street Address (Line 2)","showIf":"primary_occupation !== _empty && primary_occupation !== retired && primary_occupation !== homemaker && primary_occupation !== not_employed"},
  "employer_city": {"page":"Work/Education/Training: Present","step":14,"type":"text","required":false,"label":"City","showIf":"primary_occupation !== _empty && primary_occupation !== retired && primary_occupation !== homemaker && primary_occupation !== not_employed"},
  "employer_state_province": {"page":"Work/Education/Training: Present","step":14,"type":"text","required":false,"label":"State/Province","showIf":"primary_occupation !== _empty && primary_occupation !== retired && primary_occupation !== homemaker && primary_occupation !== not_employed"},
  "employer_postal_code": {"page":"Work/Education/Training: Present","step":14,"type":"text","required":false,"label":"Postal Zone/ZIP Code","showIf":"primary_occupation !== _empty && primary_occupation !== retired && primary_occupation !== homemaker && primary_occupation !== not_employed"},
  "employer_country": {"page":"Work/Education/Training: Present","step":14,"type":"select","required":false,"label":"Country/Region","showIf":"primary_occupation !== _empty && primary_occupation !== retired && primary_occupation !== homemaker && primary_occupation !== not_employed"},
  "employer_phone": {"page":"Work/Education/Training: Present","step":14,"type":"text","required":false,"label":"Phone Number","showIf":"primary_occupation !== _empty && primary_occupation !== retired && primary_occupation !== homemaker && primary_occupation !== not_employed"},
  "job_title": {"page":"Work/Education/Training: Present","step":14,"type":"text","required":false,"label":"Job Title","showIf":"primary_occupation !== _empty && primary_occupation !== retired && primary_occupation !== homemaker && primary_occupation !== not_employed"},
  "employment_start_date": {"page":"Work/Education/Training: Present","step":14,"type":"date","required":false,"label":"Start Date","showIf":"primary_occupation !== _empty && primary_occupation !== retired && primary_occupation !== homemaker && primary_occupation !== not_employed"},
  "monthly_salary": {"page":"Work/Education/Training: Present","step":14,"type":"text","required":false,"label":"Monthly Income in Local Currency (if employed)","showIf":"primary_occupation !== _empty && primary_occupation !== retired && primary_occupation !== homemaker && primary_occupation !== not_employed"},
  "job_duties": {"page":"Work/Education/Training: Present","step":14,"type":"textarea","required":false,"label":"Briefly Describe Your Duties","showIf":"primary_occupation !== _empty && primary_occupation !== retired && primary_occupation !== homemaker && primary_occupation !== not_employed"},
  "has_previous_employer": {"page":"Work/Education/Training: Previous","step":15,"type":"radio","required":true,"label":"Were you previously employed?"},
  "prev_employer_name": {"page":"Work/Education/Training: Previous","step":15,"type":"text","required":false,"label":"Employer Name","showIf":"has_previous_employer === yes","repeatGroup":"previous_employers"},
  "prev_employer_address_street1": {"page":"Work/Education/Training: Previous","step":15,"type":"text","required":false,"label":"Street Address (Line 1)","showIf":"has_previous_employer === yes","repeatGroup":"previous_employers"},
  "prev_employer_address_street2": {"page":"Work/Education/Training: Previous","step":15,"type":"text","required":false,"label":"Street Address (Line 2)","showIf":"has_previous_employer === yes","repeatGroup":"previous_employers"},
  "prev_employer_city": {"page":"Work/Education/Training: Previous","step":15,"type":"text","required":false,"label":"City","showIf":"has_previous_employer === yes","repeatGroup":"previous_employers"},
  "prev_employer_state": {"page":"Work/Education/Training: Previous","step":15,"type":"text","required":false,"label":"State/Province","showIf":"has_previous_employer === yes","repeatGroup":"previous_employers"},
  "prev_employer_postal": {"page":"Work/Education/Training: Previous","step":15,"type":"text","required":false,"label":"Postal Zone/ZIP Code","showIf":"has_previous_employer === yes","repeatGroup":"previous_employers"},
  "prev_employer_country": {"page":"Work/Education/Training: Previous","step":15,"type":"select","required":false,"label":"Country/Region","showIf":"has_previous_employer === yes","repeatGroup":"previous_employers"},
  "prev_employer_phone": {"page":"Work/Education/Training: Previous","step":15,"type":"text","required":false,"label":"Telephone Number","showIf":"has_previous_employer === yes","repeatGroup":"previous_employers"},
  "prev_job_title": {"page":"Work/Education/Training: Previous","step":15,"type":"text","required":false,"label":"Job Title","showIf":"has_previous_employer === yes","repeatGroup":"previous_employers"},
  "prev_supervisor_surname": {"page":"Work/Education/Training: Previous","step":15,"type":"text","required":false,"label":"Supervisor's Surnames","showIf":"has_previous_employer === yes","repeatGroup":"previous_employers"},
  "prev_supervisor_given_names": {"page":"Work/Education/Training: Previous","step":15,"type":"text","required":false,"label":"Supervisor's Given Names","showIf":"has_previous_employer === yes","repeatGroup":"previous_employers"},
  "prev_employment_start_date": {"page":"Work/Education/Training: Previous","step":15,"type":"date","required":false,"label":"Employment Date From","showIf":"has_previous_employer === yes","repeatGroup":"previous_employers"},
  "prev_employment_end_date": {"page":"Work/Education/Training: Previous","step":15,"type":"date","required":false,"label":"Employment Date To","showIf":"has_previous_employer === yes","repeatGroup":"previous_employers"},
  "prev_job_duties": {"page":"Work/Education/Training: Previous","step":15,"type":"textarea","required":false,"label":"Briefly Describe Your Duties","showIf":"has_previous_employer === yes","repeatGroup":"previous_employers"},
  "has_attended_education": {"page":"Work/Education/Training: Previous","step":15,"type":"radio","required":true,"label":"Have you attended any educational institutions at a secondary level or above?"},
  "education_institution_name": {"page":"Work/Education/Training: Previous","step":15,"type":"text","required":false,"label":"Name of Institution","showIf":"has_attended_education === yes","repeatGroup":"education"},
  "education_address_line1": {"page":"Work/Education/Training: Previous","step":15,"type":"text","required":false,"label":"Street Address (Line 1)","showIf":"has_attended_education === yes","repeatGroup":"education"},
  "education_address_line2": {"page":"Work/Education/Training: Previous","step":15,"type":"text","required":false,"label":"Street Address (Line 2)","showIf":"has_attended_education === yes","repeatGroup":"education"},
  "education_city": {"page":"Work/Education/Training: Previous","step":15,"type":"text","required":false,"label":"City","showIf":"has_attended_education === yes","repeatGroup":"education"},
  "education_state_province": {"page":"Work/Education/Training: Previous","step":15,"type":"text","required":false,"label":"State/Province","showIf":"has_attended_education === yes","repeatGroup":"education"},
  "education_postal_code": {"page":"Work/Education/Training: Previous","step":15,"type":"text","required":false,"label":"Postal Zone/ZIP Code","showIf":"has_attended_education === yes","repeatGroup":"education"},
  "education_country": {"page":"Work/Education/Training: Previous","step":15,"type":"select","required":false,"label":"Country/Region","showIf":"has_attended_education === yes","repeatGroup":"education"},
  "education_course_of_study": {"page":"Work/Education/Training: Previous","step":15,"type":"text","required":false,"label":"Course of Study","showIf":"has_attended_education === yes","repeatGroup":"education"},
  "education_start_date": {"page":"Work/Education/Training: Previous","step":15,"type":"date","required":false,"label":"Date of Attendance From","showIf":"has_attended_education === yes","repeatGroup":"education"},
  "education_end_date": {"page":"Work/Education/Training: Previous","step":15,"type":"date","required":false,"label":"Date of Attendance To","showIf":"has_attended_education === yes","repeatGroup":"education"},
  "has_clan_tribe": {"page":"Work/Education/Training: Additional","step":16,"type":"radio","required":true,"label":"Do you belong to a clan or tribe?"},
  "clan_tribe_name": {"page":"Work/Education/Training: Additional","step":16,"type":"text","required":false,"label":"Clan/Tribe Name","showIf":"has_clan_tribe === yes"},
  "language_name": {"page":"Work/Education/Training: Additional","step":16,"type":"text","required":true,"label":"Language Name","repeatGroup":"languages"},
  "has_traveled_last_five_years": {"page":"Work/Education/Training: Additional","step":16,"type":"radio","required":true,"label":"Have you traveled to any countries/regions within the last five years?"},
  "traveled_country": {"page":"Work/Education/Training: Additional","step":16,"type":"select","required":false,"label":"Country/Region","showIf":"has_traveled_last_five_years === yes","repeatGroup":"traveled_countries"},
  "has_belonged_to_organization": {"page":"Work/Education/Training: Additional","step":16,"type":"radio","required":true,"label":"Have you belonged to, contributed to, or worked for any professional, social, or charitable organization?"},
  "organization_name": {"page":"Work/Education/Training: Additional","step":16,"type":"text","required":false,"label":"Organization Name","showIf":"has_belonged_to_organization === yes","repeatGroup":"organizations"},
  "has_specialized_skills": {"page":"Work/Education/Training: Additional","step":16,"type":"radio","required":true,"label":"Do you have any specialized skills or training, such as firearms, explosives, nuclear, biological, or chemical experience?"},
  "specialized_skills_explain": {"page":"Work/Education/Training: Additional","step":16,"type":"textarea","required":false,"label":"Explain","showIf":"has_specialized_skills === yes"},
  "has_served_military": {"page":"Work/Education/Training: Additional","step":16,"type":"radio","required":true,"label":"Have you ever served in the military?"},
  "military_country": {"page":"Work/Education/Training: Additional","step":16,"type":"select","required":false,"label":"Country/Region","showIf":"has_served_military === yes","repeatGroup":"military_service"},
  "military_branch": {"page":"Work/Education/Training: Additional","step":16,"type":"text","required":false,"label":"Branch of Service","showIf":"has_served_military === yes","repeatGroup":"military_service"},
  "military_rank": {"page":"Work/Education/Training: Additional","step":16,"type":"text","required":false,"label":"Rank/Position","showIf":"has_served_military === yes","repeatGroup":"military_service"},
  "military_specialty": {"page":"Work/Education/Training: Additional","step":16,"type":"text","required":false,"label":"Military Specialty","showIf":"has_served_military === yes","repeatGroup":"military_service"},
  "military_date_from": {"page":"Work/Education/Training: Additional","step":16,"type":"date","required":false,"label":"Date of Service From","showIf":"has_served_military === yes","repeatGroup":"military_service"},
  "military_date_to": {"page":"Work/Education/Training: Additional","step":16,"type":"date","required":false,"label":"Date of Service To","showIf":"has_served_military === yes","repeatGroup":"military_service"},
  "has_served_paramilitary": {"page":"Work/Education/Training: Additional","step":16,"type":"radio","required":true,"label":"Have you ever served in, been a member of, or been involved with a paramilitary unit, vigilante unit, rebel group, guerrilla group, or insurgent organization?"},
  "paramilitary_explain": {"page":"Work/Education/Training: Additional","step":16,"type":"textarea","required":false,"label":"Explain","showIf":"has_served_paramilitary === yes"},
  "vwp_denial": {"page":"Previous U.S. Travel","step":5,"type":"radio","required":true,"label":"Have you ever been denied a U.S. Visa Waiver Program (ESTA) authorization?"},
  "mobile_phone": {"page":"Address and Phone","step":6,"type":"text","required":false,"label":"Mobile (Cellular) Phone Number"},
  "has_social_media": {"page":"Address and Phone","step":6,"type":"radio","required":true,"label":"Have you used any social media platforms in the last five years?"},
  "social_media_provider": {"page":"Address and Phone","step":6,"type":"select","required":false,"label":"Social Media Platform","showIf":"has_social_media === yes"},
  "social_media_identifier": {"page":"Address and Phone","step":6,"type":"text","required":false,"label":"Social Media Identifier (handle / username)","showIf":"has_social_media === yes"},
  "passport_has_expiry": {"page":"Passport Information","step":7,"type":"radio","required":true,"label":"Does your passport have an expiration date?"},
  "father_in_us": {"page":"Family Information: Relatives","step":9,"type":"radio","required":true,"label":"Is your father in the U.S.?","showIf":"father_surname !== DO_NOT_KNOW || father_given_names !== DO_NOT_KNOW"},
  "mother_in_us": {"page":"Family Information: Relatives","step":9,"type":"radio","required":true,"label":"Is your mother in the U.S.?","showIf":"mother_surname !== DO_NOT_KNOW || mother_given_names !== DO_NOT_KNOW"},
  "has_communicable_disease": {"page":"Security and Background: Part 1","step":17,"type":"radio","required":true,"label":"Do you have a communicable disease of public health significance? (Communicable diseases of public significance include chancroid, gonorrhea, granuloma inguinale, infectious leprosy, lymphogranuloma venereum, infectious stage syphilis, active tuberculosis, and other diseases as determined by the Department of Health and Human Services.)"},
  "has_communicable_disease_explain": {"page":"Security and Background: Part 1","step":17,"type":"textarea","required":true,"label":"Explain","showIf":"has_communicable_disease === yes"},
  "has_physical_mental_disorder": {"page":"Security and Background: Part 1","step":17,"type":"radio","required":true,"label":"Do you have a mental or physical disorder that poses or is likely to pose a threat to the safety or welfare of yourself or others?"},
  "has_physical_mental_disorder_explain": {"page":"Security and Background: Part 1","step":17,"type":"textarea","required":true,"label":"Explain","showIf":"has_physical_mental_disorder === yes"},
  "is_drug_abuser": {"page":"Security and Background: Part 1","step":17,"type":"radio","required":true,"label":"Are you or have you ever been a drug abuser or addict?"},
  "is_drug_abuser_explain": {"page":"Security and Background: Part 1","step":17,"type":"textarea","required":true,"label":"Explain","showIf":"is_drug_abuser === yes"},
  "has_arrest_conviction": {"page":"Security and Background: Part 2","step":18,"type":"radio","required":true,"label":"Have you ever been arrested or convicted for any offense or crime, even though subject of a pardon, amnesty, or other similar action?"},
  "has_arrest_conviction_explain": {"page":"Security and Background: Part 2","step":18,"type":"textarea","required":true,"label":"Explain","showIf":"has_arrest_conviction === yes"},
  "has_violated_controlled_substance": {"page":"Security and Background: Part 2","step":18,"type":"radio","required":true,"label":"Have you ever violated, or engaged in a conspiracy to violate, any law relating to controlled substances?"},
  "has_violated_controlled_substance_explain": {"page":"Security and Background: Part 2","step":18,"type":"textarea","required":true,"label":"Explain","showIf":"has_violated_controlled_substance === yes"},
  "has_prostitution": {"page":"Security and Background: Part 2","step":18,"type":"radio","required":true,"label":"Are you coming to the United States to engage in prostitution or unlawful commercialized vice or have you been engaged in prostitution or procuring prostitutes within the past 10 years?"},
  "has_prostitution_explain": {"page":"Security and Background: Part 2","step":18,"type":"textarea","required":true,"label":"Explain","showIf":"has_prostitution === yes"},
  "has_money_laundering": {"page":"Security and Background: Part 2","step":18,"type":"radio","required":true,"label":"Have you ever been involved in, or do you seek to engage in, money laundering?"},
  "has_money_laundering_explain": {"page":"Security and Background: Part 2","step":18,"type":"textarea","required":true,"label":"Explain","showIf":"has_money_laundering === yes"},
  "has_human_trafficking": {"page":"Security and Background: Part 2","step":18,"type":"radio","required":true,"label":"Have you ever committed or conspired to commit a human trafficking offense in the United States or outside the United States?"},
  "has_human_trafficking_explain": {"page":"Security and Background: Part 2","step":18,"type":"textarea","required":true,"label":"Explain","showIf":"has_human_trafficking === yes"},
  "has_aided_human_trafficking": {"page":"Security and Background: Part 2","step":18,"type":"radio","required":true,"label":"Have you ever knowingly aided, abetted, assisted or colluded with an individual who has committed, or conspired to commit a severe human trafficking offense in the United States or outside the United States?"},
  "has_aided_human_trafficking_explain": {"page":"Security and Background: Part 2","step":18,"type":"textarea","required":true,"label":"Explain","showIf":"has_aided_human_trafficking === yes"},
  "has_trafficking_beneficiary": {"page":"Security and Background: Part 2","step":18,"type":"radio","required":true,"label":"Are you the spouse, son, or daughter of an individual who has committed or conspired to commit a human trafficking offense in the United States or outside the United States and have you within the last five years, knowingly benefited from the trafficking activities?"},
  "has_trafficking_beneficiary_explain": {"page":"Security and Background: Part 2","step":18,"type":"textarea","required":true,"label":"Explain","showIf":"has_trafficking_beneficiary === yes"},
  "intend_illegal_activity": {"page":"Security and Background: Part 3","step":19,"type":"radio","required":true,"label":"Do you seek to engage in espionage, sabotage, export control violations, or any other illegal activity while in the United States?"},
  "intend_illegal_activity_explain": {"page":"Security and Background: Part 3","step":19,"type":"textarea","required":true,"label":"Explain","showIf":"intend_illegal_activity === yes"},
  "intend_terrorist_activity": {"page":"Security and Background: Part 3","step":19,"type":"radio","required":true,"label":"Do you seek to engage in terrorist activities while in the United States or have you ever engaged in terrorist activities?"},
  "intend_terrorist_activity_explain": {"page":"Security and Background: Part 3","step":19,"type":"textarea","required":true,"label":"Explain","showIf":"intend_terrorist_activity === yes"},
  "has_provided_terrorist_support": {"page":"Security and Background: Part 3","step":19,"type":"radio","required":true,"label":"Have you ever or do you intend to provide financial assistance or other support to terrorists or terrorist organizations?"},
  "has_provided_terrorist_support_explain": {"page":"Security and Background: Part 3","step":19,"type":"textarea","required":true,"label":"Explain","showIf":"has_provided_terrorist_support === yes"},
  "is_terrorist_member": {"page":"Security and Background: Part 3","step":19,"type":"radio","required":true,"label":"Are you a member or representative of a terrorist organization?"},
  "is_terrorist_member_explain": {"page":"Security and Background: Part 3","step":19,"type":"textarea","required":true,"label":"Explain","showIf":"is_terrorist_member === yes"},
  "is_terrorist_family": {"page":"Security and Background: Part 3","step":19,"type":"radio","required":true,"label":"Are you the spouse, son, or daughter of an individual who has engaged in terrorist activity, including providing financial assistance or other support to terrorists or terrorist organizations, in the last five years?"},
  "is_terrorist_family_explain": {"page":"Security and Background: Part 3","step":19,"type":"textarea","required":true,"label":"Explain","showIf":"is_terrorist_family === yes"},
  "has_genocide": {"page":"Security and Background: Part 3","step":19,"type":"radio","required":true,"label":"Have you ever ordered, incited, committed, assisted, or otherwise participated in genocide?"},
  "has_genocide_explain": {"page":"Security and Background: Part 3","step":19,"type":"textarea","required":true,"label":"Explain","showIf":"has_genocide === yes"},
  "has_torture": {"page":"Security and Background: Part 3","step":19,"type":"radio","required":true,"label":"Have you ever committed, ordered, incited, assisted, or otherwise participated in torture?"},
  "has_torture_explain": {"page":"Security and Background: Part 3","step":19,"type":"textarea","required":true,"label":"Explain","showIf":"has_torture === yes"},
  "has_extrajudicial_killings": {"page":"Security and Background: Part 3","step":19,"type":"radio","required":true,"label":"Have you committed, ordered, incited, assisted, or otherwise participated in extrajudicial killings, political killings, or other acts of violence?"},
  "has_extrajudicial_killings_explain": {"page":"Security and Background: Part 3","step":19,"type":"textarea","required":true,"label":"Explain","showIf":"has_extrajudicial_killings === yes"},
  "has_child_soldier": {"page":"Security and Background: Part 3","step":19,"type":"radio","required":true,"label":"Have you ever engaged in the recruitment or the use of child soldiers?"},
  "has_child_soldier_explain": {"page":"Security and Background: Part 3","step":19,"type":"textarea","required":true,"label":"Explain","showIf":"has_child_soldier === yes"},
  "has_religious_freedom_violation": {"page":"Security and Background: Part 3","step":19,"type":"radio","required":true,"label":"Have you, while serving as a government official, been responsible for or directly carried out, at any time, particularly severe violations of religious freedom?"},
  "has_religious_freedom_violation_explain": {"page":"Security and Background: Part 3","step":19,"type":"textarea","required":true,"label":"Explain","showIf":"has_religious_freedom_violation === yes"},
  "has_population_control": {"page":"Security and Background: Part 3","step":19,"type":"radio","required":true,"label":"Have you ever been directly involved in the establishment or enforcement of population controls forcing a woman to undergo an abortion against her free choice or a man or a woman to undergo sterilization against his or her free will?"},
  "has_population_control_explain": {"page":"Security and Background: Part 3","step":19,"type":"textarea","required":true,"label":"Explain","showIf":"has_population_control === yes"},
  "has_coercive_transplant": {"page":"Security and Background: Part 3","step":19,"type":"radio","required":true,"label":"Have you ever been directly involved in the coercive transplantation of human organs or bodily tissue?"},
  "has_coercive_transplant_explain": {"page":"Security and Background: Part 3","step":19,"type":"textarea","required":true,"label":"Explain","showIf":"has_coercive_transplant === yes"},
  "has_immigration_fraud": {"page":"Security and Background: Part 4","step":20,"type":"radio","required":true,"label":"Have you ever sought to obtain or assist others to obtain a visa, entry into the United States, or any other United States immigration benefit by fraud or willful misrepresentation or other unlawful means?"},
  "has_immigration_fraud_explain": {"page":"Security and Background: Part 4","step":20,"type":"textarea","required":true,"label":"Explain","showIf":"has_immigration_fraud === yes"},
  "has_removal_order": {"page":"Security and Background: Part 4","step":20,"type":"radio","required":true,"label":"Have you ever been removed or deported from any country?"},
  "has_removal_order_explain": {"page":"Security and Background: Part 4","step":20,"type":"textarea","required":true,"label":"Explain","showIf":"has_removal_order === yes"},
  "has_withheld_child_custody": {"page":"Security and Background: Part 5","step":21,"type":"radio","required":true,"label":"Have you ever withheld custody of a U.S. citizen child outside the United States from a person granted legal custody by a U.S. court?"},
  "has_withheld_child_custody_explain": {"page":"Security and Background: Part 5","step":21,"type":"textarea","required":true,"label":"Explain","showIf":"has_withheld_child_custody === yes"},
  "has_voted_illegally": {"page":"Security and Background: Part 5","step":21,"type":"radio","required":true,"label":"Have you voted in the United States in violation of any law or regulation?"},
  "has_voted_illegally_explain": {"page":"Security and Background: Part 5","step":21,"type":"textarea","required":true,"label":"Explain","showIf":"has_voted_illegally === yes"},
  "has_renounced_citizenship": {"page":"Security and Background: Part 5","step":21,"type":"radio","required":true,"label":"Have you ever renounced United States citizenship for the purposes of avoiding taxation?"},
  "has_renounced_citizenship_explain": {"page":"Security and Background: Part 5","step":21,"type":"textarea","required":true,"label":"Explain","showIf":"has_renounced_citizenship === yes"},
  "ds160_preparer_assistance": {"page":"Sign and Submit","step":22,"type":"radio","required":true,"label":"Did anyone assist you in filling out this application?"},
  "ds160_preparer_surname": {"page":"Sign and Submit","step":22,"type":"text","required":true,"label":"Surnames","showIf":"ds160_preparer_assistance === yes"},
  "ds160_preparer_given_names": {"page":"Sign and Submit","step":22,"type":"text","required":true,"label":"Given Names","showIf":"ds160_preparer_assistance === yes","allowsDoesNotApply":true},
  "ds160_preparer_organization_name": {"page":"Sign and Submit","step":22,"type":"text","required":true,"label":"Organization Name","showIf":"ds160_preparer_assistance === yes","allowsDoesNotApply":true},
  "ds160_preparer_street1": {"page":"Sign and Submit","step":22,"type":"text","required":true,"label":"Street Address (Line 1)","showIf":"ds160_preparer_assistance === yes"},
  "ds160_preparer_street2": {"page":"Sign and Submit","step":22,"type":"text","required":false,"label":"Street Address (Line 2)","showIf":"ds160_preparer_assistance === yes","optional":true},
  "ds160_preparer_city": {"page":"Sign and Submit","step":22,"type":"text","required":true,"label":"City","showIf":"ds160_preparer_assistance === yes"},
  "ds160_preparer_state_province": {"page":"Sign and Submit","step":22,"type":"text","required":true,"label":"State/Province","showIf":"ds160_preparer_assistance === yes","allowsDoesNotApply":true},
  "ds160_preparer_postal_code": {"page":"Sign and Submit","step":22,"type":"text","required":true,"label":"Postal Zone/ZIP Code","showIf":"ds160_preparer_assistance === yes","allowsDoesNotApply":true},
  "ds160_preparer_country": {"page":"Sign and Submit","step":22,"type":"select","required":true,"label":"Country/Region","showIf":"ds160_preparer_assistance === yes"},
  "ds160_preparer_relationship": {"page":"Sign and Submit","step":22,"type":"text","required":true,"label":"Relationship to You","showIf":"ds160_preparer_assistance === yes"},
};

export const DS160_FIELD_CONTRACT_COUNT = 336;
