/**
 * CEAC country labels observed on 2026-09-21.
 *
 * Generated from the repository's CEAC snapshot at
 * viza-fe/internal-website/lib/ds160-official-options.snapshot.json. The
 * submission service keeps this copy local so the runner does not import the
 * frontend bundle at runtime. It includes the union of the observed Geography
 * and Nationality catalogs; nationality overrides are retained as aliases.
 */
export const DS160_COUNTRY_LABELS: Readonly<Record<string, readonly string[]>> = {
  "AFGH": ["AFGHANISTAN"],
  "ALB": ["ALBANIA"],
  "ALGR": ["ALGERIA"],
  "ANDO": ["ANDORRA"],
  "ANGL": ["ANGOLA"],
  "ANGU": ["ANGUILLA"],
  "ANTI": ["ANTIGUA AND BARBUDA"],
  "ARB": ["ARUBA"],
  "ARG": ["ARGENTINA"],
  "ARM": ["ARMENIA"],
  "ASMO": ["AMERICAN SAMOA"],
  "ASTL": ["AUSTRALIA"],
  "AUST": ["AUSTRIA"],
  "AZR": ["AZERBAIJAN"],
  "BAHR": ["BAHRAIN"],
  "BAMA": ["BAHAMAS"],
  "BANG": ["BANGLADESH"],
  "BELG": ["BELGIUM"],
  "BENN": ["BENIN"],
  "BERM": ["BERMUDA"],
  "BHU": ["BHUTAN"],
  "BIH": ["BOSNIA-HERZEGOVINA"],
  "BLZ": ["BELIZE"],
  "BOL": ["BOLIVIA"],
  "BON": ["BONAIRE"],
  "BOT": ["BOTSWANA"],
  "BRDO": ["BARBADOS"],
  "BRND": ["BURUNDI"],
  "BRNI": ["BRUNEI"],
  "BRVI": ["VIRGIN ISLANDS, BRITISH"],
  "BRZL": ["BRAZIL"],
  "BULG": ["BULGARIA"],
  "BURK": ["BURKINA FASO"],
  "BURM": ["BURMA"],
  "BYS": ["BELARUS"],
  "CAFR": ["CENTRAL AFRICAN REPUBLIC"],
  "CAN": ["CANADA"],
  "CAVI": ["CABO VERDE"],
  "CAYI": ["CAYMAN ISLANDS"],
  "CBDA": ["CAMBODIA"],
  "CHAD": ["CHAD"],
  "CHIL": ["CHILE"],
  "CHIN": ["CHINA"],
  "CHRI": ["CHRISTMAS ISLAND"],
  "CKIS": ["COOK ISLANDS"],
  "CMRN": ["CAMEROON"],
  "COCI": ["COCOS KEELING ISLANDS"],
  "COD": ["CONGO, DEMOCRATIC REPUBLIC OF THE"],
  "COL": ["COLOMBIA"],
  "COMO": ["COMOROS"],
  "CONB": ["CONGO, REPUBLIC OF THE"],
  "CSTR": ["COSTA RICA"],
  "CUBA": ["CUBA"],
  "CUR": ["CURACAO"],
  "CYPR": ["CYPRUS"],
  "CZEC": ["CZECH REPUBLIC"],
  "DEN": ["DENMARK"],
  "DJI": ["DJIBOUTI"],
  "DOMN": ["DOMINICA"],
  "DOMR": ["DOMINICAN REPUBLIC"],
  "ECUA": ["ECUADOR"],
  "EGN": ["EQUATORIAL GUINEA"],
  "EGYP": ["EGYPT"],
  "ELSL": ["EL SALVADOR"],
  "ERI": ["ERITREA"],
  "EST": ["ESTONIA"],
  "ETH": ["ETHIOPIA"],
  "FIJI": ["FIJI"],
  "FIN": ["FINLAND"],
  "FKLI": ["FALKLAND ISLANDS"],
  "FPOL": ["FRENCH POLYNESIA"],
  "FRAN": ["FRANCE"],
  "FRGN": ["FRENCH GUIANA"],
  "FRO": ["FAROE ISLANDS"],
  "FSAT": ["FRENCH SOUTHERN AND ANTARCTIC TERRITORIES"],
  "FSM": ["MICRONESIA"],
  "GABN": ["GABON"],
  "GAM": ["GAMBIA, THE"],
  "GEO": ["GEORGIA"],
  "GER": ["GERMANY"],
  "GHAN": ["GHANA"],
  "GIB": ["GIBRALTAR"],
  "GNEA": ["GUINEA"],
  "GRBR": ["UNITED KINGDOM"],
  "GRC": ["GREECE"],
  "GREN": ["GRENADA"],
  "GRLD": ["GREENLAND"],
  "GUAD": ["GUADELOUPE"],
  "GUAM": ["GUAM"],
  "GUAT": ["GUATEMALA"],
  "GUIB": ["GUINEA - BISSAU"],
  "GUY": ["GUYANA"],
  "HAT": ["HAITI"],
  "HMD": ["HEARD AND MCDONALD ISLANDS"],
  "HNK": ["HONG KONG","HONG KONG SAR"],
  "HOKO": ["HONG KONG BNO"],
  "HOND": ["HONDURAS"],
  "HRV": ["CROATIA"],
  "HUNG": ["HUNGARY"],
  "ICLD": ["ICELAND"],
  "IDSA": ["INDONESIA"],
  "IND": ["INDIA"],
  "IOT": ["BRITISH INDIAN OCEAN TERRITORY"],
  "IRAN": ["IRAN"],
  "IRAQ": ["IRAQ"],
  "IRE": ["IRELAND"],
  "ISRL": ["ISRAEL"],
  "ITLY": ["ITALY"],
  "IVCO": ["COTE D`IVOIRE"],
  "JAM": ["JAMAICA"],
  "JORD": ["JORDAN"],
  "JPN": ["JAPAN"],
  "JRSM": ["JERUSALEM"],
  "KAZ": ["KAZAKHSTAN"],
  "KENY": ["KENYA"],
  "KGZ": ["KYRGYZSTAN"],
  "KIRI": ["KIRIBATI"],
  "KOR": ["KOREA, REPUBLIC OF (SOUTH)"],
  "KSV": ["KOSOVO"],
  "KUWT": ["KUWAIT"],
  "LAOS": ["LAOS"],
  "LATV": ["LATVIA"],
  "LBYA": ["LIBYA"],
  "LCHT": ["LIECHTENSTEIN"],
  "LEBN": ["LEBANON"],
  "LES": ["LESOTHO"],
  "LIBR": ["LIBERIA"],
  "LITH": ["LITHUANIA"],
  "LXM": ["LUXEMBOURG"],
  "MAC": ["MACAU"],
  "MADG": ["MADAGASCAR"],
  "MAF": ["SAINT MARTIN"],
  "MALI": ["MALI"],
  "MALW": ["MALAWI"],
  "MART": ["MARTINIQUE"],
  "MAUR": ["MAURITANIA"],
  "MDWI": ["MIDWAY ISLANDS"],
  "MEX": ["MEXICO"],
  "MKD": ["MACEDONIA, NORTH"],
  "MLAS": ["MALAYSIA"],
  "MLD": ["MOLDOVA"],
  "MLDI": ["MALDEN ISLAND"],
  "MLDV": ["MALDIVES"],
  "MLTA": ["MALTA"],
  "MNP": ["NORTH MARIANA ISLANDS"],
  "MON": ["MONACO"],
  "MONG": ["MONGOLIA"],
  "MONT": ["MONTSERRAT"],
  "MORO": ["MOROCCO"],
  "MOZ": ["MOZAMBIQUE"],
  "MRTS": ["MAURITIUS"],
  "MTG": ["MONTENEGRO"],
  "MYT": ["MAYOTTE"],
  "NAMB": ["NAMIBIA"],
  "NAU": ["NAURU"],
  "NCAL": ["NEW CALEDONIA"],
  "NEP": ["NEPAL"],
  "NETH": ["NETHERLANDS"],
  "NFK": ["NORFOLK ISLAND"],
  "NIC": ["NICARAGUA"],
  "NIR": ["NIGER"],
  "NIRE": ["NORTHERN IRELAND"],
  "NIUE": ["NIUE"],
  "NORW": ["NORWAY"],
  "NRA": ["NIGERIA"],
  "NZLD": ["NEW ZEALAND"],
  "OMAN": ["OMAN"],
  "PAL": ["PALESTINIAN AUTHORITY"],
  "PALA": ["PALAU"],
  "PAN": ["PANAMA"],
  "PARA": ["PARAGUAY"],
  "PERU": ["PERU"],
  "PHIL": ["PHILIPPINES"],
  "PITC": ["PITCAIRN ISLANDS"],
  "PKST": ["PAKISTAN"],
  "PLMR": ["PALMYRA ATOLL"],
  "PNG": ["PAPUA NEW GUINEA"],
  "POL": ["POLAND"],
  "PORT": ["PORTUGAL"],
  "PR": ["PUERTO RICO"],
  "PRK": ["KOREA, DEMOCRATIC REPUBLIC OF (NORTH)"],
  "QTAR": ["QATAR"],
  "REUN": ["REUNION"],
  "RMI": ["MARSHALL ISLANDS"],
  "ROM": ["ROMANIA"],
  "RUS": ["RUSSIA"],
  "RWND": ["RWANDA"],
  "SABA": ["SABA ISLAND"],
  "SAFR": ["SOUTH AFRICA"],
  "SARB": ["SAUDI ARABIA"],
  "SBA": ["SERBIA"],
  "SENG": ["SENEGAL"],
  "SEYC": ["SEYCHELLES"],
  "SGS": ["SOUTH GEORGIA AND THE SOUTH SANDWICH ISLAND"],
  "SHEL": ["ST. HELENA"],
  "SING": ["SINGAPORE"],
  "SJM": ["SVALBARD"],
  "SLCA": ["ST. LUCIA"],
  "SLEO": ["SIERRA LEONE"],
  "SLMN": ["SOLOMON ISLANDS"],
  "SMAR": ["SAN MARINO"],
  "SOMA": ["SOMALIA"],
  "SPMI": ["ST. PIERRE AND MIQUELON"],
  "SPN": ["SPAIN"],
  "SRL": ["SRI LANKA"],
  "SSAH": ["WESTERN SAHARA"],
  "SSDN": ["SOUTH SUDAN"],
  "STCN": ["ST. KITTS AND NEVIS"],
  "STEU": ["ST. EUSTATIUS"],
  "STM": ["SINT MAARTEN"],
  "STPR": ["SAO TOME AND PRINCIPE"],
  "STVN": ["ST. VINCENT AND THE GRENADINES"],
  "SUDA": ["SUDAN"],
  "SURM": ["SURINAME"],
  "SVK": ["SLOVAKIA"],
  "SVN": ["SLOVENIA"],
  "SWDN": ["SWEDEN"],
  "SWTZ": ["SWITZERLAND"],
  "SYR": ["SYRIA"],
  "SZLD": ["ESWATINI"],
  "TAZN": ["TANZANIA"],
  "TCIS": ["TURKS AND CAICOS ISLANDS"],
  "THAI": ["THAILAND"],
  "TJK": ["TAJIKISTAN"],
  "TKL": ["TOKELAU"],
  "TKM": ["TURKMENISTAN"],
  "TMOR": ["TIMOR-LESTE"],
  "TNSA": ["TUNISIA"],
  "TOGO": ["TOGO"],
  "TONG": ["TONGA"],
  "TRIN": ["TRINIDAD AND TOBAGO"],
  "TRKY": ["TURKEY"],
  "TUV": ["TUVALU"],
  "TWAN": ["TAIWAN"],
  "UAE": ["UNITED ARAB EMIRATES"],
  "UGAN": ["UGANDA"],
  "UKR": ["UKRAINE"],
  "URU": ["URUGUAY"],
  "USA": ["UNITED STATES OF AMERICA"],
  "UZB": ["UZBEKISTAN"],
  "VANU": ["VANUATU"],
  "VAT": ["HOLY SEE (VATICAN CITY)"],
  "VENZ": ["VENEZUELA"],
  "VI": ["VIRGIN ISLANDS (U.S.)"],
  "VTNM": ["VIETNAM"],
  "WAFT": ["WALLIS AND FUTUNA ISLANDS"],
  "WKI": ["WAKE ISLAND"],
  "WSAM": ["SAMOA"],
  "XGZ": ["GAZA STRIP"],
  "XHI": ["HOWLAND ISLAND"],
  "XWB": ["WEST BANK"],
  "XXX": ["STATELESS"],
  "YEM": ["YEMEN"],
  "ZAMB": ["ZAMBIA"],
  "ZIMB": ["ZIMBABWE"],
};

