import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

import { resolveKvacCenter, type KvacRoutingInput } from "./kvac-routing";

export type KoreaAnswerMap = Record<string, string | null | undefined>;

interface RenderOptions {
  routing?: KvacRoutingInput;
}

export type Annex17RequiredField =
  | "family_name"
  | "given_names"
  | "date_of_birth"
  | "sex"
  | "nationality"
  | "passport_number"
  | "passport_issue_date"
  | "passport_expiry_date"
  | "email_address"
  | "mobile_phone"
  | "purpose_of_visit"
  | "intended_date_of_entry"
  | "intended_period_of_stay"
  | "address_in_korea";

const REQUIRED_FIELDS: ReadonlyArray<readonly [string, readonly string[]]> = [
  ["family_name", ["family_name", "surname", "last_name"]],
  ["given_names", ["given_names", "given_name", "first_name"]],
  ["date_of_birth", ["date_of_birth", "dob"]],
  ["sex", ["sex", "gender"]],
  ["nationality", ["nationality"]],
  ["passport_number", ["passport_number"]],
  ["passport_issue_date", ["passport_issue_date"]],
  ["passport_expiry_date", ["passport_expiry_date", "passport_expiration_date"]],
  ["email_address", ["email_address", "email"]],
  ["mobile_phone", ["mobile_phone", "mobile_number", "telephone_number"]],
  ["purpose_of_visit", ["purpose_of_visit"]],
  ["intended_date_of_entry", ["intended_date_of_entry", "arrival_date"]],
  ["intended_period_of_stay", ["intended_period_of_stay", "intended_length_of_stay"]],
  ["address_in_korea", ["address_in_korea", "accommodation_address"]],
];

const FIELD_ORDER = [
  ["Full name", ["family_name", "surname", "last_name"], ["given_names", "given_name", "first_name"]],
  ["Date of birth", ["date_of_birth", "dob"]],
  ["Sex", ["sex", "gender"]],
  ["Nationality", ["nationality"]],
  ["Passport number", ["passport_number"]],
  ["Passport issue / expiry", ["passport_issue_date"], ["passport_expiry_date"]],
  ["Email", ["email_address", "email"]],
  ["Mobile phone", ["mobile_phone", "mobile_number", "telephone_number"]],
  ["Purpose of visit", ["purpose_of_visit"]],
  ["Intended entry date", ["intended_date_of_entry", "arrival_date"]],
  ["Intended stay", ["intended_period_of_stay", "intended_length_of_stay"]],
  ["Address in Korea", ["address_in_korea", "accommodation_address"]],
  ["Inviter", ["inviter_name", "inviter_full_name"]],
] as const;

function answer(answers: KoreaAnswerMap, keys: readonly string[]): string {
  for (const key of keys) {
    const value = answers[key]?.toString().trim();
    if (value) return value;
  }
  return "";
}

function sanitize(value: string): string {
  const replacements: Record<string, string> = {
    "，": ",",
    "。": ".",
    "“": "\"",
    "”": "\"",
    "‘": "'",
    "’": "'",
    "（": "(",
    "）": ")",
    "—": "-",
    "–": "-",
    "—": "-",
    "…": "...",
  };
  let output = "";
  for (const ch of value) {
    if (replacements[ch]) {
      output += replacements[ch];
      continue;
    }
    const cp = ch.codePointAt(0) ?? 0;
    output += cp <= 0x7e && cp >= 0x20 ? ch : "?";
  }
  return output;
}

export function validateAnnex17Answers(answers: KoreaAnswerMap): Annex17RequiredField[] {
  const missing: Annex17RequiredField[] = [];
  for (const [canonical, aliases] of REQUIRED_FIELDS) {
    if (answer(answers, aliases) === "") {
      missing.push(canonical as Annex17RequiredField);
    }
  }
  return missing;
}

export async function renderKoreaC39Annex17(
  answers: KoreaAnswerMap,
  options: RenderOptions = {},
): Promise<Uint8Array> {
  const missingFields = validateAnnex17Answers(answers);
  if (missingFields.length > 0) {
    const normalized = missingFields.join(", ");
    throw new Error(`Missing required Korea Annex-17 fields: ${normalized}`);
  }

  const pdf = await PDFDocument.create();
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const routing = resolveKvacCenter(options.routing ?? {});

  for (let pageIndex = 0; pageIndex < 5; pageIndex += 1) {
    const page = pdf.addPage([595.28, 841.89]);
    const { width, height } = page.getSize();
    page.drawText("VISA APPLICATION FORM / Annex 17", {
      x: 42,
      y: height - 54,
      size: 16,
      font: bold,
      color: rgb(0.08, 0.08, 0.08),
    });
    page.drawText("Korea C-3-9 Short-Term Visit - generated by VIZA from applicant answers", {
      x: 42,
      y: height - 76,
      size: 9,
      font,
      color: rgb(0.28, 0.28, 0.28),
    });
    page.drawText(`Page ${pageIndex + 1} of 5`, {
      x: width - 96,
      y: height - 54,
      size: 9,
      font,
      color: rgb(0.28, 0.28, 0.28),
    });

    if (pageIndex === 0) {
      let y = height - 118;
      page.drawText("1. Applicant Information", { x: 42, y, size: 12, font: bold });
      y -= 26;
      for (const [label, first, second] of FIELD_ORDER) {
        const value = second
          ? [answer(answers, first), answer(answers, second)].filter(Boolean).join(" ")
          : answer(answers, first);
        page.drawText(label, { x: 50, y, size: 9, font: bold });
        page.drawRectangle({ x: 180, y: y - 4, width: 330, height: 16, borderColor: rgb(0.7, 0.7, 0.7), borderWidth: 0.5 });
        page.drawText(sanitize(value || " "), { x: 186, y, size: 9, font });
        y -= 24;
      }
    } else if (pageIndex === 1) {
      page.drawText("2. Visa Category", { x: 42, y: height - 118, size: 12, font: bold });
      page.drawText("Period of Stay: Short-term", { x: 50, y: height - 148, size: 10, font });
      page.drawText("Status of Stay: C-3-9", { x: 50, y: height - 170, size: 10, font });
      page.drawText("Purpose: Short-term general visit", { x: 50, y: height - 192, size: 10, font });
    } else if (pageIndex === 2) {
      page.drawText("3. KVAC Routing", { x: 42, y: height - 118, size: 12, font: bold });
      page.drawText(`Recommended center: ${routing.recommended.nameEn}`, { x: 50, y: height - 148, size: 10, font });
      page.drawText(`Booking URL: ${routing.recommended.bookingUrl}`, { x: 50, y: height - 170, size: 9, font });
      page.drawText(`Routing basis: ${routing.basis}`, { x: 50, y: height - 192, size: 10, font });
    } else if (pageIndex === 3) {
      page.drawText("4. Declaration", { x: 42, y: height - 118, size: 12, font: bold });
      page.drawText("Applicant must review, print, attach photo, and sign before KVAC intake.", {
        x: 50,
        y: height - 148,
        size: 10,
        font,
      });
      page.drawText("Signature: ____________________________     Date: __________________", {
        x: 50,
        y: height - 212,
        size: 10,
        font,
      });
    } else {
      page.drawText("5. VIZA Submission Notes", { x: 42, y: height - 118, size: 12, font: bold });
      page.drawText("Photo and supporting documents remain separate uploads/checklist items.", {
        x: 50,
        y: height - 148,
        size: 10,
        font,
      });
    }
  }

  return pdf.save();
}
