#!/usr/bin/env bash
set -euo pipefail

# Applies the JSON generated by agent-backend/scripts/autoscale-runners.ts.
# Machines are stopped, rather than destroyed, at desired=0 so the next
# queue-depth tick can start them again without requiring a deploy.
decisions="${1:?path to autoscaler decisions JSON is required}"
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
countries="$root/deploy/fly/countries.json"

can_stop_safely() {
  local app="$1"
  if [[ "$app" != "viza-submission-legacy" && "$app" != "viza-runner-south-korea" ]]; then
    return 0
  fi

  local status
  for check in 1 2; do
    status="$(curl --location --silent --show-error --max-time 15 \
      --output /dev/null --write-out '%{http_code}' \
      "https://${app}.fly.dev/deploy-ready" || true)"
    if [[ "$status" != "200" ]]; then
      echo "[autoscale] app=$app remains running; deploy readiness returned HTTP ${status:-unavailable}"
      return 1
    fi
    if [[ "$check" -eq 1 ]]; then sleep 5; fi
  done
  return 0
}

jq -c '.[]' "$decisions" | while read -r decision; do
  kind="$(jq -r '.kind // "country"' <<<"$decision")"
  desired="$(jq -r '.desired' <<<"$decision")"
  if [[ "$kind" == "legacy" ]]; then
    app="$(jq -r '.app' <<<"$decision")"
    paused="false"
  else
    country="$(jq -r '.country' <<<"$decision")"
    if ! jq -e --arg country "$country" '.countries | index($country)' "$countries" >/dev/null; then
      echo "[autoscale] ignoring unmapped country=$country"
      continue
    fi
    paused="$(jq -r '.paused' <<<"$decision")"
    app_country="${country//_/-}"
    app="viza-runner-$app_country"
  fi
  echo "[autoscale] app=$app desired=$desired paused=$paused"
  machines="$(fly machine list --app "$app" --json)"
  total="$(jq 'length' <<<"$machines")"

  if [[ "$total" -eq 0 ]]; then
    echo "[autoscale] app=$app has no Machines; redeploy it before autoscaling" >&2
    continue
  fi

  if [[ "$desired" -gt "$total" ]]; then
    fly scale count "$desired" --app "$app" --yes
    machines="$(fly machine list --app "$app" --json)"
  fi

  mapfile -t started_ids < <(
    jq -r '.[] | select(.state == "started" or .state == "starting") | .id' \
      <<<"$machines"
  )
  started="${#started_ids[@]}"

  if [[ "$started" -gt "$desired" ]]; then
    if [[ "$desired" -eq 0 ]] && ! can_stop_safely "$app"; then
      continue
    fi
    for ((i = desired; i < started; i++)); do
      fly machine stop "${started_ids[$i]}" --app "$app"
    done
  elif [[ "$started" -lt "$desired" ]]; then
    needed=$((desired - started))
    mapfile -t stopped_ids < <(
      jq -r '.[] | select(.state == "stopped" or .state == "suspended") | .id' \
        <<<"$machines"
    )
    if [[ "${#stopped_ids[@]}" -lt "$needed" ]]; then
      echo "[autoscale] app=$app cannot start $needed Machine(s); only ${#stopped_ids[@]} are stopped" >&2
      exit 1
    fi
    for ((i = 0; i < needed; i++)); do
      fly machine start "${stopped_ids[$i]}" --app "$app"
    done
  fi
done
