#!/usr/bin/env bash
set -euo pipefail

# Applies the JSON generated by agent-backend/scripts/autoscale-runners.ts.
# Non-paused country workers always keep one warm machine to receive new jobs.
decisions="${1:?path to autoscaler decisions JSON is required}"
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
countries="$root/deploy/fly/countries.json"

jq -c '.[]' "$decisions" | while read -r decision; do
  country="$(jq -r '.country' <<<"$decision")"
  if ! jq -e --arg country "$country" '.countries | index($country)' "$countries" >/dev/null; then
    echo "[autoscale] ignoring unmapped country=$country"
    continue
  fi
  paused="$(jq -r '.paused' <<<"$decision")"
  desired="$(jq -r '.desired' <<<"$decision")"
  if [[ "$paused" != "true" && "$desired" -lt 1 ]]; then desired=1; fi
  app_country="${country//_/-}"
  echo "[autoscale] app=viza-runner-$app_country desired=$desired paused=$paused"
  fly scale count "$desired" --app "viza-runner-$app_country" --yes
done
