export const SGAC_HOTEL_NAMES = [
  "MARINA BAY SANDS",
  "RAFFLES HOTEL SINGAPORE",
  "THE FULLERTON HOTEL SINGAPORE",
  "MANDARIN ORIENTAL, SINGAPORE",
  "PAN PACIFIC SINGAPORE",
  "SWISSOTEL THE STAMFORD",
  "CARLTON HOTEL SINGAPORE",
  "PARKROYAL COLLECTION MARINA BAY, SINGAPORE",
  "YOTEL SINGAPORE ORCHARD ROAD",
  "HOTEL BOSS",
  "V HOTEL LAVENDER",
  "FURAMA RIVERFRONT",
  "ORCHARD HOTEL SINGAPORE",
  "MERCURE SINGAPORE BUGIS",
  "IBIS SINGAPORE ON BENCOOLEN",
] as const;

const NORMALIZED_HOTEL_NAMES = new Map(
  SGAC_HOTEL_NAMES.map((name) => [name.trim().toUpperCase(), name]),
);

export function normalizeSgacHotelName(value: string): string | null {
  return NORMALIZED_HOTEL_NAMES.get(value.trim().toUpperCase()) ?? null;
}
