/**
 * Selector promotion pipeline (BOT-002).
 *
 * Reads the latest `recon-out/<YYYY-MM-DD>/<country>/selectors.json`
 * (FieldCapture[] from BOT-001) and regenerates each per-country
 * `src/<cc>/selectors.generated.ts` so runners pick up freshly
 * harvested selectors without hand-editing. Prints an added /
 * changed / removed diff against the previous generated file.
 *
 * Run:
 *   cd viza-be/submission-service
 *   npx ts-node scripts/promote-selectors.ts
 *
 * Env knobs:
 *   PROMOTE_DATE   override the date bucket (default: latest)
 *   PROMOTE_DRY    "1" to print the diff but skip writing the file
 */

import * as fs from "node:fs/promises";
import * as path from "node:path";

interface FieldCapture {
  page: string;
  index: number;
  field_id?: string;
  field_name?: string;
  label: string;
  field_type: string;
  required: boolean;
}

interface PromotionRoster {
  code: string;
  outSubdir: string;
  varName: string;
  generatedFile: string;
}

const ROSTER: PromotionRoster[] = [
  { code: "kh", outSubdir: "kh", varName: "GENERATED_KH_SELECTORS", generatedFile: "src/kh/selectors.generated.ts" },
  { code: "la", outSubdir: "la", varName: "GENERATED_LA_SELECTORS", generatedFile: "src/la/selectors.generated.ts" },
  { code: "lk", outSubdir: "lk", varName: "GENERATED_LK_SELECTORS", generatedFile: "src/lk/selectors.generated.ts" },
  { code: "za", outSubdir: "za", varName: "GENERATED_ZA_SELECTORS", generatedFile: "src/za/selectors.generated.ts" },
  { code: "in", outSubdir: "in", varName: "GENERATED_IN_SELECTORS", generatedFile: "src/in/selectors.generated.ts" },
];

async function findLatestBucket(reconRoot: string, override: string | null): Promise<string | null> {
  if (override) {
    const p = path.join(reconRoot, override);
    try {
      await fs.stat(p);
      return p;
    } catch {
      return null;
    }
  }
  let entries: string[] = [];
  try {
    entries = await fs.readdir(reconRoot);
  } catch {
    return null;
  }
  const dated = entries.filter((e) => /^\d{4}-\d{2}-\d{2}$/.test(e)).sort();
  if (dated.length === 0) return null;
  return path.join(reconRoot, dated[dated.length - 1]);
}

function selectorFor(field: FieldCapture): string | null {
  if (field.field_name) {
    const tag = field.field_type === "select" || field.field_type === "textarea" ? field.field_type : "input";
    return `${tag}[name="${field.field_name}"]`;
  }
  if (field.field_id) {
    return `#${field.field_id}`;
  }
  return null;
}

function keyFor(field: FieldCapture): string | null {
  const raw = field.field_name || field.field_id || field.label;
  if (!raw) return null;
  return raw
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 64);
}

function buildSelectorMap(fields: FieldCapture[]): Record<string, string> {
  const out: Record<string, string> = {};
  for (const f of fields) {
    if (f.field_type === "button") continue;
    const k = keyFor(f);
    const sel = selectorFor(f);
    if (!k || !sel || k in out) continue;
    out[k] = sel;
  }
  return out;
}

interface DiffEntry {
  added: string[];
  changed: Array<{ key: string; from: string; to: string }>;
  removed: string[];
}

function diffMaps(prev: Record<string, string>, next: Record<string, string>): DiffEntry {
  const added: string[] = [];
  const changed: Array<{ key: string; from: string; to: string }> = [];
  const removed: string[] = [];
  for (const k of Object.keys(next)) {
    if (!(k in prev)) added.push(k);
    else if (prev[k] !== next[k]) changed.push({ key: k, from: prev[k], to: next[k] });
  }
  for (const k of Object.keys(prev)) {
    if (!(k in next)) removed.push(k);
  }
  return { added, changed, removed };
}

async function readPrevGenerated(filePath: string, varName: string): Promise<Record<string, string>> {
  let raw: string;
  try {
    raw = await fs.readFile(filePath, "utf8");
  } catch {
    return {};
  }
  const m = raw.match(new RegExp(`${varName}\\s*:\\s*Record<string,\\s*string>\\s*=\\s*({[\\s\\S]*?});`));
  if (!m) return {};
  try {
    // Body uses single-quoted strings — convert to JSON-safe parse via Function.
    // Safe because file is repo-controlled and only ever read at dev time.
    // eslint-disable-next-line @typescript-eslint/no-implied-eval
    const parsed = Function(`"use strict";return (${m[1]});`)() as Record<string, string>;
    return parsed && typeof parsed === "object" ? parsed : {};
  } catch {
    return {};
  }
}

function renderGenerated(varName: string, map: Record<string, string>): string {
  const lines = Object.keys(map)
    .sort()
    .map((k) => `  ${JSON.stringify(k)}: ${JSON.stringify(map[k])},`);
  const body = lines.length === 0 ? "{}" : `{\n${lines.join("\n")}\n}`;
  return `/* @generated by scripts/promote-selectors.ts — do not hand-edit */\nexport const ${varName}: Record<string, string> = ${body};\n`;
}

async function main(): Promise<void> {
  const cwd = path.resolve(__dirname, "..");
  const reconRoot = path.join(cwd, "recon-out");
  const override = process.env.PROMOTE_DATE || null;
  const dryRun = process.env.PROMOTE_DRY === "1";

  const bucket = await findLatestBucket(reconRoot, override);
  if (!bucket) {
    console.log(`[promote-selectors] no recon bucket found under ${reconRoot} — run \`npm run recon:parallel\` first`);
    return;
  }
  console.log(`[promote-selectors] bucket=${bucket} dryRun=${dryRun}`);

  let countriesPromoted = 0;
  let countriesSkipped = 0;
  for (const entry of ROSTER) {
    const sourcePath = path.join(bucket, entry.outSubdir, "selectors.json");
    let fields: FieldCapture[];
    try {
      const raw = await fs.readFile(sourcePath, "utf8");
      fields = JSON.parse(raw) as FieldCapture[];
    } catch {
      console.log(`[${entry.code}] skipped — no selectors.json at ${sourcePath}`);
      countriesSkipped += 1;
      continue;
    }

    const nextMap = buildSelectorMap(fields);
    const generatedPath = path.join(cwd, entry.generatedFile);
    const prevMap = await readPrevGenerated(generatedPath, entry.varName);
    const diff = diffMaps(prevMap, nextMap);

    console.log(
      `[${entry.code}] +${diff.added.length}/~${diff.changed.length}/-${diff.removed.length} (next=${Object.keys(nextMap).length})`,
    );
    for (const k of diff.added) console.log(`  + ${k} → ${nextMap[k]}`);
    for (const c of diff.changed) console.log(`  ~ ${c.key}: ${c.from} → ${c.to}`);
    for (const k of diff.removed) console.log(`  - ${k} (was ${prevMap[k]})`);

    if (!dryRun) {
      await fs.writeFile(generatedPath, renderGenerated(entry.varName, nextMap), "utf8");
    }
    countriesPromoted += 1;
  }

  console.log(
    `\n[promote-selectors] done — promoted=${countriesPromoted} skipped=${countriesSkipped} (run typecheck before committing)`,
  );
}

main().catch((err) => {
  console.error(
    "[promote-selectors] fatal:",
    err instanceof Error ? err.message : String(err),
  );
  process.exit(1);
});
