import type { SeedFormField } from "../bilingual-seed-row";

export const TW_OVERSEAS_CN_TOURISM_ENTRY_PERMIT = "TW_OVERSEAS_CN_TOURISM_ENTRY_PERMIT";

const option = (value: string, labelZh: string, labelEn: string) => ({ value, label_zh: labelZh, label_en: labelEn });
const rules = (labelZh: string, extra: Record<string, unknown> = {}) => ({ label_zh: labelZh, official: true, ...extra });
const showIf = (condition: string) => ({ condition });

export const TW_ENTRY_PERMIT_FORM_FIELDS: SeedFormField[] = [
  { field_name: "eligibility_route", label: "Singapore eligibility route", field_type: "radio", required: true, step_number: 1, step_name: "Eligibility", display_order: 1, options: [option("student", "新加坡留学生", "Student in Singapore"), option("permanent_resident", "新加坡永久居民", "Singapore permanent resident"), option("work_one_year", "在新加坡居住满一年并有工作证明", "Resident in Singapore for one year with work proof"), option("dependent_with_funds", "依亲居留并具财力证明", "Dependent resident with financial proof"), option("accompanying_family", "随行配偶或二亲等内亲属", "Accompanying spouse or relative within second degree")], validation_rules: rules("新加坡申请资格路径") },
  { field_name: "permit_type", label: "Entry permit type", field_type: "radio", required: true, step_number: 1, step_name: "Eligibility", display_order: 2, options: [option("single", "单次入出境许可（NT$600）", "Single entry permit (NT$600)"), option("one_year_multiple", "一年多次入出境许可（NT$1,000）", "One-year multiple entry permit (NT$1,000)")], validation_rules: rules("申请许可种类") },
  { field_name: "singapore_residence_pass_number", label: "Singapore residence pass number", field_type: "text", required: true, step_number: 1, step_name: "Eligibility", display_order: 3, validation_rules: rules("新加坡居留准证号码", { maxLength: 40 }) },
  { field_name: "singapore_residence_expiry_date", label: "Singapore residence pass expiry date", field_type: "date", required: true, step_number: 1, step_name: "Eligibility", display_order: 4, validation_rules: rules("新加坡居留准证有效期", { format: "YYYY-MM-DD" }) },
  { field_name: "dependent_savings_twd", label: "Savings amount (TWD equivalent)", field_type: "text", required: true, step_number: 1, step_name: "Eligibility", display_order: 5, conditional_logic: showIf("eligibility_route === dependent_with_funds"), validation_rules: rules("依亲居留者最近一个月存款金额（新台币等值至少 100,000）", { pattern: "^[0-9]+(?:\\.[0-9]{1,2})?$", minimum: 100000 }) },
  { field_name: "relationship_to_primary_applicant", label: "Relationship to primary applicant", field_type: "text", required: true, step_number: 1, step_name: "Eligibility", display_order: 6, conditional_logic: showIf("eligibility_route === accompanying_family"), validation_rules: rules("与主要申请人的关系") },
  { field_name: "primary_applicant_name", label: "Primary applicant full name", field_type: "text", required: true, step_number: 1, step_name: "Eligibility", display_order: 7, conditional_logic: showIf("eligibility_route === accompanying_family"), validation_rules: rules("主要申请人姓名") },

  { field_name: "surname", label: "Surname", field_type: "text", required: true, step_number: 2, step_name: "Passport and Identity", display_order: 1, validation_rules: rules("姓（须与护照一致）") },
  { field_name: "given_names", label: "Given names", field_type: "text", required: true, step_number: 2, step_name: "Passport and Identity", display_order: 2, validation_rules: rules("名（须与护照一致）") },
  { field_name: "chinese_name", label: "Chinese name", field_type: "text", required: true, step_number: 2, step_name: "Passport and Identity", display_order: 3, validation_rules: rules("中文姓名（请用正体字）") },
  { field_name: "date_of_birth", label: "Date of birth", field_type: "date", required: true, step_number: 2, step_name: "Passport and Identity", display_order: 4, validation_rules: rules("出生日期", { format: "YYYY-MM-DD" }) },
  { field_name: "gender", label: "Gender", field_type: "radio", required: true, step_number: 2, step_name: "Passport and Identity", display_order: 5, options: [option("male", "男", "Male"), option("female", "女", "Female")], validation_rules: rules("性别") },
  { field_name: "place_of_birth", label: "Place of birth", field_type: "text", required: true, step_number: 2, step_name: "Passport and Identity", display_order: 6, validation_rules: rules("出生地（与护照一致）") },
  { field_name: "passport_number", label: "Mainland passport number", field_type: "text", required: true, step_number: 2, step_name: "Passport and Identity", display_order: 7, validation_rules: rules("中国大陆护照号码", { maxLength: 20 }) },
  { field_name: "passport_issue_date", label: "Passport issue date", field_type: "date", required: true, step_number: 2, step_name: "Passport and Identity", display_order: 8, validation_rules: rules("护照签发日期", { format: "YYYY-MM-DD" }) },
  { field_name: "passport_expiry_date", label: "Passport expiry date", field_type: "date", required: true, step_number: 2, step_name: "Passport and Identity", display_order: 9, validation_rules: rules("护照有效期（须至少剩余六个月）", { format: "YYYY-MM-DD", minimum_months_from_submission: 6 }) },

  { field_name: "real_email_address", label: "Applicant contact email", field_type: "text", required: true, step_number: 3, step_name: "Contact and Travel", display_order: 1, validation_rules: rules("申请人联系邮箱（不会提交大陆邮箱至官网）", { pattern: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$" }) },
  { field_name: "phone_country_code", label: "Phone country code", field_type: "text", required: true, step_number: 3, step_name: "Contact and Travel", display_order: 2, placeholder: "+65", validation_rules: rules("电话国家/地区代码", { pattern: "^\\+[0-9]{1,4}$" }) },
  { field_name: "phone_number", label: "Phone number", field_type: "text", required: true, step_number: 3, step_name: "Contact and Travel", display_order: 3, validation_rules: rules("电话号码", { pattern: "^[0-9]{6,15}$" }) },
  { field_name: "singapore_residential_address", label: "Singapore residential address", field_type: "textarea", required: true, step_number: 3, step_name: "Contact and Travel", display_order: 4, validation_rules: rules("新加坡住址", { maxLength: 240 }) },
  { field_name: "intended_arrival_date", label: "Intended arrival date", field_type: "date", required: true, step_number: 3, step_name: "Contact and Travel", display_order: 5, validation_rules: rules("预计抵达台湾日期", { format: "YYYY-MM-DD" }) },
  { field_name: "intended_departure_date", label: "Intended departure date", field_type: "date", required: true, step_number: 3, step_name: "Contact and Travel", display_order: 6, validation_rules: rules("预计离开台湾日期", { format: "YYYY-MM-DD", after: "intended_arrival_date" }) },
  { field_name: "taiwan_accommodation_address", label: "Taiwan accommodation address", field_type: "textarea", required: true, step_number: 3, step_name: "Contact and Travel", display_order: 7, validation_rules: rules("台湾住宿地址", { maxLength: 240 }) },

  { field_name: "passport_bio_page", label: "Mainland passport bio page", field_type: "file", required: true, step_number: 4, step_name: "Official Documents", display_order: 1, validation_rules: rules("中国大陆护照资料页", { accepted_file_types: ["image/jpeg", "image/png", "application/pdf"], max_size_mb: 5 }) },
  { field_name: "recent_white_background_photo", label: "Recent white-background photo", field_type: "file", required: true, step_number: 4, step_name: "Official Documents", display_order: 2, validation_rules: rules("两年内二寸白底彩色照片", { accepted_file_types: ["image/jpeg", "image/png"], max_size_mb: 5, max_age_years: 2 }) },
  { field_name: "singapore_residence_proof", label: "Singapore residence proof", field_type: "file", required: true, step_number: 4, step_name: "Official Documents", display_order: 3, validation_rules: rules("新加坡居留/准证证明", { accepted_file_types: ["image/jpeg", "image/png", "application/pdf"], max_size_mb: 5 }) },
  { field_name: "student_proof", label: "Current student proof", field_type: "file", required: true, step_number: 4, step_name: "Official Documents", display_order: 4, conditional_logic: showIf("eligibility_route === student"), validation_rules: rules("有效学生证或三个月内在学证明", { accepted_file_types: ["image/jpeg", "image/png", "application/pdf"], max_size_mb: 5 }) },
  { field_name: "permanent_residence_proof", label: "Singapore permanent residence proof", field_type: "file", required: true, step_number: 4, step_name: "Official Documents", display_order: 5, conditional_logic: showIf("eligibility_route === permanent_resident"), validation_rules: rules("新加坡永久居留权证明", { accepted_file_types: ["image/jpeg", "image/png", "application/pdf"], max_size_mb: 5 }) },
  { field_name: "work_proof", label: "Singapore work proof", field_type: "file", required: true, step_number: 4, step_name: "Official Documents", display_order: 6, conditional_logic: showIf("eligibility_route === work_one_year"), validation_rules: rules("新加坡工作证明及最近一年旅居证明", { accepted_file_types: ["image/jpeg", "image/png", "application/pdf"], max_size_mb: 5 }) },
  { field_name: "dependent_residence_proof", label: "Dependent residence proof", field_type: "file", required: true, step_number: 4, step_name: "Official Documents", display_order: 7, conditional_logic: showIf("eligibility_route === dependent_with_funds"), validation_rules: rules("依亲居留证明", { accepted_file_types: ["image/jpeg", "image/png", "application/pdf"], max_size_mb: 5 }) },
  { field_name: "recent_bank_proof", label: "Recent bank proof", field_type: "file", required: true, step_number: 4, step_name: "Official Documents", display_order: 8, conditional_logic: showIf("eligibility_route === dependent_with_funds"), validation_rules: rules("最近一个月、等值新台币十万元以上存款证明", { accepted_file_types: ["image/jpeg", "image/png", "application/pdf"], max_size_mb: 5 }) },
  { field_name: "relationship_proof", label: "Relationship proof", field_type: "file", required: true, step_number: 4, step_name: "Official Documents", display_order: 9, conditional_logic: showIf("eligibility_route === accompanying_family"), validation_rules: rules("与主要申请人的亲属关系证明", { accepted_file_types: ["image/jpeg", "image/png", "application/pdf"], max_size_mb: 5 }) },
  { field_name: "official_declaration", label: "Official declaration", field_type: "checkbox", required: true, step_number: 5, step_name: "Declaration", display_order: 1, validation_rules: rules("我确认资料真实，授权 VIZA 使用专属邮箱向移民署送件及接收通知") },
];
