/**
 * Vietnam e-Visa official nationality/country option text.
 * Source: official portal API client-service/public/dm-qt/get-all?type=
 * captured from evisa.gov.vn. Keep maQT as the key and tenQTEn as the
 * selectable Ant Design display value.
 */
export const VN_COUNTRY_NAME_BY_ALPHA3: Record<string, string> = {
  "AFG": "Afghanistan",
  "ALB": "Albania",
  "DZA": "Algeria",
  "AND": "Andorra",
  "AGO": "Angola",
  "ATG": "Antigua and Barbuda",
  "ARG": "Argentina",
  "ARM": "Armenia",
  "AUS": "Australia",
  "AUT": "Austria",
  "AZE": "Azerbaijan",
  "BHS": "Bahamas",
  "BHR": "Bahrain",
  "BGD": "Bangladesh",
  "BRB": "Barbados",
  "BLR": "Belarus",
  "BEL": "Belgium",
  "BLZ": "Belize",
  "BEN": "Benin",
  "BMU": "Bermuda",
  "BTN": "Bhutan",
  "BOL": "Bolivia",
  "BIH": "Bosnia and Herzegovina",
  "BWA": "Botswana",
  "BRA": "Brazil",
  "IOT": "British India Ocean Territory",
  "BRN": "Bruney",
  "BGR": "Bulgaria",
  "BFA": "Burkina Faso",
  "BDI": "Burundi",
  "KHM": "Cambodia",
  "CMR": "Cameroon",
  "CAN": "Canada",
  "CPV": "Cape Verde",
  "CAF": "Central African Republic",
  "TCD": "Chad",
  "CHL": "Chile",
  "CHN": "China",
  "TWN": "China(Taiwan)",
  "COL": "Colombia",
  "COM": "Comoros",
  "COG": "Congo",
  "CRI": "Costa Rica",
  "CIV": "Cote d' Ivoire",
  "HRV": "Croatia",
  "CUB": "Cuba",
  "CYP": "Cyprus",
  "CZE": "Czech Republic",
  "COD": "Democratic Republic of the Congo",
  "DNK": "Denmark",
  "DJI": "Djibouti",
  "DMA": "Dominica",
  "DOM": "Dominican Republic",
  "ECU": "Ecuador",
  "EGY": "Egypt",
  "SLV": "El Salvado",
  "GNQ": "Equatorial Guinea",
  "ERI": "Eritrea",
  "EST": "Estonia",
  "ETH": "Ethiopia",
  "FJI": "Fiji",
  "FIN": "Finland",
  "FRA": "France",
  "GAB": "Gabon",
  "GMB": "Gambia",
  "GEO": "Georgia",
  "D": "Germany",
  "GHA": "Ghana",
  "GIB": "Gibraltar",
  "GRC": "Greece",
  "GRL": "Greenland",
  "GRD": "Grenada",
  "GTM": "Guatemala",
  "GIN": "Guinea",
  "GNB": "Guinea-Bissau",
  "GUY": "Guyana",
  "HTI": "Haiti",
  "VAT": "Holy See (Vatican City State )",
  "HND": "Honduras",
  "HUN": "Hungary",
  "ISL": "Iceland",
  "IND": "India",
  "IDN": "Indonesia",
  "IRN": "Iran Ilasmic Republic of",
  "IRQ": "Iraq",
  "IRL": "Ireland",
  "ISR": "Israel",
  "ITA": "Italy",
  "JAM": "Jamaica",
  "JPN": "Japan",
  "JOR": "Jordan",
  "KAZ": "Kazakhstan",
  "KEN": "Kenya",
  "KIR": "Kiribati",
  "KOR": "Korea (South)",
  "PRK": "Korea Democratic Peoples Republic of",
  "RKS": "Kosovo",
  "KWT": "Kuwait",
  "KGZ": "Kyrgyzstan",
  "LAO": "Lao Peoples Democratic Republic",
  "LVA": "Latvia",
  "LBN": "Lebanon",
  "LSO": "Lesotho",
  "LBR": "Liberia",
  "LBY": "Libyan Arab Jamahiriya",
  "LIE": "Liechtenstein",
  "LTU": "Lithuania",
  "LUX": "Luxembourg",
  "MKD": "Macedonia",
  "MDG": "Madagascar",
  "MWI": "Malawi",
  "MYS": "Malaysia",
  "MDV": "Maldives",
  "MLI": "Mali",
  "MLT": "Malta",
  "MHL": "Marshall Islands",
  "MRT": "Mauritania",
  "MUS": "Mauritius",
  "MEX": "Mexico",
  "FSM": "Micronesia",
  "MDA": "Moldova",
  "MCO": "Monaco",
  "MNG": "Mongolia",
  "MNE": "Montenegro",
  "MSR": "Montserrat",
  "MAR": "Morocco",
  "MOZ": "Mozambique",
  "MMR": "Myanmar",
  "NAM": "Namibia",
  "NRU": "Nauru",
  "NPL": "Nepal",
  "NLD": "Netherland",
  "NZL": "New Zealand",
  "NIC": "Nicaragua",
  "NER": "Niger",
  "NGA": "Nigeria",
  "NOR": "Norway",
  "OMN": "Oman",
  "PAK": "Pakistan",
  "PLW": "Palau",
  "PSE": "Palestine",
  "PAN": "Panama",
  "PNG": "Papua New Guinea",
  "PRY": "Paraguay",
  "PER": "Peru",
  "PHL": "Philippines",
  "POL": "Poland",
  "PRT": "Portugal",
  "QAT": "Qatar",
  "ROU": "Romania",
  "RUS": "Russia",
  "RWA": "Rwanda",
  "KNA": "Saint Kitts and Nevis",
  "LCA": "Saint Lucia",
  "VCT": "Saint Vincent and the Grenadines",
  "SMR": "San Marino",
  "STP": "Sao Tome and Principe",
  "SAU": "Saudi Arabia",
  "SC-": "Scotland",
  "SEN": "Senegal",
  "SRB": "Serbia",
  "SYC": "Seychelles",
  "SLE": "Sierra Leone",
  "SGP": "Singapore",
  "SVK": "Slovakia",
  "SVN": "Slovenia",
  "SLB": "Solomon Islands",
  "SOM": "Somalia",
  "ZAF": "South Africa",
  "SSD": "South Sudan",
  "ESP": "Spain",
  "LKA": "Sri Lanka",
  "SDN": "Sudan",
  "SUR": "Suriname",
  "SWZ": "Swaziland",
  "SWE": "Sweden",
  "CHE": "Switzerland",
  "SYR": "Syrian Arab Republic",
  "TJK": "Tajikistan",
  "TZA": "Tanzania United Republic of",
  "THA": "Thailand",
  "TLS": "Timor Leste",
  "TGO": "Togo",
  "TON": "Tonga",
  "TTO": "Trinidad and Tobago",
  "TUN": "Tunisia",
  "TUR": "Turkey",
  "TKM": "Turkmenistan",
  "TUV": "Tuvalu",
  "UGA": "Uganda",
  "UKR": "Ukraine",
  "ARE": "United Arab Emirates",
  "GBD": "United Kingdom British Territories Citizen",
  "GBR": "United Kingdom of Great Britain and Northern Ireland",
  "UNO": "United Nations Organization",
  "USA": "United States of America",
  "URY": "Uruguay",
  "UZB": "Uzbekistan",
  "VUT": "Vanuatu",
  "VEN": "Venezuela",
  "VNM": "Viet Nam",
  "WSM": "Western Samoa",
  "YEM": "Yemen",
  "ZMB": "Zambia",
  "ZWE": "Zimbabwe",
};

export const VN_COUNTRY_OPTION_ORDER: string[] = Object.values(VN_COUNTRY_NAME_BY_ALPHA3);

export const VN_COUNTRY_SEARCH_TEXT_BY_ALPHA3: Record<string, string> = {
  "AFG": "Ap-ga-ni-xtan",
  "ALB": "An-ba-ni",
  "DZA": "An-giê-ri",
  "AND": "Công quốc An-đơ-ra",
  "AGO": "Ăng-gô-la",
  "ATG": "Ăng-ti-gua và Bác-bu-da",
  "ARG": "Ac-hen-ti-na",
  "ARM": "Ac-mê-ni-a",
  "AUS": "Ô-xtrây-li-a",
  "AUT": "Áo",
  "AZE": "A-déc-bai-gian",
  "BHS": "Ba-ha-ma",
  "BHR": "Ba-ra-in",
  "BGD": "Băng-la-đét",
  "BRB": "Bác-ba-đốt",
  "BLR": "Bê-la-rút",
  "BEL": "Bỉ",
  "BLZ": "Bê-li-xê",
  "BEN": "Bê-nanh",
  "BMU": "Béc-mu-đa",
  "BTN": "Bu-tan",
  "BOL": "Bô-li-vi-a",
  "BIH": "Bô-xni-a Héc-dê-gô-vi-na",
  "BWA": "Bốt-xoa-na",
  "BRA": "Bra-din",
  "IOT": "Vùng đất thuộc Anh ở Ấn Độ Dương",
  "BRN": "Brunei",
  "BGR": "Bun-ga-ri",
  "BFA": "Buốc-ki-na Pha-xô",
  "BDI": "Bu-run-đi",
  "KHM": "Căm-pu-chia",
  "CMR": "Ca-mơ-run",
  "CAN": "Ca-na-da",
  "CPV": "Cáp-ve",
  "CAF": "Cộng hoà Trung Phi",
  "TCD": "Sát",
  "CHL": "Chi-lê",
  "CHN": "Trung Quốc",
  "TWN": "Trung Quốc(Đài Loan)",
  "COL": "Cô-lôm-bi-a",
  "COM": "Cô-mo",
  "COG": "Công-gô",
  "CRI": "Cô-xta Ri-ca",
  "CIV": "Cốt Đi-voa",
  "HRV": "Crô-a-ti-a",
  "CUB": "Cu Ba",
  "CYP": "Đảo Síp",
  "CZE": "Cộng hoà Séc",
  "COD": "Cộng hòa dân chủ Công-gô",
  "DNK": "Đan Mạch",
  "DJI": "Đi-bô-u-ti",
  "DMA": "Đô-mi-ni-ca",
  "DOM": "CH Đô-mi-ni-ca-na",
  "ECU": "Ê-cu-a-đo",
  "EGY": "Ai Cập",
  "SLV": "En Xan-va-đo",
  "GNQ": "Ghi-nê Xích đạo",
  "ERI": "Ê-ri-tơ-ri-a",
  "EST": "Ê-xtô-ni-a",
  "ETH": "Ê-ti-ô-pi-a",
  "FJI": "Fi-ji",
  "FIN": "Phần Lan",
  "FRA": "Pháp",
  "GAB": "Ga-bông",
  "GMB": "Găm-bi-a",
  "GEO": "Gru-di-a",
  "D": "CH Liên bang Đức",
  "GHA": "Ga-na",
  "GIB": "Gibraltar",
  "GRC": "Hy Lạp",
  "GRL": "Grin-lơn",
  "GRD": "Grê-na-đa",
  "GTM": "Goa-tê-ma-la",
  "GIN": "Ghi-nê",
  "GNB": "Ghi-nê Bít-xao",
  "GUY": "Gui-na",
  "HTI": "Ha-i-ti",
  "VAT": "Va-ti-căng",
  "HND": "Hon-du-rat",
  "HUN": "Hung-ga-ri",
  "ISL": "Ai-xơ-len",
  "IND": "Ấn Độ",
  "IDN": "In-đô-nê-xi-a",
  "IRN": "CH Hồi giáo I-ran",
  "IRQ": "I-rắc",
  "IRL": "Ai-rơ-len",
  "ISR": "I-xra-en",
  "ITA": "I-ta-li-a",
  "JAM": "Ja-mai-ca",
  "JPN": "Nhật Bản",
  "JOR": "Joc-đan",
  "KAZ": "Ka-dắc-xtan",
  "KEN": "Kê-ni-a",
  "KIR": "Ki-ri-ba-ti",
  "KOR": "CH Hàn Quốc",
  "PRK": "CHDCND Triều Tiên",
  "RKS": "Kô-sô-vô",
  "KWT": "Cô-oét",
  "KGZ": "Kiếc-ghi-di-a",
  "LAO": "CHDCND Lào",
  "LVA": "Lát-vi-a",
  "LBN": "Li-ban",
  "LSO": "Lê-xô-thô",
  "LBR": "Li-bê-ri-a",
  "LBY": "Gia-ma-hi-ri-i-a A-rập Li-bi Nhân dân",
  "LIE": "Công quốc Lích-ten-xtên",
  "LTU": "Lit-hua-ni-a",
  "LUX": "Luých-xem-bua",
  "MKD": "Ma-xê-đô-ni-a",
  "MDG": "Ma-đa-ga-xca",
  "MWI": "Ma-la-uy",
  "MYS": "Ma lai",
  "MDV": "Man-đi-vơ",
  "MLI": "Ma-li",
  "MLT": "Man-ta",
  "MHL": "Quần đảo Mác-san",
  "MRT": "Mô-ra-ta-ni",
  "MUS": "Mô-ri-xơ",
  "MEX": "Mê-xi-cô",
  "FSM": "Mai-crô-nê-xi-a",
  "MDA": "Môn-đô-va",
  "MCO": "Công quốc Mô-na-cô",
  "MNG": "Mông Cổ",
  "MNE": "Môn-tê-nê-grô",
  "MSR": "Môn-xê-rat",
  "MAR": "Ma-rốc",
  "MOZ": "Mô-dăm-bích",
  "MMR": "Mi-an-ma",
  "NAM": "Na-mi-bi-a",
  "NRU": "Na-u-ru",
  "NPL": "Nê-pan",
  "NLD": "Hà Lan",
  "NZL": "Niu Di-lân",
  "NIC": "Ni-ca-ra-goa",
  "NER": "Ni-giê",
  "NGA": "Ni-giê-ri-a",
  "NOR": "Vương quốc Na-uy",
  "OMN": "Ô-man",
  "PAK": "Pa-ki-xtan",
  "PLW": "Pa-lau",
  "PSE": "Pa-le-xtin",
  "PAN": "Pa-na-ma",
  "PNG": "Pa-pua Niu Ghi-nê",
  "PRY": "Pa-ra-goay",
  "PER": "Pê-ru",
  "PHL": "Phi-líp-pin",
  "POL": "Ba Lan",
  "PRT": "Bồ Đào Nha",
  "QAT": "Qua-ta",
  "ROU": "Rumani",
  "RUS": "Liên bang Nga",
  "RWA": "Ru-an-đa",
  "KNA": "Liên bang Xanh Kít và Nê-vít",
  "LCA": "Xanh Lu-xi-a",
  "VCT": "Xanh Vin-xen và Grê-na-din",
  "SMR": "Xan Ma-ri-nô",
  "STP": "Xao Tô-mê và Prin-xi-pê",
  "SAU": "A-rập Xau-đi",
  "SC-": "Xcô-lent",
  "SEN": "Xe-ne-gan",
  "SRB": "Xéc-bi-a",
  "SYC": "Quần đảo Xây-sen",
  "SLE": "Xi-ê-ra Li-ôn",
  "SGP": "Xin-ga-po",
  "SVK": "Xlô-va-ki-a",
  "SVN": "Slo-vê-ni-a",
  "SLB": "Quần đảo Xa-lô-mông",
  "SOM": "Xô-ma-li",
  "ZAF": "Nam Phi",
  "SSD": "Nam Sudan",
  "ESP": "Tây Ban Nha",
  "LKA": "Xri-Lan-ca",
  "SDN": "Xu-đăng",
  "SUR": "Xu-ri-nam",
  "SWZ": "Xoa-di-len",
  "SWE": "Thuỵ Điển",
  "CHE": "Thuỵ Sĩ",
  "SYR": "CH A-rập Xy-ri",
  "TJK": "Ta-gi-ki-xtan",
  "TZA": "CH thống nhất Tan-da-ni-a",
  "THA": "Thái Lan",
  "TLS": "Đông Ti-mo",
  "TGO": "Tô-gô",
  "TON": "Tôn-ga",
  "TTO": "CH Tơ-ri-ni-đát và Tô-ba-gô",
  "TUN": "Tu-ni-di",
  "TUR": "Thổ Nhĩ Kỳ",
  "TKM": "Tuốc-mê-ni-xtan",
  "TUV": "Tu-va-lu",
  "UGA": "U-gan-da",
  "UKR": "U-crai-na",
  "ARE": "A-rập thống nhất",
  "GBD": "Công dân các địa phận thuộc Vương quốc liên hiệp Anh",
  "GBR": "Vương quốc Anh và Bắc Ai len",
  "UNO": "HC Liên hiệp quốc",
  "USA": "Hoa Kỳ",
  "URY": "U-ru-goay",
  "UZB": "U-dơ-bê-ki-xtan",
  "VUT": "Va-nu-a-tu",
  "VEN": "Vê-nê-du-ê-la",
  "VNM": "Việt Nam",
  "WSM": "Xa-moa",
  "YEM": "Y-ê-men",
  "ZMB": "Dăm-bi-a",
  "ZWE": "Dim-ba-bu-ê",
};
