-- Publish the DS-160 Sign and Submit preparer contract that is already defined
-- by seed-ds160-form-fields.ts. This is deliberately limited to the eleven
-- stable ds160_preparer_* keys; it does not reseed the catalog or touch answer
-- rows. Existing field IDs are retained by the conflict update.

INSERT INTO public.visa_form_fields (
  visa_type,
  field_name,
  label,
  field_type,
  required,
  step_number,
  step_name,
  display_order,
  placeholder,
  validation_rules,
  options,
  conditional_logic
)
VALUES
  (
    'DS160',
    'ds160_preparer_assistance',
    'Did anyone assist you in filling out this application?',
    'radio',
    TRUE,
    22,
    'Sign and Submit',
    1,
    NULL,
    '{"official_source":"CEAC DS160 Sign and Submit page (2014 government screenshot; current DOM not yet verified)","label_zh":"是否有人协助您填写此申请？","label_en":"Did anyone assist you in filling out this application?","official_label_en":"Did anyone assist you in filling out this application?"}'::jsonb,
    '[{"value":"yes","text":"Yes","label_en":"Yes","official_label":"Yes"},{"value":"no","text":"No","label_en":"No","official_label":"No"}]'::jsonb,
    NULL
  ),
  (
    'DS160',
    'ds160_preparer_surname',
    'Surnames',
    'text',
    TRUE,
    22,
    'Sign and Submit',
    2,
    NULL,
    '{"official_source":"CEAC DS160 Sign and Submit page (2014 government screenshot; current DOM not yet verified)","label_zh":"姓氏","label_en":"Surnames","official_label_en":"Surnames"}'::jsonb,
    NULL,
    '{"showIf":"ds160_preparer_assistance === yes"}'::jsonb
  ),
  (
    'DS160',
    'ds160_preparer_given_names',
    'Given Names',
    'text',
    TRUE,
    22,
    'Sign and Submit',
    3,
    NULL,
    '{"official_source":"CEAC DS160 Sign and Submit page (2014 government screenshot; current DOM not yet verified)","label_zh":"名字","has_does_not_apply":true,"does_not_apply_label":"Does Not Apply","label_en":"Given Names","official_label_en":"Given Names"}'::jsonb,
    NULL,
    '{"showIf":"ds160_preparer_assistance === yes"}'::jsonb
  ),
  (
    'DS160',
    'ds160_preparer_organization_name',
    'Organization Name',
    'text',
    TRUE,
    22,
    'Sign and Submit',
    4,
    NULL,
    '{"official_source":"CEAC DS160 Sign and Submit page (2014 government screenshot; current DOM not yet verified)","label_zh":"组织名称","has_does_not_apply":true,"does_not_apply_label":"Does Not Apply","label_en":"Organization Name","official_label_en":"Organization Name"}'::jsonb,
    NULL,
    '{"showIf":"ds160_preparer_assistance === yes"}'::jsonb
  ),
  (
    'DS160',
    'ds160_preparer_street1',
    'Street Address (Line 1)',
    'text',
    TRUE,
    22,
    'Sign and Submit',
    5,
    NULL,
    '{"official_source":"CEAC DS160 Sign and Submit page (2014 government screenshot; current DOM not yet verified)","label_zh":"街道地址（第1行）","label_en":"Street Address (Line 1)","official_label_en":"Street Address (Line 1)"}'::jsonb,
    NULL,
    '{"showIf":"ds160_preparer_assistance === yes"}'::jsonb
  ),
  (
    'DS160',
    'ds160_preparer_street2',
    'Street Address (Line 2)',
    'text',
    FALSE,
    22,
    'Sign and Submit',
    6,
    NULL,
    '{"official_source":"CEAC DS160 Sign and Submit page (2014 government screenshot; current DOM not yet verified)","label_zh":"街道地址（第2行）","optional_label":true,"label_en":"Street Address (Line 2)","official_label_en":"Street Address (Line 2)"}'::jsonb,
    NULL,
    '{"showIf":"ds160_preparer_assistance === yes"}'::jsonb
  ),
  (
    'DS160',
    'ds160_preparer_city',
    'City',
    'text',
    TRUE,
    22,
    'Sign and Submit',
    7,
    NULL,
    '{"official_source":"CEAC DS160 Sign and Submit page (2014 government screenshot; current DOM not yet verified)","label_zh":"城市","label_en":"City","official_label_en":"City"}'::jsonb,
    NULL,
    '{"showIf":"ds160_preparer_assistance === yes"}'::jsonb
  ),
  (
    'DS160',
    'ds160_preparer_state_province',
    'State/Province',
    'text',
    TRUE,
    22,
    'Sign and Submit',
    8,
    NULL,
    '{"official_source":"CEAC DS160 Sign and Submit page (2014 government screenshot; current DOM not yet verified)","label_zh":"州/省","has_does_not_apply":true,"does_not_apply_label":"Does Not Apply","label_en":"State/Province","official_label_en":"State/Province"}'::jsonb,
    NULL,
    '{"showIf":"ds160_preparer_assistance === yes"}'::jsonb
  ),
  (
    'DS160',
    'ds160_preparer_postal_code',
    'Postal Zone/ZIP Code',
    'text',
    TRUE,
    22,
    'Sign and Submit',
    9,
    NULL,
    '{"official_source":"CEAC DS160 Sign and Submit page (2014 government screenshot; current DOM not yet verified)","label_zh":"邮政区/邮政编码","has_does_not_apply":true,"does_not_apply_label":"Does Not Apply","label_en":"Postal Zone/ZIP Code","official_label_en":"Postal Zone/ZIP Code"}'::jsonb,
    NULL,
    '{"showIf":"ds160_preparer_assistance === yes"}'::jsonb
  ),
  (
    'DS160',
    'ds160_preparer_country',
    'Country/Region',
    'select',
    TRUE,
    22,
    'Sign and Submit',
    10,
    NULL,
    '{"official_source":"CEAC DS160 Sign and Submit page (2014 government screenshot; current DOM not yet verified)","label_zh":"国家/地区","source":"ISO3166-1","label_en":"Country/Region","official_label_en":"Country/Region"}'::jsonb,
    NULL,
    '{"showIf":"ds160_preparer_assistance === yes"}'::jsonb
  ),
  (
    'DS160',
    'ds160_preparer_relationship',
    'Relationship to You',
    'text',
    TRUE,
    22,
    'Sign and Submit',
    11,
    NULL,
    '{"official_source":"CEAC DS160 Sign and Submit page (2014 government screenshot; current DOM not yet verified)","label_zh":"与您的关系","label_en":"Relationship to You","official_label_en":"Relationship to You"}'::jsonb,
    NULL,
    '{"showIf":"ds160_preparer_assistance === yes"}'::jsonb
  )
ON CONFLICT (visa_type, field_name) DO UPDATE
SET
  label = EXCLUDED.label,
  field_type = EXCLUDED.field_type,
  required = EXCLUDED.required,
  step_number = EXCLUDED.step_number,
  step_name = EXCLUDED.step_name,
  display_order = EXCLUDED.display_order,
  placeholder = EXCLUDED.placeholder,
  validation_rules = EXCLUDED.validation_rules,
  options = EXCLUDED.options,
  conditional_logic = EXCLUDED.conditional_logic,
  updated_at = now();
