import type { ReviewTableRule } from "./review-table-contract";

const PRESENT_WORK_GROUP = "Edit Present Work Information";
const PREVIOUS_WORK_GROUP = "Edit Previous Work Information";
const ADDITIONAL_WORK_GROUP = "Edit Additional Information";

const SCHOOL_SCOPE_ANCHOR = "Name of Institution ({n}):";

/**
 * CEAC's review pages expose these rows without control IDs.  The labels and
 * repeat containers below are copied from the captured review DOM; values are
 * deliberately not part of this catalog.
 */
export const WORK_REVIEW_TABLE_RULES = [
  // Work/Education/Training: Present.
  {
    page: "workeducation",
    section: "work_education_present",
    group: PRESENT_WORK_GROUP,
    label: "Primary Occupation:",
    fields: ["primary_occupation"],
  },
  {
    page: "workeducation",
    section: "work_education_present",
    group: PRESENT_WORK_GROUP,
    label: "Present Employer or School Name:",
    fields: ["employer_name"],
  },
  {
    page: "workeducation",
    section: "work_education_present",
    group: PRESENT_WORK_GROUP,
    label: "Present Employer or School Address:",
    fields: ["employer_address_line1"],
  },
  {
    page: "workeducation",
    section: "work_education_present",
    group: PRESENT_WORK_GROUP,
    label: "City:",
    fields: ["employer_address_city"],
  },
  {
    page: "workeducation",
    section: "work_education_present",
    group: PRESENT_WORK_GROUP,
    label: "State/Province:",
    fields: ["employer_address_state_na"],
    format: "na",
  },
  {
    page: "workeducation",
    section: "work_education_present",
    group: PRESENT_WORK_GROUP,
    label: "Postal Zone/Zip Code:",
    fields: ["employer_address_postal"],
  },
  {
    page: "workeducation",
    section: "work_education_present",
    group: PRESENT_WORK_GROUP,
    label: "Country/Region:",
    fields: ["employer_address_country"],
  },
  {
    page: "workeducation",
    section: "work_education_present",
    group: PRESENT_WORK_GROUP,
    label: "Start Date:",
    fields: [
      "employment_start_date_day",
      "employment_start_date_month",
      "employment_start_date_year",
    ],
    format: "date",
  },
  {
    page: "workeducation",
    section: "work_education_present",
    group: PRESENT_WORK_GROUP,
    label: "Work Phone Number:",
    fields: ["employer_phone"],
  },
  {
    page: "workeducation",
    section: "work_education_present",
    group: PRESENT_WORK_GROUP,
    label: "Monthly Salary in Local Currency (if employed):",
    fields: ["monthly_income_na"],
    format: "na",
  },
  {
    page: "workeducation",
    section: "work_education_present",
    group: PRESENT_WORK_GROUP,
    label: "Briefly Describe your Duties:",
    fields: ["job_duties"],
  },

  // Work/Education/Training: Previous.
  {
    page: "workeducation",
    section: "work_education_previous",
    group: PREVIOUS_WORK_GROUP,
    label: "Were you previously employed?",
    fields: ["has_previous_employer"],
  },
  {
    page: "workeducation",
    section: "work_education_previous",
    group: PREVIOUS_WORK_GROUP,
    container: "EDUCYs",
    label: SCHOOL_SCOPE_ANCHOR,
    fields: ["education_institution_name"],
    scopeAnchor: SCHOOL_SCOPE_ANCHOR,
  },
  {
    page: "workeducation",
    section: "work_education_previous",
    group: PREVIOUS_WORK_GROUP,
    container: "EDUCYs",
    label: "Address of Institution:",
    fields: ["education_address_line1"],
    scopeAnchor: SCHOOL_SCOPE_ANCHOR,
  },
  {
    page: "workeducation",
    section: "work_education_previous",
    group: PREVIOUS_WORK_GROUP,
    container: "EDUCYs",
    label: "City:",
    fields: ["education_city"],
    scopeAnchor: SCHOOL_SCOPE_ANCHOR,
  },
  {
    page: "workeducation",
    section: "work_education_previous",
    group: PREVIOUS_WORK_GROUP,
    container: "EDUCYs",
    label: "State/Province:",
    fields: ["education_state_province"],
    scopeAnchor: SCHOOL_SCOPE_ANCHOR,
  },
  {
    page: "workeducation",
    section: "work_education_previous",
    group: PREVIOUS_WORK_GROUP,
    container: "EDUCYs",
    label: "Postal Zone/ZIP Code:",
    fields: ["education_postal_code"],
    scopeAnchor: SCHOOL_SCOPE_ANCHOR,
  },
  {
    page: "workeducation",
    section: "work_education_previous",
    group: PREVIOUS_WORK_GROUP,
    container: "EDUCYs",
    label: "Country/Region:",
    fields: ["education_country"],
    scopeAnchor: SCHOOL_SCOPE_ANCHOR,
  },
  {
    page: "workeducation",
    section: "work_education_previous",
    group: PREVIOUS_WORK_GROUP,
    container: "EDUCYs",
    label: "Course of Study:",
    fields: ["education_course_of_study"],
    scopeAnchor: SCHOOL_SCOPE_ANCHOR,
  },
  {
    page: "workeducation",
    section: "work_education_previous",
    group: PREVIOUS_WORK_GROUP,
    container: "EDUCYs",
    label: "Date of Attendance From:",
    fields: [
      "education_start_date_day",
      "education_start_date_month",
      "education_start_date_year",
    ],
    format: "date",
    scopeAnchor: SCHOOL_SCOPE_ANCHOR,
  },
  {
    page: "workeducation",
    section: "work_education_previous",
    group: PREVIOUS_WORK_GROUP,
    container: "EDUCYs",
    label: "Date of Attendance To:",
    fields: [
      "education_end_date_day",
      "education_end_date_month",
      "education_end_date_year",
    ],
    format: "date",
    scopeAnchor: SCHOOL_SCOPE_ANCHOR,
  },
  {
    page: "workeducation",
    section: "work_education_previous",
    group: PREVIOUS_WORK_GROUP,
    label: "Have you attended any educational institutions at a secondary level or above?",
    fields: ["has_other_education"],
  },

  // Work/Education/Training: Additional.
  {
    page: "workeducation",
    section: "work_education_additional",
    group: ADDITIONAL_WORK_GROUP,
    label: "Do you belong to a clan or tribe?",
    fields: ["has_clan_tribe"],
  },
  {
    page: "workeducation",
    section: "work_education_additional",
    group: ADDITIONAL_WORK_GROUP,
    container: "LANGUs",
    label: "Language Name ({n}):",
    fields: ["language_name"],
  },
  {
    page: "workeducation",
    section: "work_education_additional",
    group: ADDITIONAL_WORK_GROUP,
    label: "Have you traveled to any countries/regions within the last five years?",
    fields: ["has_countries_visited"],
  },
  {
    page: "workeducation",
    section: "work_education_additional",
    group: ADDITIONAL_WORK_GROUP,
    container: "CNTRYVYs",
    label: "Country/Region({n}):",
    fields: ["traveled_country"],
  },
  {
    page: "workeducation",
    section: "work_education_additional",
    group: ADDITIONAL_WORK_GROUP,
    label: "Have you belonged to, contributed to, or worked for any professional, social, or charitable organization?",
    fields: ["has_organization"],
  },
  {
    page: "workeducation",
    section: "work_education_additional",
    group: ADDITIONAL_WORK_GROUP,
    label: "Do you have any specialized skills or training, such as firearms, explosives, nuclear, biological, or chemical experience?",
    fields: ["has_specialized_skills"],
  },
  {
    page: "workeducation",
    section: "work_education_additional",
    group: ADDITIONAL_WORK_GROUP,
    label: "Have you ever served in the military?",
    fields: ["has_served_military"],
  },
  {
    page: "workeducation",
    section: "work_education_additional",
    group: ADDITIONAL_WORK_GROUP,
    label: "Have you ever served in, been a member of, or been involved with a paramilitary unit, vigilante unit, rebel group, guerrilla group, or insurgent organization?",
    fields: ["has_served_insurgent"],
  },

  // Security and Background: Part 1.
  {
    page: "security",
    section: "security_background_1",
    group: "Edit Part 1",
    label: "Do you have a communicable disease of public health significance? (Communicable diseases of public significance include chancroid, gonorrhea, granuloma inguinale, infectious leprosy, lymphogranuloma venereum, infectious stage syphilis, active tuberculosis, and other diseases as determined by the Department of Health and Human Services.)",
    fields: ["has_communicable_disease"],
  },
  {
    page: "security",
    section: "security_background_1",
    group: "Edit Part 1",
    label: "Do you have a mental or physical disorder that poses or is likely to pose a threat to the safety or welfare of yourself or others?",
    fields: ["has_physical_mental_disorder"],
  },
  {
    page: "security",
    section: "security_background_1",
    group: "Edit Part 1",
    label: "Are you or have you ever been a drug abuser or addict?",
    fields: ["is_drug_abuser"],
  },

  // Security and Background: Part 2.
  {
    page: "security",
    section: "security_background_2",
    group: "Edit Part 2",
    label: "Have you ever been arrested or convicted for any offense or crime, even though subject of a pardon, amnesty, or other similar action?",
    fields: ["has_arrest_conviction"],
  },
  {
    page: "security",
    section: "security_background_2",
    group: "Edit Part 2",
    label: "Have you ever violated, or engaged in a conspiracy to violate, any law relating to controlled substances?",
    fields: ["has_violated_controlled_substance"],
  },
  {
    page: "security",
    section: "security_background_2",
    group: "Edit Part 2",
    label: "Are you coming to the United States to engage in prostitution or unlawful commercialized vice or have you been engaged in prostitution or procuring prostitutes within the past 10 years?",
    fields: ["has_prostitution"],
  },
  {
    page: "security",
    section: "security_background_2",
    group: "Edit Part 2",
    label: "Have you ever been involved in, or do you seek to engage in, money laundering?",
    fields: ["has_money_laundering"],
  },
  {
    page: "security",
    section: "security_background_2",
    group: "Edit Part 2",
    label: "Have you ever committed or conspired to commit a human trafficking offense in the United States or outside the United States?",
    fields: ["has_human_trafficking"],
  },
  {
    page: "security",
    section: "security_background_2",
    group: "Edit Part 2",
    label: "Are you the spouse, son, or daughter of an individual who has committed or conspired to commit a human trafficking offense in the United States or outside the United States and have you within the last five years, knowingly benefited from the trafficking activities?",
    fields: ["has_trafficking_beneficiary"],
  },
  {
    page: "security",
    section: "security_background_2",
    group: "Edit Part 2",
    label: "Have you knowingly aided, abetted, assisted or colluded with an individual who has committed or conspired to commit a severe human trafficking offense in the United States or outside the United States?",
    fields: ["has_aided_human_trafficking"],
  },

  // Security and Background: Part 3.
  {
    page: "security",
    section: "security_background_3",
    group: "Edit Part 3",
    label: "Do you seek to engage in espionage, sabotage, export control violations, or any other illegal activity while in the United States?",
    fields: ["intend_illegal_activity"],
  },
  {
    page: "security",
    section: "security_background_3",
    group: "Edit Part 3",
    label: "Do you seek to engage in terrorist activities while in the United States or have you ever engaged in terrorist activities?",
    fields: ["intend_terrorist_activity"],
  },
  {
    page: "security",
    section: "security_background_3",
    group: "Edit Part 3",
    label: "Have you ever or do you intend to provide financial assistance or other support to terrorists or terrorist organizations?",
    fields: ["has_provided_terrorist_support"],
  },
  {
    page: "security",
    section: "security_background_3",
    group: "Edit Part 3",
    label: "Are you a member or representative of a terrorist organization?",
    fields: ["is_terrorist_member"],
  },
  {
    page: "security",
    section: "security_background_3",
    group: "Edit Part 3",
    label: "Are you the spouse, son, or daughter of an individual who has engaged in terrorist activity, including providing financial assistance or other support to terrorists or terrorist organizations, in the last five years?",
    fields: ["is_terrorist_family"],
  },
  {
    page: "security",
    section: "security_background_3",
    group: "Edit Part 3",
    label: "Have you ever ordered, incited, committed, assisted, or otherwise participated in genocide?",
    fields: ["has_genocide"],
  },
  {
    page: "security",
    section: "security_background_3",
    group: "Edit Part 3",
    label: "Have you ever committed, ordered, incited, assisted, or otherwise participated in torture?",
    fields: ["has_torture"],
  },
  {
    page: "security",
    section: "security_background_3",
    group: "Edit Part 3",
    label: "Have you committed, ordered, incited, assisted, or otherwise participated in extrajudicial killings, political killings, or other acts of violence?",
    fields: ["has_extrajudicial_killings"],
  },
  {
    page: "security",
    section: "security_background_3",
    group: "Edit Part 3",
    label: "Have you ever engaged in the recruitment or the use of the child soldiers?",
    fields: ["has_child_soldier"],
  },
  {
    page: "security",
    section: "security_background_3",
    group: "Edit Part 3",
    label: "Have you, while serving as a government official, been responsible for or directly carried out, at any time, particularly severe violations of religious freedom?",
    fields: ["has_religious_freedom_violation"],
  },
  {
    page: "security",
    section: "security_background_3",
    group: "Edit Part 3",
    label: "Have you ever been directly involved in the establishment or enforcement of the population controls forcing a woman to undergo an abortion against her free choice or a man or a woman to undergo sterilization against his or her free will?",
    fields: ["has_population_control"],
  },
  {
    page: "security",
    section: "security_background_3",
    group: "Edit Part 3",
    label: "Have you ever been directly involved in the coercive transplantation of human organs or bodily tissue?",
    fields: ["has_coercive_transplant"],
  },

  // Security and Background: Part 4.
  {
    page: "security",
    section: "security_background_4",
    group: "Edit Part 4",
    label: "Have you ever sought to obtain or assist others to obtain a visa, entry into the United States, or any other United States immigration benefit by fraud or willful misrepresentation or other unlawful means?",
    fields: ["has_immigration_fraud"],
  },
  {
    page: "security",
    section: "security_background_4",
    group: "Edit Part 4",
    label: "Have you ever been removed or deported from any country?",
    fields: ["has_removal_order"],
  },

  // Security and Background: Part 5.
  {
    page: "security",
    section: "security_background_5",
    group: "Edit Part 5",
    label: "Have you ever withheld custody of a U.S. citizen child outside the United States from a person granted legal custody by a U.S. court?",
    fields: ["has_withheld_child_custody"],
  },
  {
    page: "security",
    section: "security_background_5",
    group: "Edit Part 5",
    label: "Have you voted in the United States in violation of any law or regulation?",
    fields: ["has_voted_illegally"],
  },
  {
    page: "security",
    section: "security_background_5",
    group: "Edit Part 5",
    label: "Have you ever renounced United States citizenship for the purpose of avoiding taxation?",
    fields: ["has_renounced_citizenship"],
  },
] as const satisfies readonly ReviewTableRule[];
