import type { ReviewTableRule } from "./review-table-contract";

/**
 * Review-table rules for the personal, travel, contact, and family review
 * pages. The labels and nested container IDs are copied from the observed
 * public CEAC review DOM; applicant values never belong in this catalog.
 */
export const PERSONAL_REVIEW_TABLE_RULES: readonly ReviewTableRule[] = [
  // ReviewPersonal: Edit Personal Information.
  {
    page: "personal",
    section: "personal_information_1",
    group: "Edit Personal Information",
    label: "Name Provided:",
    fields: ["surname", "given_names"],
    format: "name",
  },
  {
    page: "personal",
    section: "personal_information_1",
    group: "Edit Personal Information",
    label: "Full Name in Native Alphabet:",
    fields: ["full_name_native_alphabet"],
  },
  {
    page: "personal",
    section: "personal_information_1",
    group: "Edit Personal Information",
    label: "Other Names Used:",
    fields: ["has_other_names"],
  },
  {
    page: "personal",
    section: "personal_information_1",
    group: "Edit Personal Information",
    label: "Telecode Name Used:",
    fields: ["has_telecode"],
  },
  {
    page: "personal",
    section: "personal_information_1",
    group: "Edit Personal Information",
    label: "Sex:",
    fields: ["sex"],
  },
  {
    page: "personal",
    section: "personal_information_1",
    group: "Edit Personal Information",
    label: "Marital Status:",
    fields: ["marital_status"],
  },
  {
    page: "personal",
    section: "personal_information_1",
    group: "Edit Personal Information",
    label: "Date of Birth:",
    fields: ["date_of_birth_day", "date_of_birth_month", "date_of_birth_year"],
    format: "date",
  },
  {
    page: "personal",
    section: "personal_information_1",
    group: "Edit Personal Information",
    label: "Country/Region of Birth:",
    fields: ["city_of_birth", "state_of_birth", "country_of_birth"],
    format: "place",
  },
  {
    page: "personal",
    section: "personal_information_2",
    group: "Edit Personal Information",
    label: "Country/Region of Origin (Nationality):",
    fields: ["nationality_country"],
  },
  {
    page: "personal",
    section: "personal_information_2",
    group: "Edit Personal Information",
    label: "Do you hold or have you held any nationality other than the one indicated above on nationality?",
    fields: ["other_nationality"],
  },
  {
    page: "personal",
    section: "personal_information_2",
    group: "Edit Personal Information",
    label: "Are you a permanent resident of a country/region other than your country/region of origin (nationality) above?",
    fields: ["permanent_resident_other_country"],
  },
  {
    page: "personal",
    section: "personal_information_2",
    group: "Edit Personal Information",
    label: "National Identification Number:",
    fields: ["national_id_number"],
  },
  {
    page: "personal",
    section: "personal_information_2",
    group: "Edit Personal Information",
    label: "U.S. Social Security Number:",
    fields: ["us_social_security_number_na"],
    format: "na",
  },
  {
    page: "personal",
    section: "personal_information_2",
    group: "Edit Personal Information",
    label: "U.S. Taxpayer ID Number:",
    fields: ["us_taxpayer_id_na"],
    format: "na",
  },

  // ReviewPersonal: Edit Address and Phone Information.
  {
    page: "personal",
    section: "address_and_phone",
    group: "Edit Address and Phone Information",
    label: "Home Address:",
    fields: ["home_address_line1"],
  },
  {
    page: "personal",
    section: "address_and_phone",
    group: "Edit Address and Phone Information",
    label: "Home Address:",
    fields: ["home_address_line2"],
    continuation: true,
  },
  {
    page: "personal",
    section: "address_and_phone",
    group: "Edit Address and Phone Information",
    label: "City:",
    fields: ["home_address_city"],
  },
  {
    page: "personal",
    section: "address_and_phone",
    group: "Edit Address and Phone Information",
    label: "State/Province:",
    fields: ["home_address_state"],
  },
  {
    page: "personal",
    section: "address_and_phone",
    group: "Edit Address and Phone Information",
    label: "Postal Zone/ZIP Code:",
    fields: ["home_address_postal"],
  },
  {
    page: "personal",
    section: "address_and_phone",
    group: "Edit Address and Phone Information",
    label: "Country/Region:",
    fields: ["home_address_country"],
  },
  {
    page: "personal",
    section: "address_and_phone",
    group: "Edit Address and Phone Information",
    label: "Same Mailing Address?",
    fields: ["mailing_same_as_home"],
  },
  {
    page: "personal",
    section: "address_and_phone",
    group: "Edit Address and Phone Information",
    label: "Primary Phone Number:",
    fields: ["primary_phone"],
  },
  {
    page: "personal",
    section: "address_and_phone",
    group: "Edit Address and Phone Information",
    label: "Secondary Phone Number:",
    fields: ["mobile_phone_na"],
    format: "na",
  },
  {
    page: "personal",
    section: "address_and_phone",
    group: "Edit Address and Phone Information",
    label: "Work Phone Number:",
    fields: ["work_phone_na"],
    format: "na",
  },
  {
    page: "personal",
    section: "address_and_phone",
    group: "Edit Address and Phone Information",
    label: "Have you used additional phone numbers in the last five years?",
    fields: ["has_other_phone"],
  },
  {
    page: "personal",
    section: "address_and_phone",
    group: "Edit Address and Phone Information",
    label: "Email Address:",
    fields: ["email_address"],
  },
  {
    page: "personal",
    section: "address_and_phone",
    group: "Edit Address and Phone Information",
    label: "Have you used additional email addresses in the last five years?",
    fields: ["has_other_email"],
  },
  {
    page: "personal",
    section: "address_and_phone",
    group: "Edit Address and Phone Information",
    label: "Have you used additional social media platforms in the last five years?",
    fields: ["has_other_social_media"],
  },
  {
    page: "personal",
    section: "address_and_phone",
    group: "Edit Address and Phone Information",
    container: "SOCIALMEDIAs",
    label: "Social Media Provider/Platform ({n}):",
    fields: ["social_media_provider"],
    scopeAnchor: "Social Media Provider/Platform ({n}):",
  },

  // ReviewPersonal: Edit Passport/Travel Document Information.
  {
    page: "personal",
    section: "passport",
    group: "Edit Passport/Travel Document Information",
    label: "Passport/Travel Document Type:",
    fields: ["passport_document_type"],
  },
  {
    page: "personal",
    section: "passport",
    group: "Edit Passport/Travel Document Information",
    label: "Passport/Travel Document Number:",
    fields: ["passport_number"],
  },
  {
    page: "personal",
    section: "passport",
    group: "Edit Passport/Travel Document Information",
    label: "Passport Book Number:",
    fields: ["passport_book_number_na"],
    format: "na",
  },
  {
    page: "personal",
    section: "passport",
    group: "Edit Passport/Travel Document Information",
    label: "Country/Authority that Issued Passport/Travel Document:",
    fields: ["passport_issuing_country"],
  },
  {
    page: "personal",
    section: "passport",
    group: "Edit Passport/Travel Document Information",
    label: "City where issued:",
    fields: ["passport_issuance_city"],
  },
  {
    page: "personal",
    section: "passport",
    group: "Edit Passport/Travel Document Information",
    label: "State/Province where issued:",
    fields: ["passport_issuance_state"],
  },
  {
    page: "personal",
    section: "passport",
    group: "Edit Passport/Travel Document Information",
    label: "Country/Region where issued:",
    fields: ["passport_issuance_country"],
  },
  {
    page: "personal",
    section: "passport",
    group: "Edit Passport/Travel Document Information",
    label: "Issuance Date:",
    fields: ["passport_issue_day", "passport_issue_month", "passport_issue_year"],
    format: "date",
  },
  {
    page: "personal",
    section: "passport",
    group: "Edit Passport/Travel Document Information",
    label: "Expiration Date:",
    fields: ["passport_expiry_day", "passport_expiry_month", "passport_expiry_year"],
    format: "date",
    naField: "passport_expiry_na",
  },
  {
    page: "personal",
    section: "passport",
    group: "Edit Passport/Travel Document Information",
    label: "Have you ever lost a passport or had one stolen?",
    fields: ["passport_lost_or_stolen"],
  },

  // ReviewTravel: Edit Travel Information.
  {
    page: "travel",
    section: "travel_information",
    group: "Edit Travel Information",
    container: "PURPYs",
    label: "Purpose of Trip to the U.S. ({n}):",
    fields: ["purpose_of_trip"],
    scopeAnchor: "Purpose of Trip to the U.S. ({n}):",
  },
  {
    page: "travel",
    section: "travel_information",
    group: "Edit Travel Information",
    container: "PURPYs",
    label: "Specify:",
    fields: ["purpose_of_trip_specify"],
    scopeAnchor: "Purpose of Trip to the U.S. ({n}):",
  },
  {
    page: "travel",
    section: "travel_information",
    group: "Edit Travel Information",
    label: "Have you made specific travel plans?",
    fields: ["has_specific_travel_plans"],
  },
  {
    page: "travel",
    section: "travel_information",
    group: "Edit Travel Information",
    label: "Intended Date of Arrival:",
    fields: ["intended_arrival_date_day", "intended_arrival_date_month", "intended_arrival_date_year"],
    format: "date",
  },
  {
    page: "travel",
    section: "travel_information",
    group: "Edit Travel Information",
    label: "Intended Length of Stay in U.S.:",
    fields: ["intended_length_of_stay", "intended_length_of_stay_unit"],
    format: "length",
  },
  {
    page: "travel",
    section: "travel_information",
    group: "Edit Travel Information",
    label: "Address where you will stay in the U.S.:",
    fields: ["us_address_street"],
  },
  {
    page: "travel",
    section: "travel_information",
    group: "Edit Travel Information",
    label: "Address where you will stay in the U.S.:",
    fields: ["us_address_city", "us_address_state", "us_address_zip"],
    format: "locality",
    continuation: true,
  },
  {
    page: "travel",
    section: "travel_information",
    group: "Edit Travel Information",
    label: "Person/Entity Paying for Your Trip:",
    fields: ["who_is_paying", "travel_payer"],
    format: "aliases",
  },

  // ReviewTravel: Edit Travel Companions Information.
  {
    page: "travel",
    section: "travel_companions",
    group: "Edit Travel Companions Information",
    label: "Other Persons Traveling with You:",
    fields: ["has_companions"],
  },

  // ReviewTravel: Edit Previous U.S. Travel Information.
  {
    page: "travel",
    section: "previous_us_travel",
    group: "Edit Previous U.S. Travel Information",
    label: "Have you ever been in the U.S.?",
    fields: ["has_been_in_us"],
  },
  {
    page: "travel",
    section: "previous_us_travel",
    group: "Edit Previous U.S. Travel Information",
    label: "Have you ever been issued a U.S. visa?",
    fields: ["has_us_visa"],
  },
  {
    page: "travel",
    section: "previous_us_travel",
    group: "Edit Previous U.S. Travel Information",
    label: "Have you ever been refused a U.S. Visa, or been refused admission to the United States, or withdrawn your application for admission at the port of entry?",
    fields: ["has_been_refused"],
  },
  {
    page: "travel",
    section: "previous_us_travel",
    group: "Edit Previous U.S. Travel Information",
    label: "Has anyone ever filed an immigrant petition on your behalf with the United States Citizenship and Immigration Services?",
    fields: ["immigrant_petition_filed"],
  },

  // ReviewUSContact: Edit U.S. Point of Contact Information.
  {
    page: "uscontact",
    section: "us_contact",
    group: "Edit U.S. Point of Contact Information",
    label: "Contact Person Name in the U.S.:",
    fields: ["us_contact_name_na"],
    format: "unknown",
  },
  {
    page: "uscontact",
    section: "us_contact",
    group: "Edit U.S. Point of Contact Information",
    label: "Organization Name in the U.S.:",
    fields: ["us_contact_organization"],
  },
  {
    page: "uscontact",
    section: "us_contact",
    group: "Edit U.S. Point of Contact Information",
    label: "Relationship to You:",
    fields: ["us_contact_relationship"],
  },
  {
    page: "uscontact",
    section: "us_contact",
    group: "Edit U.S. Point of Contact Information",
    label: "U.S. Contact Address:",
    fields: ["us_contact_address_street1"],
  },
  {
    page: "uscontact",
    section: "us_contact",
    group: "Edit U.S. Point of Contact Information",
    label: "U.S. Contact Address:",
    fields: ["us_contact_city", "us_contact_state", "us_contact_zip"],
    format: "locality",
    continuation: true,
  },
  {
    page: "uscontact",
    section: "us_contact",
    group: "Edit U.S. Point of Contact Information",
    label: "Phone Number:",
    fields: ["us_contact_phone"],
  },
  {
    page: "uscontact",
    section: "us_contact",
    group: "Edit U.S. Point of Contact Information",
    label: "Email Address:",
    fields: ["us_contact_email"],
  },

  // ReviewFamily: Edit Family Information: Relatives.
  {
    page: "family",
    section: "family_relatives",
    group: "Edit Family Information: Relatives",
    label: "Father's Surnames:",
    fields: ["father_surname_unknown"],
    format: "unknown",
  },
  {
    page: "family",
    section: "family_relatives",
    group: "Edit Family Information: Relatives",
    label: "Father's Given Names:",
    fields: ["father_given_names_unknown"],
    format: "unknown",
  },
  {
    page: "family",
    section: "family_relatives",
    group: "Edit Family Information: Relatives",
    label: "Mother's Surnames:",
    fields: ["mother_surname_unknown"],
    format: "unknown",
  },
  {
    page: "family",
    section: "family_relatives",
    group: "Edit Family Information: Relatives",
    label: "Mother's Given Names:",
    fields: ["mother_given_names_unknown"],
    format: "unknown",
  },
  {
    page: "family",
    section: "family_relatives",
    group: "Edit Family Information: Relatives",
    label: "Do you have any immediate relatives, not including parents in the U.S.?",
    fields: ["has_immediate_us_relatives"],
  },
  {
    page: "family",
    section: "family_relatives",
    group: "Edit Family Information: Relatives",
    label: "Do you have any other relatives in the United States?",
    fields: ["has_other_us_relatives"],
  },
] as const;
