/**
 * Cambodia (evisa.gov.kh) selector bindings.
 *
 * FALLBACK = stable selectors hand-derived from the form-recon walker
 * (Livewire SPA, name-attribute stable). GENERATED is regenerated by
 * `scripts/promote-selectors.ts` from `recon-out/<date>/kh/selectors.json`
 * and overrides the fallback when fresh recon data is available.
 */
import { GENERATED_KH_SELECTORS } from "./selectors.generated";

const FALLBACK = {
  last_name: 'input[name="last_name"]',
  first_name: 'input[name="first_name"]',
  email: 'input[name="email"]',
  phone: 'input[name="phone"]',
  date_of_birth: 'input[name="date_of_birth"]',
  nationality: 'select[name="nationality"]',
  passport_number: 'input[name="passport_number"]',
  passport_expiry: 'input[name="passport_expiry"]',
  passport_issuing_country: 'select[name="passport_issuing_country"]',
  next_button: 'button:has-text("Next")',
} as const;

export type KhSelectorKey = keyof typeof FALLBACK;

export const KH_SELECTORS: Record<KhSelectorKey, string> = {
  ...FALLBACK,
  ...(GENERATED_KH_SELECTORS as Partial<Record<KhSelectorKey, string>>),
};
