import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { Pool, type PoolClient } from "pg";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

const confirm = process.env.DATABASE_PERFORMANCE_INDEXES_DB_CONFIRM === "local-test";
const databaseUrl =
	process.env.DATABASE_PERFORMANCE_INDEXES_DATABASE_URL ?? process.env.DATABASE_URL ?? "";
const marker = (process.env.DATABASE_PERFORMANCE_INDEXES_DB_NONPRODUCTION ?? "").toLowerCase();
const allowedMarkers = new Set(["local", "local-test", "test", "development"]);
const localHost = (() => {
	try {
		const host = new URL(databaseUrl).hostname.toLowerCase();
		return host === "localhost" || host === "127.0.0.1" || host === "::1" || host === "supabase";
	} catch {
		return false;
	}
})();
const migrationPath = fileURLToPath(
	new URL("../../drizzle/0159_database_performance_indexes.sql", import.meta.url),
);
const migrationSql = existsSync(migrationPath) ? readFileSync(migrationPath, "utf8") : "";
const liveGateEnabled =
	Boolean(databaseUrl) && confirm && localHost && allowedMarkers.has(marker) && migrationSql.length > 0;

type JsonPlan = {
	Plan: {
		"Node Type": string;
		"Index Name"?: string;
		"Total Cost": number;
		Plans?: JsonPlan["Plan"][];
	};
};

let pool: Pool | undefined;
let client: PoolClient | undefined;

const query = async <T extends Record<string, unknown> = Record<string, unknown>>(
	sql: string,
	values: unknown[] = [],
) => {
	if (!client) throw new Error("database performance index integration client is not initialized");
	return client.query<T>(sql, values);
};

const explain = async (sql: string, values: unknown[]) => {
	const result = await query<{ "QUERY PLAN": JsonPlan[] }>(`EXPLAIN (FORMAT JSON) ${sql}`, values);
	return result.rows[0]?.["QUERY PLAN"][0]?.Plan;
};

const flattenPlan = (plan: JsonPlan["Plan"]): JsonPlan["Plan"][] => [
	plan,
	...(plan.Plans ?? []).flatMap(flattenPlan),
];

describe.skipIf(!liveGateEnabled)("database performance indexes PostgreSQL integration", () => {
	beforeAll(async () => {
		pool = new Pool({ connectionString: databaseUrl, max: 1 });
		client = await pool.connect();
		const environment = await query<{ environment: string | null }>(
			"SELECT current_setting('app.viza_environment', true) AS environment",
		);
		const databaseMarker = (environment.rows[0]?.environment ?? "").toLowerCase();
		if (!allowedMarkers.has(databaseMarker)) {
			throw new Error(
				`Refusing performance-index integration DDL: database marker ${databaseMarker || "<unset>"} is not local/test`,
			);
		}

		await query(`
			DROP TABLE IF EXISTS public.submission_queue CASCADE;
			DROP TABLE IF EXISTS public.visa_chunks CASCADE;
			DROP TABLE IF EXISTS public.pii_access_log CASCADE;
			CREATE TABLE public.submission_queue (
				id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				application_id UUID NOT NULL,
				updated_at TIMESTAMPTZ NOT NULL,
				created_at TIMESTAMPTZ NOT NULL
			);
			CREATE TABLE public.visa_chunks (
				id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				document_id UUID NOT NULL,
				content TEXT NOT NULL
			);
			CREATE TABLE public.pii_access_log (
				id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				application_id UUID,
				created_at TIMESTAMPTZ NOT NULL
			);
			INSERT INTO public.submission_queue (application_id, updated_at, created_at)
			SELECT
				pg_catalog.md5(series::text)::uuid,
				pg_catalog.clock_timestamp() - (series || ' seconds')::interval,
				pg_catalog.clock_timestamp() - (series || ' seconds')::interval
			FROM pg_catalog.generate_series(1, 50000) AS series;
			INSERT INTO public.visa_chunks (document_id, content)
			SELECT pg_catalog.md5(series::text)::uuid, pg_catalog.repeat('x', 128)
			FROM pg_catalog.generate_series(1, 50000) AS series;
			INSERT INTO public.pii_access_log (application_id, created_at)
			SELECT pg_catalog.md5(series::text)::uuid, pg_catalog.clock_timestamp()
			FROM pg_catalog.generate_series(1, 50000) AS series;
			ANALYZE public.submission_queue;
			ANALYZE public.visa_chunks;
			ANALYZE public.pii_access_log;
		`);
	});

	afterAll(async () => {
		if (client) {
			await client.query(`
				DROP TABLE IF EXISTS public.submission_queue CASCADE;
				DROP TABLE IF EXISTS public.visa_chunks CASCADE;
				DROP TABLE IF EXISTS public.pii_access_log CASCADE;
			`);
			client.release();
		}
		await pool?.end();
	});

	it("builds each index independently and improves its target plan by at least 3x", async () => {
		const targets = [
			{
				index: "submission_queue_application_latest_idx",
				sql: "SELECT id, updated_at, created_at FROM public.submission_queue WHERE application_id = $1 ORDER BY updated_at DESC, created_at DESC LIMIT 1",
			},
			{
				index: "visa_chunks_document_id_idx",
				sql: "SELECT id FROM public.visa_chunks WHERE document_id = $1",
			},
			{
				index: "pii_access_log_application_id_idx",
				sql: "SELECT id FROM public.pii_access_log WHERE application_id = $1",
			},
		] as const;
		const targetId = "00000000-0000-0000-0000-000000000001";
		const beforePlans = new Map<string, JsonPlan["Plan"]>();
		for (const target of targets) {
			const plan = await explain(target.sql, [targetId]);
			expect(plan).toBeDefined();
			beforePlans.set(target.index, plan as JsonPlan["Plan"]);
		}

		const statements = migrationSql
			.replace(/\/\*[\s\S]*?\*\//g, " ")
			.replace(/--[^\r\n]*/g, " ")
			.split(";")
			.map((statement) => statement.trim())
			.filter(Boolean);
		for (const statement of statements) await query(statement);
		await query("ANALYZE public.submission_queue; ANALYZE public.visa_chunks; ANALYZE public.pii_access_log;");

		for (const target of targets) {
			const before = beforePlans.get(target.index);
			const after = await explain(target.sql, [targetId]);
			expect(before).toBeDefined();
			expect(after).toBeDefined();
			expect((before as JsonPlan["Plan"])["Total Cost"] / (after as JsonPlan["Plan"])["Total Cost"]).toBeGreaterThanOrEqual(3);
			expect(flattenPlan(after as JsonPlan["Plan"]).some((node) => node["Index Name"] === target.index)).toBe(true);
		}
	});

	it("leaves every approved index ready, valid, and exact", async () => {
		const result = await query<{
			index_name: string;
			indisready: boolean;
			indisvalid: boolean;
		}>(`SELECT
			index_class.relname AS index_name,
			index_state.indisready,
			index_state.indisvalid
		FROM pg_catalog.pg_index AS index_state
		JOIN pg_catalog.pg_class AS index_class ON index_class.oid = index_state.indexrelid
		WHERE index_class.relname = ANY($1::text[])
		ORDER BY index_class.relname`, [[
			"pii_access_log_application_id_idx",
			"submission_queue_application_latest_idx",
			"visa_chunks_document_id_idx",
		]]);
		expect(result.rows).toEqual([
			{ index_name: "pii_access_log_application_id_idx", indisready: true, indisvalid: true },
			{ index_name: "submission_queue_application_latest_idx", indisready: true, indisvalid: true },
			{ index_name: "visa_chunks_document_id_idx", indisready: true, indisvalid: true },
		]);
	});
});
