import type { InterfaceLocale } from "@/lib/i18n/locale";

export const MARKETING_COPY = {
  en: {
    eyebrow: "Marketing operations",
    dashboardTitle: "Marketing control room",
    dashboardDescription: "Manage editorial content, social distribution, and privacy-safe performance signals from one authenticated workspace.",
    blogTitle: "Blog publishing",
    blogDescription: "Draft, generate, review, and publish VIZA-owned articles.",
    socialTitle: "Social distribution",
    socialDescription: "Compose platform-specific posts and hand approved work to Zernio.",
    newPost: "New blog post",
    newSocial: "New social composition",
    trackingTitle: "Campaign tracking",
    trackingDescription: "Create VIZA-owned redirects and review privacy-safe click totals.",
    newTrackingLink: "New tracked link",
    noTrackingLinks: "No tracked links yet.",
    active: "Active",
    inactive: "Inactive",
    clicks: "clicks",
    createSocialFromBlog: "Create social posts",
    automationRuns: "Automation runs",
    automationDescription: "Scheduled generation and watchdog outcomes. Content always remains a draft until an admin publishes it.",
    noAutomationRuns: "No automation runs yet.",
    back: "Back",
    edit: "Edit",
    noPosts: "No blog posts yet.",
    noSocial: "No social compositions yet.",
    providers: "Provider readiness",
    providerDescription: "Only connection status and non-secret identifiers are shown.",
    connected: "Connected",
    notConnected: "Not connected",
    analytics: "Analytics (last 30 days)",
    users: "Users",
    sessions: "Sessions",
    views: "Page views",
    conversions: "Conversions",
    searchClicks: "Search clicks",
    searchImpressions: "Search impressions",
    socialPosts: "Tracked social posts",
    socialImpressions: "Social impressions",
    socialClicks: "Social clicks",
    engagementRate: "Engagement rate",
    trafficTrend: "Daily users",
    topCountries: "Top countries",
    noAnalyticsRows: "No analytics rows are available yet.",
    days: "days",
    platformsUnit: "platforms",
    synced: "synced",
    statusDraft: "Draft",
    statusPublished: "Published",
    statusArchived: "Archived",
    statusScheduled: "Scheduled",
    statusPublishing: "Publishing",
    statusPartial: "Partial",
    statusFailed: "Failed",
    statusCancelled: "Cancelled",
    statusRunning: "Running",
    statusSucceeded: "Succeeded",
    statusSkipped: "Skipped",
    recentBlog: "Recent blog work",
    recentSocial: "Recent social work",
    status: "Status",
    locale: "Locale",
    updated: "Updated",
    platforms: "Platforms",
    scheduled: "Scheduled",
    notScheduled: "Not scheduled",
    unavailable: "Unavailable until the provider is connected.",
    colPost: "Post",
    colLocale: "Locale",
    colSource: "Source",
    colUpdated: "Updated",
    colStatus: "Status",
    colScore: "Score",
    colKeyword: "SEO keyword",
    colPlatform: "Platform",
    colCaption: "Caption",
    colDelivery: "Delivery",
    colLink: "Link",
    colWhen: "When",
    colJob: "Job",
    colOutcome: "Outcome",
    colDetail: "Detail",
    colProvider: "Provider",
    colDestination: "Destination",
    colCampaign: "Campaign",
    colClicks: "Clicks",
    colLastClick: "Last click",
    colShortLink: "Short link",
    noSource: "Written by hand",
    unmeasuredKeyword: "Not measured",
    notConfigured: "Not configured on this deployment",
    viewPost: "View post",
    noPublicUrl: "The platform returned no public link",
    waitsForApproval: "Waits for approval",
    blogPortalDescription:
      "Stories drafted into articles and held here for review. Nothing reaches the marketing site until an admin approves it.",
    socialPortalDescription:
      "The posts written from each article, one row per platform. They go out when an admin publishes the composition, and anything that failed can be sent again from here.",
  },
  zh: {
    eyebrow: "营销运营",
    dashboardTitle: "营销控制台",
    dashboardDescription: "在经过身份验证的工作区管理编辑内容、社交分发及隐私安全的效果数据。",
    blogTitle: "博客发布",
    blogDescription: "起草、生成、审核并发布 VIZA 自有文章。",
    socialTitle: "社交媒体分发",
    socialDescription: "为各平台编辑内容，并将已批准内容交由 Zernio 发布。",
    newPost: "新建博客",
    newSocial: "新建社交内容",
    trackingTitle: "活动跟踪",
    trackingDescription: "创建 VIZA 自有跳转链接并查看隐私安全的点击总数。",
    newTrackingLink: "新建跟踪链接",
    noTrackingLinks: "暂无跟踪链接。",
    active: "已启用",
    inactive: "已停用",
    clicks: "次点击",
    createSocialFromBlog: "创建社交内容",
    automationRuns: "自动化运行",
    automationDescription: "定时生成及看门狗结果。内容在管理员发布前始终保持为草稿。",
    noAutomationRuns: "暂无自动化运行记录。",
    back: "返回",
    edit: "编辑",
    noPosts: "暂无博客内容。",
    noSocial: "暂无社交媒体内容。",
    providers: "服务连接状态",
    providerDescription: "仅显示连接状态及非机密标识符。",
    connected: "已连接",
    notConnected: "未连接",
    analytics: "数据分析（近 30 天）",
    users: "用户",
    sessions: "会话",
    views: "页面浏览",
    conversions: "转化",
    searchClicks: "搜索点击",
    searchImpressions: "搜索曝光",
    socialPosts: "已跟踪社交内容",
    socialImpressions: "社交曝光",
    socialClicks: "社交点击",
    engagementRate: "互动率",
    trafficTrend: "每日用户",
    topCountries: "主要国家或地区",
    noAnalyticsRows: "暂无分析数据。",
    days: "天",
    platformsUnit: "个平台",
    synced: "已同步",
    statusDraft: "草稿",
    statusPublished: "已发布",
    statusArchived: "已归档",
    statusScheduled: "已安排",
    statusPublishing: "发布中",
    statusPartial: "部分完成",
    statusFailed: "失败",
    statusCancelled: "已取消",
    statusRunning: "运行中",
    statusSucceeded: "成功",
    statusSkipped: "已跳过",
    recentBlog: "近期博客工作",
    recentSocial: "近期社交媒体工作",
    status: "状态",
    locale: "语言",
    updated: "更新时间",
    platforms: "平台",
    scheduled: "计划发布",
    notScheduled: "未安排",
    unavailable: "连接相应服务后才可使用。",
    colPost: "文章",
    colLocale: "语言",
    colSource: "来源",
    colUpdated: "更新",
    colStatus: "状态",
    colScore: "评分",
    colKeyword: "SEO 关键词",
    colPlatform: "平台",
    colCaption: "文案",
    colDelivery: "投放",
    colLink: "链接",
    colWhen: "时间",
    colJob: "任务",
    colOutcome: "结果",
    colDetail: "详情",
    colProvider: "服务",
    colDestination: "目标地址",
    colCampaign: "活动",
    colClicks: "点击",
    colLastClick: "最近点击",
    colShortLink: "短链接",
    noSource: "手动撰写",
    unmeasuredKeyword: "未实测",
    notConfigured: "本环境未配置",
    viewPost: "查看帖子",
    noPublicUrl: "平台未返回公开链接",
    waitsForApproval: "等待审批",
    blogPortalDescription: "新闻线索起草成文章后在此等待审核。管理员批准前不会出现在营销站点上。",
    socialPortalDescription: "由每篇文章生成的社媒内容，按平台逐行列出。管理员发布后投放，失败的可在此重发。",
  },
} as const satisfies Record<InterfaceLocale, Record<string, string>>;

export type MarketingCopy = (typeof MARKETING_COPY)[InterfaceLocale];

export function marketingStatusLabel(copy: MarketingCopy, status: string): string {
  const key = `status${status.charAt(0).toUpperCase()}${status.slice(1)}` as keyof MarketingCopy;
  return copy[key] ?? status;
}

export function marketingDateLocale(copy: MarketingCopy): string {
  return copy === MARKETING_COPY.zh ? "zh-CN" : "en-SG";
}
