-- VIZA marketing operations: editorial content, social distribution, and
-- privacy-safe campaign click attribution. The public marketing site never
-- talks to these tables directly; authenticated server routes use the service
-- role after checking VIZA staff/admin membership.

CREATE TABLE IF NOT EXISTS public.marketing_blog_posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  locale TEXT NOT NULL DEFAULT 'en' CHECK (locale IN ('en', 'zh-CN')),
  slug TEXT NOT NULL CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
  title TEXT NOT NULL,
  excerpt TEXT NOT NULL DEFAULT '',
  body_markdown TEXT NOT NULL DEFAULT '',
  cover_image_url TEXT,
  category TEXT,
  author_name TEXT NOT NULL DEFAULT 'VIZA Editorial',
  seo_title TEXT,
  seo_description TEXT,
  generation_brief TEXT,
  generated_by_model TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object'),
  version INTEGER NOT NULL DEFAULT 1 CHECK (version > 0),
  created_by UUID NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  updated_by UUID NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  published_by UUID REFERENCES public.users(id) ON DELETE SET NULL,
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT marketing_blog_publish_state_check CHECK (
    (status = 'published' AND published_at IS NOT NULL AND published_by IS NOT NULL)
    OR status <> 'published'
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS marketing_blog_posts_locale_slug_uidx
  ON public.marketing_blog_posts (locale, lower(slug));
CREATE INDEX IF NOT EXISTS marketing_blog_posts_public_feed_idx
  ON public.marketing_blog_posts (locale, published_at DESC)
  WHERE status = 'published';
CREATE INDEX IF NOT EXISTS marketing_blog_posts_updated_idx
  ON public.marketing_blog_posts (updated_at DESC);

CREATE TABLE IF NOT EXISTS public.marketing_social_compositions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  blog_post_id UUID REFERENCES public.marketing_blog_posts(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  brief TEXT NOT NULL DEFAULT '',
  destination_url TEXT,
  media_url TEXT,
  document_url TEXT,
  status TEXT NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'scheduled', 'publishing', 'published', 'partial', 'failed', 'cancelled')),
  platforms JSONB NOT NULL DEFAULT '[]'::jsonb CHECK (jsonb_typeof(platforms) = 'array'),
  platform_content JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(platform_content) = 'object'),
  zernio_posts JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(zernio_posts) = 'object'),
  scheduled_for TIMESTAMPTZ,
  last_synced_at TIMESTAMPTZ,
  created_by UUID NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  updated_by UUID NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS marketing_social_compositions_status_idx
  ON public.marketing_social_compositions (status, updated_at DESC);
CREATE INDEX IF NOT EXISTS marketing_social_compositions_blog_idx
  ON public.marketing_social_compositions (blog_post_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS public.marketing_provider_activity (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider TEXT NOT NULL CHECK (provider IN ('openrouter', 'zernio', 'google-analytics', 'search-console', 'system')),
  operation TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('started', 'succeeded', 'failed', 'skipped')),
  entity_type TEXT,
  entity_id TEXT,
  actor_user_id UUID REFERENCES public.users(id) ON DELETE SET NULL,
  request_metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(request_metadata) = 'object'),
  response_metadata JSONB NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(response_metadata) = 'object'),
  error_code TEXT,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS marketing_provider_activity_entity_idx
  ON public.marketing_provider_activity (entity_type, entity_id, created_at DESC);
CREATE INDEX IF NOT EXISTS marketing_provider_activity_provider_idx
  ON public.marketing_provider_activity (provider, status, created_at DESC);

CREATE TABLE IF NOT EXISTS public.marketing_short_links (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT NOT NULL UNIQUE CHECK (code ~ '^[A-Za-z0-9_-]{6,32}$'),
  destination_url TEXT NOT NULL CHECK (destination_url ~ '^https://'),
  source TEXT NOT NULL DEFAULT 'social',
  campaign TEXT,
  content_key TEXT,
  active BOOLEAN NOT NULL DEFAULT true,
  click_count BIGINT NOT NULL DEFAULT 0 CHECK (click_count >= 0),
  last_clicked_at TIMESTAMPTZ,
  created_by UUID NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.marketing_short_link_clicks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  short_link_id UUID NOT NULL REFERENCES public.marketing_short_links(id) ON DELETE CASCADE,
  clicked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  referrer_host TEXT,
  user_agent_family TEXT,
  country_code TEXT CHECK (country_code IS NULL OR country_code ~ '^[A-Z]{2}$'),
  session_hash TEXT CHECK (session_hash IS NULL OR length(session_hash) BETWEEN 32 AND 128)
);

CREATE INDEX IF NOT EXISTS marketing_short_link_clicks_link_idx
  ON public.marketing_short_link_clicks (short_link_id, clicked_at DESC);

ALTER TABLE public.marketing_blog_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketing_social_compositions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketing_provider_activity ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketing_short_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.marketing_short_link_clicks ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.marketing_blog_posts FROM anon, authenticated;
REVOKE ALL ON TABLE public.marketing_social_compositions FROM anon, authenticated;
REVOKE ALL ON TABLE public.marketing_provider_activity FROM anon, authenticated;
REVOKE ALL ON TABLE public.marketing_short_links FROM anon, authenticated;
REVOKE ALL ON TABLE public.marketing_short_link_clicks FROM anon, authenticated;

GRANT ALL ON TABLE public.marketing_blog_posts TO service_role;
GRANT ALL ON TABLE public.marketing_social_compositions TO service_role;
GRANT ALL ON TABLE public.marketing_provider_activity TO service_role;
GRANT ALL ON TABLE public.marketing_short_links TO service_role;
GRANT ALL ON TABLE public.marketing_short_link_clicks TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.marketing_provider_activity_id_seq TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.marketing_short_link_clicks_id_seq TO service_role;

COMMENT ON TABLE public.marketing_blog_posts IS
  'VIZA-owned editorial drafts and published marketing blog snapshots.';
COMMENT ON TABLE public.marketing_social_compositions IS
  'VIZA social composition intent and Zernio post identifiers; Zernio remains live-state source of truth.';
COMMENT ON TABLE public.marketing_provider_activity IS
  'Redacted audit trail for VIZA marketing provider calls. Secrets and full generated copy are prohibited.';
COMMENT ON TABLE public.marketing_short_link_clicks IS
  'Privacy-safe social attribution; never store raw IP addresses, full user agents, or personal data.';
