import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

type OwnershipManifest = {
	version: number;
	reconciliation: {
		status: "pending-live-reconciliation" | "reconciled";
		productionProjectRef: string;
		requiredArtifact: "architecture-audit";
		artifactSha256: string | null;
	};
	candidateOwnership: {
		"drizzle-managed": string[];
		"rest-service-only": string[];
		"compatibility-only": string[];
	};
	knownDrizzleDeclarationsPendingLiveCheck: string[];
};

const manifestPath = fileURLToPath(new URL("./schema-ownership.manifest.json", import.meta.url));
const schemaPath = fileURLToPath(new URL("./schema.ts", import.meta.url));
const manifestSource = readFileSync(manifestPath, "utf8");
const manifest = JSON.parse(manifestSource) as OwnershipManifest;
const schemaSource = readFileSync(schemaPath, "utf8");

describe("database schema ownership candidate manifest", () => {
	it("waits for the hashed architecture-audit artifact before claiming live reconciliation", () => {
		expect(manifest.version).toBe(2);
		expect(manifest.reconciliation).toEqual({
			status: "pending-live-reconciliation",
			productionProjectRef: "oyjxdzsoejraedqghndi",
			requiredArtifact: "architecture-audit",
			artifactSha256: null,
		});
		expect(manifestSource).not.toContain("productionCatalogCapturedAt");
		expect(manifestSource).not.toContain('"owners"');
	});

	it("assigns every candidate exactly once without treating candidates as a live snapshot", () => {
		const assignments = Object.values(manifest.candidateOwnership).flat();
		expect(assignments.length).toBeGreaterThan(0);
		expect(new Set(assignments).size).toBe(assignments.length);
	});

	it("keeps every drizzle-managed candidate declared in schema.ts", () => {
		for (const table of manifest.candidateOwnership["drizzle-managed"]) {
			expect(schemaSource).toContain(`pgTable("${table}"`);
		}
	});

	it("adds typed contracts for the selected service tables", () => {
		for (const table of [
			"runner_concurrency_metric",
			"takeover_session",
			"takeover_action_log",
			"application_inbox_aliases",
			"ds160_live_sessions",
		]) {
			expect(schemaSource).toContain(`pgTable("${table}"`);
		}
	});

	it("keeps unresolved Drizzle declarations explicit until live reconciliation", () => {
		const candidateAssignments = new Set(Object.values(manifest.candidateOwnership).flat());
		for (const table of manifest.knownDrizzleDeclarationsPendingLiveCheck) {
			expect(schemaSource).toContain(`pgTable("${table}"`);
			expect(candidateAssignments.has(table)).toBe(false);
		}
	});

	it("marks unsupported identity and per-column DESC details as migration-owned type-only metadata", () => {
		expect(schemaSource).toMatch(/TYPE-ONLY SCHEMA COMPATIBILITY/i);
		expect(schemaSource).toMatch(
			/runner_concurrency_metric[\s\S]*GENERATED BY DEFAULT AS IDENTITY[\s\S]*recorded_at DESC/i,
		);
		expect(schemaSource).toMatch(/application_inbox_aliases[\s\S]*created_at DESC/i);
		expect(schemaSource).toMatch(/id:\s*bigint\("id",\s*\{\s*mode:\s*"number"\s*\}\)\.primaryKey\(\)/i);
		expect(schemaSource).not.toContain('index("runner_concurrency_metric_recorded_idx")');
		expect(schemaSource).not.toContain('index("runner_concurrency_metric_event_recorded_idx")');
		expect(schemaSource).not.toContain('index("application_inbox_aliases_applicant_idx")');
	});
});
